### PR TITLE
Fix #15212: Smooth panning advanced setting

### LINKED ISSUE #15212: [MU4 Issue] Continuous mode smooth scrolling (during Playback)
**Edited by** @DmitryArefiev 

**Describe the bug**
MuseScore 4 doesn't seem to have the `smoothPan/enabled` advanced option of MuseScore 3 

**To Reproduce**
1. Go to **Preferences>Advanced**

**Expected behavior**
The option should be there and be functional.

**Screenshots**

https://user-images.githubusercontent.com/90187801/234865116-2edbacfe-ea3e-4293-b982-2839969ffa64.mp4

**Platform information**
 - OS: Windows

**Additional context**
From https://musescore.org/en/node/340597 :

> Smooth panning is not available anymore, annoying for choir singers that would like to see whats next and not wait for a pageturn during playback
> 
> For our (older) choirmembers **this is a blocker to work with version 4**, I understand for the development of this version missing this option is even les then a minor . But perhaps there is a quickfix or workaround that can help.

### PR DESCRIPTION
**Pull request by 22justinl**
Resolves: #15212

Smooth panning advanced setting that used to be in MuseScore 3

Some things I am not sure about:
- I am not sure about how to change the order of the advanced preferences items, is this only possible if we list all the advanced preferences manually?
- The screen is slightly jittery when playing back, which is most likely because I am moving the screen to the cursor instead of moving the screen independently. Im not sure if this was the case in MuseScore 3.
- Should I add the other advanced preferences (that used to be in MuseScore 3) relating to smooth panning (cursor position on screen, cursor visibility, etc.)?

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

File: src/notation/view/abstractnotationpaintview.cpp [hunk 1]
```diff
@@ -805,9 +805,7 @@ qreal AbstractNotationPaintView::startVerticalScrollPosition() const
 bool AbstractNotationPaintView::adjustCanvasPosition(const RectF& logicRect, bool adjustVertically)
 {
     TRACEFUNC;
-
     RectF viewRect = viewport();
-
```
Comment (cbjeukendrup) [inline src/notation/view/abstractnotationpaintview.cpp:810]: Please preserve these empty lines (here and also before `return moveCanvasToPosition(pos);` both times)

File: src/notation/view/abstractnotationpaintview.cpp [hunk 2]
```diff
@@ -881,7 +889,7 @@ bool AbstractNotationPaintView::ensureViewportInsideScrollableArea()
 bool AbstractNotationPaintView::moveCanvasToPosition(const PointF& logicPos)
 {
     TRACEFUNC;
-
+    LOGW() << "moveCanvasToPosition()";
```
Comment (cbjeukendrup) [inline src/notation/view/abstractnotationpaintview.cpp:892]: Please remove this before we merge the PR (and make sure to return the empty line in its place)

File: src/notation/view/abstractnotationpaintview.cpp [hunk 3]
```diff
@@ -1284,10 +1292,13 @@ void AbstractNotationPaintView::movePlaybackCursor(midi::tick_t tick)
...
     }
 
-    if (configuration()->isAutomaticallyPanEnabled() && m_autoScrollEnabled) {
+    if (configuration()->isAutomaticallyPanEnabled()) {
         bool adjustVertically = needAdjustCanvasVerticallyWhilePlayback(newCursorRect);
 
-        if (adjustCanvasPosition(newCursorRect, adjustVertically)) {
+        if (configuration()->isSmoothPanning() && adjustCanvasPositionSmoothPan(newCursorRect)) {
+            return;
+        }
```
Comment (cbjeukendrup) [inline src/notation/view/abstractnotationpaintview.cpp:1300]: The `adjustVertically` variable is only needed if the `if` condition is false. Since the method `needAdjustCanvasVerticallyWhilePlayback` is not quite trivial, and this code will be called very often, it would be preferable to call the method only if strictly necessary.

**Review by cbjeukendrup — COMMENTED** [review]
A few minor comments, of which most only cosmetic. Looks very good already!

**Review by cbjeukendrup — COMMENTED** [review]
Looks very good, thanks! I'll ask a colleague to give this a final review, but to me it seems ready for merging!

**Comment by RomanPudashkin** [comment]
Please squash your commits (using git rebase). There should only be one commit

**Review by RomanPudashkin — APPROVED** [review]

File: src/notation/internal/notationconfiguration.cpp [hunk 4]
```diff
@@ -164,6 +165,10 @@ void NotationConfiguration::init()
     settings()->setDefaultValue(IS_METRONOME_ENABLED, Val(false));
     settings()->setDefaultValue(IS_COUNT_IN_ENABLED, Val(false));
 
+    settings()->setDefaultValue(PLAYBACK_SMOOTH_PANNING, Val(false));
+    settings()->setDescription(PLAYBACK_SMOOTH_PANNING, qtrc("notation", "Smooth panning").toStdString());
```
Comment (RomanPudashkin) [inline src/notation/internal/notationconfiguration.cpp:169]: You can replace `qtrc("notation", "Smooth panning").toStdString()` with `trc("notation", "Smooth panning")`

**Comment by zacjansheski** [comment]
Tested on Mac OS 11.6.5, Ubuntu 20.04.6, Windows 11
https://github.com/musescore/MuseScore/issues/15212 FIXED

**Comment by nh2** [comment]
Thank you so much!
