### PR TITLE
Remplementing minimum tie length and minimum glissando length

### LINKED ISSUE #11823: [MU4 Issue] Glissando and slides are too short and overdubbing next/previous elements
**Describe the bug**
1. Straight Glissando is to short when placed between notes
2. Glissando overdubs another elements like accidentals, stems etc. when 

**To Reproduce**
1. Open the test score 
[test_gliss.mscz.zip](https://github.com/musescore/MuseScore/files/8804254/test_gliss.mscz.zip)
2. Pay attention to the first measure

**Expected behavior**
Glissando is displayed according to the expected view

**Screenshots**
Capture 2022-05-31_01-20-17_PM

**Additional context**
The issue is related to https://github.com/musescore/MuseScore/issues/10316

### PR DESCRIPTION
**Pull request by mike-spa**
(also resolves #11823)

Minimum tie length and minimum glissando length are re-implemented, taking advantage of the new horizontal spacing system and the new tie positioning system. Additionally, minimum glissando length has a dedicated value and does not share the same as minimum tie length (as previously done in 3.6). 

Important note: this PR only affects the spacing. The positioning of the attachment points for ties and glissandi have not been touched.

@oktophonie

### CODE REVIEW

File: src/engraving/layout/layoutchords.cpp [hunk 1]
```diff
@@ -1247,3 +1249,75 @@ void LayoutChords::repositionGraceNotesAfter(Segment* segment)
...
+    for (Segment& s : measure->segments()) {
+        if (!s.isChordRestType()) {
+            continue;
+        }
+        for (EngravingItem* e : s.elist()) {
+            if (!e || !e->isChord()) {
+                continue;
+            }
+            Chord* c = toChord(e);
+            doUpdateLineAttachPoints(c);
```
Comment (alexpavlov96) [inline src/engraving/layout/layoutchords.cpp:1283]: is that a right name, @mike-spa ?
the method doUpdateLineAttachPoints doesn't change lineAttachPoints, so it's confusing

File: src/engraving/libmscore/note.h [hunk 2]
```diff
@@ -252,6 +274,8 @@ class Note final : public EngravingItem
 
     bool sameVoiceKerningLimited() const override { return true; }
 
+    std::vector<LineAttachPoint> _lineAttachPoints;
```
Comment (alexpavlov96) [inline src/engraving/libmscore/note.h:277]: let's maybe add new elements already with "m_" prefix? or we keep them old for old files?

**Comment by boryskuzmenko** [comment]
@mike-spa is this PR ready for testing?

**Comment by mike-spa** [comment]
@boryskuzmenko I would wait before testing it, @vpereverzev will probably want to review the code first. And it will also need a rebase

File: src/engraving/layout/layoutchords.cpp (hunk 1 above)
Comment (mike-spa) [reply src/engraving/layout/layoutchords.cpp:1283]: added comments to clarify!

File: src/engraving/libmscore/note.h (hunk 2 above)
Comment (mike-spa) [reply src/engraving/libmscore/note.h:277]: All the other names have just the underscore prefix, so I would leave like this for consistency at the moment. Maybe at some point we make a separate PR and refactor all of them with m_ prefix

**Review by alexpavlov96 — APPROVED** [review]

**Comment by boryskuzmenko** [comment]
🟢 **FIXED**
Tested on macOS 12, Win 11, Ubuntu 20

Please, merge to master

**Comment by mike-spa** [comment]
sorry, I closed it by mistake, now reopened it

**Review by vpereverzev — APPROVED** [review]
