### PR TITLE
Fix #10109: Missing Icons

### LINKED ISSUE #10109: [MU4 Issue] Several Properties buttons are missing icons
**Describe the bug**
There are a couple of parts to this issue:

1. The following buttons in **Properties** are missing icons from `musescoreicon`.

- Volta (should be f410)
- Vibrato (should be f411)
- Let ring (should be f40f)
- Ottava (should be f40d)
- Palm mute (should be f40e)

Screenshot 2021-12-16 at 5 11 29 pm

2. Tuplets currently contain the incorrect icon

Screenshot 2021-12-16 at 5 32 24 pm

This should be f422, as per @Tantacrul's design spec:
 
Screenshot 2021-12-16 at 5 33 27 pm

**Desktop (please complete the following information):**
 - MacOS 11.6 (M1)
 - Windows 11

### PR DESCRIPTION
**Pull request by HemantAntony**
Resolves: #10109 

This commit adds missing icons

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

File: src/framework/ui/view/iconcodes.h [hunk 1]
```diff
@@ -174,6 +174,11 @@ class IconCode
         LINE_PEDAL_STAR_ENDING = 0xEF87,
         BEAM_FEATHERING_LEFT = 0xEF88,
         BEAM_FEATHERING_RIGHT = 0xEF89,
+        OTTAVA = 0xF40D,
+        PALM_MUTE = 0xF40E,
+        LET_RING = 0xF40F,
+        VOLTA = 0xF410,
+        VIBRATO = 0xF411,
```
Comment (cbjeukendrup) [inline src/framework/ui/view/iconcodes.h:181]: It would be great if you could keep this enum in numerical order, so if you could put them just before `DIMINUENDO` (further at the bottom of this file).

Comment (HemantAntony) [reply src/framework/ui/view/iconcodes.h:181]: Oh ok. Will do that

**Comment by cbjeukendrup** [comment]
I discovered one more thing: the Multi-Measure rest inspector popup has currently a question mark icon, because there is no dedicated icon yet in the icons font. I've asked the designers to create it, so when that's ready, it would be nice if this could be added in this PR.

**Comment by Jojo-Schmitz** [comment]
If the codepiont can get told in advance, it could get added to this PR now (and the updated font later)

**Comment by cbjeukendrup** [comment]
@HemantAntony Bradley, one of the designers, has created the icon for measure repeats. You can find the latest version of the icons font here: https://www.dropbox.com/s/30d2x5ve3ascteo/MusescoreIcon.ttf?dl=0
Please replace the font in fonts/mscore/MusescoreIcon.ttf with this updated version. 
The code for the new icon is 0xF431, and the model where you will want to use it is MeasureRepeatSettingsModel. It should look like this:
Schermafbeelding 2021-12-17 om 12 41 36
Would be great if you could fix this one too!

For testing, you can create a measure repeat by selecting a whole measure and then clicking the Measure repeat sign in the Palettes.

**Comment by DmitryArefiev** [comment]
Tested together with @bkunda  on Windows, Mac, LinuxMint - FIXED      

Please merge into master (@RomanPudashkin @Eism ) 

Thanks!

**Comment by Jojo-Schmitz** [comment]
Better get that measure reepeat thing added before merging, I guess

**Review by RomanPudashkin — APPROVED** [review]

**Comment by Jojo-Schmitz** [comment]
oops, too late, so something for another PR

**Comment by HemantAntony** [comment]
Yeah, I should have marked this pr as draft. I will make another pr for this

**Comment by HemantAntony** [comment]
If there are any more icons to add anywhere, please tell me. Its probably better to do them in one pr

**Comment by HemantAntony** [comment]
@cbjeukendrup, made a PR for measure repeat icon: #10164
