### PR TITLE
Fix #19918: Tremolo beam disappearing

### LINKED ISSUE #19918: Tremolo beam disappearing
### Issue type

Engraving bug

### Bug description

Tremolo between notes, when represented as a single full beam (stem to stem) sometimes disappears depending on the position of the notes. The width of the measure may 

### Steps to reproduce

1. Create a score from scratch
2. Add quarter notes with fully beamed tremolo in between
3. According to the pitch of the notes the beam may disappear
Please, see attached video for further details

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/149786998/fd7ff489-fd86-49f4-9014-e471ee2a0654

### MuseScore Version

4.1.1 and 11/2/2023 latest nightly

### Regression

I don't know

### Operating system

Windows 11

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by HemantAntony**
Resolves: #19918 

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by oktophonie** [comment]
Not sure what the vtest change here is about, though it doesn't particularly concern me; the issue itself seems to be fixed in this PR.

**Review by oktophonie — APPROVED** [review]

**Comment by HemantAntony** [comment]
Oh okay, that sounds great. I was a bit worried about that

**Comment by cbjeukendrup** [comment]
When I enable Diagnostics > Engraving > Color element shapes, it seems this change seems to have an not-exclusively-positive effect on the calculated shapes:
| Before | After |
|--------|--------|
| Scherm­afbeelding 2023-11-08 om 23 47 11| Scherm­afbeelding 2023-11-08 om 23 44 40|

File: src/engraving/rendering/dev/tremololayout.cpp [hunk 1]
```diff
@@ -344,10 +344,11 @@ void TremoloLayout::createBeamSegments(Tremolo* item, LayoutContext& ctx)
     double bboxTop = item->up()
                      ? std::min(mainStroke->line.y1(), mainStroke->line.y2())
                      : std::max(mainStroke->line.y1(), mainStroke->line.y2());
-    double halfWidth = ctx.conf().styleMM(Sid::beamWidth).val() / 2. * (item->up() ? -1. : 1.);
+    double width = ctx.conf().styleMM(Sid::beamWidth).val();
+    double halfWidth = width / 2. * (item->up() ? -1. : 1.);
 
     RectF bbox = RectF(mainStroke->line.x1(), bboxTop + halfWidth, mainStroke->line.x2() - mainStroke->line.x1(),
-                       std::abs(mainStroke->line.y2() - mainStroke->line.y1()) - halfWidth * 2.);
+                       std::abs(mainStroke->line.y2() - mainStroke->line.y1()) + width);
```
Comment (mike-spa) [inline src/engraving/rendering/dev/tremololayout.cpp:351]: It's the right idea, but it's not 100% correct, see:
image

It can be done more easily: there is really no need for the bbox calculation to be aware of up/down. Try this, which should work and looks clearer :)

```
LineF line = mainStroke->line;
double halfWidth = 0.5 * ctx.conf().styleMM(Sid::beamWidth).val();
double bboxTop = std::min(line.y1(), line.y2()) - halfWidth;
double bboxBottom = std::max(line.y1(), line.y2()) + halfWidth;

RectF bbox = RectF(line.x1(), bboxTop, line.x2() - line.x1(), bboxBottom - bboxTop);
```

Comment (HemantAntony) [reply src/engraving/rendering/dev/tremololayout.cpp]: Oh that makes so much sense. I had no idea why bboxTop was being calculated like that. I assumed it was correct

**Review by cbjeukendrup — APPROVED** [review]
