### PR TITLE
Fix #19535: Undo-redo-undo crash (Master)

### LINKED ISSUE #19535: Crash after delete bottom instrument, Undo, Redo and Undo (one score)
### Issue type

Crash or freeze

### Bug description

_No response_

### Steps to reproduce

1. Open [Smoke Test 18_crash.zip](https://github.com/musescore/MuseScore/files/12727672/Smoke.Test.18_crash.zip)
2. Delete **Violoncello** instrument
3. Undo
4. Redo
5. Undo

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/8fe70232-d7b4-416d-a857-101c3edc5af2

### MuseScore Version

4.2 master

### Regression

Yes, this used to work in  **MuseScore 4.0.2**

### Operating system

Windows 10

### Additional context

Similar to #18748

### PR DESCRIPTION
**Pull request by mathesoncalum**
Resolves: #19535
(Squashing #20339)

### CODE REVIEW

File: src/engraving/dom/segment.cpp [hunk 1]
```diff
@@ -546,7 +546,11 @@ void Segment::removeStaff(staff_idx_t staff)
 //---------------------------------------------------------
 
 void Segment::checkElement(EngravingItem* el, track_idx_t track)
-{
+{
```
Comment (Jojo-Schmitz) [inline src/engraving/dom/segment.cpp:549]: Still whitespace damage

**Review by RomanPudashkin — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
Tested #19535 on Win10, Mac13.6 - **FIXED**
