### PR TITLE
Fix #24723: Honor --score-transpose flag in CLI

### LINKED ISSUE #24723: CLI --score-transpose flag ignored in Musescore 4
### Issue type

Import/export issue

### Description with steps to reproduce

Run 

```sh
mscore file.mscz --score-transpose '{"mode":"by_key","direction":"closest","targetKey":0,"transposeInterval":null,"transposeKeySignatures":true,"transposeChordNames":true,"useDoubleSharpsFlats":false}'
```

and parse the result (either `pdf` or `mscz`) and the resulting output is unchanged, regardless of   what `'targetKey'` is set to.

### Supporting files, videos and screenshots

[example.zip](https://github.com/user-attachments/files/17003703/example.zip) that includes an `input.mscz` in the key of C, and several pairs of `output-targetKey{key}.pdf` and `output-targetKey{key}.mscz` files that were generated via a simple `python` script:

```python 
import json
import base64
from pathlib import Path
import subprocess


def main():
    """Main function"""

    score = Path("input.mscz")
    for key in range(-7, 7):
        config = (
            f'{{"mode":"by_key","direction":"closest","targetKey":{key},'
            '"transposeInterval":null,"transposeKeySignatures":true,"transposeChordNames":true,'
            '"useDoubleSharpsFlats":false}'
        )
        a = subprocess.run(
            [
                "mscore",
                score.absolute(),
                "--score-transpose",
                config,
            ],
            capture_output=True,
        )
        base64_pdf = json.loads(a.stdout)["pdf"]
        base64_mscz = json.loads(a.stdout)["mscz"]
        Path(f"output-targetKey{key}.pdf").write_bytes(base64.b64decode(base64_pdf))
        Path(f"output-targetKey{key}.mscz").write_bytes(base64.b64decode(base64_mscz))


if __name__ == "__main__":
    main()
```

The `python` script is just to quickly try many different keys (all result in outputs that are unchanged from the original); but the problem persist even if run directly in a terminal. (e.g.,

```sh
mscore input.mscz \
        --score-transpose '{"mode":"by_key","direction":"closest","targetKey":7,"transposeInterval":null,"transposeKeySignatures":true,"transposeChordNames":true,"useDoubleSharpsFlats":false}' \
        | jq -r .pdf | base64 --decode | > output.pdf
```

### What is the latest version of MuseScore Studio where this issue is present?

4.4.0

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

macOS 14.6.1

### Additional context

Also found a [related bug report](https://musescore.org/en/node/354550) at musescore.org. 

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by jongbinjung**
Resolves: #24723

While investigating #24723 three problems were identified and addressed in this PR:

* A temporary "filename" with `.mscx` extension that should be `.mscz` (but immaterial)
* `BackendApi::parseTransposeOptions` was not setting `options.interval` and `options.key` before returning
* ~~Since `4.0`,~~ [Score::transpose](https://github.com/musescore/MuseScore/blob/c16c3a79e5758e3eabee2709d39b823d12ac92a6/src/engraving/dom/transpose.cpp#L281) only applies to a selected range. In the GUI, this is accommodated by [selecting all](https://github.com/musescore/MuseScore/blob/c16c3a79e5758e3eabee2709d39b823d12ac92a6/src/notation/view/widgets/transposedialog.cpp#L46-L49) when the `TransposeDialog` is opened without a selection. Because the CLI will never have a selection, treat it like opening the `TransposeDialog` with no selection and replicate the behavior of selecting all. 

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

File: src/converter/internal/compat/backendapi.cpp [hunk 1]
```diff
@@ -747,6 +749,8 @@ Ret BackendApi::applyTranspose(const INotationPtr notation, const std::string& o
         return make_ret(Ret::Code::InternalError);
     }
 
+    interaction->selectAll();
```
Comment (Jojo-Schmitz) [inline src/converter/internal/compat/backendapi.cpp:752]: This is basically what Mu3 does too, in file.cpp, `MuseScore::exportTransposedScoreToJSON`

**Review by cbjeukendrup — APPROVED** [review]
