### PR TITLE
fixed #31972: Revert to factory settings is going with crash

### LINKED ISSUE #31972: Revert to factory settings is going with crash
### Issue type

Crash or freeze

### Description with steps to reproduce

https://github.com/user-attachments/assets/5575f1e9-4db3-45dc-b513-8f692b90a209

[MuseScore4.exe(1).8356.zip](https://github.com/user-attachments/files/24984839/MuseScore4.exe.1.8356.zip)

[logs.zip](https://github.com/user-attachments/files/24984841/logs.zip)

### In which versions of MuseScore Studio is this issue present?

4.7 master (4.7.0-260131034)

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

Windows 10

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by Eism**
Resolves: #31972

### CODE REVIEW

File: src/app/main.cpp [hunk 1]
```diff
@@ -178,6 +182,20 @@ int main(int argc, char** argv)
...
+#ifdef QT_QPROCESS_SUPPORTED
+        QString program = qApp->arguments()[0];
+
+        // NOTE: remove the first argument - the program name
+        QStringList arguments = qApp->arguments().mid(1);
+
+        QProcess::startDetached(program, arguments);
+#else
+        NOT_SUPPORTED;
+#endif
```
Comment (igorkorsukov) [inline src/app/main.cpp]: Why was it necessary to move this here?

Comment (Eism) [reply src/app/main.cpp]: We haven't finished the current one and are trying to create a new instance - the new instance is registered in the multi-window system - the previous instance is trying to send something to the new instance.

But overall, these changes seem logical to me: first, we'll wait for the program to finish all its work, and only then will we create a new instance. Isn't that right?

Comment (igorkorsukov) [reply src/app/main.cpp]: I don't mind, I just want to know the motivation.

I'm confused that this isn't in the framework; it needs to be repeated in other apps...

Maybe it makes sense to move this code to the app->finish() method?

Comment (Eism) [reply src/app/main.cpp]: sounds good, thanks, moved back to BaseApplication

File: src/framework/audio/driver/platform/win/asio/asioaudiodriver.cpp [hunk 2]
```diff
@@ -80,6 +80,11 @@ AsioAudioDriver::AsioAudioDriver()
 {
 }
 
+AsioAudioDriver::~AsioAudioDriver()
+{
+    close();
```
Comment (RomanPudashkin) [inline src/framework/audio/driver/platform/win/asio/asioaudiodriver.cpp]: It's virtual, we should not call virtual functions from constructors/destructors

File: src/framework/audio/driver/platform/win/asio/asioaudiodriver.h [hunk 3]
```diff
@@ -33,6 +33,7 @@ class AsioAudioDriver : public IAudioDriver, public async::Asyncable
 {
 public:
     AsioAudioDriver();
+    ~AsioAudioDriver();
```
Comment (RomanPudashkin) [inline src/framework/audio/driver/platform/win/asio/asioaudiodriver.h]:
```suggestion
    ~AsioAudioDriver() override;
```

File: src/framework/audio/driver/platform/win/asio/asioaudiodriver.cpp (hunk 2 above)
Comment (igorkorsukov) [reply src/framework/audio/driver/platform/win/asio/asioaudiodriver.cpp]: in base classes...

Comment (Eism) [reply src/framework/audio/driver/platform/win/asio/asioaudiodriver.cpp]: I changed it just so it would be the same as other similar classes
