### PR TITLE
[MU4] Fix #9998 Crash when open a new part (some scores)

### LINKED ISSUE #9998: [MU4 Issue] Crash when open a new part (some scores)
**To Reproduce**
1. Open [test_palette.zip](https://github.com/musescore/MuseScore/files/7669970/test_palette.zip)
2. In Parts, create a new part and open it

https://user-images.githubusercontent.com/90187801/145069573-ac870c60-e833-457d-8fde-a4131f2e863d.mp4

**Desktop:**
 - OS: Windows10, Mac12 (didn't try on Linux)

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Resolves: https://github.com/musescore/MuseScore/issues/9998

### CODE REVIEW

**Review by vpereverzev — APPROVED** [review]

File: src/notation/internal/notationparts.cpp [hunk 1]
```diff
@@ -859,7 +859,7 @@ void NotationParts::moveStaves(const IDList& sourceStavesIds, const ID& destinat
     int destinationStaffIndex = (mode == InsertMode::Before ? destinationStaff->idx() : destinationStaff->idx() + 1);
     destinationStaffIndex -= score()->staffIdx(destinationPart); // NOTE: convert to local part's staff index
 
-    deselectAll();
+    onBeforeStavesChanged();
```
Comment (vpereverzev) [inline src/notation/internal/notationparts.cpp:862]: it might be better to call it as "reset" or somewhat like that

**Review by vpereverzev — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
Tested #9998 on Win10, Mac12, LinuxMint 20.2 - FIXED      

Please merge into master
