### PR TITLE
Fix #24363: Crash on creating new part in some scores

### LINKED ISSUE #24363: Crash adding new part in score with pick-up or non-counted measures
### Issue type

Crash or freeze

### Description with steps to reproduce

When I open the attached score (contained in the ZIP file), MuseScore Studio 4.4.0 crashes when trying to add a new part in the parts dialog.

[Glinka_Drei_Russische_Lieder_VlVaPno_I.zip](https://github.com/user-attachments/files/16830138/Glinka_Drei_Russische_Lieder_VlVaPno_I.zip)

The score has initially been created using a PDF import and manually cleaned up afterwards.

Console output is the following:

```
$ /Applications/MuseScore\ 4.app/Contents/MacOS/mscore Glinka_Drei_Russische_Lieder_VlVaPno_I.mscz
qt.qml.typeregistration: Invalid QML element name "IconCode"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "MusicalSymbolCodes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "ContainerType"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "NavigationEvent"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "MUAccessible"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "CompareType"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "SelectionMode"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "ToolBarItemType"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "DockToolBarAlignment"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "Location"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "CloudVisibility"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "SaveToCloudResponse"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "DirectionTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "SlurTieTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "NoteHead"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "Beam"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "Hairpin"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "OrnamentTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "Dynamic"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "Glissando"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "CommonTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "BarlineTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "MarkerTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "KeySignatureTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "AccidentalTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "FretDiagramTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "LineTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "TextTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "ArticulationTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "AmbitusTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "ChordSymbolTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "BendTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "TremoloBarTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "TremoloTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "VoiceTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "InstrumentsTreeItemType"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "StandardButton"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "SaveLocationType"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "GenerateAudioTimePeriodType"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "MigrationType"; value type names should begin with a lowercase letter
20:33:24.210 | INFO  | main_thread     | GlobalModule::onPreInit | log path: /Users/wglas/Library/Application Support/MuseScore/MuseScore4/logs/MuseScore_240901_203324.log
20:33:24.210 | INFO  | main_thread     | GlobalModule::onPreInit | === Started MuseScore Studio 4.4.0, build: 242390800 ===
20:33:24.212 | INFO  | main_thread     | LanguagesService::effectiveLanguageCode | System language code: "de-AT" 
20:33:24.212 | ERROR | main_thread     | LanguagesService::setCurrentLanguage | Error loading translator "/Applications/MuseScore 4.app/Contents/Resources//locale/qt_de.qm" 
20:33:24.212 | WARN  | main_thread     | IpcSocket::connect | failed connect to server
20:33:24.212 | WARN  | main_thread     | IpcSocket::connect | failed connect to server
20:33:24.213 | INFO  | main_thread     | IpcSocket::connect | success connected to ipc server
20:33:24.213 | INFO  | 0x16dddb000     | IpcServer::listen | id: "d6125c77c2e840f9ba59977eb7e4a2a3" 
2024-09-01 20:33:24.218 mscore[61962:970701] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
20:33:24.234 | INFO  | main_thread     | DiagnosticsModule::onInit | success start crash handler
20:33:24.339 | INFO  | main_thread     | OSXAudioDriver::open | Connected to Systems default with bufferSize 512, sampleRate 44100
20:33:24.923 | ERROR | main_thread     | MuseSamplerLibHandler::MuseSamplerLibHandler | Unable to open MuseSampler library, path: /Users/wglas/Library/Application Support/MuseSampler/lib/libMuseSamplerCoreLib.dylib
20:33:24.923 | ERROR | main_thread     | MuseSamplerResolver::doInit | Incompatible MuseSampler library; ignoring
20:33:24.923 | ERROR | main_thread     | MuseSamplerLibHandler::MuseSamplerLibHandler | Unable to open MuseSampler library, path: /usr/local/lib/libMuseSamplerCoreLib.dylib
20:33:24.923 | ERROR | main_thread     | MuseSamplerResolver::doInit | Incompatible MuseSampler library; ignoring
20:33:24.926 | WARN  | main_thread     | Qt              | QIODevice::read (QFile, "/Users/wglas/Library/Application Support/MuseScore/MuseScore4/shortcuts.xml"): device not open
20:33:24.927 | WARN  | main_thread     | Qt              | QIODevice::read (QFile, "/Users/wglas/Library/Application Support/MuseScore/MuseScore4/midi_mappings.xml"): device not open
20:33:25.251 | WARN  | main_thread     | AbstractCloudService::readTokens | Could not find the tokens file: /Users/wglas/Library/Application Support/MuseScore/MuseScore4/audiocom_cred.dat
20:33:25.623 | WARN  | main_thread     | Qt              | QQmlEngine::setContextForObject(): Object already has a QQmlContext
20:33:25.636 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/internal/PopupContent.qml:81:5: QML QQuickItem: Binding loop detected for property "implicitWidth"

20:33:25.636 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/internal/PopupContent.qml:81:5: QML QQuickItem: Binding loop detected for property "implicitWidth"
20:33:25.636 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/internal/PopupContent.qml:81:5: QML QQuickItem: Binding loop detected for property "implicitWidth"

20:33:25.636 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/internal/PopupContent.qml:81:5: QML QQuickItem: Binding loop detected for property "implicitWidth"
20:33:25.671 | ERROR | main_thread     | ExtensionsConfiguration::manifestConfigs | failed read config data, err: [406] Beim Lesen der Datei ist ein Fehler aufgetreten, file: /Users/wglas/Library/Application Support/MuseScore/MuseScore4/plugins/plugins.json
20:33:25.715 | INFO  | main_thread     | ActionsDispatcher::dispatch | try call action: file-open
20:33:25.715 | INFO  | main_thread     | ProjectActionsController::openProject | Try open project: url = "file:///Users/wglas/privat/Heidemarie/Glinka_Drei_Russische_Lieder_VlVaPno_I.mscz" , displayNameOverride = "" 
20:33:25.819 | ERROR | main_thread     | MuseSoundsCheckUpdateScenario::doCheckForUpdate | Unable to check for update, error: [1701] 
20:33:26.300 | INFO  | 0x16e123000     | FluidSynth::addSoundFonts | success load soundfont: /Applications/MuseScore 4.app/Contents/Resources/sound/MS Basic.sf3
20:33:26.301 | INFO  | 0x16e123000     | FluidSynth::addSoundFonts | success load soundfont: /Applications/MuseScore 4.app/Contents/Resources/sound/MS Basic.sf3
20:33:26.323 | INFO  | 0x16e123000     | FluidSynth::addSoundFonts | success load soundfont: /Applications/MuseScore 4.app/Contents/Resources/sound/MS Basic.sf3
20:33:26.323 | INFO  | 0x16e123000     | FluidSynth::addSoundFonts | success load soundfont: /Applications/MuseScore 4.app/Contents/Resources/sound/MS Basic.sf3
20:33:26.794 | ERROR | main_thread     | UpdateScenario::doCheckForUpdate | Unable to check for update, error: [1701] 
20:33:26.833 | INFO  | 0x16e123000     | FluidSynth::addSoundFonts | success load soundfont: /Applications/MuseScore 4.app/Contents/Resources/sound/MS Basic.sf3
20:33:26.833 | INFO  | 0x16e123000     | FluidSynth::addSoundFonts | success load soundfont: /Applications/MuseScore 4.app/Contents/Resources/sound/MS Basic.sf3
20:33:26.846 | INFO  | 0x16e123000     | FluidSynth::addSoundFonts | success load soundfont: /Applications/MuseScore 4.app/Contents/Resources/sound/MS Basic.sf3
20:33:26.846 | INFO  | 0x16e123000     | FluidSynth::addSoundFonts | success load soundfont: /Applications/MuseScore 4.app/Contents/Resources/sound/MS Basic.sf3
20:33:26.860 | INFO  | 0x16e123000     | FluidSynth::addSoundFonts | success load soundfont: /Applications/MuseScore 4.app/Contents/Resources/sound/MS Basic.sf3
20:33:26.861 | INFO  | 0x16e123000     | FluidSynth::addSoundFonts | success load soundfont: /Applications/MuseScore 4.app/Contents/Resources/sound/MS Basic.sf3
20:33:26.863 | INFO  | 0x16e123000     | FluidSynth::addSoundFonts | success load soundfont: /Applications/MuseScore 4.app/Contents/Resources/sound/MS Basic.sf3
20:33:26.864 | INFO  | 0x16e123000     | FluidSynth::addSoundFonts | success load soundfont: /Applications/MuseScore 4.app/Contents/Resources/sound/MS Basic.sf3
20:33:29.155 | INFO  | main_thread     | ActionsDispatcher::dispatch | try call action: parts
20:33:29.166 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/Ui/InteractiveProvider.qml:148: Error: Cannot assign to non-existent property "sync"
[61964:970792:20240901,203330.706186:WARNING in_range_cast.h:38] value -97304226 out of range
[61964:970793:20240901,203330.710435:ERROR directory_reader_posix.cc:43] opendir /Users/wglas/Library/Application Support/MuseScore/MuseScore4/logs/dumps/attachments/2569b0d6-41ae-422b-a41b-491b19f4a634: No such file or directory (2)
[61964:970792:20240901,203330.710610:WARNING crash_report_exception_handler.cc:235] UniversalExceptionRaise: (os/kern) failure (5)
Segmentation fault: 11
```

### Supporting files, videos and screenshots

[Glinka_Drei_Russische_Lieder_VlVaPno_I.zip](https://github.com/user-attachments/files/16830138/Glinka_Drei_Russische_Lieder_VlVaPno_I.zip)

### What is the latest version of MuseScore Studio where this issue is present?

OS: macOS 14.6, Arch.: arm64, MuseScore Studio version (64-bit): 4.4.0-242390800, revision: github-musescore-musescore-0fcd11b

### Regression

I was unable to check

### Operating system

macOS 14.6.1, arm64

### Additional context

_No response_

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mathesoncalum**
Resolves: #24363

### CODE REVIEW

File: src/engraving/dom/segmentlist.cpp [hunk 1]
```diff
@@ -48,11 +48,10 @@ SegmentList SegmentList::clone() const
 
 Segment* SegmentList::firstActive() const
 {
-    Segment* segment = m_first;
-    if (segment->isActive()) {
-        return segment;
+    if (Segment* segment = m_first) {
```
Comment (mike-spa) [inline src/engraving/dom/segmentlist.cpp:51]: Is it actually ok for m_first to be null? Cause that means that the Measure contains no Segments at all. Do we actually allow that? Is it just a temporary state?

**Review by mike-spa — APPROVED** [review]

**Comment by zacjansheski** [comment]
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/24363 FIXED
