### PR TITLE
fix #19480 last tied note accidentals

### LINKED ISSUE #19480: removing or adding accidental to first tied note causes wrong last tied note
### Issue type

Engraving bug

### Bug description

If there are tied notes and user adds accidental to first one (or remove), last tied note became wrong.

### Steps to reproduce

1. write tied notes
2. add accidental to first note
3. see - last note is corrupted

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/1646034/99e1843b-30ef-4a7d-aa63-55347663705f

### MuseScore Version

master

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Ubuntu 22.04

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sammik**
Resolves: #19480 

Caused by [43df579](https://github.com/musescore/MuseScore/pull/18780/commits/43df579064264092db0265dcf7e63b9781605409) 

Last tied note was excluded by for loop condition

I reverted that change and added other safety check(s)

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [x] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by sammik** [comment]
@mike-spa

**Review by mike-spa — APPROVED** [review]

**Review by oktophonie — APPROVED** [review]

File: src/engraving/dom/cmd.cpp [hunk 1]
```diff
@@ -2032,8 +2032,12 @@ static void changeAccidental2(Note* n, int pitch, int tpc)
...
         } else {
-            for (Note* nn = n; nn && nn->tieFor(); nn = nn->tieFor()->endNote()) {
-                score->undo(new ChangePitch(nn, pitch, tpc1, tpc2));
+            Note* nn = n;
+            while (nn && nn->tieFor()) {
+                nn = nn->tieFor()->endNote();
+                if (nn) {
+                    score->undo(new ChangePitch(nn, pitch, tpc1, tpc2));
+                }
             }
```
Comment (cbjeukendrup) [inline src/engraving/dom/cmd.cpp:2041]: Why not:
```suggestion
            for (Note* nn = n; nn; nn = nn->tieFor() ? nn->tieFor()->endNote() : nullptr) {
                score->undo(new ChangePitch(nn, pitch, tpc1, tpc2));
            }
```

Comment (sammik) [reply src/engraving/dom/cmd.cpp:2041]: > Why not:
I think
1. becouse `endNote()` may by `nullptr`, so we would need nullcheck anyway
2. because we dont need to change `n` (which is tie start note), but need to start with next tied note

Comment (cbjeukendrup) [reply src/engraving/dom/cmd.cpp:2041]: > 1. becouse `endNote()` may by `nullptr`, so we would need nullcheck anyway

That would be done by the `; nn;`. 

Anyway, I'll stop nitpicking about things like this :)
