### PR TITLE
fixed #11234: External MIDI keyboard unable to play MuseScore instruments (Sound preview not working)

### LINKED ISSUE #11234: [MU4 Issue] External MIDI keyboard unable to play MuseScore instruments (Sound preview not working)
**Describe the bug**
There has been a regression in MS4. Now, the MuseScore instruments _cannot be played at all_. Input is only possible in note input mode, which of course stops the user from using the software to test the various instrument sounds or to demo ideas _without_ commiting them to notation.

**To Reproduce**
1. Ensure that your external MIDI keyboard is connected before launching MS4, and that the settings in Preferences > I/O are correct. 
2. Create a jazz combo from the Template secion, for example.
3. Click on a rest in the top staff and play the MIDI keyboard. Try other staves as well.

_Actual result_: No sound. 

**Expected behavior**

As MuseScore 2, the user should be able to click on any staff in non-note-input mode and be able to play the staff instrument.

**Platform information**
OS: Linux Mint 20.1, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-2059995262, revision: github-musescore-musescore-cafefd7 . Akai LPK25 USB keyboard.

### PR DESCRIPTION
**Pull request by Eism**
Resolves: #11234

### CODE REVIEW

File: src/notation/internal/notationmidiinput.h [hunk 1]
```diff
@@ -57,7 +57,8 @@ class NotationMidiInput : public INotationMidiInput
     mu::engraving::Score* score() const;
 
     void doProcessEvents();
-    Note* onAddNote(const midi::Event& e);
+    Note* addNoteToScore(const midi::Event& e);
```
Comment (vpereverzev) [inline src/notation/internal/notationmidiinput.h:60]: Is that really necessary to return a value here? Looks like it could be 'void' instead

**Review by vpereverzev — APPROVED** [review]

File: src/notation/internal/notationmidiinput.h (hunk 1 above)
Comment (Eism) [reply src/notation/internal/notationmidiinput.h:60]: The added note is needed for playing
```
    if (note) {
        notes.push_back(note);
    }
    if (!notes.empty()) {
        playbackController()->playElements(notes);
    }
```

**Comment by DmitryArefiev** [comment]
Tested #11234 on Win10, Mac12, LinuxMint 20.2 - almost **FIXED**   

Related issue logged separately #13381
