### PR TITLE
Fix #18312 - ensure stem direction is updated correctly in tremolo properties pane

### LINKED ISSUE #18312: Tremolo stem direction does not update in Properties panel when tremolos are flipped with keyboard shortcut
(Spun off from https://github.com/musescore/MuseScore/pull/18259; thanks to @LupusCaeruleus for the original)

### Issue type

UI bug

### Bug description

Unlike independent notes, pressing X to flip the tremolo beam will not update the state of the Stem direction buttons in the properties panel. The buttons will only update after the user de-select and re-select the tremolo notes.

### Steps to reproduce

1. Select a tremolo beam, press X for multiple times.
2. See the Stem direction buttons in the properties panel.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/20604032/e8ef884d-fff1-4ed7-b2fd-dd6d5b9c86d1

### MuseScore Version

4.1.0

### Regression

No.

### Operating system

Windows 10, Linux

### PR DESCRIPTION
**Pull request by wizofaus**
Resolves: #18312

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

File: src/inspector/models/notation/tremolos/tremolosettingsmodel.cpp [hunk 1]
```diff
@@ -70,6 +70,11 @@ void TremoloSettingsModel::resetProperties()
     m_direction->resetToDefault();
 }
 
+void TremoloSettingsModel::onNotationChanged(const PropertyIdSet&, const StyleIdSet&)
+{
+    loadProperties();
+}
```
Comment (wizofaus) [inline src/inspector/models/notation/tremolos/tremolosettingsmodel.cpp:76]: NB at least InspectorModelWithVoiceAndPositionOptions has exactly the same implementation, other models tend to check whether the changed property set contains the relevant ID, but it strikes me as premature optimisation...

Comment (RomanPudashkin) [reply src/inspector/models/notation/tremolos/tremolosettingsmodel.cpp:76]: And it's not perfectly done in that model either. You should check if PropertyIdSet contains the required properties

Comment (wizofaus) [reply src/inspector/models/notation/tremolos/tremolosettingsmodel.cpp:76]: Ok so can I propose as a compromise:

a) we add "loadProperties( const PropertyIdSet&, const StyleIdSet&) to AbstractInspectorModel, and the default implementation of onNotationChanged is to call this
b) all models should only have a single loadProperties( ) function, whereby the assumption is that if the sets are empty, then all properties should be loaded.

Because the current duplication of code seems to be highly likely to lead to unexpected behaviour in the future if one version of loadProperties( ) is updated differently from the other.

Comment (RomanPudashkin) [reply src/inspector/models/notation/tremolos/tremolosettingsmodel.cpp:76]: Let's avoid any refactoring within the scope of this PR and only change the implementation of TremoloSettingsModel::onNotationChanged

Comment (wizofaus) [reply src/inspector/models/notation/tremolos/tremolosettingsmodel.cpp:76]: But then you're asking me to continue the pattern of code duplication in the other models that we really should be trying to avoid. If you'd prefer to do the refactoring yourself then ok, as that will fix this issue and prevent similar future issues.

Comment (wizofaus) [reply src/inspector/models/notation/tremolos/tremolosettingsmodel.cpp:76]: If you can advise how we can get this closed without the code duplication issue that exists in the other property model classes I'd like to get this one approved and merged.

Comment (cbjeukendrup) [reply src/inspector/models/notation/tremolos/tremolosettingsmodel.cpp:76]: @wizofaus I would suggest to look at `AppearancePreferencesModel::loadProperties`. That implementation is perhaps not perfect either, but probably the best we can get without a lot of refactoring.

Comment (wizofaus) [reply src/inspector/models/notation/tremolos/tremolosettingsmodel.cpp:85]: Seems a reasonable compromise, done.

**Review by RomanPudashkin — APPROVED** [review]

**Comment by zacjansheski** [comment]
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/18312 FIXED
