### PR TITLE
Remove system locks containing mmRests on certain operations

### LINKED ISSUE #27242: Hiding all staves then unhiding one or more staves caused score to display on a single system (system lock interaction?)
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

I don't know how to replicate this - after working on the score some more it stopped happening.
What I did was:
- Hide all staves using the Layout panel
- Unhide one or more staves
- The score has become mulch (it tries to display the entire piece on one system for some reason).

Using "undo" to reverse the unhiding/hiding of staves restored the score to how it was supposed to look so I could continue working without issue. 

### Supporting files, videos and screenshots

Image
Image

### What is the latest version of MuseScore Studio where this issue is present?

4.5.0

### Regression

I was unable to check

### Operating system

Linux Mint 22.1

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mike-spa**
Resolves: #27242 

In https://github.com/musescore/MuseScore/pull/26136 I made an effort to maintain the score layout somewhat reversible upon changing multirests. For example, if a System Lock contains a multirest, and the multirest gets deactivated, then the same SystemLock will contain all the underlying measures of the multirest.

It's now clear to me that that's a bad idea, and that mapping System Locks across multirest changes is just not feasible. Obvious example (which is also the cause of the linked issue) is the case of adding a new instrument to a part. The new instrument may play in all of the places where the previous one had multirests, and if we keep the measures previously grouped in the multirests all locked together we can easily end up with the whole score compressed in one system.

I think the only safe way to play this is that, when some specific operations are performed which may cause multirests to ungroup, we just remove any System Locks containing multirests. These operations are, in particular
- Turning multirests off from style
- Turning a new staff visible
- Turning a new part visible
- Inserting a new part

### CODE REVIEW

File: src/engraving/dom/score.cpp [hunk 1]
```diff
@@ -5816,6 +5816,17 @@ int Score::visiblePartCount() const
     return count;
 }
 
+int Score::visibleStavesCount() const
```
Comment (cbjeukendrup) [inline src/engraving/dom/score.cpp:5819]: Preferably size_t

**Review by ghost — APPROVED** [review]

**Review by miiizen — APPROVED** [review]
