### PR TITLE
Remove stemArrangement property from Slur

### LINKED ISSUE #28151: Slur uneditable when entered from palette on specific arrangement
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. Enter these 4 notes (the stem arrangement on start and end note is relevant)
2. List-select start and end note
3. Enter a slur from the Articulation palette
4. Try to drag any of the grip points except the center one: see the slur won't respond

Image

### Supporting files, videos and screenshots

See description

### What is the latest version of MuseScore Studio where this issue is present?

Released 4.5.2

### Regression

No.

### Operating system

Any

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mike-spa**
Resolves: #28151 

_Everything_ about this is wrong. This property was created to only work on copy-paste and never gets updated during layout. In this case, it gets copy-pasted from the palette element and results in the slur grip points getting constantly reset (saving-closing-reopening the file fixes it as the property is then forgotten).

### CODE REVIEW

File: src/engraving/rendering/score/slurtielayout.cpp [hunk 1]
```diff
@@ -1018,7 +1010,7 @@ void SlurTieLayout::avoidCollisions(SlurSegment* slurSeg, PointF& pp1, PointF& p
             }
         } else if (!slurSeg->isEndPointsEdited()) {
             // In the odd iterations, adjust the end points
-            // Slurs steeper than 45° are gently compensated
+            // Slurs steeper than 45Ãƒâ€šÃ‚Â° are gently compensated
```
Comment (cbjeukendrup) [inline src/engraving/rendering/score/slurtielayout.cpp:1013]: Wonder what happened here (was it Uncrustify? 😄)

**Review by ghost — APPROVED** [review]

File: src/engraving/rendering/score/slurtielayout.cpp (hunk 1 above)
Comment (mike-spa) [reply src/engraving/rendering/score/slurtielayout.cpp:1013]: Urghhhhhhhhhh yes

**Review by miiizen — APPROVED** [review]

**Review by miiizen — CHANGES_REQUESTED** [review]
Whoops, too hasty - some tests need updating
