### PR TITLE
Fix #20922: Visibility of "insert special characters" button

### LINKED ISSUE #20922: 'Insert special characters' does not load when opening Properties with text editing active
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

If the properties panel is not currently active (i.e. it's closed or a different panel tab is open above it) AND a text object is in editing mode, making Properties active does not show the 'Insert special characters' button in the text section as it should.

Normally, with Properties active, the button shows up once a user starts editing a text element (see first half of screen recording below).

### Steps to reproduce

1. Close the properties panel (F8)
2. Double click into a text element in the score
3. Open the properties panel, see that 'Insert special characters' is not there
4. Move the cursor within the text element and see that it shows up

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/20806406/2cd4d285-30be-4bf8-b4e1-f60d8d409087

### MuseScore Version

MuseScore version (64-bit): 4.2.0-233521125, revision: github-musescore-musescore-eb8d33c

### Regression

I don't know

### Operating system

OS: macOS 14.1, Arch.: x86_64

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mathesoncalum**
Resolves: #20922

### CODE REVIEW

**Review by Eism — APPROVED** [review]

File: src/inspector/models/text/textsettingsmodel.cpp [hunk 1]
```diff
@@ -42,6 +42,7 @@ TextSettingsModel::TextSettingsModel(QObject* parent, IElementRepositoryService*
 {
     setSectionType(InspectorSectionType::SECTION_TEXT);
     setTitle(qtrc("inspector", "Text"));
+    setIsSpecialCharactersInsertionAvailable(isTextEditingStarted());
```
Comment (Eism) [inline src/inspector/models/text/textsettingsmodel.cpp:45]: I would recommend moving the setting of the value under the isTextEditingChanged().onNotify processing because these things are linked

**Comment by zacjansheski** [comment]
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/20922 FIXED
