### PR TITLE
Fix handbell palette added twice and wrong inversion color

### LINKED ISSUE #29022: New Handbell palette appears twice
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

On latest nightly, the new hanbell palette is duplicated, issue remains after factory reset

### Supporting files, videos and screenshots

Image

### What is the latest version of MuseScore Studio where this issue is present?

OS: macOS Sequoia (15.5), Arch.: arm64, MuseScore Studio version (64-bit): 4.6.0-252120329, revision: github-musescore-musescore-a35a94e

### Regression

No.

### Operating system

MacOS15

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### LINKED ISSUE #29029: Some Handbell palettes are in wrong colour
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

Latest nightly, some palettes are in black and not in their theme's font_primary colour

### Supporting files, videos and screenshots

Image

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore 4.6.0.252120329 Nightly

### Regression

No.

### Operating system

macOS 15.5

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mike-spa**
Resolves: #29022 
Resolves: #29029

### CODE REVIEW

File: src/engraving/rendering/single/singledraw.cpp [hunk 1]
```diff
@@ -461,6 +461,7 @@ void SingleDraw::draw(const Articulation* item, Painter* painter)
     if (item->textType() == ArticulationTextType::NO_TEXT) {
         item->drawSymbol(item->symId(), painter, PointF(-0.5 * item->width(), 0.0));
     } else {
+        item->text()->setColor(item->curColor());
```
Comment (cbjeukendrup) [inline src/engraving/rendering/single/singledraw.cpp:464]: Alternatively, I believe you could make `EngravingItem::setColorsInverionEnabled` virtual, and override it in Articulation just like `setSelected`.

Comment (mike-spa) [reply src/engraving/rendering/single/singledraw.cpp:464]: As you pointed out in the linked issue, this needs a proper refactor at some point. For now, I'd just prefer to stick to the bare minimum quick fix. (In general, I quite hate the idea that the EngravingItem class is aware of something so completely unrelated such as the dark or light UI theme, so if I can I'd rather move this out entirely).

Comment (cbjeukendrup) [reply src/engraving/rendering/single/singledraw.cpp:464]: Yeah... ideally it would be passed in via a parameter to the draw methods or so. 

Anyway, if we're not doing that refactor now, I think I'll just merge that PR that I linked in the linked issue. (https://github.com/musescore/MuseScore/pull/27642)
Disadvantage is that that gives us two entirely different fixes for two things that are essentially exactly the same problem, but so be it.

**Comment by zacjansheski** [comment]
Tested on MacOS 15, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/29022 FIXED
https://github.com/musescore/MuseScore/issues/29029 FIXED
