### PR TITLE
[4.6.3] Fix #30460: fix sound preview of playing technique annotations

### LINKED ISSUE #30460: Sound preview does not respect playing techniques
### Issue type

General playback bug

### Description with steps to reproduce

1. Enter a bunch of notes for a string instrument like a violin.
2. Select one note and click on pizz. in the text palette.

Expected result
The note will be played pizzicato.
Actual result:
The note is played arco.

### Supporting files, videos and screenshots

file:///home/omega13a/Documents/MuseScore4/Scores/Mussorgsky-Pictures_At_An_Exhibition.zip

### In which versions of MuseScore Studio is this issue present?

4.6.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Fedora

### Additional context

Strange thing is that when I use staff text to modify the playing technique, it works perfectly meaning if I want the playback to be correct, I have to replace all the places in my projects (there is more then one) I use pizz.  with staff text and that would be a major pain (arco doesn't seem to be effected).

This is in MuseScore 4.6.1 on Fedora with MuseSounds and I just recently updated from MuseScore 4.5.2.

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Resolves: https://github.com/musescore/MuseScore/issues/30460

### CODE REVIEW

File: src/engraving/playback/metaparsers/notearticulationsparser.cpp [hunk 1]
```diff
@@ -131,11 +131,11 @@ ArticulationType NoteArticulationsParser::articulationTypeByNoteheadGroup(const
     }
 }
 
-void NoteArticulationsParser::parsePlayingTechnique(const RenderingContext& ctx, mpe::ArticulationMap& result)
+void NoteArticulationsParser::parsePlayingTechnique(const Note* note, const RenderingContext& ctx, mpe::ArticulationMap& result)
 {
-    int chordPosTickWithOffset = ctx.nominalPositionStartTick + ctx.positionTickOffset;
+    int notePosTickWithOffset = note->tick().ticks() + ctx.positionTickOffset;
```
Comment (cbjeukendrup) [inline src/engraving/playback/metaparsers/notearticulationsparser.cpp]: I must say I don't fully understand why/when `note->tick().ticks()` is different from `ctx.nominalPositionStartTick`

**Comment by DmitryArefiev** [comment]
Tested #30460 on Win10, Mac13.7.8, LinuxUbuntu24.04.3 LTS - **FIXED**
