### PR TITLE
Fix #7654: Added ability to hide multiple instruments at once

### LINKED ISSUE #7654: [MU4 Issue] If multiple instruments selected and click to hide them, only one item hidden
**Describe the bug**
Only clicked instrument hidden

**To Reproduce**
1. Create a score with multiple instruments
2. Select several instruments from the left side panel
3. Click on an eye near instrument to hide it

**Expected behavior**
All selected instruments should be hidden when we click on an eye near any of selected instruments

**Desktop (please complete the following information):**
MacOS

### PR DESCRIPTION
**Pull request by HemantAntony**
Resolves: #7654
Closes: #7940

This PR solved #7654 and also adds the ability to select multiple instruments using Ctrl

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

File: src/instrumentsscene/view/instrumentspaneltreemodel.cpp [hunk 1]
```diff
@@ -48,13 +48,10 @@ static QString notationToKey(const INotationPtr notation)
 }
 
 InstrumentsPanelTreeModel::InstrumentsPanelTreeModel(QObject* parent)
-    : QAbstractItemModel(parent)
+    : QAbstractItemModel(parent), m_selectionModel(new ItemMultiSelectionModel(this))
 {
     m_partsNotifyReceiver = std::make_shared<async::Asyncable>();
 
-    m_selectionModel = new ItemMultiSelectionModel(this);
-    m_selectionModel->setAllowedModifiers(Qt::ShiftModifier);
```
Comment (cbjeukendrup) [inline src/instrumentsscene/view/instrumentspaneltreemodel.cpp:56]: Does moving instruments up and down still work correctly if there is a non-contiguous selection?

Comment (HemantAntony) [reply src/instrumentsscene/view/instrumentspaneltreemodel.cpp:56]: It didn't at that time. It got all messed up.

I don't know about the present condition. But I think I will remove that commit. I don't think the problem of not being able to select instrument is too big (@Tantacrul hope you agree)

File: src/instrumentsscene/view/instrumentspaneltreemodel.cpp [hunk 2]
```diff
@@ -414,6 +411,31 @@ bool InstrumentsPanelTreeModel::moveRows(const QModelIndex& sourceParent, int so
...
+    bool toVisible = true;
+
+    for (QModelIndex index : selectedIndexes) {
+        AbstractInstrumentsPanelTreeItem* item = modelIndexToItem(index);
+        item->isVisible() ? visibleItems++ : hiddenItems++;
+    }
+
+    if (visibleItems > hiddenItems) {
+        toVisible = false;
+    }
```
Comment (cbjeukendrup) [inline src/instrumentsscene/view/instrumentspaneltreemodel.cpp:431]: Would it be an idea to base the new visibility on the old visibility of the instrument that was clicked, instead of on the number of visible selected instruments?

i.e. If there are two instruments selected, and the first is visible, but the second not, and you click on the eye icon for the first instrument, then both instruments become invisible, because the first instrument was visible.
And if you'd click the eye icon for the second instrument, both instruments become visible, because the second instrument was not visible. 

I think that would feel more predictable / easier for the user to figure out what the pattern is.

File: src/instrumentsscene/view/instrumentspaneltreemodel.cpp [hunk 3]
```diff
@@ -414,6 +411,31 @@ bool InstrumentsPanelTreeModel::moveRows(const QModelIndex& sourceParent, int so
     return true;
 }
 
+void InstrumentsPanelTreeModel::changeVisibilityOfSelectedRows()
```
Comment (cbjeukendrup) [inline src/instrumentsscene/view/instrumentspaneltreemodel.cpp:414]: Tiny thing: I would call it <code><b>toggle</b>VisibilityOfSelectedRows</code>

**Comment by cbjeukendrup** [comment]
@HemantAntony Tiny remark: the commit message of the first commit mentions the wrong issue number. So if you are going to force-push this once more, it'd be great if you could fix that too.

File: src/instrumentsscene/view/instrumentspaneltreemodel.cpp (hunk 2 above)
Comment (HemantAntony) [reply src/instrumentsscene/view/instrumentspaneltreemodel.cpp:431]: Okay that seems like a better idea

File: src/instrumentsscene/view/instrumentspaneltreemodel.cpp (hunk 1 above)
Comment (cbjeukendrup) [reply src/instrumentsscene/view/instrumentspaneltreemodel.cpp:56]: I believe I had long ago created an algorithm for moving non-contiguous selections up and down. It was aimed at the parts dialog (never got merged into there though), but could probably be adapted for the instruments panel. I'll try to reuse it after this PR gets merged. But for now, let's indeed drop the commit from this PR.

**Comment by HemantAntony** [comment]
Also linked #7940 to be closed if this PR gets accepted

**Comment by Tantacrul** [comment]
I've tested it. Working great.

**Comment by Tantacrul** [comment]
@RomanPudashkin - same question :)

Are you happy with this solution? If so, it is working well from a functional point of view

**Comment by RomanPudashkin** [comment]
> @RomanPudashkin - same question :)
> 
> Are you happy with this solution? If so, it is working well from a functional point of view

Yes, I'm happy! Let's merge it :)
