### PR TITLE
Fix #26896 and #26170: Fixed radio button UX/UI bugs

### LINKED ISSUE #26896: Some radio buttons need tweaking
### Issue type

UI bug (incorrect info or interface appearance)

### Supporting files, videos and screenshots

_**TRANSPOSE DIALOG**_
The circles in the radio buttons are off-centered
Image

These are too close
Image
Image

_**STYLE DIALOG**_
Image
Also these two buttons.

Exactly the same in light mode.

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.6.0-250620308, revision: github-musescore-musescore-76dba2b

### Regression

I was unable to check

### Operating system

Windows 10 Pro

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by not-rubenz**
Clicking multiple times on some radio boxes no longer toggles them. Fixed background color of the radio buttons and placed them correctly.

Resolves: #26896 
Resolves: #26170 

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

File: src/notation/view/widgets/editstyle.cpp [hunk 1]
```diff
@@ -2578,7 +2578,15 @@ void EditStyle::enableStyleWidget(const StyleId idx, bool enable)
 
 void EditStyle::enableVerticalSpreadClicked(bool checked)
 {
-    disableVerticalSpread->setChecked(!checked);
+    if (checked) {
+        setStyleValue(StyleId::enableVerticalSpread, true);
+        disableVerticalSpread->setChecked(false);
+    } else {
+        if (!disableVerticalSpread->isChecked()) {
+            setStyleValue(StyleId::enableVerticalSpread, false);
```
Comment (cbjeukendrup) [inline src/notation/view/widgets/editstyle.cpp:2586]: Shouldn't this be `true` as well?
```suggestion
            setStyleValue(StyleId::enableVerticalSpread, true);
```

**Review by cbjeukendrup — APPROVED** [review]

**Comment by zacjansheski** [comment]
Radio buttons and drop-downs are reversed visually

PR:
Screenshot 2025-03-20 at 3 18 51 PM


Nightly for reference:

Screenshot 2025-03-20 at 3 19 30 PM

**Comment by cbjeukendrup** [comment]
Sorry, I should have said that; I did it on purpose, because that seemed to make more sense. But maybe it doesn't. What do others think?

**Comment by zacjansheski** [comment]
@cbjeukendrup I think either way is fine really, but I think someone on the design team should look at it.  I'm not sure how I feel about the way the vertically centered drop-downs look

**Comment by cbjeukendrup** [comment]
FWIW, the motivation for the vertical centering is that otherwise the dropdowns make the spacing between the radio buttons very irregular.

**Comment by zacjansheski** [comment]
@cbjeukendrup makes sense.

I wonder if stacking dropdown and radio buttons would be better.

I'll defer to @avvvvve but if that holds this up too much, it's good as is (after I test functionality)

**Comment by cbjeukendrup** [comment]
@not-rubenz It is intentional, I added a commit to this branch, because I wanted to clean up the hardcoded heights of some radio buttons

**Comment by not-rubenz** [comment]
Oh ok, I also think that the swap between them would be more visually pleasant as it makes it less "noisy" with buttons.

**Comment by zacjansheski** [comment]
Tested on MacOS 15, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/26896 FIXED
https://github.com/musescore/MuseScore/issues/26170 FIXED

**Comment by avvvvve** [comment]
I agree with @zacjansheski  that the dropdowns should not be vertically centered to the radio buttons—can we just top-align them please? Swapping the left/right columns is fine.

Also, we need to fix this. The dialog was super narrow when I opened it in this build. Can we make the initial width it opens at something like 480px instead? @cbjeukendrup 

image

We should save the effort on other tweaks for when we rebuild this in QML. It needs a full design renovation :)

**Review by avvvvve — CHANGES_REQUESTED** [review]
see comment!

**Comment by cbjeukendrup** [comment]
How is this?
Scherm­afbeelding 2025-03-22 om 16 38 56

**Comment by zacjansheski** [comment]
Thank you!  Approved

**Comment by cbjeukendrup** [comment]
Thanks @not-rubenz! And sorry for my interference with your PR, in hindsight my changes were a bit too significant to just 'lift' with those of yours :)
