### PR TITLE
Remove empty segments without pushing the action to undo stack

### LINKED ISSUE #30149: Crash after revealing instruments in Part, Undo and Redo
### Issue type

Crash or freeze

### Description with steps to reproduce

1. Create score with 3 instruments
2. Open part
3. Show other 2 instruments
4. Undo two times
5. Redo two times

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/42296e21-6637-48a0-8ddf-d19198887bff

### What is the latest version of MuseScore Studio where this issue is present?

4.6.0-252661332 (RC 1)

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

all

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mike-spa**
The creation of the new segments is done via `Measure::getSegment` without adding it to the undo stack, so we can't instead add to the undo stack the removal of the empty ones, cause we're making the operation asymmetrical. We should add both or none, and I think none is the simpler option here.

Resolves: #30149

### CODE REVIEW

File: src/engraving/dom/excerpt.cpp [hunk 1]
```diff
@@ -1621,7 +1621,8 @@ void Excerpt::cloneStaff2(Staff* srcStaff, Staff* dstStaff, const Fraction& star
         for (Segment& seg : nm->segments()) {
             seg.checkEmpty();
             if (seg.empty()) {
-                score->doUndoRemoveElement(&seg);
+                nm->remove(&seg);
+                delete &seg;
```
Comment (cbjeukendrup) [inline src/engraving/dom/excerpt.cpp]: Isn't `seg.next()` read when advancing the iterator?

Comment (mike-spa) [reply src/engraving/dom/excerpt.cpp]: Ha, good catch thank you

**Review by miiizen — APPROVED** [review]
