### PR TITLE
Fix #16748: Fix articulation combinations on MXML import / export, and ensure placement of articulations is respected

### LINKED ISSUE #16748: MusicXML Accent-Staccato Export
### Issue type

Other type of issue

### Bug description

Notes marked with an accent-staccato articulation in the score are exported as staccato only.

### Steps to reproduce

1. Create a new score with any instrument
2. In a staff, add two notes
3. Select the first note, open articulations, and select "accent-staccato above"
4. Select the second note, then select "Staccato above"
5. Select the second note again, then select "Accent above"
6. Click File -> Export, set the format to MusicXML
7. Either open the exported MusicXML file, or  

### Screenshots/Screen recordings

A zip file with an mcsz and mxl is attached:
[accent+staccato.zip](https://github.com/musescore/MuseScore/files/10949794/accent%2Bstaccato.zip)

Measure from the mcsz file:
image

Measure from the mxl file:
image

### MuseScore Version

MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

### Regression

I don't know

### Operating system

Debian GNU/Linux bookworm/sid

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by asattely**
Resolves: https://github.com/musescore/MuseScore/issues/16748

This PR began as a direct port of https://github.com/musescore/MuseScore/pull/8190, which deals with articulation marks combining (such as tenuto-staccato being a single combined glyph). We also take care not to combine when the placement of the accidentals suggest that they have been manually set at one placement or another.

In testing this PR, I noticed that musescore doesn't export articulation placement at all, so I added that in as well, as per the MusicXML spec.

### CODE REVIEW

**Comment by asattely** [comment]
I'm out of time today but I will have tests for this one tomorrow, please stand by!

**Comment by Jojo-Schmitz** [comment]
Maybe #8514 would be a better basis?

File: src/importexport/musicxml/internal/musicxml/exportxml.cpp [hunk 1]
```diff
@@ -2741,68 +2741,95 @@ static void fermatas(const QVector<EngravingItem*>& cra, XmlWriter& xml, Notatio
...
+        break;
+
+    case SymId::articSoftAccentTenutoAbove:
+    case SymId::articSoftAccentTenutoBelow:
+        return { "soft-accent", "tenuto" };
+        break;
+
+    case SymId::articSoftAccentTenutoStaccatoAbove:
+    case SymId::articSoftAccentTenutoStaccatoBelow:
+        return { "soft-accent", "detached-legato" };
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/exportxml.cpp:2794]: Not `return { "staccato", "soft-accent", "tenuto" };`?

**Comment by Jojo-Schmitz** [comment]
One unit test needs fixing, https://github.com/musescore/MuseScore/actions/runs/4428468868/jobs/7767593095?pr=16828#step:9:9196

File: src/importexport/musicxml/internal/musicxml/exportxml.cpp (hunk 1 above)
Comment (asattely) [reply src/importexport/musicxml/internal/musicxml/exportxml.cpp:2794]: nope, detached-legato is the glyph for combined staccato and tenuto markings

Comment (Jojo-Schmitz) [reply src/importexport/musicxml/internal/musicxml/exportxml.cpp:2794]: OK, thanks for checking anyway ;-)

**Review by RomanPudashkin — APPROVED** [review]
