### PR TITLE
fix #12076: not breaking imported text line elements by rests

### LINKED ISSUE #12076: [MU4 Issue] [GP] Line elements are divided when rests present under it
**Describe the bug**
There're affected elements:
- octave up/down
- let-ring
- palm mute
- rasgueado

**To Reproduce**
1. Open the test file in MU4
[Line elements with rests.gp.zip](https://github.com/musescore/MuseScore/files/8929131/Line.elements.with.rests.gp.zip)
2. Pay attention to the division of line elements

**Screenshots**
Capture 2022-06-17_07-09-36_PM

**Expected behavior**
Line elements are not divided when rests present under it
Capture 2022-06-17_07-08-50_PM

### PR DESCRIPTION
**Pull request by alexpavlov96**
Resolves: *https://github.com/musescore/MuseScore/issues/12076*

*included rests in text line elements (ottavas, let ring, ...) while importing from gp*
*refactoring of text line elements in gp import module*

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

File: src/importexport/guitarpro/internal/gtp/gpconverter.cpp [hunk 1]
```diff
@@ -58,72 +58,72 @@
...
+        { String("DaSegnoAlCoda"), Jump::Type::DS_AL_CODA },
+        { String("DaSegnoAlDoubleCoda"), Jump::Type::DS_AL_DBLCODA },
+        { String("DaSegnoAlFine"), Jump::Type::DS_AL_FINE },
+        { String("DaSegnoSegno"), Jump::Type::DSS },
+        { String("DaSegnoSegnoAlCoda"), Jump::Type::DSS_AL_CODA },
+        { String("DaSegnoSegnoAlDoubleCoda"), Jump::Type::DSS_AL_DBLCODA },
+        { String("DaSegnoSegnoAlFine"), Jump::Type::DSS_AL_FINE },
+        { String("DaCoda"), Jump::Type::DCODA },
+        { String("DaDoubleCoda"), Jump::Type::DDBLCODA },
+        { String("DaCoda"), Jump::Type::DCODA },
```
Comment (cbjeukendrup) [inline src/importexport/guitarpro/internal/gtp/gpconverter.cpp:77]: The better solution (at least the solution that is used in most other places) is to prefix the literals with `u`, i.e. `u"DaCapo"`, `u"DaCapoAlFine"`.

**Review by RomanPudashkin — APPROVED** [review]

**Comment by boryskuzmenko** [comment]
🟢 **FIXED**
Tested on macOS 12, Win 11, Ubuntu 20

Please, merge to master
