### PR TITLE
Fix #32470: Tremolo & repeat selection interaction [4.7.0]

### LINKED ISSUE #32470: Tremolos no longer repeat with R
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

Write a note with a tremolo, list select, press R

### Supporting files, videos and screenshots

Image

### In which versions of MuseScore Studio is this issue present?

OS: macOS Tahoe (26.2), Arch.: arm64, MuseScore Studio version (64-bit): 4.7.0-260303043, revision: github-musescore-musescore-934b7a3

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

MacOS Tahoe 26.2

### Additional context

I think this might have been a necessary trade off for https://github.com/musescore/MuseScore/pull/28525

But if it could be resolved for parenthesis and articulations, I thought it would be worth investigating if iwe can do it for tremolos as well

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mathesoncalum**
Resolves: #32470

Hopefully this will be the last patch we add to this part of the code before we take a more holistic look at this system and how it relates to copy/paste.

The corresponding unit test now features a tremolo:

orig
ref

### CODE REVIEW

File: src/engraving/dom/paste.cpp [hunk 1]
```diff
@@ -320,7 +321,21 @@ bool Score::cmdRepeatListSelection()
...
         }
 
-        newNote->chord()->updateArticulations(sourceChord->articulationSymbolIds());
+        Chord* newChord = newNote->chord();
+
+        newChord->updateArticulations(sourceChord->articulationSymbolIds());
+
+        const TremoloSingleChord* oldTsc = sourceChord->tremoloSingleChord();
+        if (!newChord->tremoloSingleChord() && oldTsc) {
+            if (TremoloSingleChord* newTsc = oldTsc->clone()) {
```
Comment (cbjeukendrup) [inline src/engraving/dom/paste.cpp]: This null check seems unnecessary to me (otherwise we should null-check every usage of `new`, which is nonsense...)

**Comment by zacjansheski** [comment]
Tested on MacOS Tahoe 26.2, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/32470 FIXED
