### PR TITLE
Fix #17648: Audio bug on Windows when output device has more than 2 channels

### LINKED ISSUE #17648: Playback high pitched and/or sped up/faster when using multi-channel or surround WASAPI Audio Output (Buffering issue)
### Issue type

General playback bug

### Bug description

MuseScore 4 does not handle Surround WASAPI output correctly, the samples intended only for two channels gets split up into all channels (can be seen in my mixer software, see atached video), so when the remaining samples (in my case only 1/4 of all samples (7.1 configuration)) get played pack, it sounds hig pitched and sped up. I discovered this while testing builds for #15235 (Although the issue should persist scince MultiChannel Output was first introduced in #15698.

### Steps to reproduce

1. start a mu4 instance built with code from #15698.
2. select a multi channel WASAPI output in settings
3. Playback any note or song
4. Sounds high-pitched and sped up. In mixing software of the audio device it can be seen that all channels of it receive input, not just the first two.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/30872344/223803798-83b0316b-dd1f-4826-b072-44ac51783762.mp4

### MuseScore Version

>= 4.0.1

### Regression

No.

### Operating system

Windows 10

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mathesoncalum**
Resolves: #17648

The changes in this PR are effectively the same as those proposed [here](https://github.com/musescore/MuseScore/issues/17648#issuecomment-1554433697) (with some minor tweaks). As previously discussed, this approach is not ideal but will at least make playback usable while we work on a better solution.

Quick before/after demonstrating the effects of these changes with a virtual 5.1 setup (only the stereo channels are written to, and the audio is no longer glitchy):
before after

### CODE REVIEW

File: src/framework/audio/internal/platform/win/wasapiaudioclient.h [hunk 1]
```diff
@@ -71,6 +71,8 @@ struct WasapiAudioClient : implements<WasapiAudioClient, IActivateAudioInterface
     void setState(const DeviceState newState);
     void setStateAndNotify(const DeviceState newState, hresult resultCode);
 
+    std::vector<uint8_t> m_tempBuffer; //! NOTE: Used for surround workaround - see #17648
```
Comment (RomanPudashkin) [inline src/framework/audio/internal/platform/win/wasapiaudioclient.h:74]: m_surroundAudioBuffer? (to make the purpose of this buffer clearer)

File: src/framework/audio/internal/platform/win/wasapiaudioclient.cpp [hunk 2]
```diff
@@ -560,11 +560,33 @@ void WasapiAudioClient::getSamples(uint32_t framesAvailable)
...
+        if (clientFrameSize > muFrameSize) {
+            const size_t tempBufferDesiredSize = actualFramesToRead * muFrameSize;
+            if (m_tempBuffer.size() < tempBufferDesiredSize) {
+                m_tempBuffer.resize(tempBufferDesiredSize);
+            }
+
+            m_sampleRequestCallback(nullptr, m_tempBuffer.data(), (int)tempBufferDesiredSize);
+
+            for (uint32_t i = 0; i < actualFramesToRead; ++i) {
+                std::memcpy(data + i * clientFrameSize, m_tempBuffer.data() + i * muFrameSize, muFrameSize);
```
Comment (RomanPudashkin) [inline src/framework/audio/internal/platform/win/wasapiaudioclient.cpp:584]: Perhaps we should add a temp variable for i * clientFrameSize (or even for data + i * clientFrameSize), so it doesn't have to be recalculated twice

**Review by RomanPudashkin — APPROVED** [review]

**Review by RomanPudashkin — APPROVED** [review]

**Comment by cbjeukendrup** [comment]
Sorry I had one more idea about this: would it make sense to try to move as many calculations as possible out of getSamples? Perhaps we can pre-calculate some things at the moment that we 'open' the audio output, and then store one callback based on that, and just call that simple callback in getSamples. Or, Roman, do you think that's not a valuable optimisation?

**Comment by mathesoncalum** [comment]
@cbjeukendrup I think some of the small ones like `clientFrameSize` and `muFrameSize` could potentially be moved - but `framesAvailable` seems to change quite rapidly from call to call and a lot of the calculations depend on this.

**Comment by RomanPudashkin** [comment]
> Sorry I had one more idea about this: would it make sense to try to move as many calculations as possible out of getSamples? Perhaps we can pre-calculate some things at the moment that we 'open' the audio output, and then store one callback based on that, and just call that simple callback in getSamples. Or, Roman, do you think that's not a valuable optimisation?

tbh, I don't think it would make a big difference (the only things we can optimize here are this check `if (actualFramesToRead > 0)` and muFrameSize calculation). However, after this optimization, the code would be harder to maintain (as it would be scattered all over the driver implementation)

File: src/framework/audio/internal/platform/win/wasapiaudioclient.cpp [hunk 3]
```diff
@@ -560,11 +560,34 @@ void WasapiAudioClient::getSamples(uint32_t framesAvailable)
...
-    if (actualBytesToRead > 0) {
-        m_sampleRequestCallback(nullptr, data, actualBytesToRead);
+    if (actualFramesToRead > 0) {
+        // Based on the previous calculations, the only way that clientFrameSize will be larger than muFrameSize is
+        // if the client specifies more than 2 channels. MuseScore doesn't support this (yet), so we use a workaround
+        // where the missing channels are padded with zeroes...
+        if (clientFrameSize > muFrameSize) {
+            const size_t surroundBufferDesiredSize = actualFramesToRead * muFrameSize;
+            if (m_surroundAudioBuffer.size() < surroundBufferDesiredSize) {
+                m_surroundAudioBuffer.resize(surroundBufferDesiredSize);
```
Comment (RomanPudashkin) [inline src/framework/audio/internal/platform/win/wasapiaudioclient.cpp:578]: m_surroundAudioBuffer.resize(surroundBufferDesiredSize, 0); -- please add this for safety

**Comment by DmitryArefiev** [comment]
Tested #17648 on Win10. Looks as **FIXED**  via VB-Audio matrix (virtual audio routing app)
