### PR TITLE
[MU4] Fix #11549: Reinstate drag-and-drop interaction for SoundFont installation

### LINKED ISSUE #11549: [MU4 Issue] Reinstate drag-and-drop interaction for SoundFont installation
**Describe the bug**
In MS3.6, it was possible to install a SoundFont by dragging and dropping it into the main score window. This interaction has been lost in MS4 and is therefore a regression.  

**To Reproduce**
1. Drag and drop a SoundFont into the MuseScore 4 main window
Nothing happens

**Expected behavior**
This interaction should work as per MuseScore 3.6 (see videos):

1. Installing a SoundFont for the first time 

https://user-images.githubusercontent.com/86290556/167135182-dc184b6c-2c66-4bdb-9706-b156b9441897.mov

2. Messaging when a SoundFont has already been installed 

https://user-images.githubusercontent.com/86290556/167135311-f8550032-fa1e-4e02-89b4-8b293f866042.mov

3. Dialogs will obviously require updating. Please use the below as references for updated microcopy: 

Frame 137

Frame 138

Frame 139

**Platform information**
 - MacOS 12.3.1 (M1) 

Thanks!

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Resolves: https://github.com/musescore/MuseScore/issues/11549

### CODE REVIEW

File: src/framework/audio/internal/soundfontmanager.cpp [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+#include "translation.h"
+
+using namespace mu::audio;
+using namespace mu::audio::synth;
+using namespace mu::framework;
+
+mu::Ret SoundFontManager::installSoundFont(const SoundFontPath& path)
+{
+    std::string title = qtrc("audio", "Do you want to add the SoundFont: %1?")
+                        .arg(io::filename(path).toQString()).toStdString();
```
Comment (vpereverzev) [inline src/framework/audio/internal/soundfontmanager.cpp:33]: I think toStdString would be enough

**Review by vpereverzev — APPROVED** [review]

**Comment by RomanPudashkin** [comment]
@bkunda thanks for testing! The problem you found should be logged separately, as it is not directly related to this fix (the problem in the dialog component implementation)
