### PR TITLE
fix #15292: Opening a score (clicking its file) launches the homepage instead of opening the score view (macOS only)

### LINKED ISSUE #15292: [MU4 Issue] Opening a score (clicking its file) launches the homepage instead of opening the score view (macOS only)
Haven't seen a report of this which I'd find odd, considering opening a file is pretty common to do.

**To Reproduce**
1. Ensure MS4 is not running. Scores open properly if there is an existing instance running
1. Open any MS4 score (older score versions prompt the update notice and open the score properly).
2. Note that the program launches to the homepge. It does not navigate to the Score tab nor does it show it there either.

**Expected Behavior**
Opening a score should open an instance that presents the Score view.

**Platform information**
 - OS: macOS Monterey 12.6

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Resolves: https://github.com/musescore/MuseScore/issues/15292

### CODE REVIEW

**Review by vpereverzev — APPROVED** [review]

File: src/appshell/internal/applicationactioncontroller.cpp [hunk 1]
```diff
@@ -41,6 +41,11 @@ using namespace mu::actions;
 void ApplicationActionController::preInit()
 {
     qApp->installEventFilter(this);
+
+    //! NOTE: process QEvent::FileOpen as early as possible if it was postponed
+#ifdef Q_OS_MACOS
+    qApp->processEvents();
+#endif
```
Comment (igorkorsukov) [inline src/appshell/internal/applicationactioncontroller.cpp:48]: I think it's better to call `processEvents` in `onAllInited` because in `preInit` modules are not initialized

Comment (RomanPudashkin) [reply src/appshell/internal/applicationactioncontroller.cpp]: Yes, let's try

**Comment by DmitryArefiev** [comment]
Tested #15292 on Mac13.1 - **FIXED**

**Comment by bkunda** [comment]
🟢 Tested on macOS. Fixed.
