### PR TITLE
[MU4] fix #7633 - ensure that adding elements from palette in search mode works

### LINKED ISSUE #7633: [MU4 Issue] Search result shows empty palettes
**Describe the bug**
Search results even if there is no match - it shows empty palettes

**To Reproduce**
1. Create a score
2. Open "palettes" tab on the left side panel
3. Enter "2" or "ch" or "dd" in a palettes search field

**Expected behavior**
Empty slots and palettes should not be shown if there is no match with letters in search field

**Screenshots**
image
Скриншот 21-12-2020 14 31 20
Скриншот 21-12-2020 14 33 05

**Desktop (please complete the following information):**
Windows 10 x64, 
MacOS

### PR DESCRIPTION
**Pull request by wizofaus**
Resolves: https://github.com/musescore/MuseScore/issues/7633

The issue reported was originally around searching not displaying the expected palette items but while that seems OK now, adding items to the score when in search mode wasn't working

- [ x ] I signed [CLA](https://musescore.org/en/cla)
- [ x ] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [ x ] I made sure the code compiles on my machine
- [ x ] I made sure there are no unnecessary changes in the code
- [ x ] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [ x ] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [ x ] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

File: src/palette/internal/palette/paletteworkspace.cpp [hunk 1]
```diff
@@ -661,6 +661,7 @@ void PaletteWorkspace::setSearching(bool searching)
     m_searching = searching;
 
     mainPalette = nullptr;
+    mainPaletteController = nullptr;
```
Comment (wizofaus) [inline src/palette/internal/palette/paletteworkspace.cpp:664]: Ensures a new UserPaletteController gets created with the correct model - I assume Qt looks after the memory management here.  Alternatively we could add a public method to `UserPaletteController` to update the model but this seems safer.

**Review by igorkorsukov — APPROVED** [review]
