### PR TITLE
Fix #18752: export swing and straight to MusicXML

### LINKED ISSUE #18752: MusicXML exporting: swing and straight tempo markings do not fully export.
### Issue type

Other type of issue

### Bug description

Swing and straight tempo markings do not fully export when exporting to MusicXML. Instead just the text is exported:

```
    <measure number="2" width="315.07">
      <direction>
        <direction-type>
          <words default-y="0.24" relative-y="20.00" font-weight="bold" font-size="12">Swing</words>
          </direction-type>
        </direction>
```

should be:

```
    <measure number="2" width="315.07">
      <direction>
        <direction-type>
          <words default-y="0.24" relative-y="20.00" font-weight="bold" font-size="12">Swing</words>
          </direction-type>
          <sound>
            <swing>
              <first>2</first>
              <second>1</second>
              <swing-type>eighth</swing-type>
            </swing>
          </sound>
        </direction>
```

### Steps to reproduce

1. Create a MuseScore project with a Swing element
2. Export to MusicXML
3. Import the MusicXML into MuseScore
4. Listen to the score and note that there is no swing playback

### Screenshots/Screen recordings

Before Export:
Screenshot 2023-07-21 105530

After Export:
Screenshot 2023-07-21 105554

Screenshot 2023-07-21 105713
(see that the swing playback is disabled)

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231921402, revision: github-musescore-musescore-2e3a93a

### Regression

I don't know

### Operating system

Windows 11

### Additional context

The MuseScore and MusicXML files:
[files.zip](https://github.com/musescore/MuseScore/files/12131241/files.zip)

### PR DESCRIPTION
**Pull request by rettinghaus**
This PR adds a little method to the MusicXML export handling `systemText` items that got `swing`. 

Closes  #18752

### CODE REVIEW

File: src/importexport/musicxml/internal/musicxml/exportxml.cpp [hunk 1]
```diff
@@ -4850,6 +4851,47 @@ void ExportMusicXml::words(TextBase const* const text, staff_idx_t staff)
...
     wordsMetronome(m_xml, m_score->style(), text, offset);
+
+    directionETag(m_xml, staff);
+}
+
+//---------------------------------------------------------
+//   systemText
+//---------------------------------------------------------
+
+void ExportMusicXml::systemText(StaffTextBase const* const text, staff_idx_t staff)
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/exportxml.cpp:4862]: Why passing in `staff` but not using it?

File: src/importexport/musicxml/internal/musicxml/exportxml.cpp [hunk 2]
```diff
@@ -4850,6 +4851,47 @@ void ExportMusicXml::words(TextBase const* const text, staff_idx_t staff)
...
+        } else {
+            const int swingPercentage = text->swingParameters().swingRatio;
+            const int swingDivisor = std::gcd(text->swingParameters().swingRatio, 100);
+            m_xml.tag("first",  100 / swingDivisor);
+            m_xml.tag("second", swingPercentage / swingDivisor);
+            if (text->swingParameters().swingUnit == Constants::DIVISION / 2) {
+                m_xml.tag("swing-type", TConv::toXml(DurationType::V_EIGHTH));
+            } else {
+                m_xml.tag("swing-type", TConv::toXml(DurationType::V_16TH));
+            }
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/exportxml.cpp:4889]: why not ```cpp
            } else if (text->swingParameters().swingUnit == Constants::DIVISION / 4){
                m_xml.tag("swing-type", TConv::toXml(DurationType::V_16TH));
            } else {
                m_xml.tag("swing-type", TConv::toXml(DurationType::V_ZERO));
            }
```

Comment (rettinghaus) [reply src/importexport/musicxml/internal/musicxml/exportxml.cpp:4889]: Because `V_ZERO` case is handled before (and would result in invalid MusicXML anyway).

**Comment by rettinghaus** [comment]
@JosephBuchholz maybe you want to give this a test run?

**Review by miiizen — APPROVED** [review]

**Comment by rettinghaus** [comment]
@cbjeukendrup could this be merged?
