### PR TITLE
Fix #15407: Hide zero-length lyrics dashes

### LINKED ISSUE #15407: [MU4 Issue] Lyrics layout breaks on incomplete input
**Describe the bug**
Lyrics self-intersect when ending with a minus (`-`).

**To Reproduce**
1. Enter more than one note.
2. Click on the first note
3. Type Ctrl-L to enter lyrics mode
4. Type "Froh-" without quotes
5. Press the `Esc` key, or click some empty part of the score, to abort entering lyrics

**Expected behavior**
I wouldn't be surprised by any of the following behaviors:
1. Because the minus key is supposed to indicate a single connected word and the user refused to write the rest of the word, the minus is removed, and only "Froh" remains.
2. Because the user refused to enter anything further, the lyrics "Froh - " appear.
3. A dialog appears asking the user what they want.
4. Because the input doesn't make sense, MuseScore reinterprets the input as "Froh_".

**Actual behavior**
The layout algorithm seems to think that "Froh" is the only remaining text node, and does the layout accordingly. However, the "-" (minus symbol) also appears, in a place that would be reasonable if "Froh" hadn't moved in the meantime. The result is that "Froh" and "-" overlap awkwardly.

**Screenshots**
I wrote "Fröh-", but that doesn't really make a difference:
Bildschirmfoto_2022-12-20_01-02-35
I didn't edit that screenshot, the weird line in the text is the minus sign.

**Platform information**
 - OS: Linux, German locale, but that probably doesn't matter.

**Additional context**
Am I spamming too much or should I keep going? Writing 8 bug reports in a row starts feeling like I should stop doing that.

### PR DESCRIPTION
**Pull request by asattely**
Resolves: https://github.com/musescore/MuseScore/issues/15407 and https://github.com/musescore/MuseScore/issues/15093

See comment, the solution for this one has changed.

### CODE REVIEW

**Comment by asattely** [comment]
This one ended up being a little more in-depth than I expected it to be.

- If the user places exactly one underscore (or dash) and then ends editing, the melisma is deleted and the alignment of the lyric is reset.
- If the user places multiple dashes, the lyric will be left-justified (as it spans multiple notes), but if the editing ends with that string of dashes, the original lyric will again have its alignment reset and the "melisma" will be deleted.

**Review by oktophonie — APPROVED** [review]

File: src/engraving/libmscore/lyrics.cpp [hunk 1]
```diff
@@ -766,4 +792,16 @@ KerningType Lyrics::doComputeKerningType(const EngravingItem* nextItem) const
     }
     return KerningType::KERNING;
 }
+
+void Lyrics::removeInvalidSegments()
```
Comment (RomanPudashkin) [inline src/engraving/libmscore/lyrics.cpp:796]: What is considered an invalid segment? I don't really understand the purpose of this method

File: src/engraving/libmscore/lyrics.cpp [hunk 2]
```diff
@@ -230,6 +230,31 @@ bool Lyrics::isMelisma() const
     return false;
 }
 
+//---------------------------------------------------------
+//   prevLyrics
+//    - find the lyric (if any) before this one (not including lines)
+//    - currently used to determine the first lyric of a melisma
+//---------------------------------------------------------
+
+Lyrics* Lyrics::prevLyrics() const
```
[the remark this answers is not in the document]
Comment (asattely) [reply src/engraving/libmscore/lyrics.cpp:239]: I'm afraid I don't understand this one. You want the lyrics class to be in navigate.h?

[the remark this answers is not in the document]
Comment (RomanPudashkin) [reply src/engraving/libmscore/lyrics.cpp:239]: No, only this function :)

File: src/engraving/libmscore/lyrics.cpp (hunk 1 above)
Comment (asattely) [reply src/engraving/libmscore/lyrics.cpp:796]: That said, I have added comments to the method!

**Review by oktophonie — APPROVED** [review]

File: src/engraving/libmscore/navigate.cpp [hunk 3]
```diff
@@ -965,4 +966,29 @@ EngravingItem* Score::prevElement()
...
     return score()->firstElement();
 }
+
+//---------------------------------------------------------
+//   prevLyrics
+//    - find the lyric (if any) before this one (not including lines)
+//    - currently used to determine the first lyric of a melisma
+//---------------------------------------------------------
+
+Lyrics* Lyrics::prevLyrics() const
```
Comment (RomanPudashkin) [inline src/engraving/libmscore/navigate.cpp:976]: This is not exactly what I meant :) You should declare a function in navigate.h (similar to prevChordRest):

`extern Lyrics* prevLyrics(const Lyrics* lyrics);
`

Then use this new function in TextBase::endEdit(EditData& ed):

```
 if (isLyrics()) {
     Lyrics* prevLyrics = prevLyrics(toLyrics(this));
     if (prevLyrics) {
         ...
     }
 }


```

Comment (asattely) [reply src/engraving/libmscore/navigate.cpp:976]: For the record, why do we want to do this? There are no other Lyrics methods in navigate.cpp, so I am wondering what the point of all of this is?

Comment (RomanPudashkin) [reply src/engraving/libmscore/navigate.cpp]: Because it can iterate implicitly over the whole score. And in general, has low cohesion in this class (it does not depend on anything within this class, and can easily be moved out of it and take it as an argument). We want engraving elements to be as simple as possible
