### PR TITLE
fixed #12465: Crash when using playback toolbar in a score with no instruments

### LINKED ISSUE #12465: [MU4 Issue] Crash when using playback toolbar in a score with no instruments
**Describe the bug**
If you try to toggle the metronome in a score that contains no instruments, a crash occurs.

**To Reproduce**
1. Create a score
2. Delete all instruments using the instruments panel
3. Save and close the score
4. Reopen the score
Note that the metronome track is not created and doesn't appear in the Mixer.
5. Click a button in the playback toolbar
A crash occurs.

**Expected behavior**
Even though scores with no instruments don't make much sense at all, it would still be nice if they don't cause crashes.

**Platform information**
 - OS: reported on macOS

### PR DESCRIPTION
**Pull request by Eism**
Resolves: #12465

### CODE REVIEW

File: src/notation/imasternotation.h [hunk 1]
```diff
@@ -52,6 +52,8 @@ class IMasterNotation
     virtual void setExcerptIsOpen(const INotationPtr excerptNotation, bool opened) = 0;
 
     virtual INotationPartsPtr parts() const = 0;
+    virtual bool isPartsEmpty() const = 0;
```
Comment (RomanPudashkin) [inline src/notation/imasternotation.h:55]: I would suggest renaming it to hasParts

File: src/notation/view/noteinputbarmodel.cpp [hunk 2]
```diff
@@ -186,6 +189,20 @@ void NoteInputBarModel::onNotationChanged()
         undoStack()->stackChanged().onNotify(this, [this]() {
             updateState();
         });
+
+        async::NotifyList<const Part*> partList = masterNotationParts()->partList();
```
Comment (RomanPudashkin) [inline src/notation/view/noteinputbarmodel.cpp:193]: It is better to add somewhere (for example, to NotationParts) one additional notification. It will notify us when the list becomes empty or not. So this code (and other similar blocks) can be rewritten as follows:

```
masterNotationParts()->hasPartsChanged(this, [this]() {
    emit isInputAllowedChanged();
});
```

**Comment by Tantacrul** [comment]
Tested on MacOS. Play bar is appropriately disabled when there are no instruments and I am unable to use a shortcut to make it play. Seems good to go!

**Comment by DmitryArefiev** [comment]
@Tantacrul It's fine about missing full stops? (discussion in #12465)

**Comment by Tantacrul** [comment]
I would just add the full stop. We've done it elsewhere and it's not 'wrong' to do so. Let's also agree to codify it in our style guides.

**Review by RomanPudashkin — APPROVED** [review]
