### PR TITLE
Don't allow copy-by-drag onto tuplets

### LINKED ISSUE #27087: Crash when click+drag pasting a non-tuplet segment over a tuplet segment that also crosses a barline
### Issue type

Crash or freeze

### Description with steps to reproduce

In the words of @mike-spa: " It crashes because we're pasting non-triplet rythm into a triplet subdivision and across a barline. At the barline, it has to split the notation and it gets stuck in an infinite loop because there just doesn't exist a non-triplet subvision that can occupy that same length".

 

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/54846f9e-bbb2-4fcb-9f19-fed6e02d3efb

### What is the latest version of MuseScore Studio where this issue is present?

RC 4.5

### Regression

No.

### Operating system

Win 11

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mike-spa**
Resolves: #27087

Copy-pasting onto a tuplet isn't allowed. Copy-by-dragging shouldn't either.

### CODE REVIEW

File: src/notation/internal/notationinteraction.cpp [hunk 1]
```diff
@@ -1971,6 +1971,30 @@ bool NotationInteraction::dropRange(const QByteArray& data, const PointF& pos, b
...
+            ChordRest* chordRest = toChordRest(item);
+            if (chordRest->tuplet() && chordRest->tick() != chordRest->topTuplet()->tick()) {
+                //MScore::setError(MsError::DEST_TUPLET);
+                allowDrop = false;
+                break;
+            }
+        }
+
+        if (!allowDrop) {
+            apply();
```
Comment (RomanPudashkin) [inline src/notation/internal/notationinteraction.cpp:1989]: Why is it needed here?

File: src/notation/internal/notationinteraction.cpp [hunk 2]
```diff
@@ -1971,6 +1971,30 @@ bool NotationInteraction::dropRange(const QByteArray& data, const PointF& pos, b
         return false;
     }
 
+    if (segment->isChordRestType()) {
+        bool allowDrop = true;
+        for (EngravingItem* item : segment->elist()) {
```
Comment (RomanPudashkin) [inline src/notation/internal/notationinteraction.cpp:1976]: It would be nice to move this code to a separate function

File: src/notation/internal/notationinteraction.cpp (hunk 1 above)
Comment (mike-spa) [reply src/notation/internal/notationinteraction.cpp:1989]: Cause if I don't call that function I get this problem that the drop region doesn't go away after finishing the drop.

https://github.com/user-attachments/assets/979db354-c159-4634-b8ab-47e81b80f18f

**Review by RomanPudashkin — APPROVED** [review]

File: src/notation/internal/notationinteraction.cpp (hunk 1 above)
Comment (RomanPudashkin) [reply src/notation/internal/notationinteraction.cpp]: Perhaps it's only necessary to call notifyAboutDropChanged()

Comment (mike-spa) [reply src/notation/internal/notationinteraction.cpp]: Ah yes you're right. Done!

Comment (RomanPudashkin) [reply src/notation/internal/notationinteraction.cpp]: Last nitpick (sorry): we should call notifyAboutDropChanged() after endDrop(). Because endDrop() changes the state of the score and notifyAboutDropChanged() causes the score to be redrawn

Comment (mike-spa) [reply src/notation/internal/notationinteraction.cpp]: Good point. Maybe we should do the same thing a few lines below then? Cause that also currently does apply() followed by endDrop().

Comment (RomanPudashkin) [reply src/notation/internal/notationinteraction.cpp]: Yeah, but perhaps we should keep apply() there and only change the order of the calls for now

Comment (mike-spa) [reply src/notation/internal/notationinteraction.cpp]: 👍 Done!

**Review by RomanPudashkin — APPROVED** [review]

**Review by bkunda — APPROVED** [review]
Works on macOS and Win.
We will need to add some messaging at our next opportunity (and it needs to be unique, because the existing error message about copying onto tuplets won't make sense in this context), however this PR addresses the most urgent crash, and so is needed for the 4.5 release.

File: src/engraving/dom/segment.cpp [hunk 3]
```diff
@@ -1095,6 +1095,25 @@ void Segment::setXPosInSystemCoords(double x)
     mutldata()->setPosX(x - measure()->x());
 }
 
+bool Segment::isInsideTuplet() const
+{
+    if (!isChordRestType()) {
```
Comment (cbjeukendrup) [inline src/engraving/dom/segment.cpp:1100]: Re. https://github.com/musescore/MuseScore/issues/27087#issuecomment-2722983723: I think this early return is the cause. That raises the question: how to handle time tick segments here? They don't have chords, so we can't get the tuplet, so then we need to look at the next or previous segment and hope that that one is a ChordRest segment... not super streamlined.

And actually, I doubt the criterium should be `isInsideTuplet` at all. Shouldn't it rather be `isTickMultipleOfPowerOfTwo`? (i.e. 1/4, 3/8, but not 1/3)

Comment (mike-spa) [reply src/engraving/dom/segment.cpp:1100]: Yep, correct. In fact I knew that the proper solution is to check for a power-of-two denominator, but as a last-of-the-last-minute solution it felt safer to just mimick the existing "Cannot paste onto tuplets" logic. In fact you know what, I'll do this right now and merge it in 4.5.1 so we have proper time to test it.
