### PR TITLE
Fix #17891: Instrument names follow largest stave spatium in part

### LINKED ISSUE #17891: Small staff in multi-staff instrument leads to incorrectly resized instrument name
### Issue type

Engraving bug

### Bug description

This happens only when resizing the uppermost staff of a multi-staff instrument (f. e. right hand of a keyboard instrument).

This scenario is used in Basso Continuo parts for an editorial realization of the BC figures.

### Steps to reproduce

1. Create a new score with a keyboard instrument and at least another instrument.
2. Resize the upper staff of the keyboard instrument to small staff.

### Screenshots/Screen recordings

grafik

### MuseScore Version

4.0.2

### Regression

I don't know

### Operating system

Linux

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by miiizen**
Resolves: #17891

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [x] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Review by mike-spa — APPROVED** [review]

**Review by oktophonie — APPROVED** [review]

File: src/engraving/dom/instrumentname.h [hunk 1]
```diff
@@ -64,6 +64,8 @@ class InstrumentName final : public TextBase
     SysStaff* sysStaff() const { return _sysStaff; }
     void setSysStaff(SysStaff* s) { _sysStaff = s; }
 
+    double spatium() const;
```
Comment (RomanPudashkin) [inline src/engraving/dom/instrumentname.h:67]: This implicitly overrides EngravingItem::spatium(). You should make EngravingItem::spatium() virtual and override it explicitly. This type of solution may not be perfect either, but at least it is more obvious, and you no longer need that cast inside TextFragment::font

Comment (miiizen) [reply src/engraving/dom/instrumentname.h:67]: Making `EngravingItem::spatium()` virtual was my first approach, but after Michele asked me to do a performance test we found that layout took noticeably longer (3-4%).  I can change the name of the method to avoid confusion, though we'd keep the cast.

Comment (mike-spa) [reply src/engraving/dom/instrumentname.h:67]: Yeah, making spatium() virtual is very elegant codewise, but spatium() is an extremely hot function, and my concern was that resolving the vtable at every call would carry a noticeable runtime cost (which seems to be indeed the case), so I advised against making it virtual. I agree that overriding the method implicitely may cause confusion though, so it's probably better to just call it a different name

Comment (RomanPudashkin) [reply src/engraving/dom/instrumentname.h:67]: Yes, you are right. You just should rename InstrumentName::spatium()

**Review by RomanPudashkin — APPROVED** [review]
