### PR TITLE
fixed #14685: Crash when opening one-measure score with 2nd ending assigned

### LINKED ISSUE #14685: [MU4 Issue] Crash when opening one-measure score with 2nd ending assigned
**Describe the bug**
This is an edge case but should be fixed 

**To Reproduce**
1. Create a simple score with 1 measure
2. Add 2nd ending from palettes
3. Save the score
4. Open the score

**Expected behavior**
Score is opened

**Screenshots**

https://user-images.githubusercontent.com/101250347/203553053-75f3cb2d-3305-4358-902b-bd9ddef72098.mp4

### PR DESCRIPTION
**Pull request by Eism**
Resolves: #14685

### CODE REVIEW

**Comment by abariska** [comment]
🟢 **TESTED on macOS 12**
Please, merge to master

**Review by RomanPudashkin — APPROVED** [review]

File: src/engraving/libmscore/repeatlist.cpp [hunk 1]
```diff
@@ -834,10 +834,10 @@ void RepeatList::unwind()
                     activeVolta = nullptr;
                     // Start next rs on the following measure
                     Measure const* const possibleNextMeasure = (*repeatListElementIt)->measure->nextMeasure();
+                    rs = new RepeatSegment(playbackCount);
                     if (possibleNextMeasure == nullptr) {
-                        rs = nullptr;                   // end of score, but will still encounter section break, notify it
+                        // end of score, but will still encounter section break, notify it
```
Comment (jeetee) [inline src/engraving/libmscore/repeatlist.cpp:839]: This now probably is a stale comment..

**Comment by jeetee** [comment]
Verified that in 3.6.2 this scenario does not lead to a crash.
