### PR TITLE
[MU4] Fix #7767 - ensure undo works properly for staff properties dialog

### LINKED ISSUE #7767: [MU4 Issue] Can't undo stave transposition (made via right-click > Stave Properties)
**Describe the bug**
Can't undo stave transposition (made via right-click > Stave Properties)
Also, can't undo text editing

**To Reproduce**
1. Create score
2. Select note
3. right-click > Stave Properties

**Expected behavior**
stave transposition functions work

**Desktop (please complete the following information):**
MacOS

**Additional context**
About transposition
https://musescore.org/en/handbook/3/transposition

### PR DESCRIPTION
**Pull request by wizofaus**
Resolves: https://github.com/musescore/MuseScore/issues/7767

Undo wasn't correctly working for changing various staff properties

- [ x ] I signed [CLA](https://musescore.org/en/cla)
- [ x ] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [ x ] I made sure the code compiles on my machine
- [ x ] I made sure there are no unnecessary changes in the code
- [ x ] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [ x ] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [ x ] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

File: src/notation/internal/notationparts.cpp [hunk 1]
```diff
@@ -706,7 +706,7 @@ void NotationParts::replaceInstrument(const ID& instrumentId, const ID& fromPart
         return;
     }
 
-    part->setInstrument(InstrumentsConverter::convertInstrument(newInstrument), oldInstrumentInfo.fraction);
+    score()->undo(new Ms::ChangePart(part, new Ms::Instrument(InstrumentsConverter::convertInstrument(newInstrument)), part->name()));
     doSetPartName(part, formatPartName(part));
```
Comment (wizofaus) [inline src/notation/internal/notationparts.cpp:710]: It does concern me that I'm now discarding oldInstrumentInfo.fraction, but I can't find a case that it's anything other than -1 - in fact that seems to be a bug, because in MU3 if you use "staff properties" at a point after a "Change Instrument" event, it shows the transposition etc. info as set by that "change instrument" event and that's what you can edit - whereas for MU4 "Change Instrument" events seem to be ignored in the staff properties dialog.
MU3 has a bunch of code in editstaff.cpp (lines 381-) to support this, but the MU4 code doesn't pass any info about the current score position when doing this.

File: src/notation/internal/notationparts.cpp [hunk 2]
```diff
@@ -706,7 +706,7 @@ void NotationParts::replaceInstrument(const ID& instrumentId, const ID& fromPart
         return;
     }
 
-    part->setInstrument(InstrumentsConverter::convertInstrument(newInstrument), oldInstrumentInfo.fraction);
+    score()->undo(new Ms::ChangePart(part, new Ms::Instrument(InstrumentsConverter::convertInstrument(newInstrument)), part->name()));
```
Comment (RomanPudashkin) [inline src/notation/internal/notationparts.cpp:709]: score()->undo(new Ms::ChangePart(...)) will be called again right after this line (see doSetPartName implementation). Better to use undo only once

Comment (wizofaus) [reply src/notation/internal/notationparts.cpp:709]: Ah yes, missed that, agree it makes sense to use just put the one ChangePart command on the undo stack, thanks.

File: src/notation/internal/notationparts.cpp [hunk 3]
```diff
@@ -706,8 +706,8 @@ void NotationParts::replaceInstrument(const ID& instrumentId, const ID& fromPart
         return;
     }
 
-    part->setInstrument(InstrumentsConverter::convertInstrument(newInstrument), oldInstrumentInfo.fraction);
-    doSetPartName(part, formatPartName(part));
+    score()->undo(new Ms::ChangePart(part, new Ms::Instrument(InstrumentsConverter::convertInstrument(newInstrument)),
+                                     formatPartName(part)));
```
Comment (wizofaus) [inline src/notation/internal/notationparts.cpp:710]: for Undo to work properly we can't change the instrument on the part before creating the "ChangePart" command, as it needs access to the original value in order to revert to it when you undo. ChangePart can also change the name, so no need to call doSetPartName explicitly.

**Review by RomanPudashkin — APPROVED** [review]
