### PR TITLE
Add subPageCodeForElement, Fix right click #19288

### LINKED ISSUE #19288: Style from right click menu shoud lead to Text Styles specific sub-section in Styles dialog (Instrument names, Composer, Subtitle etc.)
### Issue type

UI bug

### Bug description

It was fixed for **Properties > Style settings** button in #19267, but **not** for **Style** option in **right click menu**

Style option was re-implemented in #19267

Also, [see comment](https://github.com/musescore/MuseScore/pull/19267#issuecomment-1705505219) about sub-sections of Text Styles

### Steps to reproduce

1. Select Instrument name
2. Right click menu
3. Select Style - it opens Style>Text styles>**Title** instead of Style>Text styles>**Instrument name (long)**

https://github.com/musescore/MuseScore/assets/90187801/1651fb21-d923-4cde-ac40-9d8a4f98b532

(the same with Composer, Subtitle etc, but most important is Instrument name issue)

### MuseScore Version

4.2 master

### Regression

No.

### Operating system

all

### Additional context

#19267 #19203 #18837

### PR DESCRIPTION
**Pull request by re1san**
It should fix #19288 

https://github.com/musescore/MuseScore/assets/105774228/bccf7a2b-7840-4b05-af33-f6db026f6561

### CODE REVIEW

File: src/notation/view/widgets/editstyle.cpp [hunk 1]
```diff
@@ -1473,6 +1474,60 @@ QString EditStyle::pageCodeForElement(const EngravingItem* element)
...
+
+        case TextStyleType::FOOTER:
+            return "footere";
+
+        default: return "title";    
+        }
+    }
+
+    case ElementType::INSTRUMENT_NAME: {
+        const mu::engraving::InstrumentName *instruName = toInstrumentName(element);
```
Comment (XiaoMigros) [inline src/notation/view/widgets/editstyle.cpp:1513]: The * should be at the end of `InstrumentName`, rather than at the start of `instruName`

File: src/notation/view/notationcontextmenumodel.cpp [hunk 2]
```diff
@@ -209,8 +209,15 @@ MenuItemList NotationContextMenuModel::makeElementItems()
 
     if (hitElement) {
         QString pageCode = EditStyle::pageCodeForElement(hitElement);
+
         if (!pageCode.isEmpty()) {
-            item->setArgs(mu::actions::ActionData::make_arg1<QString>(pageCode));
+            if (pageCode == "text-styles") {
+                QString subPageCode = EditStyle::subPageCodeForElement(hitElement);
+                if (!subPageCode.isEmpty())
```
Comment (XiaoMigros) [inline src/notation/view/notationcontextmenumodel.cpp:216]: Adding brackets here would be preferred

**Comment by re1san** [comment]
Fixed

File: src/notation/view/widgets/editstyle.cpp [hunk 3]
```diff
@@ -1473,6 +1474,60 @@ QString EditStyle::pageCodeForElement(const EngravingItem* element)
...
 }
 
+QString EditStyle::subPageCodeForElement(const EngravingItem* element)
+{
+    IF_ASSERT_FAILED(element) {
+        return QString();
+    }
+
+    switch (element->type()) {
+    case ElementType::TEXT: {
```
Comment (XiaoMigros) [inline src/notation/view/widgets/editstyle.cpp:1484]: I believe another set of indents is required between `switch` and `case` (same applies in other places)

**Comment by re1san** [comment]
The CI_codestyle check is suggesting without indents, should I change according to that

**Comment by XiaoMigros** [comment]
> The CI_codestyle check is suggesting without indents, should I change according to that
Ah, yes, in that case, best stick with what the machines say ;)

**Comment by re1san** [comment]
finally it passed :)

**Comment by re1san** [comment]
Hey @XiaoMigros @cbjeukendrup any updates on this? If it can be merged or any changes are required?

File: src/notation/view/notationcontextmenumodel.cpp [hunk 4]
```diff
@@ -209,8 +209,16 @@ MenuItemList NotationContextMenuModel::makeElementItems()
 
     if (hitElement) {
         QString pageCode = EditStyle::pageCodeForElement(hitElement);
+
         if (!pageCode.isEmpty()) {
-            item->setArgs(mu::actions::ActionData::make_arg1<QString>(pageCode));
+            if (pageCode == "text-styles") {
```
Comment (cbjeukendrup) [inline src/notation/view/notationcontextmenumodel.cpp:214]: To prevent having `"text-styles"` written as a string here (which is typo-prone or might get out of sync in the future), I think we can just get rid of it. Checking `if (!subPageCode.isEmpty())` is enough.

File: src/notation/view/widgets/editstyle.cpp [hunk 5]
```diff
@@ -1473,6 +1474,59 @@ QString EditStyle::pageCodeForElement(const EngravingItem* element)
...
```
Comment (cbjeukendrup) [inline src/notation/view/widgets/editstyle.cpp:1484]: I think we don't need this outer switch statement here; instead, we can just check if the element is any of the text-related classes, by checking `element->isTextBase()`:
```
    if (element->isTextBase()) {
        switch (toTextBase(element)->textStyleType()) {
        case …:
```
Also, I think the inner switch should handle all possible text styles explicitly, i.e. no `default:` case. Almost all of them have a corresponding subpage.

**Review by cbjeukendrup — COMMENTED** [review]
Sorry for the late reply! Here are some last review comments :)

File: src/notation/view/widgets/editstyle.cpp (hunk 5 above)
Comment (re1san) [reply src/notation/view/widgets/editstyle.cpp]: Ok so I have added almost all of the subpage codes that I could find from https://github.com/musescore/MuseScore/blob/d1724df9d82f053bf35ed1df2decdd678b2ac3da/src/notation/view/widgets/editstyle.cpp#L99C1-L99C1, but I couldn't find for these ones: 
* Gradual tempo change
* String tunings
* Harp pedal diagram
* Harp pedal text diagram

Comment (re1san) [reply src/notation/view/widgets/editstyle.cpp]: Also I get this warning message when building as these types are not getting handled in switch for that we might need default?

```
In file included from /home/re1san/Dev/MuseScore/builds/Linux-Qt5.15.2-gcc_64-Make-RelWithDebInfo/src/notation/CMakeFiles/notation.dir/Unity/unity_4_cxx.cxx:34:
/home/re1san/Dev/MuseScore/src/notation/view/widgets/editstyle.cpp: In static member function ‘static QString mu::notation::EditStyle::subPageCodeForElement(const mu::notation::EngravingItem*)’:
/home/re1san/Dev/MuseScore/src/notation/view/widgets/editstyle.cpp:1484:16: warning: enumeration value ‘DEFAULT’ not handled in switch [-Wswitch]
 1484 |         switch (toTextBase(element)->textStyleType()) {
      |                ^
/home/re1san/Dev/MuseScore/src/notation/view/widgets/editstyle.cpp:1484:16: warning: enumeration value ‘TEMPO_CHANGE’ not handled in switch [-Wswitch]
/home/re1san/Dev/MuseScore/src/notation/view/widgets/editstyle.cpp:1484:16: warning: enumeration value ‘DYNAMICS’ not handled in switch [-Wswitch]
/home/re1san/Dev/MuseScore/src/notation/view/widgets/editstyle.cpp:1484:16: warning: enumeration value ‘STRING_TUNINGS’ not handled in switch [-Wswitch]
/home/re1san/Dev/MuseScore/src/notation/view/widgets/editstyle.cpp:1484:16: warning: enumeration value ‘HARP_PEDAL_DIAGRAM’ not handled in switch [-Wswitch]
/home/re1san/Dev/MuseScore/src/notation/view/widgets/editstyle.cpp:1484:16: warning: enumeration value ‘HARP_PEDAL_TEXT_DIAGRAM’ not handled in switch [-Wswitch]
/home/re1san/Dev/MuseScore/src/notation/view/widgets/editstyle.cpp:1484:16: warning: enumeration value ‘TEXT_TYPES’ not handled in switch [-Wswitch]
/home/re1san/Dev/MuseScore/src/notation/view/widgets/editstyle.cpp:1484:16: warning: enumeration value ‘IGNORED_TYPES’ not handled in switch [-Wswitch]
/home/re1san/Dev/MuseScore/src/notation/view/widgets/editstyle.cpp:1651:1: warning: control reaches end of non-void function [-Wreturn-type]
 1651 | }
      | ^
```

Out of these I couldn't find subpage codes for `TEMPO_CHANGE, STRING_TUNINGS, HARP_PEDAL_DIAGRAM, HARP_PEDAL_TEXT_DIAGRAM`
as mentioned above. (I found for DYNAMICS but there is no such option in right click style menu)

Comment (cbjeukendrup) [reply src/notation/view/widgets/editstyle.cpp]: I looked a bit more closely, and it turns out that `allSubPageCodes` is not in sync with the actual list of subpages. The actual list is namely generated based on `editableTextStyles()` (see the constructor of EditStyle, around line 944).

So, the solution would be to find out what's in `editableTextStyles()`, and then update `allSubPageCodes` accordingly. Then update the switch in `subPageCodeForElement`.

There are a few TextStyleTypes that have indeed no subpage; I'd list those at the bottom of the switch and return `QString()` for them.
```
        switch (toTextBase(element)->textStyleType()) {
        case TextStyleType::TITLE:
            return "title";
        …
        case TextStyleType::DYNAMICS:
        case TextStyleType::DEFAULT:
        case TextStyleType::TEXT_TYPES:
        case TextStyleType::IGNORED_TYPES:
            return QString();
```

File: src/notation/view/widgets/editstyle.cpp [hunk 6]
```diff
@@ -1336,7 +1340,8 @@ QString EditStyle::pageCodeForElement(const EngravingItem* element)
         return "page";
 
     case ElementType::INSTRUMENT_NAME:
-    case ElementType::TEXT: {
+    case ElementType::TEXT:
+    case ElementType::HARP_DIAGRAM: {
```
Comment (re1san) [inline src/notation/view/widgets/editstyle.cpp:1344]: Right click style menu on harp diagram now directs to `Text styles > Harp pedal diagram/Harp pedal text diagram`
 

https://github.com/musescore/MuseScore/assets/105774228/83183317-e029-4ae4-b8a6-5d9db3cc79ea

Comment (re1san) [reply src/notation/view/widgets/editstyle.cpp:1344]: Also now all the sub page codes and page codes are synced

File: src/notation/view/widgets/editstyle.cpp (hunk 5 above)
Comment (re1san) [reply src/notation/view/widgets/editstyle.cpp]: Done

**Review by cbjeukendrup — APPROVED** [review]
Thanks!

**Comment by XiaoMigros** [comment]
Not sure if this is the best place to ask, but I wonder if an 'text style' option that sits below the 'style' button in the context menu would be useful? Perhaps worth making a feature request for?

**Comment by re1san** [comment]
@XiaoMigros Yeah I think this will be useful for users to easily change text styles as for plenty of items we are just returning the corresponding page code first. For example, context menu opens up the Staff text page code, but if a user wants to change text style it should open Text styles > Staff

**Comment by re1san** [comment]
I think it should be solved by returning `"score"` here https://github.com/musescore/MuseScore/blob/6bf6605856cf9c8c9db14e494e2a7e639b0a73ff/src/notation/view/widgets/editstyle.cpp#L1502

File: src/notation/view/notationcontextmenumodel.cpp [hunk 7]
```diff
@@ -209,8 +209,14 @@ MenuItemList NotationContextMenuModel::makeElementItems()
 
     if (hitElement) {
         QString pageCode = EditStyle::pageCodeForElement(hitElement);
+
         if (!pageCode.isEmpty()) {
```
Comment (re1san) [inline src/notation/view/notationcontextmenumodel.cpp:213]: or we can check here as well, if `pageCode` is empty we can set it to `score`

**Comment by cbjeukendrup** [comment]
Isn't it expected that the last page is remembered? If not, then the solution is as simple as removing the code that achieves that :) 
But this was added deliberately some months ago.

**Comment by DmitryArefiev** [comment]
> Isn't it expected that the last page is remembered?
That's probably a design question.. But I'm sure the last page should not be remembered for the next score (during one MS session)

**Comment by cbjeukendrup** [comment]
Yes, it's a design question. FWIW, MS3 did remember the dialog state during the entire session, so also when opening a different score. But not across different launches of the program.

**Comment by DmitryArefiev** [comment]
> MS3 did remember the dialog state during the entire session, so also when opening a different score. But not across different launches of the program.

@cbjeukendrup Yeah, I see it now in MS3.. The same with Preferences dialog. I will think about it/log it later.
Let's merge the current PR then. It needs to be rebased/reviewed again?

**Comment by re1san** [comment]
@DmitryArefiev rebased it

**Review by cbjeukendrup — APPROVED** [review]
Thanks!

**Comment by DmitryArefiev** [comment]
Retested on Win10. All good. Merged
