### PR TITLE
Fix #8364 - remove dangerous and unneeded museScoreCore global variable

### LINKED ISSUE #8364: [MU4 Issue] Crash in Score::endCmd due to unsafe use of global variable
**Describe the bug**
Slightly random, haven't been able to reproduce 100% consistently, but certain actions (in this case trying to change the duration of a note) can cause a crash in Score::endCmd, specifically at the line `MuseScoreCore::mscoreCore->endCmd(isCmdFromInspector, rollback)`.
This seems like quite dangerous and unnecessary use of a global variable. At the point it crashed `MuseScoreCore::mscoreCore` appeared to refer to something already deleted.

**To Reproduce**
1. Create a new score
2. Open the new score dialog (Ctrl+N)
3. Cancel/close dialog
4. Add a note
5. MuseScore sometimes crashes (sometimes)

**Expected behavior**
Preferably, applicaton should not crash!

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

read access violation
>	MuseScore4.exe!Ms::Score::endCmd(const bool isCmdFromInspector, bool rollback) Line 303	C++
 	MuseScore4.exe!mu::notation::NotationUndoStack::commitChanges() Line 110	C++
 	MuseScore4.exe!mu::notation::NotationNoteInput::padNote(const Ms::Pad & pad) Line 202	C++
 	MuseScore4.exe!mu::notation::NotationActionController::padNote(const Ms::Pad & pad) Line 497	C++

Virtual table pointer for MuseScoreCore::mscoreCore was invalid.

Basically ~MuseScoreCore can occasionally be called for the object currently referred to by MuseScoreCore::mscoreCore but I haven't managed to work out why/when it happens.

### PR DESCRIPTION
**Pull request by wizofaus**
Resolves: https://github.com/musescore/MuseScore/issues/8364

Dangerous use of museScoreCore global variable was causing random crashes

- [ x ] I signed [CLA](https://musescore.org/en/cla)
- [ x ] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [ x ] I made sure the code compiles on my machine
- [ x ] I made sure there are no unnecessary changes in the code
- [ x ] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [ x ] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [ x ] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

File: src/plugins/api/qmlpluginapi.cpp [hunk 1]
```diff
@@ -374,5 +374,16 @@ void PluginAPI::registerQmlTypes()
 
     qmlTypesRegistered = true;
 }
+
+MuseScoreCore* PluginAPI::msc() const
+{
+    static MuseScoreCore mscStatic;
+    if (this->context() && this->context()->currentNotation()) {
+        mscStatic.setCurrentScore(this->context()->currentNotation()->elements()->msScore());
```
Comment (wizofaus) [inline src/plugins/api/qmlpluginapi.cpp:382]: This is still not ideal, as we're storing the pointer to the current Score potentially beyond its lifetime. Probably should change to shared_ptr, or better still get rid of MuseScoreCore completely if possible and just use Score?  Did try making MuseScoreCore injectable but that didn't seem to work.
But until the plugin mechanism is implemented in MU4 it doesn't really matter, none of this is used for anything.

File: src/plugins/api/qmlpluginapi.h [hunk 2]
```diff
@@ -74,6 +76,7 @@ class PluginAPI : public Ms::QmlPlugin
     Q_OBJECT
 
     INJECT(plugins, mu::shortcuts::IShortcutsController, shortcuts)
+    INJECT(userscores, mu::context::IGlobalContext, context)
```
Comment (igorkorsukov) [inline src/plugins/api/qmlpluginapi.h:79]: should be change `userscore` to `plugins`

**Review by igorkorsukov — APPROVED** [review]
