### PR TITLE
Fix #18471: Rename Aux channels

### LINKED ISSUE #18471: Aux channel strip labels should simply be "Aux 1" and "Aux 2", and shouldn't update to show any plugin names
### Issue type

UI bug

### Bug description

In light of recently reported confusion around the aux channel strip names, @Tantacrul and I have resolved that the simplest way to label the aux channel strips should be "Aux 1" and "Aux 2", rather than taking the name of any plugins applied to that strip.

_Current behaviour, showing Aux 1 labelled as "Reverb" and Aux 2 labelled as "Master"_:

Screenshot 2023-07-07 at 6 59 04 pm

In addition, the channel strip name should not change when a plugin is replaced. It should simply remain "Aux 1" and "Aux 2".

Note this change should affect only the **channel strips**, not the label in the aux sends (adjacent to the knobs). 

  

### Steps to reproduce

n/a

### Screenshots/Screen recordings

_No response_

### MuseScore Version

OS: macOS 13.1, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231881326, revision: github-musescore-musescore-0759bc9

### Regression

No.

### Operating system

all

### Additional context

N.B. Resolving this would also resolve https://github.com/musescore/MuseScore/issues/17514, which reports that MS needs to be restarted in order to update the channel strip label. 

@jessjwilliamson FYI

### PR DESCRIPTION
**Pull request by HemantAntony**
Resolves: #18471
Resolves: #17514

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [x] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

File: src/playback/internal/playbackcontroller.cpp [hunk 1]
```diff
@@ -1040,8 +1031,8 @@ void PlaybackController::subscribeOnAudioParamsChanges()
 
         if (auxIt != m_auxTrackIdMap.end()) {
             aux_channel_idx_t auxIdx = auxIt->first;
-            std::string oldName = resolveAuxTrackTitle(auxIdx, audioSettings()->auxOutputParams(auxIdx));
-            std::string newName = resolveAuxTrackTitle(auxIdx, params);
+            std::string oldName = resolveAuxTrackTitle(auxIdx);
+            std::string newName = resolveAuxTrackTitle(auxIdx);
```
Comment (Eism) [inline src/playback/internal/playbackcontroller.cpp:1035]: you are calling the same method twice with the same parameters

**Review by Eism — APPROVED** [review]
