### PR TITLE
Fix #32068: String tunings drag & drop

### LINKED ISSUE #32068: Guitar String Tuning drag/drop on score doesn't work in 4.7
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

Try to drag and drop "String Tuning" from guitar palette to score

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/1b21df82-1e19-4037-a718-57e2541b4949

### In which versions of MuseScore Studio is this issue present?

OS: macOS Tahoe (26.2), Arch.: arm64, MuseScore Studio version (64-bit): 4.7.0-260205182, revision: github-musescore-musescore-b46a4ef

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

MacOS Tahoe 26.2

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mathesoncalum**
Resolves: #32068

String tunings are handled by `prepareDropMeasureAnchorElement` in `NotationInteraction`. Removing the logic from `Measure::acceptDrop` in 427f6d6b164eb130654f6186c4350f08e044b5ea means that we never set a target measure for the drop. The changes in this PR revert to what we had before this commit (with a couple tweaks).

Curious to hear your thoughts too @XiaoMigros if you get a chance - copy/pasting string tunings still appears to work as expected after these changes.

### CODE REVIEW

File: src/engraving/dom/measure.cpp [hunk 1]
```diff
@@ -1523,6 +1531,17 @@ EngravingItem* Measure::drop(EditData& data)
         score()->undoAddElement(e);
         return e;
 
+    case ElementType::STRING_TUNINGS:
+        staff = staff->isPrimaryStaff() ? staff : staff->primaryStaff();
+        if (!staff) {
+            return nullptr;
+        }
+        staffIdx = staff->idx();
+        e->setParent(first());
```
Comment (cbjeukendrup) [inline src/engraving/dom/measure.cpp]: We might want to ensure that it is a "chord rest or time tick" segment and not a random key signature header segment etc

**Comment by XiaoMigros** [comment]
Yes, looks good. I believe I only tested copy/paste thoroughly, hence the oversight. Thanks for catching this!

File: src/engraving/dom/measure.cpp (hunk 1 above)
Comment (XiaoMigros) [reply src/engraving/dom/measure.cpp]: Should we consider 'reparenting' these elements to measures instead, since that's what they can be added to? Last I checked, regardless of which segment they are anchored to, they are laid out at the start of the measure (so anchoring should be disabled accordingly, too).

Comment (mathesoncalum) [reply src/engraving/dom/measure.cpp]: > ensure that it is a "chord rest or time tick segment"...

Updated now @cbjeukendrup

Comment (mathesoncalum) [reply src/engraving/dom/measure.cpp]: It's a good point @XiaoMigros - definitely worth considering. We'll need to discuss a couple of design points before going ahead with that though, so for the purposes of 4.7 we'll push ahead with the current version of string tunings. Thanks!

**Comment by zacjansheski** [comment]
Tested on MacOS Tahoe 26.2, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/32068 FIXED
