### PR TITLE
Fix #9908- Clicking cancel closes project

### LINKED ISSUE #9908: [MU4 Issue] Clicking Cancel in Save Dialog should not close project
**Describe the bug**
When you close the main project (I did it using the shortcut), it bring about a dialog to Don't Save, Cancel and Save. If you were to click Save and move on, another dialog appears. When you click on cancel, it closes the project.

**To Reproduce**
1. Close the main project
2. You will get a dialog asking you to do one of the following: Don't Save, Cancel or Save
3. Click on Save
4. Then in the succeeding dialog, click cancel
5. It closes the project

**Expected behavior**
Clicking cancel should not close the project. It should bring it back similar to how clicking cancel in the first dialog is.

**Screenshots**
image
image

**Desktop (please complete the following information):**
 - OS: Windows 11

### PR DESCRIPTION
**Pull request by HemantAntony**
Resolves: https://github.com/musescore/MuseScore/issues/9908

This commit fixes the bug that whenever a user clicks cancel in the save dialog, it causes the project to be closed. So, whenever you close a project by clicking on the cross in the project notation tab or use Ctrl+W on the main project notation (Ctrl+W shortcut will be added soon), and then subsequently click cancel in the save dialog, it will not close the project and lets you return to it. This bug would also be present if you use Alt+F4 shortcut or close the entire app. Now this commit ensures that the app will not quit when the user clicks cancel in save dialog and lets you return to your project.

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Review by igorkorsukov — APPROVED** [review]

File: src/project/internal/projectfilescontroller.cpp [hunk 1]
```diff
@@ -285,16 +290,16 @@ IInteractive::Button ProjectFilesController::askAboutSavingScore(const io::path&
...
     if (!currentNotationProject()) {
         LOGW() << "no current project";
-        return;
+        return false;
     }
 
     if (!currentNotationProject()->created().val) {
         doSaveScore();
-        return;
+        return false;
```
Comment (RomanPudashkin) [inline src/project/internal/projectfilescontroller.cpp:302]: This return looks confusing. Probably you need to take into account the result of doSaveScore()

Comment (HemantAntony) [reply src/project/internal/projectfilescontroller.cpp:302]: Ok, if I understand correctly, I should make doSaveScore() a bool function and return the value returned by doSaveScore()

Comment (RomanPudashkin) [reply src/project/internal/projectfilescontroller.cpp:302]: Yes, absolutely correct!

Comment (HemantAntony) [reply src/project/internal/projectfilescontroller.cpp]: I updates the pull request

**Comment by HemantAntony** [comment]
Hey, this pr is ready for merge

**Comment by DmitryArefiev** [comment]
Tested #9908 on latest master build (Win10, Mac12, LinuxMint 20.2) - FIXED

Thanks!
