### PR TITLE
Fix #11522 - ensure element is scrolled into view when using top-staff command

### LINKED ISSUE #11522: [MU4 Issue] Assigning a shortcut to "go to top staff" doesn't appear to work
**Describe the bug** (Edited by Martin)

1. When the shortcut is triggered it correctly selects the topmost staff but the view does not scroll up so we can see that selection (it does this in MS3). Because the scrolling does not work, the user cannot tell whether the shortcut has worked correctly.
2. It should be renamed to 'Select the top staff'

### PR DESCRIPTION
**Pull request by wizofaus**
Resolves: [*(direct link to the issue)*](https://github.com/musescore/MuseScore/issues/11522) and fixes random crash

*(short description of the changes and the motivation to make the changes)*

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

File: src/notation/internal/notationselectionrange.cpp [hunk 1]
```diff
@@ -164,8 +164,6 @@ mu::engraving::Segment* NotationSelectionRange::rangeStartSegment() const
 {
     mu::engraving::Segment* startSegment = score()->selection().startSegment();
 
-    startSegment->measure()->firstEnabled();
```
Comment (wizofaus) [inline src/notation/internal/notationselectionrange.cpp:167]: doesn't do anything useful and crashes if startSegment is nullptr which is definitely can be in some cases

**Review by RomanPudashkin — APPROVED** [review]
