### PR TITLE
Fix #22098: staff distance with hidden staves

### LINKED ISSUE #22098: [Musicxml Export] - Confusing staff-distance
### Issue type

Import/export issue

### Bug description

[hidden staves.zip](https://github.com/musescore/MuseScore/files/14800219/hidden.staves.zip)

### Steps to reproduce

In this example, I'm demonstrating various hidden staves for Musicxml export. Since Musescore still doesn't use part-object print-object="yes/no", I have to evaluate the current staff-distance to see if it fulfills the condition of implementing correct braille exsport. The result is somewhat tricky, so I'm wondering if we still need to stick on this confusing tag.
From the exported Musicxml, I learned a positive value means the staff (except the first staff, which is controlled by staff 2's value) is displayed, while a negative value means it's hidden. The problem occurs on the zero value. At the first glance, I thought it means the upper staff is hidden, and the current staff can have notes. Please see oboe part at bar 5 and 9, and violin staff 1 bar 1, where the upper staff does hide. However, at bar 1, violin 2 staff has the value 83, where the first violin staff is actually hidden. So, how can we know which staff is hidden in this case? Does this value confusing? If yes, we should abandon it and use the staff-details print-object="yes/no", otherwise the output, both musicxml import and braille conversion, will bring big confusion. Am I right? Or is there anyone to point out the correct interpretation of this value? This, and the instrument changes, are two blocking stones for my braille transcription, so I hope to make things clear and ask our software developers to implement correct braille output, before we end the dAISY Music Braille Project next year. Thanks!

Haipeng

### Screenshots/Screen recordings

_No response_

### MuseScore Version

4.2

### Regression

No.

### Operating system

Windows

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rettinghaus**
Resolves:  #22098

This PR resolves the MusicXML export problem with ngative values for `staff-distance` when staves are not shown.

### CODE REVIEW

**Comment by lvinken** [comment]
Hi Klaus, was also working on the same issue and did not notice you beat me :-). Regards, Leon.

File: src/importexport/musicxml/internal/musicxml/export/exportmusicxml.cpp [hunk 1]
```diff
@@ -7168,7 +7168,7 @@ static bool hasPageBreak(const System* const system)
  */
 
 void ExportMusicXml::print(const Measure* const m, const int partNr, const int firstStaffOfPart,
-                           const int nrStavesInPart, const MeasurePrintContext& mpc)
+                           const staff_idx_t nrStavesInPart, const MeasurePrintContext& mpc)
```
Comment (miiizen) [inline src/importexport/musicxml/internal/musicxml/export/exportmusicxml.cpp:7171]: This would make more sense as `size_t` to match `Score::nstaves()`
