### PR TITLE
fix #17350 - check trailing measures in master score

### LINKED ISSUE #17350: Tools > Remove empty trailing measures in a part score does not take other instruments into account
### Issue type

Choose option...

### Bug description

_No response_

### Steps to reproduce

1. Create score with $\geq 2$ instruments
2. Add a few notes in the first instrument
3. Add more notes later in the score for the other instrument
4. Open the part score for the first instrument
5. Tools > Remove empty trailing measures
-> expected: it looks at the full score, and removes only those trailing measures that are empty for _all_ instruments
-> actual: it only looks at the current part score, and removes measures that are empty in the current part score but do contain notes in other instruments that are not visible in this part score

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/48658420/234235078-ba63f9c8-5504-4bdd-bf3b-724c6ffdd1ac.mov

### MuseScore Version

master

### Regression

Choose option...

### Operating system

n/a

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sammik**
Resolves: #17350 

trailing measures may differ per part, so it is important, to check them in score

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [x] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

File: src/engraving/dom/cmd.cpp [hunk 1]
```diff
@@ -4030,7 +4030,7 @@ void Score::addRemoveBreaks(int interval, bool lock)
 
 void Score::cmdRemoveEmptyTrailingMeasures()
 {
-    auto beginMeasure = firstTrailingMeasure();
+    auto beginMeasure = masterScore()->firstTrailingMeasure();
```
Comment (cbjeukendrup) [inline src/engraving/dom/cmd.cpp:4033]: This will return a measure in the `MasterScore`, instead of in the current score. I wonder if `deleteMeasures` will work well if you feed it a measure from a different score.

Comment (sammik) [reply src/engraving/dom/cmd.cpp:4033]: It seems, inside `deleteMeasures` they are used to get `Fraction`, so it works, but yes, You are right, it would be better, to do everything from masterScore.

Comment (sammik) [reply src/engraving/dom/cmd.cpp:4033]: It seems, inside `deleteMeasures` measure parameters are used just to get `Fraction`, so it works, but yes, You are right, it would be better, to call everything from masterScore.

**Review by cbjeukendrup — APPROVED** [review]

**Comment by zacjansheski** [comment]
Tested on Mac OS 11.6.5, Ubuntu 20.04.6, Windows 11
https://github.com/musescore/MuseScore/issues/17350 FIXED
