### PR TITLE
Fix #30573: Lingering appearance/playback popups

### LINKED ISSUE #30573: 4.7 Playback and Apperance menus don't close / overlap
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

1. Select a note
2. in Properties open Playback panel and apperance panel, both open, only one should be open at a time
3. Click on Layout, they are still open

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/a396e813-34b2-4044-b340-9d29c78117bf

### In which versions of MuseScore Studio is this issue present?

OS: macOS Sequoia (15.6), Arch.: arm64, MuseScore Studio version (64-bit): 4.7.0-252890320, revision: github-musescore-musescore-2d72346

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

MacOS15

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mathesoncalum**
Resolves: #30573
Also seems to resolve [this comment](https://github.com/musescore/MuseScore/issues/30573#issuecomment-3571704859) (the crash is quite inconsistent on my end, but I haven't yet managed to repro it in the PR build).

Before 823afecbd4e1304fa1e7719b21e21240abf97e2a, when the close controller belonged to `WindowView`, we deactivated the close controller in the `WindowView::close` invokable. When a close event was triggered by the [call](https://github.com/musescore/MuseScore/blob/0dde587683bc0fcd5904875a4254b3b278d699da/src/framework/uicomponents/qml/Muse/UiComponents/windowview.cpp#L239) to `m_view->close()`, the close controller did nothing and the popup closed as expected.

After this commit, the controller deactivation happens in `PopupView::onHidden`. The problem is that this method only gets a call _after_ the close event has been processed which is too late (the controller has already intercepted/[ignored](https://github.com/musescore/MuseScore/blob/0dde587683bc0fcd5904875a4254b3b278d699da/src/framework/uicomponents/qml/Muse/UiComponents/internal/popupviewclosecontroller.cpp#L114-L116) the close event).

On my end I'm also seeing an empty playback properties popup - this doesn't seem related to #30138 though so we can investigate separately.

### CODE REVIEW

File: src/framework/uicomponents/qml/Muse/UiComponents/popupview.cpp [hunk 1]
```diff
@@ -128,12 +128,6 @@ void PopupView::beforeOpen()
 void PopupView::onHidden()
 {
     WindowView::onHidden();
-
-    if (m_closeController) {
-        m_closeController->setCanClosed(true);
-        m_closeController->setActive(false);
```
Comment (cbjeukendrup) [inline src/framework/uicomponents/qml/Muse/UiComponents/popupview.cpp:134]: Does this mean that the closeController is no longer deactivated when the popup is closed for a different reason than calling `close()`?

Maybe `setCanClose` should be moved to `close`, and `setActive` should stay here?

Comment (mathesoncalum) [reply src/framework/uicomponents/qml/Muse/UiComponents/popupview.cpp:134]: From what I can tell, when a popup is closed for a reason other than calling `close` (e.g. clicking outside parent), the popup's destructor is called and the close controller is deleted. I've made these changes anyway because they do seem more correct, but I think in practice it doesn't make a big difference.

**Comment by zacjansheski** [comment]
Tested on MacOS 15, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/30573 FIXED
