### PR TITLE
Fix #18381, #13220 - plugin reload issues

### LINKED ISSUE #18381: When plugins have identical file names, only one is displayed in the menu
### Issue type

Other type of issue

### Bug description

_No response_

### Steps to reproduce

1. Unzip the attached folder and move it to MuseScore's Plugins folder
2. Open MuseScore, only 'Plugin 1' is displayed
3. Rename one of the plugin files to something else
4. 'Plugin 1' and 'Plugin 2' are displayed
[filenamedemonstration.zip](https://github.com/musescore/MuseScore/files/11947978/filenamedemonstration.zip)

### Screenshots/Screen recordings

_No response_

### MuseScore Version

4.1

### Regression

I don't know

### Operating system

Windows 10

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by wizofaus**
Resolves: #18381 
Resolves: #13220

also some issues with parsing the title/descriptions from qml files & some spelling errors in the codebase, plus renamed extensionsmodel.cpp/h to match class name (extensionslistmodel)

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

File: src/framework/extensions/internal/extensionsloader.cpp [hunk 1]
```diff
@@ -36,14 +36,14 @@ using namespace muse::extensions;
 const std::string MANIFEST("manifest.json");
 const std::string DEV_EXTENSIONS("extensions/dev/");
 
-ManifestList ExtensionsLoader::loadManifesList(const io::path_t& defPath, const io::path_t& extPath) const
+ManifestList ExtensionsLoader::loadManifestList(const io::path_t& defPath, const io::path_t& extPath) const
```
Comment (wizofaus) [inline src/framework/extensions/internal/extensionsloader.cpp:39]: just a spelling fix, this code isn't actually being used for loading plugins currently AFAICT

File: src/framework/extensions/internal/legacy/extpluginsloader.cpp [hunk 2]
```diff
@@ -93,15 +93,21 @@ Manifest ExtPluginsLoader::parseManifest(const io::path_t& path) const
...
-    m.uri = Uri("muse://extensions/v1/" + fi.baseName().toLower().toStdString());
+    m.uri = Uri("muse://extensions/v1" + path.toQString().sliced(rootPath.size()).toLower().toStdString());
     m.type = Type::Macros;
     m.apiversion = 1;
     m.legacyPlugin = true;
 
-    auto dropQuotes = [](const String& str) {
+    auto dropQuotes = [](String str) {
+        while (str.back() == ';') {
+            str.truncate(str.size() - 1);
```
Comment (wizofaus) [inline src/framework/extensions/internal/legacy/extpluginsloader.cpp:103]: allow for trailing semi-colons (which do occur)

File: src/framework/extensions/internal/legacy/extpluginsloader.cpp [hunk 3]
```diff
@@ -93,15 +93,21 @@ Manifest ExtPluginsLoader::parseManifest(const io::path_t& path) const
...
+        }
         if (str.size() < 3) {
             return String();
         }
+        if (str.startsWith(u"qsTr(\"") && str.endsWith(u"\")")) {
```
Comment (wizofaus) [inline src/framework/extensions/internal/legacy/extpluginsloader.cpp:108]: strip off qsTr("  ") which is common in many plugin files (but really we should actually translate it...)

File: src/framework/extensions/internal/legacy/extpluginsloader.cpp [hunk 4]
```diff
@@ -93,15 +93,21 @@ Manifest ExtPluginsLoader::parseManifest(const io::path_t& path) const
     io::FileInfo fi(path);
 
     Manifest m;
-    m.uri = Uri("muse://extensions/v1/" + fi.baseName().toLower().toStdString());
+    m.uri = Uri("muse://extensions/v1" + path.toQString().sliced(rootPath.size()).toLower().toStdString());
```
Comment (wizofaus) [inline src/framework/extensions/internal/legacy/extpluginsloader.cpp:96]: NB this does now mean the .qml extension is also included in the uri, which I would think is preferable anyway, case there are other possible extensions etc.

File: src/framework/extensions/view/extensionsmodel.cpp [hunk 5]
```diff
@@ -150,6 +150,7 @@ void ExtensionsListModel::editShortcut(QString codeKey)
 void ExtensionsListModel::reloadPlugins()
 {
     provider()->reloadPlugins();
+    load();
```
Comment (igorkorsukov) [inline src/framework/extensions/view/extensionsmodel.cpp:153]: better make like this: 
```
ExtensionsListModel::ExtensionsListModel(QObject* parent)
    : QAbstractListModel(parent)
{
    ...

    provider()->manifestListChanged().onNotify(this, [this]() {
        load();
    });
}
```

Comment (igorkorsukov) [reply src/framework/extensions/view/extensionsmodel.cpp:153]: > Yeah I had wondered that, but it seemed to work fine as is.

the subscription option is better because it will work if the plugin reload is not caused by this model, but for some other reason (shortcut, some API, some request from the server, etc.).

> BTW do you want me to change the file name to match the class? (extensionsListModel?)

that would be nice, thank you!

Comment (wizofaus) [reply src/framework/extensions/view/extensionsmodel.cpp]: Ok, have put rename into a separate commit

**Review by igorkorsukov — APPROVED** [review]

File: share/locale/musescore_en.ts
Comment (cbjeukendrup) [inline share/locale/musescore_en.ts:1]: (This file is automatically updated every week, so in the future you don't need to worry about updating it, but it's fine for now)
