### PR TITLE
Fix #17656: Prevent mscx conversion from wiping target folder (4.3.0)

### LINKED ISSUE #17656: Musescore in batch mode deletes ALL files under the current working directory
### Issue type

File corruption

### Bug description

After calling
"C:\Program Files\MuseScore 4\bin\MuseScore4.exe" -o "C:\Users\Lothar-msc\Documents\M4-Scores\Bach\p-95C7-R2-Nun danket alle Gott\Nun danket alle Gott. mscx" "C:\Users\Lothar-msc\Documents\M4-Scores\Bach\p-95C7-R2-Nun danket alle Gott\Nun danket alle Gott.mscz"
Exists a new EMPTY file "Nun danket alle Gott.mscx", a new directory META-INF with a rather empty "container.xml", which is also quite empty (see below).
All other files are DELETED.
A further attempt shows that ALL files/directories under the current directory are deleted, META-INF is created under the current directory and only the empty .mscx file is created in the original directory.
Musescore4 4.0.4
Tested on Microsoft Windows 10 Enterprise Evaluation (10.0.19044 Build 19044) (Hyper-V)

Translated with www.DeepL.com/Translator (free version)

### Steps to reproduce

C:\Users\Lothar-msc\Documents\M4-Scores\Bach\p-95C7-R2-Nun danket alle Gott>tree /f /a
Folder PATH listing
Volume serial number is 661E-DB26
C:.
| Nun danket alle Gott.mscz
| test.mscz
| test.txt
|
---testfolder
test2infolder.txt

C:\Users\Lothar-msc\Documents\M4-Scores\Bach\p-95C7-R2-Nun danket alle Gott>dir nun*
Volume in drive C has no label.
Volume Serial Number is 661E-DB26

Directory of C:\Users\Lothar-msc\Documents\M4-Scores\Bach\p-95C7-R2-Nun danket alle Gott

12/05/2023 07:45 34.379 Nun danket alle Gott.mscz
1 File(s) 34.379 bytes
0 Dir(s) 107.785.617.408 bytes free

C:\Users\Lothar-msc\Documents\M4-Scores\Bach\p-95C7-R2-Nun danket alle Gott>
C:\Users\Lothar-msc\Documents\M4-Scores\Bach\p-95C7-R2-Nun danket alle Gott>"C:\Program Files\MuseScore 4\bin\MuseScore4.exe" -o "C:\Users\Lothar-msc\Documents\M4-Scores\Bach\p-95C7-R2-Nun danket alle Gott\Nun danket alle Gott.mscx" "C:\Users\Lothar-msc\Documents\M4-Scores\Bach\p-95C7-R2-Nun danket alle Gott\Nun danket alle Gott.mscz"

C:\Users\Lothar-msc\Documents\M4-Scores\Bach\p-95C7-R2-Nun danket alle Gott>tree /f /a
Folder PATH listing
Volume serial number is 661E-DB26
C:.
| Nun danket alle Gott.mscx
|
---META-INF
container.xml

C:\Users\Lothar-msc\Documents\M4-Scores\Bach\p-95C7-R2-Nun danket alle Gott> dir nun*
Volume in drive C has no label.
Volume Serial Number is 661E-DB26

Directory of C:\Users\Lothar-msc\Documents\M4-Scores\Bach\p-95C7-R2-Nun danket alle Gott

12/05/2023 08:36 0 Nun danket alle Gott.mscx
1 File(s) 0 bytes
0 Dir(s) 107.784.589.312 bytes free

C:\Users\Lothar-msc\Documents\M4-Scores\Bach\p-95C7-R2-Nun danket alle Gott>type META-INF\container.xml
<?xml version="1.0" encoding="UTF-8"?>

C:\Users\Lothar-msc\Documents\M4-Scores\Bach\p-95C7-R2-Nun danket alle Gott>

### Screenshots/Screen recordings

MS4-davor
MS4-danach

### MuseScore Version

Musescore 4 4.0.2

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10 Enterprise Evaluation (10.0.19044 Build 19044) (Hyper-V)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mathesoncalum**
Resolves: #17656

### CODE REVIEW

File: src/converter/internal/convertercontroller.cpp [hunk 1]
```diff
@@ -101,15 +102,35 @@ mu::Ret ConverterController::fileConvert(const io::path_t& in, const io::path_t&
 
     globalContext()->setCurrentProject(notationProject);
 
+    if (suffix == engraving::MSCZ || suffix == engraving::MSCX) {
```
Comment (cbjeukendrup) [inline src/converter/internal/convertercontroller.cpp:105]: You might want to add `engraving::MSCS` here too (if only for consistency; this extension is not really documented anywhere so early anyone knows about it, but still...)

File: src/converter/internal/convertercontroller.cpp [hunk 2]
```diff
@@ -101,15 +102,35 @@ mu::Ret ConverterController::fileConvert(const io::path_t& in, const io::path_t&
...
+
+    io::path_t targetDirPath = io::absoluteDirpath(out);
+    if (!io::File::exists(targetDirPath)) {
+        io::Dir targetDir(targetDirPath);
+        ret = targetDir.mkpath(targetDir.absolutePath());
+        if (!ret) {
+            LOGE() << "Failed to make directory, err: " << ret.toString() << ", path: " << targetDirPath;
+            return ret;
+        }
+    }
```
Comment (cbjeukendrup) [inline src/converter/internal/convertercontroller.cpp:117]: I wonder a little bit about whether this is really necessary. I believe that usually when you call `open` on a non-existent file, it creates the entire path to that file, i.e. it also creates any missing folders.
If there are specific export formats that use a different way of writing that does fail in the case of non-existent folders, we might want to put this code in the writers for those formats themselves, instead of here.

**Comment by zacjansheski** [comment]
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/17656 FIXED

**Review by RomanPudashkin — APPROVED** [review]
