### PR TITLE
Fix big courtesy time sig spacing

### LINKED ISSUE #26548: Courtesy placement when above staves
### Issue type

Engraving issue

### Description with steps to reproduce

Above-stave bracketed courtesy should not disrupt spacing
The (12/8) at the D.C. should not displace the measure rest:

Image

Nor should it create extra space before preceding notes:

Image

Also, the bracket should be right-aligned to the barline.

### What is the latest version of MuseScore Studio where this issue is present?

Master (17 Feb 25)

### Regression

No.

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mike-spa**
Resolves: #26548

### CODE REVIEW

File: src/engraving/rendering/score/systemlayout.cpp [hunk 1]
```diff
@@ -651,11 +651,13 @@ void SystemLayout::updateBigTimeSigIfNeeded(System* system, LayoutContext& ctx)
             }
 
             Segment* prevBarlineSeg = nullptr;
+            Segment* prevRepeactAnnounceTimeSigSeg = nullptr;
```
Comment (miiizen) [inline src/engraving/rendering/score/systemlayout.cpp:654]: Just a small typo

Comment (mike-spa) [reply src/engraving/rendering/score/systemlayout.cpp:654]: lol

**Review by miiizen — APPROVED** [review]
thank you!

**Review by ghost — APPROVED** [review]
