### PR TITLE
fix #22336 - mute technique incorrectly maps to pizz strings

### LINKED ISSUE #22336: Mute / con sord. sounds like pizzicato on bowed strings
### Issue type

General playback bug

### Bug description

_No response_

### Steps to reproduce

1. enter any notes/group of notes
2. add the text instruction _mute_ (translated into my language, this instruction is called "_con sord._") to any of the entered notes.
3. activate the _MuseScore Basic_ profile
4. click play

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/134041121/71062f0e-a980-4955-88f4-d4744399c306

### MuseScore Version

OS: Windows 10 Version 2009 MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

Windows 11

### Additional context

This only occurs with the _MuseScore Basic_ profile.

### PR DESCRIPTION
**Pull request by wizofaus**
Resolves: #22336

Fix issue with MS Basic where by "mute" playing technique caused strings to play back as pizzicato (also fixed woodwinds not to play back as muted trumpet)

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

File: src/framework/audio/internal/synthesizers/fluidsynth/soundmapping.h [hunk 1]
```diff
@@ -997,7 +997,9 @@ inline const ArticulationMapping& articulationSounds(const mpe::PlaybackSetupDat
     }
 
     if (setupData.category == mpe::SoundCategory::Winds) {
-        return WINDS;
+        if (setupData.id == mpe::SoundId::Horn || setupData.id >= mpe::SoundId::Tuba) {
```
Comment (wizofaus) [inline src/framework/audio/internal/synthesizers/fluidsynth/soundmapping.h:1000]: slight kludge, but at least it prevents all known woodwind instruments from using "muted trumpet" sound when marked as muted.

**Comment by wizofaus** [comment]
Can somebody else explain the compilation errors here, they make no sense - soundData.id has never been a muse::String, and there are comparisons against mpe::SoundId in the same file that are compiling fine...

**Comment by wizofaus** [comment]
BTW something else I realised on testing this - while at least now "mute" doesn't impact the MIDI preset program selection incorrectly, it still impacts the playback duration, meaning that the moment you add a "mute" instruction, notes are only played back at something like 75% their full duration. Not sure why this would be...

File: src/framework/mpe/resources/general_strings_articulations_profile.json [hunk 2]
```diff
@@ -3842,7 +3842,7 @@
         "Mute": [
             {
                 "arrangementPattern": {
-                    "durationFactor": 8000,
+                    "durationFactor": 9900,
```
Comment (wizofaus) [inline src/framework/mpe/resources/general_strings_articulations_profile.json:3845]: no reason for muted notes not to have standard playback duration

File: src/framework/audio/internal/synthesizers/fluidsynth/soundmapping.h [hunk 3]
```diff
@@ -1000,7 +1000,10 @@ inline const ArticulationMapping& articulationSounds(const mpe::PlaybackSetupDat
     }
 
     if (setupData.category == mpe::SoundCategory::Winds) {
-        return WINDS;
+        soundId = setupData.soundId();
+        if (soundId == mpe::SoundId::Horn || (int)soundId >= (int)mpe::SoundId::Tuba) {
```
Comment (RomanPudashkin) [inline src/framework/audio/internal/synthesizers/fluidsynth/soundmapping.h:1004]: It would be better to add std::unordered_set<SoundId> and explicitly specify there SoundId for which we want to use BRASS

File: src/framework/audio/internal/synthesizers/fluidsynth/soundmapping.h [hunk 4]
```diff
@@ -1000,7 +1000,10 @@ inline const ArticulationMapping& articulationSounds(const mpe::PlaybackSetupDat
     }
 
     if (setupData.category == mpe::SoundCategory::Winds) {
-        return WINDS;
+        soundId = setupData.soundId();
```
Comment (RomanPudashkin) [inline src/framework/audio/internal/synthesizers/fluidsynth/soundmapping.h:1003]: This doesn't do anything

Comment (wizofaus) [reply src/framework/audio/internal/synthesizers/fluidsynth/soundmapping.h:1003]: it mostly certain does!

File: src/framework/audio/internal/synthesizers/fluidsynth/soundmapping.h (hunk 3 above)
Comment (wizofaus) [reply src/framework/audio/internal/synthesizers/fluidsynth/soundmapping.h:1004]: I agree, just that that's a bigger change that would require more discussion

File: src/framework/audio/internal/synthesizers/fluidsynth/soundmapping.h (hunk 4 above)
Comment (RomanPudashkin) [reply src/framework/audio/internal/synthesizers/fluidsynth/soundmapping.h:1003]: what exactly?

Comment (wizofaus) [reply src/framework/audio/internal/synthesizers/fluidsynth/soundmapping.h:1003]: are you saying that at this point, soundId already has that value? When I looked that didn't seem to be true in all cases

Comment (RomanPudashkin) [reply src/framework/audio/internal/synthesizers/fluidsynth/soundmapping.h:1003]: Yes, it has the correct value. We declare it here:
Screenshot 2024-05-20 at 11 56 41

File: src/framework/audio/internal/synthesizers/fluidsynth/soundmapping.h (hunk 3 above)
Comment (RomanPudashkin) [reply src/framework/audio/internal/synthesizers/fluidsynth/soundmapping.h]: This change is not that big... You already specified the list, but you did it implicitly using this condition: (int)soundId >= (int)mpe::SoundId::Tuba. However, it is rather unreliable because it depends on the order of items in the SoundId enum

**Comment by zacjansheski** [comment]
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/22336 FIXED

**Review by RomanPudashkin — APPROVED** [review]
