### PR TITLE
[MU4] fix #7823 - ensure keyboard navigation between lyrics works as …

### LINKED ISSUE #7823: [MU4 Issue] Pressing space, dash, underscore does not move to next note
**Describe the bug**
Lyrics editing: pressing space, dash, underscore does not move to next note (try this in 3.6)

**To Reproduce**
1. Create a score
2. Add lyrics and notes
3. Select note
4. press space, dash, underscore

**Expected behavior**
pressing space, dash, underscore should move to next note (try this in 3.6)

**Screenshots**

**Desktop (please complete the following information):**
MacOS

**Additional context**

### PR DESCRIPTION
**Pull request by wizofaus**
…expected

Resolves: https://github.com/musescore/MuseScore/issues/7823

None of the code to handle navigating between Lyrics using the keyboard in MU3 had been ported to MU4 yet.
The implementation is somewhat different now - in MU3 only space for "next lyric" (which is weirdly called "Next Syllable" in the preferences dialog) was set up as command with a customisable shortcut, all the other cases were handled via special case code.
There didn't seem to be any reason all the possible navigation commands shouldn't all be treated the same way, so that's the implementation here (which prevents the need for using the MuseScoreView/ScoreCallbacks interface - it's possible we'll never need this).

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

File: src/playback/internal/playbackcontroller.cpp [hunk 1]
```diff
@@ -73,7 +73,7 @@ int PlaybackController::currentTick() const
 
 bool PlaybackController::isPlayAllowed() const
 {
-    return m_notation != nullptr;
+    return m_notation != nullptr && !m_notation->interaction()->isTextEditingStarted();
```
Comment (wizofaus) [inline src/playback/internal/playbackcontroller.cpp:76]: prevent space from starting playback while editing lyrics !

File: src/notation/internal/notationuiactions.cpp [hunk 2]
```diff
@@ -1368,6 +1368,18 @@ const UiActionList NotationUiActions::m_scoreConfigActions = {
...
+             QT_TRANSLATE_NOOP("action", "Next lyric"),
+             QT_TRANSLATE_NOOP("action", "Move to lyric on next note"),
+             Checkable::Yes
+             ),
+    UiAction("prev-lyric",
+             mu::context::UiCtxNotationOpened,
+             QT_TRANSLATE_NOOP("action", "Previous lyric"),
+             QT_TRANSLATE_NOOP("action", "Move to lyric on previous note"),
+             Checkable::Yes
              )
```
Comment (wizofaus) [inline src/notation/internal/notationuiactions.cpp:1383]: still need to add actions for up/down/melisma/nextSyllable

File: src/notation/internal/notationinteraction.cpp [hunk 3]
```diff
@@ -2040,6 +2042,130 @@ mu::async::Channel<ScoreConfigType> NotationInteraction::scoreConfigChanged() co
     return m_scoreConfigChanged;
 }
 
+void NotationInteraction::nextLyric(bool back, bool moveOnly, bool end)
+{
+    if (!m_textEditData.element || !m_textEditData.element->isLyrics()) {
```
Comment (wizofaus) [inline src/notation/internal/notationinteraction.cpp:2047]: largely copied from ScoreView::lyricsTab in MU3.6, could use some cleaning up

File: src/engraving/libmscore/lyrics.cpp [hunk 4]
```diff
@@ -504,6 +504,26 @@ Element* Lyrics::drop(EditData& data)
...
 }
 
+//---------------------------------------------------------
+//   edit
+//---------------------------------------------------------
+
+bool Lyrics::edit(EditData& ed)
+{
+    if (ed.view() && (ed.modifiers == 0 || ed.modifiers == Qt::ShiftModifier)) {
+        ed.view()->setScore(score());
```
Comment (wizofaus) [inline src/engraving/libmscore/lyrics.cpp:514]: remove this

File: src/notation/internal/notationinteraction.cpp [hunk 5]
```diff
@@ -66,7 +67,7 @@ using namespace mu::notation;
 
 NotationInteraction::NotationInteraction(Notation* notation, INotationUndoStackPtr undoStack)
     : m_notation(notation), m_undoStack(undoStack), m_gripEditData(&m_scoreCallbacks),
-    m_lasso(new Ms::Lasso(notation->score()))
+    m_lasso(new Ms::Lasso(notation->score())), m_textEditData(&m_scoreCallbacks)
```
Comment (wizofaus) [inline src/notation/internal/notationinteraction.cpp:70]: initial implementation required this, doesn't now but it still makes sense

File: src/notation/internal/instrumentsconverter.cpp [hunk 6]
```diff
@@ -116,7 +116,7 @@ Instrument InstrumentsConverter::convertInstrument(const Ms::InstrumentTemplate&
     Ms::Instrument msInstrument = Ms::Instrument::fromTemplate(&templ);
     Instrument result = convertInstrument(msInstrument);
     result.templateId = templ.id;
-    result.familyId = templ.family->id;
+    result.familyId = templ.family ? templ.family->id : QString();
```
Comment (wizofaus) [inline src/notation/internal/instrumentsconverter.cpp:119]: can't even start MuseScore without this

File: src/notation/internal/notationinteraction.h [hunk 7]
```diff
@@ -182,6 +182,12 @@ class NotationInteraction : public INotationInteraction, public async::Asyncable
     void setScoreConfig(ScoreConfig config) override;
     async::Channel<ScoreConfigType> scoreConfigChanged() const override;
 
+    virtual void nextLyrics(bool = false, bool = false, bool = true) override;
+    virtual void nextLyricsVerse(bool = false) override;
+    virtual void nextSyllable() override;
+    virtual void addMelisma() override;
+    virtual void addLyricsVerse() override;
```
Comment (igorkorsukov) [inline src/notation/internal/notationinteraction.h:189]: better without the keyword `virtual` here

**Comment by Jojo-Schmitz** [comment]
That merge commit should be in this PR

**Comment by Jojo-Schmitz** [comment]
That res.bat probably shouldn't either

**Comment by Jojo-Schmitz** [comment]
Neither that src/engraving/libmscore/8

**Comment by wizofaus** [comment]
> That merge commit should be in this PR
> That res.bat probably shouldn't either
> Neither that src/engraving/libmscore/8

i know i know, had so many issues with this PR, and I've tried squashing the commits but it just doesn't work

**Comment by wizofaus** [comment]
NB I haven't fixed the bug with the vertical positioning of lyrics/hyphens, that's unrelated and was already present, but will look into it.
