### PR TITLE
Fix Volta layout in palette

### LINKED ISSUE #30903: Palettes are appearing incorrectly in master
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

Recent change is causing problems with how palettes appear, particularly Layout, but also Keyboard and line elements like voltas

### Supporting files, videos and screenshots

Nightly on left, master on right

Image

### In which versions of MuseScore Studio is this issue present?

OS: macOS Sequoia (15.6), Arch.: arm64, MuseScore Studio version (64-bit): 4.7.0-253101846, revision: github-musescore-musescore-08261ca

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

MacOS15

### Additional context

Noticed in PRs today

Ran this build to confirm
https://github.com/musescore/MuseScore/actions/runs/19146304101

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mike-spa**
Resolves: [#30903](https://github.com/musescore/MuseScore/issues/30903)

### CODE REVIEW

**Review by cbjeukendrup — APPROVED** [review]

**Comment by cbjeukendrup** [comment]
This does probably not resolve the full issue: the "length" of the spanners in the palette is hardcoded, but apparently stored in DPI-dependent units, so some kind of migration is needed to make palettes from pre-4.7 look good

File: src/palette/internal/palettecreator.cpp [hunk 1]
```diff
@@ -478,7 +475,6 @@ PalettePtr PaletteCreator::newRepeatsPalette(bool defaultPalette)
     qreal w = gpaletteScore->style().spatium() * 8;
```
Comment (cbjeukendrup) [inline src/palette/internal/palettecreator.cpp]: This can now be removed

**Comment by zacjansheski** [comment]
Tested on MacOS 15, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/30903 FIXED
