### PR TITLE
Fix #14377: "Follow system theme" on Linux

### LINKED ISSUE #14377: [MU4 Issue] Handle Linux dark-mode settings
**Describe the bug**
MU4 doesn't currently support Linux's cross-desktop system dark mode settings. This setting provides a cross-desktop method for apps to query system settings about whether or not the user prefers a light theme, a dark theme, or has no preference. This would allow MuseScore to better respect user preferences

**To Reproduce**
1. Go to Edit > Preferences > Appearence
2. Observe that there's no "Follow System Settings" option
3. Skim MuseScore source code to see that functionality for such an option does seem to exist on Windows and macOS

**Expected behavior**
MuseScore uses the [org.freedesktop.portal.Settings](https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.Settings) dbus API to query the
`org.freedesktop.appearance color-scheme` setting, and integrates this functionality into MuseScore the same way it is done for Windows/macOS

**Screenshots**

**Platform information**
 - OS: Linux (using the GNOME DE)

**Additional context**
Even though this setting exists in and is provided to apps by the Flatpak portal infrastructure, running in a Flatpak container isn't a prerequisite. Many modern cross-desktop specifications are being implemented as Flatpak portals, for a couple of reasons:
1) It's a good place to define cross-desktop generic APIs (since apps need to talk to the portals anyway, to work inside the sandbox)
2) It has a mechanism for different desktop environments to provide a backends for these APIs without having to rewrite the whole thing
3) These APIs work exactly the same way inside of a sandbox as they do outside of a sandbox (so apps that make use of these APIs will Just Work™ in the sandbox)

The dark mode specification has already been implemented by the major DEs:
- KDE: https://github.com/KDE/xdg-desktop-portal-kde/blob/master/src/settings.cpp#L292-L306
- GNOME: https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/blob/main/src/settings.c#L174-L184
- And others

For your referernce, [here](https://invent.kde.org/frameworks/kguiaddons/-/blob/master/src/colors/kcolorschemewatcher_xdg.cpp) is KDE's existing implementation for querying the value of the setting and monitoring it for changes. [Here](https://api.kde.org/frameworks/kguiaddons/html/classKColorSchemeWatcher.html) is a description of what that code is implementing.

### PR DESCRIPTION
**Pull request by adazem009**
Resolves: #14377
Resolves: #16966

Uses the [org.freedesktop.portal.Settings](https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.Settings) dbus API to query the `org.freedesktop.appearance color-scheme` setting.

`LinuxPlatformTheme` inherits from `QObject`. This is required because the only way of connecting a D-Bus signal to a slot using `QDBusConnection::connect()` is using the old method (`SLOT()`).

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
> * What's ValNt? Is it something specific to Windows?

ValNt is a simple struct type made by us, defined in `src/framework/global/types/retval.h`. Its purpose is to conveniently store a `async::Notification` together with the value about which this notification will notify. 

> * Should I use `std::thread` like `WindowsPlatformTheme` and add a `th_listen()` method?

On Windows, listening for theme change messages is a blocking operation. It is essentially not much different than a `while (true) { … }` loop. Therefore, we need to do it on a separate thread, because otherwise the UI cannot run. 

It looks like this is not necessary on Linux. If I understand your code correctly (I haven't read it thoroughly yet), we just listen for the signal from Qt, and when that is emitted, we do some small operation. Unless that operation might potentially take long, I don't think that needs to be done on a separate thread (which would be quite a complication...).

**Comment by adazem009** [comment]
I've found this in the Qt source code. They're doing it the same way, so it should be fine.

https://github.com/qt/qtbase/blob/dev/src/plugins/platformthemes/xdgdesktopportal/qxdgdesktopportaltheme.cpp#L123

**Comment by adazem009** [comment]
I've tested this in KDE Plasma, GNOME and Unity, everything's working.

I event tried to use the `dwm` window manager (which probably doesn't have any theming) and the "Follow system theme" option didn't show at all, so that's working correctly too.

File: src/framework/ui/internal/platform/linux/linuxplatformthemelistener.h [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+#include "internal/iplatformtheme.h"
+
+class QDBusVariant;
+
+namespace mu::ui {
+class LinuxPlatformThemeListener : public QObject
+{
+    Q_OBJECT
+public slots:
+    void processSettingChange(const QString& group, const QString& key, const QDBusVariant& value);
```
Comment (Eism) [inline src/framework/ui/internal/platform/linux/linuxplatformthemelistener.h:35]: I think we don't need to create a separate class for this slot
You can add this slot to LinuxPlatformTheme

File: src/framework/ui/internal/platform/linux/linuxplatformtheme.h [hunk 2]
```diff
@@ -45,7 +46,12 @@ class LinuxPlatformTheme : public IPlatformTheme
     void applyPlatformStyleOnWindowForTheme(QWindow* window, const ThemeCode& themeCode) override;
 
 private:
+    bool isSystemThemeCurrentlyDark() const;
+
     async::Notification m_platformThemeChanged;
+    LinuxPlatformThemeListener m_listener;
+    bool m_isListening = false;
+    bool m_isSystemThemeDark;
```
Comment (Eism) [inline src/framework/ui/internal/platform/linux/linuxplatformtheme.h:54]: need to initialize the variable

File: src/framework/ui/internal/platform/linux/linuxplatformthemelistener.h (hunk 1 above)
Comment (adazem009) [reply src/framework/ui/internal/platform/linux/linuxplatformthemelistener.h:35]: > I think we don't need to create a separate class for this slot You can add this slot to LinuxPlatformTheme

`LinuxPlatformTheme` would then need to inherit from QObject. Is that okay?

Comment (cbjeukendrup) [reply src/framework/ui/internal/platform/linux/linuxplatformthemelistener.h:35]: @adazem009 I believe that if you use the modern `connect` overloads (for example, passing `&LinuxPlatformTheme:: processSettingChange` instead of `SLOT(processSettingChange(…))` for the slot, and the same for the signal), then `&LinuxPlatformTheme:: processSettingChange` doesn't even need to be a slot, and `LinuxPlatformTheme` doesn't need to be a `QObject`. Not 100% sure though.

Comment (adazem009) [reply src/framework/ui/internal/platform/linux/linuxplatformthemelistener.h:35]: > @adazem009 I believe that if you use the modern `connect` overloads (for example, passing `&LinuxPlatformTheme:: processSettingChange` instead of `SLOT(processSettingChange(…))` for the slot, and the same for the signal), then `&LinuxPlatformTheme:: processSettingChange` doesn't even need to be a slot, and `LinuxPlatformTheme` doesn't need to be a `QObject`. Not 100% sure though.

The problem is that `QDBusConnection::connect()` doesn't have the modern overloads. (https://doc.qt.io/qt-5/qdbusconnection.html#connect)

See https://forum.qt.io/topic/75117/lambdas-in-qdbusconnection-connect

Comment (adazem009) [reply src/framework/ui/internal/platform/linux/linuxplatformthemelistener.h]: > I think we don't need to create a separate class for this slot You can add this slot to LinuxPlatformTheme

done

File: src/framework/ui/internal/platform/linux/linuxplatformtheme.cpp [hunk 3]
```diff
@@ -28,26 +28,45 @@
...
 }
 
 bool LinuxPlatformTheme::isFollowSystemThemeAvailable() const
 {
+    const QDBusConnection connection = QDBusConnection::sessionBus();
+    static const QString registrarService = QStringLiteral("org.freedesktop.portal.Desktop");
+    if (const auto iface = connection.interface()) {
+        return iface->isServiceRegistered(registrarService);
+    }
     return false;
```
Comment (cbjeukendrup) [inline src/framework/ui/internal/platform/linux/linuxplatformtheme.cpp:61]: It is our convention to add some extra newlines for readability. For example, here...
```suggestion
    const QDBusConnection connection = QDBusConnection::sessionBus();
    
    if (const auto iface = connection.interface()) {
        static const QString registrarService = QStringLiteral("org.freedesktop.portal.Desktop");
        return iface->isServiceRegistered(registrarService);
    }
    
    return false;
```

File: src/framework/ui/internal/platform/linux/linuxplatformtheme.cpp [hunk 4]
```diff
@@ -28,26 +28,45 @@
...
 }
 
 bool LinuxPlatformTheme::isSystemThemeDark() const
 {
-    return false;
+    if (m_isListening) {
+        return m_isSystemThemeDark;
+    }
+    return isSystemThemeCurrentlyDark();
```
Comment (cbjeukendrup) [inline src/framework/ui/internal/platform/linux/linuxplatformtheme.cpp:69]: And here...
```suggestion
    if (m_isListening) {
        return m_isSystemThemeDark;
    }
    
    return isSystemThemeCurrentlyDark();
```

File: src/framework/ui/internal/platform/linux/linuxplatformtheme.cpp [hunk 5]
```diff
@@ -72,3 +91,23 @@ void LinuxPlatformTheme::applyPlatformStyleOnAppForTheme(const ThemeCode&)
...
+bool LinuxPlatformTheme::isSystemThemeCurrentlyDark() const
+{
+    auto message = QDBusMessage::createMethodCall(service, path, interface, QStringLiteral("Read"));
+    message << QStringLiteral("org.freedesktop.appearance") << QStringLiteral("color-scheme");
+    QDBusReply<QVariant> reply = QDBusConnection::sessionBus().call(message);
+    if (reply.isValid()) {
+        const QDBusVariant dbusVariant = qvariant_cast<QDBusVariant>(reply.value());
+        return dbusVariant.variant().toUInt() == 1;
+    }
+    return false;
```
Comment (cbjeukendrup) [inline src/framework/ui/internal/platform/linux/linuxplatformtheme.cpp:112]: And here:
```suggestion
    auto message = QDBusMessage::createMethodCall(service, path, interface, QStringLiteral("Read"));
    message << QStringLiteral("org.freedesktop.appearance") << QStringLiteral("color-scheme");

    QDBusReply<QVariant> reply = QDBusConnection::sessionBus().call(message);
    if (reply.isValid()) {
        const QDBusVariant dbusVariant = qvariant_cast<QDBusVariant>(reply.value());
        return dbusVariant.variant().toUInt() == 1;
    }
    
    return false;
```

File: src/framework/ui/internal/platform/linux/linuxplatformtheme.cpp [hunk 6]
```diff
@@ -72,3 +91,23 @@ void LinuxPlatformTheme::applyPlatformStyleOnAppForTheme(const ThemeCode&)
 void LinuxPlatformTheme::applyPlatformStyleOnWindowForTheme(QWindow*, const ThemeCode&)
 {
 }
+
+void LinuxPlatformTheme::processSettingChange(const QString& group, const QString& key, const QDBusVariant& value)
+{
+    if (group == "org.freedesktop.appearance" && key == "color-scheme") {
```
Comment (cbjeukendrup) [inline src/framework/ui/internal/platform/linux/linuxplatformtheme.cpp:97]: In other places you're using QStringLiteral, maybe that would be good here too?
```suggestion
    if (group == QStringLiteral("org.freedesktop.appearance") && key == QStringLiteral("color-scheme")) {
```

**Review by cbjeukendrup — COMMENTED** [review]
I've some stylistic remarks (which is an euphemism for nitpicks), but for the rest this looks good to me!

**Review by Eism — APPROVED** [review]

**Comment by zacjansheski** [comment]
Mac 11.6.5 and Windows 11 builds are functioning as expected (nothing is broken).

"Follow System Theme" does not function in Ubuntu 20.04.6  (if that was expected here)
https://github.com/musescore/MuseScore/assets/69917893/a8427b59-1f48-4224-bdcf-f2cb20e55fbe

**Comment by adazem009** [comment]
> Mac 11.6.5 and Windows 11 builds are functioning as expected (nothing is broken).
> 
> "Follow System Theme" does not function in Ubuntu 20.04.6 (if that was expected here) Sorry for the video quality, not a very powerful device :) https://github.com/musescore/MuseScore/assets/69917893/a8427b59-1f48-4224-bdcf-f2cb20e55fbe

I think it's because the `color-scheme` setting was implemented in GNOME after Ubuntu 20.04 was released (https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/commit/4c1d8c2b28578ca736915e409afef7bb57b0cca1)

I'll try to find a way to check whether the desktop environment provides the setting instead of checking whether the `org.freedesktop.portal.Desktop` service is available, and I'll update the PR.

**Comment by adazem009** [comment]
@zacjansheski Done, can you please test it again? The expected behavior on Ubuntu 20.04 is that MuseScore shouldn't show the "Follow system theme" option at all because GNOME didn't have support for it at the time of Ubuntu 20.04 release.

It should work in Ubuntu 22.04 and newer. I don't know whether 21.10 has support for it.

@cbjeukendrup I've done some small changes to `isFollowSystemThemeAvailable()`. It now returns false when the reply of the `Read` method call is invalid (when reading the `color-scheme` setting).

**Comment by zacjansheski** [comment]
Looks good!

Tested on Mac 11.6.5, Windows 11, Ubuntu 20.04.6

File: src/framework/ui/internal/platform/linux/linuxplatformtheme.cpp [hunk 7]
```diff
@@ -28,26 +28,53 @@
...
+                                             SLOT(processSettingChange(QString,QString,QDBusVariant)));
+    m_isListening = false;
 }
 
 bool LinuxPlatformTheme::isFollowSystemThemeAvailable() const
 {
-    return false;
+    const QDBusConnection connection = QDBusConnection::sessionBus();
+
+    static const QString registrarService = QStringLiteral("org.freedesktop.portal.Desktop");
```
Comment (cbjeukendrup) [inline src/framework/ui/internal/platform/linux/linuxplatformtheme.cpp:58]: Can't this be `service`? Or is it really a different thing with a different role, that only coincidentally has the same value as `service`?

File: src/framework/ui/internal/platform/linux/linuxplatformtheme.cpp [hunk 8]
```diff
@@ -28,26 +28,53 @@
...
+    const auto iface = connection.interface();
+    if (!iface->isServiceRegistered(registrarService)) {
+        return false;
+    }
+
+    auto message = QDBusMessage::createMethodCall(service, path, interface, QStringLiteral("Read"));
+    message << QStringLiteral("org.freedesktop.appearance") << QStringLiteral("color-scheme");
+
+    QDBusReply<QVariant> reply = QDBusConnection::sessionBus().call(message);
```
Comment (cbjeukendrup) [inline src/framework/ui/internal/platform/linux/linuxplatformtheme.cpp:67]: Maybe it's a good idea to extract these lines into separate method that returns `QDBusReply<QVariant>`, and reuse it in `isSystemThemeCurrentlyDark()`, to prevent the duplication. 

Also, I see multiple references to `QStringLiteral("org.freedesktop.appearance")` and `QStringLiteral("color-scheme")`, maybe we should create `static const QStrings` for those.

File: src/framework/ui/internal/platform/linux/linuxplatformtheme.cpp (hunk 7 above)
Comment (adazem009) [reply src/framework/ui/internal/platform/linux/linuxplatformtheme.cpp:58]: > Can't this be `service`? Or is it really a different thing with a different role, that only coincidentally has the same value as `service`?

I didn't notice that, I'll fix it...
Both strings are used for the same D-Bus service.

**Review by cbjeukendrup — APPROVED** [review]

**Comment by zacjansheski** [comment]
I approve, @Eism ?
