### PR TITLE
fix #10986: double / triple click  to select word / all  and other text editing refinements

### LINKED ISSUE #10986: [MU4 Issue] Playback. Ornaments notes play only around 1 semitone up and down when 2 semitones are between the notes
**To Reproduce**
1. Open any score 
2. Put any ornament to a note
3. Play the score and pay attention to the ornament playback

**Expected behavior**
Ornaments notes play according to the current scale and accidentals in the current measure

**Screenshots**

https://user-images.githubusercontent.com/101250347/160901103-76258db0-2a01-4251-a208-f75c61625aac.mov

**Platform information**
 - OS: [macOS, Windows]

### PR DESCRIPTION
**Pull request by Obliquely**
- double click to select word when editing text elements in score
- second click on selected element moves text element into editing mode
- make cursor narrower - more in line with non-score text editing UI
- make highlight larger - more in line with non-score text editing UI
- make highlight color match highlight color in the theme

### CODE REVIEW

**Comment by IsaacWeiss** [comment]
Nice!

**Comment by Jojo-Schmitz** [comment]
Please change the commit title (and optionaly the PR title) to start with "fix #290271: "

**Comment by IsaacWeiss** [comment]
Sorry, can you change it again to "#10986"? See https://musescore.org/en/node/290271#comment-924648. (Also, it would be cool if you want to implement triple-click to select paragraph while you're at it.)

File: libmscore/textbase.cpp [hunk 1]
```diff
@@ -1645,6 +1689,19 @@ void TextBase::selectAll(TextCursor* _cursor)
...
       }
 
+//---------------------------------------------------------
+//   multiClickSelect
+//    for double and triple clicks
+//---------------------------------------------------------
+
+void TextBase::multiClickSelect(EditData& editData, int clicks)
+      {
+      if (clicks == 2)
```
Comment (Jojo-Schmitz) [inline libmscore/textbase.cpp]: What about single click, i.e. if `clicks` is 1?

Comment (Obliquely) [reply libmscore/textbase.cpp]: I've changed the int parameter to an enum so the code/intent is clearer. There are only two cases - double or triple click - handled by this method and that's now fully explicit.

**Comment by dmitrio95** [comment]
Could you please extract those changes that are not related to the double/triple-click handling feature (that is, color changes, cursor width changes etc.) to a separate pull request? Even if they make things clearly better they are not related to the main topic of this PR and should better be considered (and committed) separately.

File: libmscore/textbase.cpp [hunk 2]
```diff
@@ -328,6 +328,52 @@ bool TextCursor::movePosition(QTextCursor::MoveOperation op, QTextCursor::MoveMo
...
+                  ++_column;
+
+            _selectColumn = _column;
+
+            _column = startPosition;
+            while (_column  < curLine().columns() && currentCharacter().isSpace())
+                  ++_column;
+            }
+            updateCursorFormat();
+            _text->score()->addRefresh(_text->canvasBoundingRect());
```
Comment (dmitrio95) [inline libmscore/textbase.cpp]: Wrong indentation of these two lines: as far as I can see they don't belong to the "if-else" block above so should be indented one level less.

Comment (Obliquely) [reply libmscore/textbase.cpp]: OK

**Comment by Obliquely** [comment]
> Could you please extract those changes that are not related to the double/triple-click handling feature (that is, color changes, cursor width changes etc.) to a separate pull request? Even if they make things clearly better they are not related to the main topic of this PR and should better be considered (and committed) separately.

I've removed cursor color change, cursor width change, and size of highlight change and will put them in a separate PR.

File: libmscore/textbase.h [hunk 3]
```diff
@@ -288,6 +298,9 @@ class TextBase : public Element {
       bool deleteSelectedText(EditData&);
 
       void selectAll(TextCursor*);
+      void multiClickSelect(EditData&, MultiClick);
+      bool isPrimed() const               { return _primed; }
```
Comment (dmitrio95) [inline libmscore/textbase.h]: Is this `primed` flag used anywhere? I don't see this flag influence anything currently.

File: libmscore/textbase.cpp [hunk 4]
```diff
@@ -328,6 +328,52 @@ bool TextCursor::movePosition(QTextCursor::MoveOperation op, QTextCursor::MoveMo
...
+                  --_column;
+
+            if (!currentCharacter().isSpace())
+                  ++_column;
+
+            _selectColumn = _column;
+
+            _column = startPosition;
+            while (_column  < curLine().columns() && currentCharacter().isSpace())
+                  ++_column;
```
Comment (dmitrio95) [inline libmscore/textbase.cpp]: The selection code is good but these two branches of `if` statement are absolutely equal except the fact that one is searches for space characters and other — for non-space characters. Can they be perhaps merged to avoid the code duplication? As a simple option, we could make some boolean flag, say,
`const bool selectSpaces = currentCharacher().isSpace();`
and use it in conditions in this code, for example
```
while (_column > 0 && (currentCharacter().isSpace() == selectSpaces))
      --_column;
// etc.
```
Then we won't need to write this code twice.

File: mscore/events.cpp [hunk 5]
```diff
@@ -368,6 +404,26 @@ void ScoreView::mousePressEventNormal(QMouseEvent* ev)
 
 void ScoreView::mousePressEvent(QMouseEvent* ev)
       {
+
+      if (tripleClickPending) {
+            qDebug()<<"triple click detected...";
```
Comment (dmitrio95) [inline mscore/events.cpp]: Could you please remove these `qDebug()` messages? They can be easily added if needed, and it is better not to keep them in the common codebase in most cases.

File: mscore/events.cpp [hunk 6]
```diff
@@ -368,6 +404,26 @@ void ScoreView::mousePressEventNormal(QMouseEvent* ev)
...
+                && editData.element
+                && editData.element->isTextBase()) {
+                  TextBase* textBase = toTextBase(editData.element);
+                  textBase->multiClickSelect(editData, MultiClick::Triple);
+                  mscore->textTools()->updateTools(editData);
+                  textBase->endHexState(editData);
+                  qDebug()<<"tripleClick - selecting ALL";
+                  update();
+                  return;
+            }
```
Comment (dmitrio95) [inline mscore/events.cpp]: Wrong indentation: 6 spaces more are needed

File: libmscore/textbase.h (hunk 3 above)
Comment (Obliquely) [reply libmscore/textbase.h]: It's used in startTextEditingOnMouseRelease in events.cpp

File: libmscore/textbase.cpp (hunk 4 above)
Comment (Obliquely) [reply libmscore/textbase.cpp]: OK. I've done that. I think it's a wee bit harder to follow the code now, but it does reduce duplication.

File: mscore/events.cpp (hunk 5 above)
Comment (Obliquely) [reply mscore/events.cpp]: Thanks. Hadn't spotted that I'd left those in there.

File: mscore/events.cpp (hunk 6 above)
Comment (Obliquely) [reply mscore/events.cpp]: Fixed

**Comment by Obliquely** [comment]
Thanks for review. All changes requested now made. I also spotted and extra stray qDebug() and removed that. I hadn't realised that QT has a global for double click interval (QApplication::doubleClickInterval()). I've used that instead of the previously hard-coded 400 value.

File: libmscore/textbase.h (hunk 3 above)
Comment (dmitrio95) [reply libmscore/textbase.h]: Ah, I see now. Doesn't that duplicate the logic of `selected` flag though? That is, would calling `textBase->selected()` instead of `textBase->isPrimed()` achieve the desired effect? Or is the purpose of this flag different?

Comment (Obliquely) [reply libmscore/textbase.h]: The purpose is different. Without an extra flag startTextEditingOnMouseRelease can't tell the difference between the item being selected (for the first time, in which, we don't want to start editing) or for the second time (in which case we do). That's because the selection status is already set before mouse up. Hence the extra flag.

Comment (dmitrio95) [reply libmscore/textbase.h]: OK, thanks for the explanation! Then I'll leave a probably final code style review, and I believe after correcting those styling issues this PR can be merged.

File: libmscore/textbase.h [hunk 7]
```diff
@@ -232,6 +241,7 @@ class TextBase : public Element {
       bool _layoutToParentWidth     { false };
 
       int  hexState                 { -1    };
+      bool _primed                  { 0 };
```
Comment (dmitrio95) [inline libmscore/textbase.h]: As this is `bool`, it is better to initialize it with `false` rather than `0`.

File: mscore/events.cpp [hunk 8]
```diff
@@ -221,11 +221,44 @@ void ScoreView::focusOutEvent(QFocusEvent* event)
...
+            // mouse up OUTSIDE textbase - clear any priming
+            textBase->setPrimed(false);
+            return false;
+            }
+
+      if (!textBase->isPrimed()) {
+            // mouse up INSIDE textBase - set priming
+            textBase->setPrimed(true);
+            return false;
+      }
```
Comment (dmitrio95) [inline mscore/events.cpp]: Wrong indentation for this brace: 6 spaces more needed.

**Comment by dmitrio95** [comment]
Merged that for a pre-release, those issues are minor anyway.
Thanks for implementing this, an 8-years issue got finally resolved :)
