### PR TITLE
fix #19244 - [MusicXML import] reversed wedge not imported

### LINKED ISSUE #19244: Chord symbols not attached to a specific note or rest are skipped by Alt+Left/Right
### Issue type

UI bug

### Bug description

If you use Space or semicolon or other shortcut to enter a chord symbol on a beat position that lacks a note or rest, then keyboard navigation (Alt+Left/Right) skips it.

### Steps to reproduce

1. Empty score
2. Click first measure rest
3. Ctrl+K to enter chord symbols
4. Type C Space D to enter those chord symbols on beats 1 & 2
5. Esc to leave chord symbol / text input mode
6. Use Alt+Left/Right to navigate through the measure

ResultL: the D chord on beat 2 is skipped

This is an accessibility issue as well as a general usability issue.  It is not new with MU4; it was the same in MU3.

### Screenshots/Screen recordings

_No response_

### MuseScore Version

OS: Debian GNU/Linux 11 (bullseye), Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

No.

### Operating system

Debian 11

### Additional context

Also broken in current master.

### PR DESCRIPTION
**Pull request by lvinken**
Resolves: https://musescore.org/en/node/19244

Fix import of all reversed spanners and improve spanner error handling

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://musescore.org/en/handbook/developers-handbook/finding-your-way-around/musescore-coding-rules)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [x] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by anatoly-os** [comment]
@lvinken could you please rebase the PR?

**Comment by lvinken** [comment]
Rebase done

File: mscore/importmxmlpass2.h [hunk 1]
```diff
@@ -147,10 +161,11 @@ class MxmlLogger;
 
 using SlurStack = std::array<SlurDesc, MAX_NUMBER_LEVEL>;
 using TrillStack = std::array<Trill*, MAX_NUMBER_LEVEL>;
-using BracketsStack = std::array<SLine*, MAX_BRACKETS>;
-using DashesStack = std::array<SLine*, MAX_DASHES>;
```
Comment (dmitrio95) [inline mscore/importmxmlpass2.h]: As `MAX_DASHES` seems to be not used anymore, could you please remove it also from `musicxml.h`?
https://github.com/musescore/MuseScore/blob/8f0c2dd908c7cf75d28153f69f15885a15b82447/mscore/musicxml.h#L52

File: mscore/importmxmlpass2.h [hunk 2]
```diff
@@ -147,10 +161,11 @@ class MxmlLogger;
...
-using OttavasStack = std::array<SLine*, MAX_NUMBER_LEVEL>;
-using HairpinsStack = std::array<SLine*, MAX_NUMBER_LEVEL>;
+using BracketsStack = std::array<MusicXmlExtendedSpannerDesc, MAX_NUMBER_LEVEL>;
```
Comment (dmitrio95) [inline mscore/importmxmlpass2.h]: With this change `BracketsStack` becomes decreased in its length: before this change it contained `MAX_BRACKETS` (which equals to 9) items while now it contains `MAX_NUMBER_LEVEL` (which is 6). Is this change intentional?

File: mscore/importmxmlpass2.h [hunk 3]
```diff
@@ -220,11 +235,12 @@ class MusicXMLParserPass2 {
 
       // part specific data interface functions
       void addSpanner(const MusicXmlSpannerDesc& desc);
-      SLine* getSpanner(const MusicXmlSpannerDesc& desc);
+      MusicXmlExtendedSpannerDesc& getSpanner(const MusicXmlSpannerDesc& desc);
       void clearSpanner(const MusicXmlSpannerDesc& desc);
 
 private:
       void initPartState(const QString& partId);
+      SpannerSet FindIncompleteSpannersAtPartEnd();
```
Comment (dmitrio95) [inline mscore/importmxmlpass2.h]: Could you please rename this function to start from a small `f` letter? Names started with capital letter are usually reserved for names of types and enumerators within MuseScore code, and MusicXML import code seems to follow this rule as well.

File: mscore/importmxmlpass2.cpp [hunk 4]
```diff
@@ -1307,29 +1307,51 @@ void MusicXMLParserPass2::initPartState(const QString& partId)
...
-      //      glissandoColor = "";
       _multiMeasureRestCount = -1;
       _extendedLyrics.init();
       }
 
+//---------------------------------------------------------
+//   FindIncompleteSpannersInStack
+//---------------------------------------------------------
+
+static void FindIncompleteSpannersInStack(const QString& spannerType, SpannerStack& stack, SpannerSet& res)
```
Comment (dmitrio95) [inline mscore/importmxmlpass2.cpp]: Same as above

File: mscore/importmxmlpass2.h (hunk 1 above)
Comment (lvinken) [reply mscore/importmxmlpass2.h]: Will do, but am unable to do it right now (real life obligations).

File: mscore/importmxmlpass2.h (hunk 2 above)
Comment (lvinken) [reply mscore/importmxmlpass2.h]: Yes, as it makes the importer comply with the spec, which states that the number must be between 1 and 6. See: http://usermanuals.musicxml.com/MusicXML/MusicXML.htm#ST-MusicXML-number-level.htm. Larger numbers in MusicXML files should lead to validation errors on import, followed by ignoring the elements whose numbers are too high. If MuseScore allows it (don't know, would have to check), the limits for all stacks could be set higher. In that case the validation error would remain, but the import would be as expected. In retrospect, this might be better, but I'd suggest to make this explicit ib a separate issue.

File: mscore/importmxmlpass2.h (hunk 3 above)
Comment (lvinken) [reply mscore/importmxmlpass2.h]: Sure, thanks for catching my mistake.

File: mscore/importmxmlpass2.cpp (hunk 4 above)
Comment (lvinken) [reply mscore/importmxmlpass2.cpp]: OK

File: mscore/importmxmlpass2.h (hunk 2 above)
Comment (lvinken) [reply mscore/importmxmlpass2.h]: Created issue https://musescore.org/en/node/297357.

File: mscore/importmxmlpass2.h (hunk 1 above)
Comment (lvinken) [reply mscore/importmxmlpass2.h]: Done
