### PR TITLE
Fix #21175: Include fret diagram harmony symbols, bend holds, and bend text in range selections

### LINKED ISSUE #21175: Child elements are not visibly selected in range selections
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

Some score elements have multiple objects that can be individually positioned (i.e. in guitar bend in tablature, the note that is bent to, or the chord symbol attached to fret diagrams).

When a measure containing one of these elements is selected, the "parent" object is shown in the selected color but the "child" object is not. Both should appear selected.

### Steps to reproduce

1. Add a fret diagram to a score
2. Click on the measure it is attached to
3. See that the fret diagram itself is blue, but the chord symbol is not

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/20806406/74bb93da-c28b-49b7-b5e1-401e23aa891b

### MuseScore Version

MuseScore version (64-bit): 4.2.0-233521125, revision: github-musescore-musescore-eb8d33c

### Regression

I don't know

### Operating system

OS: macOS 14.1, Arch.: x86_64

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mathesoncalum**
Resolves: #21175

### CODE REVIEW

File: src/engraving/dom/select.cpp [hunk 1]
```diff
@@ -552,6 +558,25 @@ void Selection::appendTupletHierarchy(Tuplet* innermostTuplet)
...
 
+void Selection::appendGuitarBend(GuitarBend* guitarBend)
+{
+    if (!guitarBend) {
+        return;
+    }
+
+    m_el.push_back(guitarBend);
+
+    if (GuitarBendHold* hold = guitarBend->holdLine()) {
```
Comment (cbjeukendrup) [inline src/engraving/dom/select.cpp:569]: This seems to cause a tiny inconsistency: most spanners are selected if and only if they are entirely contained in the selected range, but a bend hold line is selected if and only if the start is contained in the selected range. In particular, this looks not ideal when the hold line extends further to the right than the selected range.

**Review by cbjeukendrup — APPROVED** [review]

**Comment by zacjansheski** [comment]
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/21175 FIXED
