### PR TITLE
Fix #9745: Changed instrument connection to instrument title and instrument name

### LINKED ISSUE #9745: [MU4 Issue] Instrument name doesn't change in instruments panel when replacing instrument
**Describe the bug**
When replacing an instrument, the instrument's name in the instrument panel doesn't update correctly.

https://user-images.githubusercontent.com/86290556/141954519-9d35c968-fae7-4a0a-87a6-cd41bcffa899.mp4

**Expected behavior**
1. Both the instrument panel label AND the part name should update with the name of the replacement instrument 
2. The instrument panel label should follow the name of the instrument in the main score, not the part name
3. The ability to create separate instrument names between the main score and the part should be retained

**Desktop (please complete the following information):**
 - MacOS 11.6
 - Windows 11

### PR DESCRIPTION
**Pull request by HemantAntony**
Resolves: #9745

*(short description of the changes and the motivation to make the changes)*

Prior to this commit, if you were to change the part name in the
instruments dialog, it would automatically get updated in the instrument
title (the text for the corresponding instrument button). However, with
this commit, this "connection" is changed to instrument name and the
instrument title, that is, if you now change the instrument name, the
same would be the instrument title. Also, this commit does not fix the
entire issue. Another problem mentioned in this issue had been fixed
earlier in a separate pull request #10014

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by HemantAntony** [comment]
If anyone is wondering, the fix was only the change in parttreeitem.cpp. However, this would cause the part name to be the instrument title (and indirectly the instrument name). As a result, the other fixes were necessary

**Comment by bkunda** [comment]
Tested in MacOS and Windows. FIXED.

File: src/instrumentsscene/view/parttreeitem.cpp [hunk 1]
```diff
@@ -48,7 +48,7 @@ void PartTreeItem::init(const notation::Part* masterPart)
     }
 
     setId(part->id());
-    setTitle(part->partName().isEmpty() ? part->instrument()->name() : part->partName());
+    setTitle(part->instrument()->name().isEmpty() ? part->partName() : part->instrument()->name());
```
Comment (Jojo-Schmitz) [inline src/instrumentsscene/view/parttreeitem.cpp:51]: I believe the intrument name can never be empty, only the part name can, at least that's how it was in 3.x IIRC

File: src/instrumentsscene/view/parttreeitem.cpp [hunk 2]
```diff
@@ -48,7 +48,7 @@ void PartTreeItem::init(const notation::Part* masterPart)
     }
 
     setId(part->id());
-    setTitle(part->partName().isEmpty() ? part->instrument()->name() : part->partName());
+    setTitle(part->instrument()->name());
```
Comment (Jojo-Schmitz) [inline src/instrumentsscene/view/parttreeitem.cpp:51]: Still the part name can be different from the instrument name, like when a part contains more than one instrument, can't it? Like I usually ha a "Choir" part, containing the "Women" and Men" 'instruments'.

Comment (HemantAntony) [reply src/instrumentsscene/view/parttreeitem.cpp:51]: I didn't know you can have multiple instruments in a single part. When you say part, do you mean like this with the separate score:
image

Comment (Jojo-Schmitz) [reply src/instrumentsscene/view/parttreeitem.cpp:51]: Yes, exactly.

**Comment by bkunda** [comment]
I've had a look at this build and from my end, it achieves what it aims to do, which is make the instrument panel label match the "Name on main score" 👍🏻

instrument-name-fix

There still remain other issues, but I believe these are being discussed elsewhere.

To be clear, yes the part name should be able to be set as something different from the instrument name.
@HemantAntony, it might be worth you reading through #10128 (if you haven't already), which outlines some of the complications still to resolve re: instruments and parts 🙂

File: src/instrumentsscene/view/parttreeitem.cpp (hunk 2 above)
Comment (HemantAntony) [reply src/instrumentsscene/view/parttreeitem.cpp:51]: But, this works as intended. I think there might be a confusion regarding the naming conventions. Though we say part to refer to the scores, its apparently different in the source code

**Comment by HemantAntony** [comment]
> I've had a look at this build and from my end, it achieves what it aims to do, which is make the instrument panel label match the "Name on main score" 👍🏻
> 
> instrument-name-fix
> 
> There still remain other issues, but I believe these are being discussed elsewhere.
> 
> To be clear, yes the part name should be able to be set as something different from the instrument name. @HemantAntony, it might be worth you reading through #10128 (if you haven't already), which outlines some of the complications still to resolve re: instruments and parts 🙂

I agree that the naming conventions have to finalized. Its really confusing 😕.

**Comment by HemantAntony** [comment]
I have found another possible issue. When I change the instrument name in one part (part as in score), it does not get updated across all parts. This is probably an issue unless its intended

**Comment by bkunda** [comment]
> I have found another possible issue. When I change the instrument name in one part (part as in score), it does not get updated across all parts. This is probably an issue unless its intended

@HemantAntony is this perhaps related to your other issue #10122?

**Comment by HemantAntony** [comment]
> > I have found another possible issue. When I change the instrument name in one part (part as in score), it does not get updated across all parts. This is probably an issue unless its intended
> 
> @HemantAntony is this perhaps related to your other issue #10122?

I think it probably is. But I'm not exactly sure. So, I will add "possibly related to #10122" as part of additional context

**Comment by HemantAntony** [comment]
> > I have found another possible issue. When I change the instrument name in one part (part as in score), it does not get updated across all parts. This is probably an issue unless its intended
> 
> @HemantAntony is this perhaps related to your other issue #10122?

I don't think so. It seems like a separate issue

**Comment by DmitryArefiev** [comment]
Tested #9745 on Win10, Mac12, LinuxMint 20.2 - FIXED      

Please merge into master
