### PR TITLE
Fix #21725 - Glissando from grace note.

### LINKED ISSUE #21725: MuseScore 4 Project File Won't Open--Stuck on Not Responding
### Issue type

Opening/saving issue

### Bug description

My MuseScore 4 file will not open, despite having tried on numerous devices.  It stays loading until I click a button, and then it goes not responding.  It an attempt to view the project another way, I uploaded it to MuseScore online, and it has been processing for two days now.  The compressed Zip file with the project is attached.   
[Dance of a Hundred Steps Full Score.zip](https://github.com/musescore/MuseScore/files/14425001/Dance.of.a.Hundred.Steps.Full.Score.zip)

### Steps to reproduce

1. Open "Dance of a Hundred Steps Full Score" in MuseScore 4.

### Screenshots/Screen recordings

_No response_

### MuseScore Version

MuseScore 4 

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11 and Windows 10

### Additional context

This worked on the same MuseScore 4 version I have now only a few days ago, but has since stopped working even though I haven't updated anything.

### PR DESCRIPTION
**Pull request by mgavioli**
Fix #21725 - Glissando from grace note.

### CODE REVIEW

**Comment by lasconic** [comment]
1.3 file with glissando from grace note to note are not loaded correctly. I guess guessInitialNote will need the same treatment.

**Comment by mgavioli** [comment]
Fix reading old format scores & some missing cases involving before-after graces

*) Old scores:
- grace_before-to-note glissandi in old scores are read correctly.

*) New glissandi involving graces
- In all cases, the ending note is identified correctly in the main chord, in the next main chord, in the graces-after of the main chord, in the graces-before of the next chord, whichever comes first.
- Spacing of cases involving graces-before is correct.

*) Spacing of cases involving graces-after.

It is not always optimal, as layout of graces-after pushes them as to the right as possible.

So, for instance, when a glissando is added between a grace-after of a chord and the next chord, the additional spacing added before the next chord to accommodate the gliss. is skipped by the grace-after.

I took the decision to ignore such cases as the usage of grace-after and of glissando has a rather little intersection. Those cases will need manual adjusting, for instance, in the example above, by moving the graces-after slightly to the left (the glissando will adjust its width by itself).

File: libmscore/glissando.cpp [hunk 1]
```diff
@@ -220,7 +220,11 @@ void Glissando::layout()
 
       // FINAL SYSTEM-INITIAL NOTE
       // if the last gliss. segment attaches to a system-initial note, some extra width has to be added
-      if (cr2->segment()->measure() == cr2->segment()->system()->firstMeasure() && cr2->rtick() == 0)
```
Comment (lasconic) [inline libmscore/glissando.cpp]: This seems weird.. If a CR is a gracenote, calling segment() on it will get its parent (a chord I believe) and cast it to segment, (see ChordRest::segment()) calling ->measure() will probably give weird result.

Comment (mgavioli) [inline libmscore/glissando.cpp]: Well, no, actually. Calling the `segment()` of a `Chord` does indeed return a `Segment` (and to all evidence **its** `Segment`), as it can be seen at: https://github.com/musescore/MuseScore/blob/master/libmscore/chord.cpp#L2867

Comment (lasconic) [inline libmscore/glissando.cpp]: Ok. I missed that cr2 was a Chord... since cr stands for ChordRest for me..
