### PR TITLE
Fix #23499: Remove extra treatment for tab pitch in MusicXML export

### LINKED ISSUE #23499: MusicXML export not recognizing octave transposing instruments
### Issue type

Import/export issue

### Bug description

When exporting a linked system of bass guitar notation and tablature, the octave information is not transposed consistently.
On reimport of the file the tablature is an octave lower than the notation.

As reported on the forum: https://musescore.org/en/node/365947

### Steps to reproduce

1. Create a new score with "5-str. Electric Bass"
2. Under "Instruments" add a linked staff and set to "Tab. 5-str. simple"
3. Put some notes in the upper staff
4. Export as musicXML
5. Import the musicXML
6. The tablature is now an octave lower or broken, if the original notes were too low to support a lower octave

### Screenshots/Screen recordings

_No response_

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.2-241630831, revision: github-musescore-musescore-22b46f2

### Regression

I don't know

### Operating system

Windows 10

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rettinghaus**
Resolves: #23499 

This PR fixes the export of pitches on tab staves with transposing instruments.

### CODE REVIEW

File: src/importexport/musicxml/internal/musicxml/export/exportmusicxml.cpp [hunk 1]
```diff
@@ -4148,14 +4128,10 @@ static void writePitch(XmlWriter& xml, const Note* const note, const bool useDru
     int alter = 0;
     int octave = 0;
     const Chord* chord = note->chord();
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/export/exportmusicxml.cpp:4130]: Seems this variable is now unused

Comment (rettinghaus) [reply src/importexport/musicxml/internal/musicxml/export/exportmusicxml.cpp]: Good catch, thanks!
