### PR TITLE
Fix #30198: Improved vertical positioning of spacers

### LINKED ISSUE #30198: Spacers yield unexpected results on staves with a non-1 line distance
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. Add a staff with a non-1 line distance (e.g. a tab staff), and add a spacer
2. Add a spacer below, observe that it does not account for the line distance factor
3. Add a staff type change and set the line distance to 1, add a new spacer
4. Observe the correct placement of the top end of the spacer, but an incorrect distance at the bottom

### Supporting files, videos and screenshots

Image

### What is the latest version of MuseScore Studio where this issue is present?

master

### Regression

No.

### Operating system

Windows 10

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by XiaoMigros**
Resolves: #30198
Resolves: #30494 

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
It would be nice to see a VTest for the second commit, but in general this looks good to me!

File: src/engraving/rendering/score/tlayout.cpp [hunk 1]
```diff
@@ -1776,7 +1776,7 @@ void TLayout::layoutBreath(const Breath* item, Breath::LayoutData* ldata, const
         return;
     }
 
-    int voiceOffset = item->placeBelow() * (item->staff()->lines(item->tick()) - 1) * item->spatium();
+    const double voiceOffset = item->placeBelow() * item->staff()->staffHeight(item->tick());
```
Comment (cbjeukendrup) [inline src/engraving/rendering/score/tlayout.cpp]: Actually I do have one suggestion, to improve clarity slightly

```suggestion
    const double voiceOffset = item->placeBelow() ? item->staff()->staffHeight(item->tick()) : 0.0;
```

**Comment by XiaoMigros** [comment]
Has been taken care of, thanks!

**Review by its-not-nice — APPROVED** [review]
