### PR TITLE
Resolve #11253 - Add 'To Back' and 'To Front' buttons to 'Arrange'

### LINKED ISSUE #11253: 'Arrange' back/forward feature missing two options
**Describe the bug**
At the moment, the 'Arrange' feature allows users to move an item behind or in front of another item. However, standard practice is to also have options to arrange 'To front' and 'To back'.

To front: this would move the selected item in front of anything else in the score.
To back: this would move the selected item to the back of the score

image

This feature was never fully completed (by design) due to the transition from MS3 to MS4 - as this new inspector was originally created to live in V3.

### PR DESCRIPTION
**Pull request by OfekZeevi**
Resolves: [#11253](https://github.com/musescore/MuseScore/issues/11253)

*I've added a "To Back" and "To Front" buttons to the "Arrange" section of an item's "Appearance" settings. These would immediately push the selected items to the front or back of the score (in the z-axis).*

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by Eism** [comment]
@OfekZeevi please change the destination branch from 4.0_alpha to master

**Comment by DmitryArefiev** [comment]
> These would immediately push the selected items to the front or back of the score (in the z-axis).

@OfekZeevi Hi, found that with some elements **when clicking To front  you can't override value 'to be in front' of the second element.** 
When making text in front of notes by clicking To front it makes text in front. Now select the notes and click To front, it doesn't make notes in front of text. You need to select text and click To back.

https://user-images.githubusercontent.com/90187801/170698719-fe134378-16d4-4b00-8e4a-b2f8e68cd845.mp4

File: src/inspector/models/general/appearance/appearancesettingsmodel.cpp [hunk 1]
```diff
@@ -103,16 +103,48 @@ void AppearanceSettingsModel::loadOffsets()
...
     m_arrangeOrder->setValue(m_arrangeOrder->value().toInt() - REARRANGE_ORDER_STEP);
 }
 
-void AppearanceSettingsModel::pushFrontInOrder()
+void AppearanceSettingsModel::pushForwardsInOrder()
 {
     m_arrangeOrder->setValue(m_arrangeOrder->value().toInt() + REARRANGE_ORDER_STEP);
 }
 
+void AppearanceSettingsModel::pushToBackInOrder()
```
Comment (MarcSabatella) [inline src/inspector/models/general/appearance/appearancesettingsmodel.cpp:124]: FWIW, this seems to be the exact same approach that would also be needed to fix the existing Forwards/Backwards buttons, which basically do almost nothing now because they only move by REARRANGE_ORDER_STEP rather than finding the previous/next element and pushing past that.  So currently they require you to click Forwards literally dozens of times before you see anything happen.

I mention this here because ideally I think both of these issues should be addressed to together so the code is designed well to handle both commands with a minimum of duplication.

**Comment by OfekZeevi** [comment]
> > These would immediately push the selected items to the front or back of the score (in the z-axis).
> 
> @OfekZeevi Hi, found that with some elements **when clicking To front you can't override value 'to be in front' of the second element.** When making text in front of notes by clicking To front it makes text in front. Now select the notes and click To front, it doesn't make notes in front of text. You need to select text and click To back.
> bandicam.2022-05-27.15-11-12-809.mp4

Thanks! I'm looking into that. It seems like maybe there's a bigger issue here with the z-value of text elements, but I'm not yet sure.

File: src/inspector/models/general/appearance/appearancesettingsmodel.cpp (hunk 1 above)
Comment (OfekZeevi) [reply src/inspector/models/general/appearance/appearancesettingsmodel.cpp:124]: Thanks, that's an interesting point. I'll look into that to see if there's an elegant solution for both problems.

Comment (OfekZeevi) [reply src/inspector/models/general/appearance/appearancesettingsmodel.cpp:164]: I've updated the pull request to support that feature as well :)

**Comment by OfekZeevi** [comment]
> > These would immediately push the selected items to the front or back of the score (in the z-axis).
> 
> @OfekZeevi Hi, found that with some elements **when clicking To front you can't override value 'to be in front' of the second element.** When making text in front of notes by clicking To front it makes text in front. Now select the notes and click To front, it doesn't make notes in front of text. You need to select text and click To back.
> bandicam.2022-05-27.15-11-12-809.mp4

I've figured it out! When you select a "note" element, you're not actually selecting the note but rather an element of type "Chord" that contains it. The chord isn't actually printed on the page, it's just a logical container for the notes within. For this reason, when playing with the front/back buttons, the z-value of the chord changes but that doesn't matter because the notes themselves remain at their original z-value. This explains why you can't move the notes by pressing those buttons (like you showed in the video). It's important to mention that this means the forwards/backwards buttons never affected notes, even before the changes I've made here.
I would like to point out that maybe this is intentional - from digging through the code, it seems like the order in which notes are printed matters, e.g. so that note-heads will be drawn after their note-flags and such. This makes me think that perhaps the fact that you're not able to change the z-value of notes is a feature and not a bug.
Either way, I think this issue requires a separate ticket so we can discuss it properly, and again - it isn't actually affected by my changes. So I decided to leave this issue unresolved for now.
Please let me know if you disagree :)

**Comment by DmitryArefiev** [comment]
> > > These would immediately push the selected items to the front or back of the score (in the z-axis).
> > 
> > 
> > @OfekZeevi Hi, found that with some elements **when clicking To front you can't override value 'to be in front' of the second element.** When making text in front of notes by clicking To front it makes text in front. Now select the notes and click To front, it doesn't make notes in front of text. You need to select text and click To back.
> > bandicam.2022-05-27.15-11-12-809.mp4
> 
> I've figured it out! When you select a "note" element, you're not actually selecting the note but rather an element of type "Chord" that contains it. The chord isn't actually printed on the page, it's just a logical container for the notes within. For this reason, when playing with the front/back buttons, the z-value of the chord changes but that doesn't matter because the notes themselves remain at their original z-value. This explains why you can't move the notes by pressing those buttons (like you showed in the video). It's important to mention that this means the forwards/backwards buttons never affected notes, even before the changes I've made here. I would like to point out that maybe this is intentional - from digging through the code, it seems like the order in which notes are printed matters, e.g. so that note-heads will be drawn after their note-flags and such. This makes me think that perhaps the fact that you're not able to change the z-value of notes is a feature and not a bug. Either way, I think this issue requires a separate ticket so we can discuss it properly, and again - it isn't actually affected by my changes. So I decided to leave this issue unresolved for now. Please let me know if you disagree :)

@OfekZeevi  Thanks for explanation! Agree not to fix that in this PR.

BTW #10877 also looks much better now in this PR. But the position of buttons should be re-arranged now (to the new design). It's described in the description in #10877. Maybe you want to implement this as well in the current PR? :)

**Comment by DmitryArefiev** [comment]
@Eism Can you review please :)

**Review by Eism — APPROVED** [review]
