### PR TITLE
Fix #10888: Enable Tuplet Button Always

### LINKED ISSUE #10888: [MU4 Issue] Hiding and showing the tuplet button causes it to appear disabled
**Describe the bug**
When the tuplet button in the note input toolbar is hidden then shown again, it returns in an apparently disabled (greyed-out) state. 

disabled-tuplet-icon

This doesn't affect its functionality, but it does present as a bit strange because the behaviour is not replicated across other buttons in the toolbar. 

**Expected behavior**
Triplet icon shouldn't appear greyed out when changing visibility states.
When nothing is selected in the score, clicking on the tuplet button should perform no action (as per current behaviour of "Tie", "Slur" and "Flip direction" buttons).

**Platform information**
 - MacOS 12.1 (M1)
- Windows 11 

**Note**
The weird scrolling behaviour you see will be the subject of another issue (@Tantacrul FYI)

### PR DESCRIPTION
**Pull request by HemantAntony**
Resolves: #10888

*(short description of the changes and the motivation to make the changes)*
This PR always enables the Tuplet Button regardless of the selected element

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by HemantAntony** [comment]
@bkunda This always enabled the Tuplet button even if something non applicable is selected

**Comment by bkunda** [comment]
Hi @HemantAntony,
Thanks for working on this. It is _almost_ perfect 🙂

If no applicable element is selected when the tuplet button is clicked, it should just perform **no** action, rather than triggering the menu. 

The behaviour should be the same as for the tie and slur buttons:

https://user-images.githubusercontent.com/86290556/168599246-29b53d84-8518-43d4-a7e3-3f4763c053ba.mov

Thanks!

**Comment by Eism** [comment]
@HemantAntony I don't see any updates on this PR
Do you plan to finish fixing the issue? Or you need help?

**Comment by HemantAntony** [comment]
@Eism Sorry! I forgot about this. It seems like an easy fix. I'm going to work on this

**Comment by HemantAntony** [comment]
@bkunda I know you said the behaviour should be similar to that of Slurs and Ties

But I think the Cross-staff beaming button is similar to how the tuplet buttons should behave. The cross-staff beaming button just disables the menu items:

https://user-images.githubusercontent.com/88136054/170654830-ac6f0ab8-523d-443f-adc9-1cff5cbf5071.mp4


But, if you do want the behaviour to be that of Slurs and ties, then shouldn't the cross-staff beaming button also behave like that?

**Comment by bkunda** [comment]
Actually I think you're right here, @HemantAntony. Because the tuplet button triggers a menu, rather than working as a "switch", it would make sense if its behaviour was the same as other menu-triggering buttons, like the cross-staff beams button. 

Thanks for this suggestion :-)

**Comment by HemantAntony** [comment]
I have updated the PR, but something to note is that the tuplet buttons will be disabled is the Add menu too

https://user-images.githubusercontent.com/88136054/170811177-dbb2e1db-c7b5-4448-a475-708950e986c4.mp4

**Comment by Eism** [comment]
@bkunda 
Also, they will also be enabled if there is a selection on the score, no matter which one
Previously it depended on a note or a rest was selected
Do you agree?

**Comment by bkunda** [comment]
> @bkunda
> Also, they will also be enabled if there is a selection on the score, no matter which one
> Previously it depended on a note or a rest was selected
> Do you agree?

Can it still be conditional on whether a note or rest is selected? 
If I understand you right, the user will see these options enabled if they select _anything_ (e.g. text objects). This doesn't make much sense.

**Comment by HemantAntony** [comment]
> Can it still be conditional on whether a note or rest is selected? If I understand you right, the user will see these options enabled if they select _anything_ (e.g. text objects). This doesn't make much sense.

Yeah I accidently added that. I'll add that condition for note / rest selection too

**Comment by bkunda** [comment]
> > Can it still be conditional on whether a note or rest is selected? If I understand you right, the user will see these options enabled if they select _anything_ (e.g. text objects). This doesn't make much sense.
> 
> Yeah I accidently added that. I'll add that condition for note / rest selection too

Great. Thanks @HemantAntony. Probably worth me giving it one quick last test before we merge. Could you let me know when it's ready to go please?

File: src/notation/internal/notationactioncontroller.cpp [hunk 1]
```diff
@@ -1729,6 +1729,17 @@ Ms::EngravingItem* NotationActionController::selectedElement() const
     return selection ? selection->element() : nullptr;
 }
 
+bool NotationActionController::noteOrRestSelected() const
+{
+    EngravingItem* element = selectedElement();
```
Comment (Eism) [inline src/notation/internal/notationactioncontroller.cpp:1734]: Just copy the logic from resolveTupletEnabled
Your code will not work for range selection

Comment (bkunda) [reply src/notation/internal/notationactioncontroller.cpp:1734]: Good spot, @Eism!

**Comment by HemantAntony** [comment]
@Eism I have updated the PR
