### PR TITLE
Fix #18587: Expression snap to invisible dynamics

### LINKED ISSUE #18587: Expression: snap to dynamic snaps to invisible dynamics
### Issue type

Engraving bug

### Bug description

_No response_

### Steps to reproduce

1. Add a dynamic and expression
2. Make the dynamic invisible
3. See that expression is still snapped to dynamic

### Screenshots/Screen recordings

image

### MuseScore Version

4.1.0

### Regression

No.

### Operating system

Windows 11

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mike-spa**
Resolves: #18587

### CODE REVIEW

**Review by oktophonie — APPROVED** [review]

File: src/engraving/rendering/dev/tlayout.cpp [hunk 1]
```diff
@@ -1660,7 +1660,7 @@ void TLayout::layout(Expression* item, LayoutContext& ctx)
     }
 
     Dynamic* dynamic = toDynamic(segment->findAnnotation(ElementType::DYNAMIC, item->track(), item->track()));
-    if (!dynamic || dynamic->placeAbove() != item->placeAbove()) {
+    if (!dynamic || dynamic->placeAbove() != item->placeAbove() || !dynamic->visible()) {
```
Comment (RomanPudashkin) [inline src/engraving/rendering/dev/tlayout.cpp:1663]: Could you please add a vtest?
