### PR TITLE
Fix #17921: Prevent lingering popups after minimize (MacOS only)

### LINKED ISSUE #17921: Contextual popups linger after minimizing MuseScore
### Issue type

UI bug

### Bug description

Same behavior in earlier versions of MS4
Does not occur in Windows
Applies to contextual popups: Appearance and More in Properties, guitar capo popup, harp pedal diagram popup

### Steps to reproduce

1. Select an element, like a rest or some text
2. Open the properties panel, select "Appearance" or "More"
3. Minimize MuseScore

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/027980e1-8853-40f7-ad74-229260fa803f

### MuseScore Version

OS: macOS 11.6, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231600308, revision: github-musescore-musescore-22c5a25

### Regression

No.

### Operating system

OS: macOS 11.6

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mathesoncalum**
Resolves: #17921

### CODE REVIEW

File: src/framework/uicomponents/view/internal/platform/macos/macospopupviewclosecontroller.mm [hunk 1]
```diff
@@ -61,3 +70,14 @@
 
     return false;
 }
+
+void MacOSPopupViewCloseController::initWindowMinimizedObserver()
+{
+    minimizeObserverToken = [[NSNotificationCenter defaultCenter]
+                             addObserverForName:@"NSWindowWillMiniaturizeNotification"
+                             object:nil
```
Comment (cbjeukendrup) [inline src/framework/uicomponents/view/internal/platform/macos/macospopupviewclosecontroller.mm:78]: By not providing an `object` here, you will receive minimise notifications from all windows, not just the main window. Is that intentional?

Comment (mathesoncalum) [reply src/framework/uicomponents/view/internal/platform/macos/macospopupviewclosecontroller.mm]: Fixed!

File: src/framework/uicomponents/view/internal/platform/macos/macospopupviewclosecontroller.mm [hunk 2]
```diff
@@ -61,3 +71,18 @@
...
+    WId wid = parentItem()->window()->winId();
+    NSView* nsView = (__bridge NSView*)reinterpret_cast<void*>(wid);
+    NSWindow* nsWindow = [nsView window];
+
+    minimizeObserverToken = [[NSNotificationCenter defaultCenter]
+                             addObserverForName:@"NSWindowWillMiniaturizeNotification"
+                             object:nsWindow
+                             queue:nil
+                             usingBlock:^(NSNotification*) {
+                                 closeNotification().notify();
```
Comment (cbjeukendrup) [inline src/framework/uicomponents/view/internal/platform/macos/macospopupviewclosecontroller.mm:86]: It might be slightly cleaner to make `notifyAboutClose()` a protected method of `PopupViewCloseController`, and use that method instead. For the rest this looks good to me!

**Comment by zacjansheski** [comment]
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved

For issue management, the issue still occurs on Ubuntu

**Review by cbjeukendrup — APPROVED** [review]

**Comment by cbjeukendrup** [comment]
> For issue management, the issue still occurs on Ubuntu

Should a new issue be opened about this, or shall we reopen and edit the original one?

**Comment by zacjansheski** [comment]
> > For issue management, the issue still occurs on Ubuntu
> 
> Should a new issue be opened about this, or shall we reopen and edit the original one?

I reopened the original and labeled as linux issue.  Let me know if there is any issue with that, thank you!
