### PR TITLE
Fix #22615: Colours for bends and vibrato

### LINKED ISSUE #22615: GuitarBend color not saved
### Issue type

Opening/saving issue

### Bug description

The color information of guitar bends is not saved.

### Steps to reproduce

1. add guitar bend to score
2. assign color to guitar bend
3. save score
4. reopen score

### Screenshots/Screen recordings

_No response_

### MuseScore Version

4.2

### Regression

No.

### Operating system

macOS 14.4

### Additional context

Interestingly, if you color a bend *and* make it invisible the color is stored. Looking at the MuseScore XML it seems that invisibility triggers writing the `Segment` child of `GuitarBend` which also holds the color.

### PR DESCRIPTION
**Pull request by mathesoncalum**
Resolves: #22615
Closes: #25943

I think this issue has evolved a bit since #25943 was opened. The changes here bring bends and vibrato in-line with trills where the colours are set/saved/recalled as expected (see #22852).

The changes here don't seem to interfere with `GuitarBend::curColor`. Critical/warning colours are still displayed in the Score tab, while the "true" colour is always displayed in the Publish tab.

### CODE REVIEW

File: src/engraving/dom/guitarbend.cpp [hunk 1]
```diff
@@ -302,8 +302,14 @@ bool GuitarBend::setProperty(Pid propertyId, const PropertyValue& v)
     case Pid::BEND_END_TIME_FACTOR:
         setEndTimeFactor(v.toReal());
         break;
+    case Pid::COLOR:
+        setColor(v.value<Color>());
+        [[fallthrough]];
```
Comment (mike-spa) [inline src/engraving/dom/guitarbend.cpp]: I think this should `break` though?

Comment (mathesoncalum) [reply src/engraving/dom/guitarbend.cpp]: The fallthrough was so that we set `m_lineColor` - that said I think it's much nicer if we just do that explicitly here and `break` (also updated `trill.cpp`).

**Review by mike-spa — APPROVED** [review]
