### PR TITLE
fix #18957 - add missing initial key signature for transposing instruments

### LINKED ISSUE #18957: Crash if trying to change instrument for staff without key signature
### Issue type

Crash or freeze

### Bug description

Musescore 4.1.1 and master crashes when trying to change instrument with the following conditions:
1. Musescore file created with previous versions (created for 3.6.2 and 4.0.2)
2. Soprano Saxophone is the current instrument
3. Key signature is completely removed for current staff (in previous versions of Musescore it was allowed to do so removing key signature completely)

based on report https://musescore.org/en/node/352301

### Steps to reproduce

1. Create/open file with musescore 3.6.2 or 4.0.2
2. Set instrument Soprano Saxophone
3. Remove key signature and save file
4. Open this file with Musescore 4.1.1
5. Change instrument for current staff
6. Crash

### Screenshots/Screen recordings

Demo with file created in Musescore 4.0.2

https://github.com/musescore/MuseScore/assets/919446/96b08eae-8bff-4872-be7d-3c85a23eb9db

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

OS: Windows 10 Version 2009

### Additional context

Empty score created with Musescore 4.0.2
[emptySopranoSax4.0.2.zip](https://github.com/musescore/MuseScore/files/12281684/emptySopranoSax4.0.2.zip)

### PR DESCRIPTION
**Pull request by sammik**
Resolves: #18957 

In previous versions, it was possible, to remove initial key signature. 
Check older score during import, if they have transposing instrument and don't have initial keysig, and add written C major signature.

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by sammik** [comment]
I checked it with 4.0.2, 3.6.2, and 2.3.2
I didnt check MU1

**Comment by sammik** [comment]
Perspective of fixing hundreds utests scared me enough to changed PR. 

It forces initial key sig during import only for transposing instruments now.

@oktophonie @RomanPudashkin

File: src/engraving/libmscore/staff.cpp [hunk 1]
```diff
@@ -790,6 +790,33 @@ Fraction Staff::currentKeyTick(const Fraction& tick) const
...
 }
 
+//---------------------------------------------------------
+//   Staff::addMissingInitKeyForTransposingInstrument
+//
+//    if there is no key signature at the begining
+//    of the score, add written C major
+//---------------------------------------------------------
+
+void Staff::addMissingInitKeyForTransposingInstrument()
```
Comment (RomanPudashkin) [inline src/engraving/libmscore/staff.cpp:800]: A more appropriate place for this function is CompatUtils - there it should be declared as a static function taking Staff as an argument:

CompatUtils::addMissingInitKeyForTransposingInstrument(Score* score, Staff* staff)

**Comment by zacjansheski** [comment]
Tested on Mac OS 11.6.5, Ubuntu 20.04.6, Windows 11
https://github.com/musescore/MuseScore/issues/18957 FIXED

File: src/engraving/libmscore/staff.cpp (hunk 1 above)
Comment (sammik) [reply src/engraving/libmscore/staff.cpp]: I moved it to CompatUtils, it is now there, called only from `doCompatibilityConversions` as `CompatUtils::addMissingInitKeyForTransposingInstrument(MasterScore* score)`

I also realized, that 4.1 files can be affected too, if user opened old file in 4.1 and saved it.

So all files before 4.2 are checked.

I reverted first attempt. If this one is OK, I can drop it from PR, if needed.

Comment (sammik) [reply src/engraving/libmscore/staff.cpp]: > 
@mercuree, I just tested atonal at first measure, 4.1.1 and master.
Cannot reproduce behaviour, You mentioned.

Comment (mercuree) [reply src/engraving/libmscore/staff.cpp]: @sammik 
Checked twice. Musescore 4.1.1
1. Create from template -> Treble clef -> Done
2. Save score
3. Set open/atonal key at first measure
4.  Delete first measure
5. Save score

Now if you open mscx (inside mscz archive), you will not find `<KeySig>` element inside.
However it will not crash if you try to change instrument, because it crashes with transposing instrument (do the same with soprano sax, save and reopen file and it will crash on change instrument)

Comment (mercuree) [reply src/engraving/libmscore/staff.cpp]: @sammik Thank You! New issue is here #19063

**Review by RomanPudashkin — APPROVED** [review]
