### PR TITLE
[4.7.0] Fix #32568: Sound glitches with Loop playback enabled 

### LINKED ISSUE #32568: Sound glitches with Loop playback enabled
### Issue type

General playback bug

### Description with steps to reproduce

1. Open any score
2. Select a measure and enable the Loop playback
3. Play and pay attention to the first notes in the loop when the measure is repeating

There're few first notes are missing when using MS Basic and there's a glitch when using MuseSounds

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/8c445011-7f36-4f73-b584-056173385d4e

### In which versions of MuseScore Studio is this issue present?

4.7

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

MacOS 26.3

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Resolves: https://github.com/musescore/MuseScore/issues/32568

### CODE REVIEW

**Comment by abariska** [comment]
@RomanPudashkin 
Behaviour has changed but still not fixed. With MS Basic the first note is not played at all 

https://github.com/user-attachments/assets/2bf0830a-c98f-48a3-8ca5-ad8afc70d9f2

File: src/framework/audio/engine/iclock.h [hunk 1]
```diff
@@ -62,9 +60,18 @@ class IClock
     virtual async::Notification countDownEnded() const = 0;
 
     virtual async::Channel<secs_t> timeChanged() const = 0;
+
+    enum ActionType {
+        Seek,
+        LoopEndReached,
+    };
+
+    using OnActionFunc = std::function<void (ActionType type)>;
```
Comment (igorkorsukov) [inline src/framework/audio/engine/iclock.h]: I think it would be good to add a second argument here – the current time. The action was such-and-such, it happened then...

File: src/framework/audio/engine/internal/sequenceplayer.cpp [hunk 2]
```diff
@@ -34,8 +34,15 @@ using namespace muse::async;
 SequencePlayer::SequencePlayer(IGetTracks* getTracks, IClockPtr clock, const modularity::ContextPtr& iocCtx)
     : Contextable(iocCtx), m_getTracks(getTracks), m_clock(clock)
 {
-    m_clock->seekOccurred().onNotify(this, [this]() {
-        seekAllTracks(m_clock->currentTime());
+    m_seekOccuredId = m_clock->addOnAction([this](const IClock::ActionType type) {
```
Comment (igorkorsukov) [inline src/framework/audio/engine/internal/sequenceplayer.cpp]: It's better to name it `clockActionId`, maybe it will be something else besides seek

File: src/framework/audio/engine/internal/clock.cpp [hunk 3]
```diff
@@ -57,7 +57,8 @@ void Clock::forward(const msecs_t nextMsecs)
     msecs_t newTime = m_currentTime + nextMsecs;
 
     if (m_timeLoopStart < m_timeLoopEnd && newTime >= m_timeLoopEnd) {
-        seek(m_timeLoopStart);
+        setCurrentTime(m_timeLoopStart);
+        onAction(ActionType::LoopEndReached);
```
Comment (igorkorsukov) [inline src/framework/audio/engine/internal/clock.cpp]: What's confusing me here is that we're jumping to the beginning of the loop.
It seems to me that the clock should signal that we've reached the end of the loop, but it doesn't know what happens next (maybe we want to repeat the loop 5 times and then stop).

File: src/framework/audio/engine/internal/sequenceplayer.cpp (hunk 2 above)
Comment (igorkorsukov) [inline src/framework/audio/engine/internal/sequenceplayer.cpp]: Let's add a macro `ONLY_AUDIO_PROC_THREAD` here.
The thread sanitizer is broken right now, but these macros serve as markers for developers.

File: src/framework/audio/engine/internal/clock.cpp (hunk 3 above)
Comment (RomanPudashkin) [reply src/framework/audio/engine/internal/clock.cpp]: I'll try to fix this in another PR

**Comment by abariska** [comment]
🟢 **FIXED**
Tested on macOS 26.3, Win 11, Ubuntu 20
