### PR TITLE
Fix #26208 (Dynamics): [Musicxml Export] - End-bar items lost

### LINKED ISSUE #26208: [Musicxml Export] - End-bar items lost due to various fraction offsets
### Issue type

Import/export issue

### Description with steps to reproduce

[Violin_Sonata_No._3_Sonata_Epica_-_Nikolai_Medtner.zip](https://github.com/user-attachments/files/18513953/Violin_Sonata_No._3_Sonata_Epica_-_Nikolai_Medtner.zip)

### Supporting files, videos and screenshots

In this score, at bar 40, there are 3 incorrectly exported things:
1. Trill, the fraction is 5/8, so it should be offset to next note, not ended at the same note.
2. "rit." should have a small offset from the end.
3. The last dynamic pp is missing.

### What is the latest version of MuseScore Studio where this issue is present?

4.4.4

### Regression

No.

### Operating system

Windows

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by pacebes**
Resolves: #26208 (Dynamics) 

This PR exports dynamic elements (_p, pp, fff_...) when they are linked to a TimeTickType segment 

- [X] I signed the [CLA](https://musescore.org/en/cla)
- [X] The title of the PR describes the problem it addresses
- [X] Each commit's message describes its purpose and effects, and references the issue it resolves
- [X] If changes are extensive, there is a sequence of easily reviewable commits
- [X] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [X] There are no unnecessary changes
- [X] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by pacebes** [comment]
I have attached the tests files (mscx original and .musicxml exported files): 
[Score_26208_test1.zip](https://github.com/user-attachments/files/18707481/Score_26208_test1.zip)

File: src/importexport/musicxml/internal/musicxml/export/exportmusicxml.cpp [hunk 1]
```diff
@@ -8245,6 +8245,11 @@ void ExportMusicXml::writeMeasureTracks(const Measure* const m,
                 const track_idx_t endtrack = staff2track(spannerStaff + 1);
                 spannerStop(this, starttrack, endtrack, seg->tick(), partRelStaffNo, spannersStopped);
 
+                // We check if there are also dynamic annotations
+                if (seg->findAnnotation(ElementType::DYNAMIC, strack, etrack - 1)) {
```
Comment (miiizen) [inline src/importexport/musicxml/internal/musicxml/export/exportmusicxml.cpp:8249]: Looks good - I have one suggestion. Since https://github.com/musescore/MuseScore/pull/25741, any text based item can be added to a timetick segment.  This should extend the functionality to all of these items as well.
```suggestion
                for (EngravingItem* annotation : seg->annotations()) {
                    if (annotation->track() != track || !annotation->isTextBase()) {
                        continue;
                    }
```

Comment (pacebes) [reply src/importexport/musicxml/internal/musicxml/export/exportmusicxml.cpp]: I agree.

I made the minimum change to stick only to the request.

Comment (pacebes) [reply src/importexport/musicxml/internal/musicxml/export/exportmusicxml.cpp]: @miiizen , this proposed change has made the Visual Tests fail. I don't know why. Do you have any idea about the problem ?

```
Run echo "This PR appears to change some of the visual tests."
This PR appears to change some of the visual tests.
Please carefully review the new visual test results in the uploaded artifact that can be found here: https://github.com/musescore/MuseScore/actions/runs/13282708891
Error: Process completed with exit code 1.
```

Comment (miiizen) [reply src/importexport/musicxml/internal/musicxml/export/exportmusicxml.cpp]: A rebase will fix those!
