### PR TITLE
Fix #30615: Align split measure position with normal barline applying behavior

### LINKED ISSUE #30615: Applying a barline from the palette with `Ctrl` held should split the measure at the same position as without `Ctrl`
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

When applying barline from palette, pressing `Ctrl` creates barline to a different position than not pressing it.
In #16641, the position where a barline is created when applied from the palette was changed, but this change should also have been applied to the position where the measure is split when Ctrl is pressed.

1. Select note on the score
2. Apply barline from the palette without `Ctrl`. This creates barline after the chordrest. (expected)
3. Apply barline with `Ctrl`. This creates barline before the chordrest. (not expected)

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/3bf37b3f-e55a-4862-beb4-94126bff7ada

### In which versions of MuseScore Studio is this issue present?

4.1.0 - 4.6.2

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by bakajikara**
Resolves: #30615

The position of the barline created by a normal click now varies depending on its type. Previously, the measure was always split with a single barline regardless of which barline was clicked. In this PR, the split position has been aligned with that of a normal click, and at the same time, the functionality has been extended so that the clicked barline type is properly applied.

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

File: src/engraving/editing/splitjoinmeasure.cpp [hunk 1]
```diff
@@ -98,7 +98,6 @@ void SplitJoinMeasure::splitMeasure(MasterScore* score, const Fraction& tick)
     options.createEmptyMeasures = true;
     options.moveSignaturesClef = false;
     options.moveStaffTypeChanges = false;
-    options.ignoreBarLines = true;
```
Comment (cbjeukendrup) [inline src/engraving/editing/splitjoinmeasure.cpp:101]: As these are the only places where `ignoreBarLines` was used, I think we can remove that from the `InsertMeasureOptions` struct completely

File: src/engraving/dom/measure.cpp [hunk 2]
```diff
@@ -1745,18 +1745,19 @@ EngravingItem* Measure::drop(EditData& data)
...
-            if (seg) {
-                for (EngravingItem* ee : seg->elist()) {
-                    if (ee) {
-                        ee->drop(data);
-                        break;
-                    }
+            seg = undoGetSegmentR(SegmentType::EndBarLine, ticks());
+            // if any staff lacks a barline, create one
+            for (size_t stIdx = 0; stIdx < score()->nstaves(); ++stIdx) {
+                BarLine* bl = toBarLine(seg->element(stIdx * VOICES));
```
Comment (cbjeukendrup) [inline src/engraving/dom/measure.cpp]: This generates a warning on MSVC, because there is already something called `bl` in an outer scope

File: src/engraving/dom/measure.cpp [hunk 3]
```diff
@@ -1745,18 +1745,19 @@ EngravingItem* Measure::drop(EditData& data)
...
+                    bl = Factory::createBarLine(seg);
+                    bl->setParent(seg);
+                    bl->setTrack(stIdx * VOICES);
+                    undoAddElement(bl);
                 }
-            } else {
-                delete e;
             }
+            // drop to barline
+            seg->element(staffIdx * VOICES)->drop(data);
```
Comment (cbjeukendrup) [inline src/engraving/dom/measure.cpp]: should the result of this `drop` call be `return`ed?

File: src/engraving/editing/splitjoinmeasure.cpp (hunk 1 above)
Comment (bakajikara) [reply src/engraving/editing/splitjoinmeasure.cpp:101]: My apologies, this change was an experimental line that accidentally slipped into the PR.

We need to revert this deletion, because removing this line introduces a crash on Undo if the barline at the end of the measure being split has been modified.

**Review by cbjeukendrup — APPROVED** [review]
Thanks!

**Comment by zacjansheski** [comment]
Tested on MacOS 15, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/30615 FIXED
