### PR TITLE
Fix #12788: Slur with lyrics

### LINKED ISSUE #12788: [MU4 Issue] Weird shaped slur
**Describe the bug**
Slurs on notes with lyrics are weird shaped

**To Reproduce**
1. Enter notes
2. Add lyrics
3. Add slur
4. See weird shaped slur

**Screenshots**
スクリーンショット (40)

**Platform information**
 - OS: Windows 11

**Additional context**
Checked with Public Alpha

### PR DESCRIPTION
**Pull request by mike-spa**
Resolves #12788 

The origin of the problem is in the way that lyrics shapes are handled, but that is something that will be addressed later on, as we're planning to overhaul lyrics at some point in 4.x versions. For now, slur should simply ignore lyrics when looking for collisions.

### CODE REVIEW

**Review by oktophonie — APPROVED** [review]

File: src/engraving/libmscore/slur.cpp [hunk 1]
```diff
@@ -462,6 +462,12 @@ void SlurSegment::avoidCollisions(PointF& pp1, PointF& p2, PointF& p3, PointF& p
                 secondStaffShape.translate(PointF(0.0, dist));
                 segShape.add(secondStaffShape);
             }
+
+            // HACK: ignore lyrics shape by removing them from the vector
+            segShape.erase(std::remove_if(segShape.begin(), segShape.end(), [](ShapeElement& shapeEl){
```
Comment (RomanPudashkin) [inline src/engraving/libmscore/slur.cpp:467]: Please use mu::remove_if

**Review by RomanPudashkin — APPROVED** [review]

File: src/engraving/libmscore/slur.cpp (hunk 1 above)
Comment (mike-spa) [reply src/engraving/libmscore/slur.cpp]: thanks, done!
