### PR TITLE
Fix #10307: Rearranged Palettes

### LINKED ISSUE #10307: [MU4 Task] Tidy up default palette visibility settings
**Task description**
This task firstly aims to specify which palette objects should appear by default in their respective main palette, and which ones should be hidden in the "More" popups. 

Further, this task will define some size and grid settings for the layout of specific palettes that currently have formatting and/or readability issues. 

Finally, we suggest which palettes should be exposed by default, and which ones should be exposed only by clicking `Add Palletes`.

Most of the palette object specifications below come from [this article](https://alice.mu.se/x/URUACw) by @oktophonie (internal team only).

### Clefs
Only the following should be shown in the main palette:
- Treble clef
- Treble clef 8va alta
- Treble clef 15ma alta
- Treble clef 8va bassa
- Alto clef
- Tenor clef
- Bass clef
- Bass clef 8va alta
- Bass clef 8va bassa
- Percussion
- Tablature
- Tablature 4 lines 

All other clefs should be hidden in the "More" popup by default:
Screenshot 2022-01-19 at 5 42 25 pm

**Note**: "TAB" clefs have been duplicated in the "More" popup. There should be no duplication of palette elements between this popup and the main palette.

**Default cell size specifications (Clefs)**
Width=36
Height=50
Element offset=1sp
Scale=0.8
Show grid=Yes

### Key signatures
Current palette objects are fine; only an adjustment to the cell size is needed.

**Default cell size specifications (Key signatures)**
Width=56
Height=50
Element offset=1sp
Scale=0.8
Show grid=Yes

### Time signatures
Only the following should be shown in the main palette:
- 2/4
- 3/4
- 4/4
- 5/4
- 6/4
- 3/8
- 4/8*
- 5/8*
- 6/8
- 7/8
- 9/8
- 12/8
- Common time
- Cut time
- 2/2*
- 3/2

*Add default time signatures for 4/8, 5/8 and 2/2 (shown in green):

Time signatures

There is some broken functionality for creating custom time signatures, which I shall raise in a separate issue. 

### Accidentals
Only the following should be shown in the main palette:
- Flat
- Natural
- Sharp
- Double sharp
- Double flat

All other accidentals should be hidden in the "More" popup by default: 
Screenshot 2022-01-19 at 8 26 15 pm

### Articulations
Only the following should be shown in the main palette:
- Accent above
- Staccato above
- Staccatissimo above
- Tenuto above
- Louré (tenuto-staccato) above
- Marcato above
- Accent-staccato above
- Laissez vibrer (l.v.) above
- Marcato-staccato above
- Marcato-tenuto above
- Staccatissimo stroke above
- Staccatissimo wedge above
- Stress above
- Tenuto-accent above
- Unstress above
- Open
- Muted (closed)
- Harmonic
- Up bow
- Down bow

All other articulation marks should be hidden in the "More" popup by default:
Screenshot 2022-01-19 at 5 46 31 pm

### Ornaments
Only the following should be shown in the main palette:
- Inverted turn
- Turn
- Trill
- Short trill
- Mordent

All other ornaments should be hidden in the "More" popup by default:

Screenshot 2022-01-19 at 8 13 58 pm

**Default cell size specifications (Ornaments)**
Width=42
Height=25
Element offset=0sp
Scale=1.2
Show grid=Yes

### Breaths & pauses
Only the following should be shown in the main palette:
- Fermata above
- Short fermata above
- Long fermata above
- Breath mark (comma)
- Breath mark (tick-like)
- Breath mark (Salzedo)
- Breath mark (upbow-like)
- Curved caesura
- Caesura
- Short caesura
- Thick caesura

All other breaths & pauses should be hidden in the "More" popup by default:

Screenshot 2022-01-19 at 8 08 09 pm

**Note**: `Caesura` (`U+E8F8`) would ideally be renamed "Chant Caesura" if possible. 

### Lines
Only the following should be shown in the main palette:
- Slur
- Crescendo hairpin
- Diminuendo hairpin
- Crescendo line
- Diminuendo line
- Dynamic + hairpin
- Prima volta
- Seconda volta, open
- 8va alta
- 8va bassa
- 15ma alta
- Pedal (with ped and line)
- Pedal (with ped and asterisk)
- Pedal (straight hooks)
- Trill line
- Downprall line
- Prallprall line
- Staff text line
- System text line
- Line
- Ambitus
- Let ring
- Guitar vibrato wide
- Vibrato sawtooth
- Palm mute

All other lines should be hidden in the "More" popup by default:
Screenshot 2022-01-19 at 6 14 15 pm

### Barlines
Only the following should be shown in the main palette: 
- Single barline
- Double barline
- Left (start) repeat sign
- Right (end) repeat sign
- Dashed barline
- Final barline
- Right and left repeat sign
- Dotted barline
- Reverse final barline
- Heavy barline
- Heavy double barline

All other barlines should be hidden in the "More" popup by default: 
Screenshot 2022-01-19 at 6 19 01 pm

**Default cell size specifications (Barlines)**
Width=48
Height=38
Element offset=0sp
Scale=0.8
Show grid=Yes

### Text
Only the following should be shown in the main palette: 
- Staff text
- Expression text
- Instrument change
- Rehearsal mark
- System text
- Pizzicato
- Acro
- Tremolo
- Mute
- Open

The object "Straight" should be relocated to the "Tempo" palette.

All other text objects should be hidden in the "More" popup by default:
Screenshot 2022-01-19 at 6 30 54 pm

### Tempo
All tempo palette objects can be shown by default.

The "More" popup can remain empty. We suggest that "Allegro moderato" is deleted as it doesn't fit elegantly within a palette tile and is easily reproducible with an existing tempo palette item.

Please also ensure that there is no duplication of palette objects between the main palette and the "More" popup (currently "Swing" appears twice). 

Screenshot 2022-01-19 at 7 24 42 pm

**Default cell size specifications (Tempo)**
Width=90
Height=30
Element offset=0sp
Scale=0.65
Show grid=Yes

### Dynamics
Only the following should be shown in the main palette: 
- ppp
- pp
- p
- mp
- mf
- f
- ff
- fff
- fp
- pf
- sf
- sfz
- sff
- sffz
- sfp
- sfpp
- rfz
- rf
- fz

All other dynamics should be hidden in the "More" popup by default:

Screenshot 2022-01-19 at 7 16 00 pm

**Default cell size specifications (Dynamics)**
Width=50
Height=28
Element offset=0sp
Scale=0.9
Show grid=Yes

### Repeats and jumps
Only the following should be shown in the main palette:
- Repeat last bar
- Segno
- Coda
- Fine
- To Coda
- Da Capo
- Da Capo al Fine
- Da Capo al Coda
- D.S. al Coda
- D.S. al Fine
- D.S.
- Left (start) repeat sign
- Right (end) repeat sign
- Right and left repeat sign

All other repeats and jumps should be hidden in the "More" popup by default:

Screenshot 2022-01-19 at 7 41 49 pm

Note: There is a bug with this palette that is preventing `Palette Properties...` from working. I shall raise this as a separate issue.

### Fingering
Only the following should be shown in the main palette:
- Fingering 1
- Fingering 2
- Fingering 3
- Fingering 4
- Fingering 5
- RH guitar fingering p
- RH guitar fingering i
- RH guitar fingering m
- RH guitar fingering a
- RH guitar fingering c
- LH guitar fingering 1
- LH guitar fingering 2
- LH guitar fingering 3
- LH guitar fingering 4
- LH guitar fingering 5
- LH guitar fingering T
- String number 0
- String number 1
- String number 2
- String number 3
- String number 4
- String number 5
- String number 6
- Thumb position

All other repeats and jumps should be hidden in the "More" popup by default:

Screenshot 2022-01-19 at 7 46 36 pm

### Layout
"Staff type change" appears to have the incorrect icon. It should be an "S" in a box (see `musescoreicon`, `U+EF7E`).
There is also a missing icon for "Insert one measure". I shall raise this as a separate issue. 

### DEFAULT PALETTES
The following palettes should be exposed (in this order) by default:
- Clefs
- Key signatures
- Time signatures
- Tempo
- Accidentals
- Dynamics
- Articulations
- Text
- Lines
- Repeats & jumps
- Barlines
- Layout

Thank you!

### PR DESCRIPTION
**Pull request by HemantAntony**
Resolves: #10307 

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [ ] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by HemantAntony** [comment]
@bkunda, I could not add the icon for Staff Type Change. Also, in the issue, you had asked me to change description of a cell to "Chant Caesura". I changed it to "Chant caesura" to make it consistent with other descriptions. If you want to me to change it to the former, please tell me.

**Comment by bkunda** [comment]
> @bkunda, I could not add the icon for Staff Type Change. Also, in the issue, you had asked me to change description of a cell to "Chant Caesura". I changed it to "Chant caesura" to make it consistent with other descriptions. If you want to me to change it to the former, please tell me.

Sentence case is correct so you're spot on about this! 🙌🏻

I'll follow up separately with our dev team re: that extra icon. There are a few other questions I have about that palette so we will resolve it at some point soon I'm sure.

Many thanks again! 🙏🏻

**Comment by HemantAntony** [comment]
@bkunda, can you please check Bagpipe Embellishments palette. Its a bit too long in my opinion

**Comment by bkunda** [comment]
From a UX perspective, this is working well. Great work @HemantAntony.
I have a list of small tweaks I'd like to make (some are corrections, others can now be specified since the bug about the `&` has been fixed up, others still are micro adjustments I have observed after a second viewing of this whole issue). I'll list these below....

Meanwhile @RomanPudashkin, could you or one of your colleagues please just have a look at this code and give @HemantAntony any feedback before we finalise everything? 

-----------------------------
Final adjustments (For now... 😉 ):

**Tempo**
- "Swing" seems to have disappeared. It should appear alongside "Straight".

**Fingering**  
- “Fingering 0” and “LH guitar fingering 0” should be in main palette (not in “More”)

Arpeggios & glissandi:
- “Straight glissando” and “Wavy glissando” are duplicated. Remove them from “more” popup. 
- Now that the “Palette properties” are working, there is an issue with the alignment of specifically these two elements:

Arpeggios   glissandi

They appear too high up in the upper right corner of their respective palette tile. It would be great if they could be centred somehow. If this could be achieved, I’d like to see the palette properties for this as follows: 
Width=42
Height=44
Elements offset=0sp
Scale=1
Show grid=yes

**Grace notes**
- “Scale” doesn’t seem to be working (a separate bug might be needed for this)
- Change properties to: Width=45, Height=40, Element offset=0sp, Scale=1, Show grid=yes

**Breaths and pauses**
- Change width to 40 (Width=40, Height=40, Element offset=0, Scale=1, Show grid=yes)

**Repeats and jumps**
- Change properties to: Width=75, Height=28, Element offset=0, Scale=0.85, Show grid=yes

**Dynamics**
- Change scale to 1

Hope this makes sense. @HemantAntony let me know if you have any questions, and thank you so much for your work on this! 🙏🏻

**Comment by bkunda** [comment]
@HemantAntony this is almost ready from my end! 
Can we please just have the default properties for "arpeggios & glissandi" set to:

Width=42
Height=44
Elements offset=0sp
Scale=1
Show grid=yes

Many thanks,
Bradley

**Comment by HemantAntony** [comment]
I updated the PR. Also @RomanPudashkin, was I supposed to have created this PR with different commits instead of a single one

**Comment by bkunda** [comment]
@Eism @RomanPudashkin @igorkorsukov this looks good to me from a UX perspective. If one of you could please have a look at it, that would be great. 

I've only tested on MacOS (the scaling issue in Windows means I can't accurately see the scaling of palette objects, I can't test it yet in this environment). 

Many thanks @HemantAntony!

File: src/engraving/libmscore/marker.cpp [hunk 1]
```diff
@@ -56,7 +56,7 @@ const MarkerTypeItem markerTypeTable[] = {
 
 int markerTypeTableSize()
 {
-    return sizeof(markerTypeTable) / sizeof(MarkerTypeItem) - 1; //-1 for the user defined
+    return markerTypeTable.size() - 1; //-1 for the user defined
```
Comment (RomanPudashkin) [inline src/engraving/libmscore/marker.cpp:59]: Better to add an explicit cast to int here:

return static_cast<int>(markerTypeTable.size()) - 1;

Comment (RomanPudashkin) [reply src/engraving/libmscore/marker.cpp:59]: Actually, this method is no longer needed. You can remove it and use markerTypeTable.size() instead

File: src/engraving/libmscore/trill.cpp [hunk 2]
```diff
@@ -56,7 +56,7 @@ const TrillTableItem trillTable[] = {
 
 int trillTableSize()
```
Comment (RomanPudashkin) [inline src/engraving/libmscore/trill.cpp:57]: Now you can remove this method :)

File: src/palette/internal/palettecreator.cpp [hunk 3]
```diff
@@ -121,28 +123,30 @@ PaletteTreePtr PaletteCreator::newMasterPaletteTree()
...
-    tree->append(newDynamicsPalette());
     tree->append(newFingeringPalette());
-    tree->append(newRepeatsPalette());
     tree->append(newFretboardDiagramPalette());
     tree->append(newAccordionPalette());
     tree->append(newBagpipeEmbellishmentPalette());
-    tree->append(newLayoutPalette());
     tree->append(newBeamPalette());
 
+    LOGI() << "Master: " << tree->palettes[17]->cellsCount();
```
Comment (RomanPudashkin) [inline src/palette/internal/palettecreator.cpp:148]: Please, remove this log

File: src/palette/internal/palettecreator.cpp [hunk 4]
```diff
@@ -152,29 +156,31 @@ PaletteTreePtr PaletteCreator::newDefaultPaletteTree()
...
-    defaultPalette->append(newFingeringPalette());
-    defaultPalette->append(newRepeatsPalette());
+    defaultPalette->append(newFingeringPalette(true));
     defaultPalette->append(newFretboardDiagramPalette());
     defaultPalette->append(newAccordionPalette());
     defaultPalette->append(newBagpipeEmbellishmentPalette());
-    defaultPalette->append(newLayoutPalette());
     defaultPalette->append(newBeamPalette());
 
+    LOGI() << "Default: " << defaultPalette->palettes[17]->cellsCount();
```
Comment (RomanPudashkin) [inline src/palette/internal/palettecreator.cpp:182]: Please, remove this log

File: src/palette/internal/palettecreator.cpp [hunk 5]
```diff
@@ -779,17 +851,28 @@ PalettePtr PaletteCreator::newBreathPalette()
...
+    // Breaths
+
+    for (auto i : defaultPalette ? defaultFermatas : masterFermatas) {
         auto f = Factory::makeFermata(gpaletteScore->dummy());
         f->setSymId(i);
         sp->appendElement(f, f->userName());
     }
 
-    for (BreathType bt : Breath::breathList) {
+    for (unsigned int i = 0; i < Breath::breathList.size() - 1; i++) { //Last breath is not a default breath. Hence, - 1
```
Comment (RomanPudashkin) [inline src/palette/internal/palettecreator.cpp:862]: You should use size_t instead of unsigned int here. Also, it is better to skip elements explicitly (not by size() - 1)

File: src/palette/internal/palettecreator.cpp [hunk 6]
```diff
@@ -779,17 +851,28 @@ PalettePtr PaletteCreator::newBreathPalette()
...
-        a->setSymId(bt.id);
-        a->setPause(bt.pause);
-        sp->appendElement(a, SymNames::translatedUserNameForSymId(bt.id));
+        a->setSymId(breath.id);
+        a->setPause(breath.pause);
+        sp->appendElement(a, SymNames::translatedUserNameForSymId(breath.id));
+    }
+
+    if (!defaultPalette) {
+        auto breath = Breath::breathList.at(Breath::breathList.size() - 1);
```
Comment (RomanPudashkin) [inline src/palette/internal/palettecreator.cpp:871]: Better to find the desired element by type rather than by the assumed index

File: src/palette/internal/palettecreator.cpp [hunk 7]
```diff
@@ -1431,13 +1534,42 @@ PalettePtr PaletteCreator::newTimePalette()
...
+        { 6,  8, TimeSigType::NORMAL, "6/8" },
+        { 7,  8, TimeSigType::NORMAL, "7/8" },
+        { 9,  8, TimeSigType::NORMAL, "9/8" },
+        { 12, 8, TimeSigType::NORMAL, "12/8" },
+        { 4,  4, TimeSigType::FOUR_FOUR,  QT_TRANSLATE_NOOP("symUserNames", "Common time") },
+        { 2,  2, TimeSigType::ALLA_BREVE, QT_TRANSLATE_NOOP("symUserNames", "Cut time") },
+        { 2,  2, TimeSigType::NORMAL, "2/2" },
+        { 3,  2, TimeSigType::NORMAL, "3/2" }
+    };
+    //        { 4,  2, TimeSigType::NORMAL, "4/2" },
```
Comment (RomanPudashkin) [inline src/palette/internal/palettecreator.cpp:1560]: Please, remove these comments

**Comment by RomanPudashkin** [comment]
Overall looks very good! I left several small comments for you. This PR can be merged after resolving them. Thank you!

File: src/palette/internal/palettecreator.cpp (hunk 5 above)
Comment (HemantAntony) [reply src/palette/internal/palettecreator.cpp:862]: I used range-based for loop to resolve this and the following review. Hope that's okay

**Review by RomanPudashkin — APPROVED** [review]

File: src/engraving/types/symnames.cpp [hunk 8]
```diff
@@ -3805,7 +3805,7 @@ constexpr const std::array<const char*, size_t(SymId::lastSym) + 1> SymNames::s_
     "Punctum auctum, ascending",
     "Punctum auctum, descending",
     "Augmentum (mora)",
-    QT_TRANSLATE_NOOP("symUserNames", "Caesura"),
+    QT_TRANSLATE_NOOP("symUserNames", "Chant caesura"),
```
Comment (Jojo-Schmitz) [inline src/engraving/types/symnames.cpp:3808]: This is not the name used in SMuFL!
Yes, ithe glyph is `chantCaesure`, but the clear text name is "Caesura" (unfortunatly, complain to SMuFL).
Whenever ...tools/fonttools/smufl2sym.[{sh,bat} is run again, it'd revert this change.

Comment (Jojo-Schmitz) [reply src/engraving/types/symnames.cpp:3808]: Esp. the commented out code in the mtests checking for duplicates, as in 3.x this was only in the master palette
