### PR TITLE
Fix #31531: Deleting a chord/rest at the end of a measure followed by…

### LINKED ISSUE #31531: Deleting a chord/rest at the end of a measure followed by a horizontal frame additionally deletes that frame and the measure after it
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. Create a score, e.g. from the Treble Clef template, 4 measures long, 4/4 time sig
2. Enter some quarter notes, into the first 3 measures
3. Insert a horizontal frame between 1st and 2nd measure (this is the most important part, the trigger)
4. Select that last note in measure 1 (the 2nd important part, it got to be a single select)
5. Press Ctrl+Del (Windows/Linux, on a Mac that'd be Cmd+Del)

Expected result: the note gets deleted, the measure's actual duration gets shortened accordingly, but nothing else

Actual result: the rest gets deleted, the measure's actual duration gets shortened accordingly (so far, so good), but the horizontal frame and the next measure get deleted too

Doing the same with a vertical frame or a text frame results in that frame to stay, but the measure after it to get delete too.

### Supporting files, videos and screenshots

n/a

### In which versions of MuseScore Studio is this issue present?

Apparently all Mu3 and Mu4 versions up to latest master branch

### Regression

No.

### Operating system

Windows 11, but that most probably doesn't matter

### Additional context

Came up in https://musescore.org/en/node/388058

Workarounds:
* Right-click into that measure, measure properties, change actual duration
* Make range selection around the chord/rest (e.g. via Shift+Down) and then issue the Ctrl+Del
  So apparently a single select is treated different from a range select

Leads me to believe that here in line 4901
https://github.com/musescore/MuseScore/blob/84094a325b383d09b799f83670e63299b0bd346f/src/engraving/editing/edit.cpp#L4885-L4906
the calculation of the `endSegment` goes wrong.
Thorough debug session pending...

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by worldwideweary**
… a horizontal frame additionally deletes that frame and the measure after it

Resolves: #31531 

See https://github.com/musescore/MuseScore/issues/31531 for further details of problem.
During testing of the issue, I realized that the MeasureBase* type was being used instead of Measure*, after verifying differences in the ticks when the score had a following frame. As a matter of fact, it's not absolutely just the frame's fault. If the score had've had a few more measures before the first measure, the problem wouldn't arise because of the prev() check (verified this). Anyways. This should get the ball rolling for the fix of this little issue.

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/muse_framework/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [] The code compiles and runs on my machine, preferably after each commit individually
- [] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
> If the score had've had a few more measures before the first measure, the problem wouldn't arise because of the prev() check

Hmm, same issue if there are more measures before that frame. How much is "_a few more_"?

Anyway: Indeed fixes the issue and is at the line of code I last looked at as being suspicious.

**Comment by worldwideweary** [comment]
I might've been imagining things when doing some tests, but I'm pretty sure the measurebase* to measure* type should resolve it. 

I think I was testing the 
 ```cpp
ie = endSegment->prev(SegmentType::ChordRest) ? endSegment->measure() : endSegment->measure()->prevMeasure();
```
line and it "seemed" like there was no problem when it passed the first condition... but again I might've overlooked the results in passing.

File: src/engraving/editing/edit.cpp [hunk 1]
```diff
@@ -4974,7 +4974,7 @@ void Score::doTimeDelete(Segment* startSegment, Segment* endSegment)
     MeasureBase* mbEnd;
 
     if (endSegment) {
-        mbEnd = endSegment->prev(SegmentType::ChordRest) ? endSegment->measure() : endSegment->measure()->prev();
+        mbEnd = endSegment->prev(SegmentType::ChordRest) ? endSegment->measure() : endSegment->measure()->prevMeasure();
```
Comment (Jojo-Schmitz) [inline src/engraving/editing/edit.cpp:4977]: What I don't quite understand is why here (and in many other places) `SegmentType::ChordRest` is used. but in some other places (further up and further down) `CR_TYPE`, which is the same thing, I just wonder about the inconsistency in use

Comment (worldwideweary) [reply src/engraving/editing/edit.cpp:4977]: Probably just inconsistent use with multiple contributors. Just a constexpr shorthand. Happens a lot in MS code (3.x base at least) similar with comparing a certain attribute to an enumerator directly versus using a helper function that does the exact same thing in a more specific manner like with "isQuality()" functions. Makes it more difficult to find situations because then you gotta search for two different things for the same instance of a use-case... 

Could probably do some "hit and run" consolidations to the codebase to make things more singular in use...

Comment (Jojo-Schmitz) [reply src/engraving/editing/edit.cpp:4977]: It is certainly unrelated to the problem at hand

**Review by cbjeukendrup — APPROVED** [review]

**Comment by zacjansheski** [comment]
Tested on MacOS 15, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/31531 FIXED
