### PR TITLE
Fix #18681: Overwrite read-only files

### LINKED ISSUE #18681: On Linux, MuseScore 4.1 can overwrite read-only files
### Issue type

Other type of issue

### Bug description

I'm writing a books of 500 saxophone etudes which I keep in my home directory: /home/myusername/Sync/500_Daily_Saxophone_Etudes/mscz/

I name each etude by its number, for example 050.mscz, or 442.mscz.  After I finanalize each etude, I set it to read-only so that I don't inadvertently change it after it's finalized. I then use the sha256sum cli function to get the etude's hash, and record it in a records file. I verified that each etude has 444 permissions (read-only for user, group, and other) using the ls -l command.

To my surprise, the MuseScore 4.1 appimage binary can still save over the MuseScore file, even though it is set to read-only. Steps to reproduce are below.

### Steps to reproduce

1. Download Musescore 4.1 appimage on a Pop!_OS 22.04 LTS system.
2. Make the MuseScore appimage executable.
3. Create a new MuseScore score in your home directory.
4. Save the new Musescore score in your home directory.
5. Make the new score read-only using either CLI command chmod 444 newscore.mscz, or using the GUI interface.
6. Open the read-only score using the MuseScore 4.1 appimage.
7. Make a change to the score, and attempt to save the changed version.

Expected behavior:
MuseScore should say something like "the file cannot be saved because it is read-only".

Actual behavior:
MuseScore saves over the file, and after the save, the file is no longer read-only.

### Screenshots/Screen recordings

I don't have the ability to screen capture right now, but I have verified the behavior above on my Pop!_OS 22.04 LTS system several times in the last few days.

### MuseScore Version

4.1

### Regression

I don't know

### Operating system

Pop!_OS 22.04 LTS

### Additional context

I trust the MuseScore developers, but this seems like a security issue: is it possible that MuseScore could write over read-only Linux system files?

### PR DESCRIPTION
**Pull request by johny4**
In Linux, MuseScore4 doesn't respect file permissions and overwrites read-only files. Added a verification before save-file operation to check if a file is read-only using QFileInfo, preventing it from overwriting the file, imitating Windows' behaviour. 

Tested on Ubuntu and Windows.

Resolves: #18681 

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

File: src/project/internal/projectactionscontroller.cpp [hunk 1]
```diff
@@ -854,6 +854,21 @@ bool ProjectActionsController::saveProjectLocally(const io::path_t& filePath, Sa
...
+    }
+
+    else if (saveMode == SaveMode::SaveAs || saveMode == SaveMode::SaveCopy) {
+        QFileInfo saveAsPath(filePath.toQString());
+        if (saveAsPath.exists() && !saveAsPath.isWritable()) {
+            warnScoreCouldnotBeSaved(trc("project/save", "This file is read-only."));
+            return false;
+        }
+    }
+
```
Comment (Jojo-Schmitz) [inline src/project/internal/projectactionscontroller.cpp:871]: Why not
```cpp
    // Prevents Save operation from overwriting read-only files
    QFileInfo savePath(project->path().toQString());
    if (saveMode == SaveMode::SaveAs || saveMode == SaveMode::SaveCopy) {
        saveAsPath(() =filePath.toQString();
    }
    if (savePath.exists() && !savePath.isWritable() && saveMode == SaveMode::Save) {
        warnScoreCouldnotBeSaved(trc("project/save", "This file is read-only."));
        return false;
    }

```

Comment (Jojo-Schmitz) [reply src/project/internal/projectactionscontroller.cpp:871]: Maybe even exclude this for Windows and Mac

Comment (johny4) [reply src/project/internal/projectactionscontroller.cpp:871]: Thank for your input! I agree with your suggestion. I'm assuming before the else if you meant } and not ], right?

Comment (Jojo-Schmitz) [reply src/project/internal/projectactionscontroller.cpp:871]: Also why not doing the entire check inside `save()`?

Comment (Jojo-Schmitz) [reply src/project/internal/projectactionscontroller.cpp:871]: Yes, of course  }

Comment (Jojo-Schmitz) [reply src/project/internal/projectactionscontroller.cpp:871]: Or even better do it in `doSave`, there os a check for writability already:

```cpp
    // Step 1: check writable
    {
#if defined(Q_OS_WIN) || defined(Q_OS_MAC) 
        if (fileSystem()->exists(savePath) && !fileSystem()->isWritable(savePath)) {
#else
        QFileInfo savePath(path.toQString());
        if (savePath.exists() && !savePath.isWritable()) {
#endif
            LOGE() << "failed save, not writable path: " << savePath;
            return make_ret(notation::Err::UnknownError);
        }
```

Comment (Jojo-Schmitz) [reply src/project/internal/projectactionscontroller.cpp:871]: Actually it might be as easy as
```cpp
    // Step 1: check writable
    {
        if (fileSystem()->exists(savePath) && !fileSystem()->isWritable(savePath)
              && fileSystem()->exists(targetContainerPath) && !fileSystem()->isWritable(targetContainerPath)) {
            LOGE() << "failed save, not writable path: " << savePath;
            return make_ret(notation::Err::UnknownError);
        }
```

Comment (johny4) [reply src/project/internal/projectactionscontroller.cpp:871]: > Actually there (in `doSave()`) it might be as easy as
> 
> ```c++
>     // Step 1: check writable
>     {
>         if ((fileSystem()->exists(savePath) && !fileSystem()->isWritable(savePath)) ||
>             (fileSystem()->exists(targetContainerPath) && !fileSystem()->isWritable(targetContainerPath))) {
>             LOGE() << "failed save, not writable path: " << targetContainerPath;
>             return make_ret(notation::Err::UnknownError);
>         }
> ```
> 
> a 1-line addition...

Thanks. This solution is indeed cleaner. Tested on Linux and it works, will test on Windows now. However, I feel like the user should have more information when this error occurs, instead of "unknown error". What do you think of creating an Err for this verification with a text like "This file is read-only" or "This file or folder is not writable".

Comment (Jojo-Schmitz) [reply src/project/internal/projectactionscontroller.cpp:871]: Even shorter:
´´´cpp
    // Step 1: check writable
    {
        if (!fileSystem()->isWritable(savePath) || !fileSystem()->isWritable(targetContainerPath))) {
            LOGE() << "failed save, not writable path: " << targetContainerPath;
            return make_ret(notation::Err::UnknownError);
        }
```

Comment (Jojo-Schmitz) [reply src/project/internal/projectactionscontroller.cpp]: For a proper error message:
```cpp
#include "global/io/ioretcodes.h"
    // Step 1: check writable
    {
        if (fileSystem()->exists(savePath) && !fileSystem()->isWritable(savePath)) {
            LOGE() << "failed save, not writable path: " << savePath;
            return make_ret(mu::io::Err::FSWriteError);
        }

        if (ioMode == engraving::MscIoMode::Dir) {
            // Dir needs to be created, otherwise we can't move to it
            if (!QDir(targetContainerPath).mkpath(".")) {
                LOGE() << "Couldn't create container directory";
                return make_ret(mu::io::Err::FSMakingError);
            }
        }
    }
```

File: src/project/internal/notationproject.cpp [hunk 2]
```diff
@@ -566,9 +566,10 @@ mu::Ret NotationProject::doSave(const io::path_t& path, engraving::MscIoMode ioM
 
     // Step 1: check writable
     {
-        if (fileSystem()->exists(savePath) && !fileSystem()->isWritable(savePath)) {
+        if ((fileSystem()->exists(savePath) && !fileSystem()->isWritable(savePath))
+            || (fileSystem()->exists(targetContainerPath) && !fileSystem()->isWritable(targetContainerPath))) {
             LOGE() << "failed save, not writable path: " << savePath;
-            return make_ret(notation::Err::UnknownError);
+            return make_ret(notation::Err::NotWritable);
```
Comment (Jojo-Schmitz) [inline src/project/internal/notationproject.cpp:572]: That might work, but these really ain't notation errors, but rather I/O errors

File: src/project/internal/projectactionscontroller.cpp [hunk 3]
```diff
@@ -1764,4 +1749,4 @@ QUrl ProjectActionsController::scoreManagerUrl() const
 void ProjectActionsController::openProjectProperties()
 {
     interactive()->open(PROJECT_PROPERTIES_URI);
-}
+}q
```
Comment (Jojo-Schmitz) [inline src/project/internal/projectactionscontroller.cpp:1752]: Huh?

File: src/project/internal/notationproject.cpp (hunk 2 above)
Comment (johny4) [reply src/project/internal/notationproject.cpp:572]: I tried to be coherent and use the same namespace (notation) as the file where this verification is made, notationprokect.cpp, uses. Do you think the error should be handled elsewhere?

Comment (Jojo-Schmitz) [reply src/project/internal/notationproject.cpp:572]: IMHO yes, as these ain't notation errors, but file I/O errors

File: src/project/internal/projectactionscontroller.cpp (hunk 1 above)
Comment (Jojo-Schmitz) [reply src/project/internal/projectactionscontroller.cpp]: These may not be the final error codes, but are the closest existing ones I could find. Maybe ioretcodes.h needs to get extended with some better onesbut these do seem to be io errors rather than notation errors

File: src/project/internal/notationproject.cpp (hunk 2 above)
Comment (Jojo-Schmitz) [reply src/project/internal/notationproject.cpp:572]: But see https://github.com/musescore/MuseScore/pull/22054#discussion_r1538007993)

Comment (johny4) [reply src/project/internal/notationproject.cpp]: Thanks again for your valuable contributions. I pushed a new commit changing the error codes. I agree with you, those are not notation, but rather I/O errors. I'll leave it to the team to check if the messages presented to the user should be updated (make them more descriptive), but they are better than "Unknown error" in my opinion.

File: src/project/internal/notationproject.cpp [hunk 4]
```diff
@@ -566,16 +567,17 @@ mu::Ret NotationProject::doSave(const io::path_t& path, engraving::MscIoMode ioM
 
     // Step 1: check writable
     {
-        if (fileSystem()->exists(savePath) && !fileSystem()->isWritable(savePath)) {
+        if ((fileSystem()->exists(savePath) && !fileSystem()->isWritable(savePath))
+            || (fileSystem()->exists(targetContainerPath) && !fileSystem()->isWritable(targetContainerPath))) {
```
Comment (Jojo-Schmitz) [inline src/project/internal/notationproject.cpp:571]: As mentioned earlied, this can get shortened to
```cpp
        if ( !fileSystem()->isWritable(savePath) || !fileSystem()->isWritable(targetContainerPath)) {
```
IMHO there's no need to test for existence, as isWriteable() does that too

File: src/project/internal/notationproject.cpp [hunk 5]
```diff
@@ -566,16 +567,17 @@ mu::Ret NotationProject::doSave(const io::path_t& path, engraving::MscIoMode ioM
...
             LOGE() << "failed save, not writable path: " << savePath;
```
Comment (Jojo-Schmitz) [inline src/project/internal/notationproject.cpp:572]: here better use `targetContainerPath`, the "_saving" is just confusing

File: src/project/internal/notationproject.cpp [hunk 6]
```diff
@@ -566,16 +567,17 @@ mu::Ret NotationProject::doSave(const io::path_t& path, engraving::MscIoMode ioM
...
-            return make_ret(notation::Err::UnknownError);
+            return make_ret(io::Err::FSWriteError);
         }
 
         if (ioMode == engraving::MscIoMode::Dir) {
             // Dir needs to be created, otherwise we can't move to it
             if (!QDir(targetContainerPath).mkpath(".")) {
                 LOGE() << "Couldn't create container directory";
```
Comment (Jojo-Schmitz) [inline src/project/internal/notationproject.cpp:579]: here better add the filename `LOGE() << "Couldn't create container directory: " << targetContainerPath;`

File: src/project/internal/notationproject.cpp (hunk 4 above)
Comment (johny4) [reply src/project/internal/notationproject.cpp:571]: The existence test was there before and I'm not totally comfortable removing it without fully understanding its consequences. Besides, I'm not sure if testing if a file is writable when it exists is equivalent to testing only if it is writable (existing or not).

File: src/project/internal/notationproject.cpp (hunk 6 above)
Comment (johny4) [reply src/project/internal/notationproject.cpp]: Thanks again! Added this a new commit.

File: src/project/internal/notationproject.cpp (hunk 5 above)
Comment (johny4) [reply src/project/internal/notationproject.cpp]: Also added in new commit.

**Review by igorkorsukov — APPROVED** [review]
