### PR TITLE
Fix #21742: MusicXML import shows red notes when midi-program is set to guitar

### LINKED ISSUE #21742: MusicXML import shows red notes when <midi-program> is set to guitar
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

When importing a MusicXML file with following properties, some notes appear in red unexpectedly:
```
<midi-instrument id="P1-I1">
    <midi-channel>1</midi-channel>
    <midi-program>26</midi-program>
</midi-instrument>
```

midi program 26 is a steel string guitar.
See example file attached below, with one single A3 note: it appears red, while it fits correctly in guitar's amplitude.
After deleting <midi-instrument> node (and child nodes), note appears correctly in black

### Steps to reproduce

1. Open attached MusicXML file
[test.zip](https://github.com/musescore/MuseScore/files/14440267/test.zip)

### Screenshots/Screen recordings

Screenshot_20240228_223330

### MuseScore Version

OS: openSUSE Tumbleweed, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-, revision: github-musescore-musescore-

### Regression

I don't know

### Operating system

Linux OpenSUSE tumbleweed (rolling release)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by pacebes**
Resolves: #21742

This pull request changes the way an instrument is selected when importing an XML
- Before: the selected instrument was the first in the list among all the instruments with the same score
- Now: the selected instrument was the first in the list among all the instruments with the same score and the lowest Levenshtein distance (name of the imported instrument and the track name or long name of the selected instrument). Levenshtein distance is used only if the name of the importing instrument has some meaning (not empty and not meaningless names)

- [X] I signed the [CLA](https://musescore.org/en/cla)
- [X] The title of the PR describes the problem it addresses
- [X] Each commit's message describes its purpose and effects, and references the issue it resolves
- [X] If changes are extensive, there is a sequence of easily reviewable commits
- [X] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [X] There are no unnecessary changes
- [X] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

File: src/engraving/dom/instrtemplate.cpp [hunk 1]
```diff
@@ -792,7 +830,44 @@ const InstrumentTemplate* combinedTemplateSearch(const String& mxmlId, const Str
...
+                    }
                 }
+
+                instTemplateScoredVector.insert(instTemplateScoredVector.end(), instTemplateScored);
+                minLevenshteinDistance = std::min(minLevenshteinDistance, instTemplateScored.score);
+            }
+        }
+    }
+
+    // We keep the first instrument with the bigger score and the lower Levenshtein fistance
```
Comment (miiizen) [inline src/engraving/dom/instrtemplate.cpp:865]:
```suggestion
    // We keep the first instrument with the bigger score and the lower Levenshtein distance
```

**Review by miiizen — COMMENTED** [review]
This is great, thank you very much! I've just left a few minor comments.

File: src/engraving/dom/instrtemplate.cpp [hunk 2]
```diff
@@ -717,9 +718,46 @@ const InstrumentTemplate* searchTemplate(const String& name)
     return 0;
 }
 
+static int levenshteinDistance(const std::string& s1, const std::string& s2)
```
[the remark this answers is not in the document]
Comment (pacebes) [reply src/engraving/dom/instrtemplate.cpp:721]: Ok

File: src/engraving/dom/instrtemplate.cpp [hunk 3]
```diff
@@ -717,9 +718,46 @@ const InstrumentTemplate* searchTemplate(const String& name)
...
+}
+
 const InstrumentTemplate* combinedTemplateSearch(const String& mxmlId, const String& name, const int transposition, int bank,
                                                  int program)
 {
+    struct InstrumentTemplateScored
+    {
+        const InstrumentTemplate* instrumentTemplate=nullptr;
+        int score = std::numeric_limits<int>::max();
+        InstrumentTemplateScored() { instrumentTemplate = nullptr; score = std::numeric_limits<int>::max(); }
```
[the remark this answers is not in the document]
Comment (pacebes) [reply src/engraving/dom/instrtemplate.cpp:755]: Ok

File: src/engraving/dom/instrtemplate.cpp [hunk 4]
```diff
@@ -792,7 +830,44 @@ const InstrumentTemplate* combinedTemplateSearch(const String& mxmlId, const Str
...
+                    minLevenshteinDistance = std::numeric_limits<int>::max();
+                }
+            }
+            // We keep a list of every instrument with the current bestMatchStrength
+            if ((matchStrength == bestMatchStrength) && (matchStrength > 0)) {
+                InstrumentTemplateScored instTemplateScored;
+                instTemplateScored.instrumentTemplate = it;
+
+                // if the name is meaningless keep the longest distance
+                if ((name.isEmpty()) || (name == "MusicXML Part") || (name == "Staff")) {
```
[the remark this answers is not in the document]
Comment (pacebes) [reply src/engraving/dom/instrtemplate.cpp:845]: Ok

File: src/engraving/dom/instrtemplate.cpp [hunk 5]
```diff
@@ -792,7 +804,46 @@ const InstrumentTemplate* combinedTemplateSearch(const String& mxmlId, const Str
...
+                instTemplateScored.instrumentTemplate = it;
+
+                // if the name is meaningless keep the longest distance
+                if ((name.isEmpty()) || (name == u"MusicXML Part") || (name == u"Staff")) {
+                    instTemplateScored.score = std::numeric_limits<int>::max();
+                } else {
+                    // We keep the lowest distance with trackName ...
+                    instTemplateScored.score = muse::strings::levenshteinDistance(StaffName(
+                                                                                      name).toString().toStdString(),
+                                                                                  it->trackName.toStdString());
```
Comment (cbjeukendrup) [inline src/engraving/dom/instrtemplate.cpp:825]: Looks like uncrustify made a mess here; perhaps there should only be one line break namely after `levenshteinDistance(`.

File: src/engraving/dom/instrtemplate.cpp [hunk 6]
```diff
@@ -720,6 +722,16 @@ const InstrumentTemplate* searchTemplate(const String& name)
...
 {
+    struct InstrumentTemplateScored
+    {
+        const InstrumentTemplate* instrumentTemplate=nullptr;
+        int score = std::numeric_limits<int>::max();
+        InstrumentTemplateScored() {};
+    };
+
+    std::vector <InstrumentTemplateScored> instTemplateScoredVector;
+    int minLevenshteinDistance = std::numeric_limits<int>::max();
```
Comment (cbjeukendrup) [inline src/engraving/dom/instrtemplate.cpp:733]: Instead of building a scored list, and then at the end iterating through it to find the one with the lowest score, would it be possible to store only `int minLevenshteinDistance` and `InstrumentTemplate* templateWithMinLevenshteinDistance`?

Comment (pacebes) [reply src/engraving/dom/instrtemplate.cpp:733]: OK

File: src/engraving/dom/instrtemplate.cpp (hunk 5 above)
Comment (pacebes) [reply src/engraving/dom/instrtemplate.cpp]: OK

**Review by miiizen — APPROVED** [review]
