### PR TITLE
Fix duplicate measure numbers when set to all staves and some staves are hidden

### LINKED ISSUE #31046: Measure numbers above/below all staves are not hidden with hidden staves
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. Create a score with multiple instruments / staves (or add more instruments to an existing score).
2. Add some notes on one staff but leave other staves empty.  Add notes in measures on multiple systems.
3. In Style / Measure numbers, set the Position to Show "On all staves".  Either Above or Below doesn't matter.  To make the bug more obvious, set Frequency to "Every 1 measures".
4. In Style / Score, check "Automatically hide all empty staves".

Expected results:
Measure numbers should be displayed above or below only the staves that are visible.

Actual results:
Overlapping measure numbers are displayed for all staves, including hidden staves.

### Supporting files, videos and screenshots

Image

### In which versions of MuseScore Studio is this issue present?

4.6 through latest nightly

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 12

### Additional context

4.5.2 and older behaved as expected; this is new in 4.6.  Workaround is to right-click one of the measure numbers that shouldn't be there, Select / Similar on this staff, and press V to toggle visibility.

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mike-spa**
Resolves: #31046

### CODE REVIEW

File: src/engraving/dom/measure.cpp [hunk 1]
```diff
@@ -2121,14 +2121,19 @@ void Measure::scanElements(std::function<void(EngravingItem*)> func)
...
+        MeasureNumber* measureNumber = ms->measureNumber();
+        if (measureNumber && measureNumber->systemFlag() && showMeasureNumberOnStaff(staffIdx)) {
+            func(measureNumber);
         }
 
         if (!(visible(staffIdx) && score()->staff(staffIdx)->show()) && !isCutawayClef(staffIdx)) {
             continue;
         }
 
+        if (measureNumber && !measureNumber->systemFlag()) {
```
Comment (cbjeukendrup) [inline src/engraving/dom/measure.cpp:2133]: Is there no need to check `showMeasureNumberOnStaff(staffIdx)` here?

Comment (mike-spa) [reply src/engraving/dom/measure.cpp:2133]: No because in this case the measure number is just another staff element, for which all the necessary conditions are already checked at the previous if

**Review by ghost — APPROVED** [review]

**Review by miiizen — APPROVED** [review]
