### PR TITLE
Fix #11440: Make advanced settings' descriptions more user friendly

### LINKED ISSUE #11440: [MU4 Issue] Preferences > Advanced - Change text descriptions to user friendly
**Describe the bug**
In Preferences > Advanced the preference descriptions are developer reference vs. user friendly descriptions.

**To Reproduce**
1. Go to Preferences > Advanced
2. See preference descriptions

**Expected behavior**
Preferences descriptions should be clear and user friendly in order to be immediately understood and less intimidating.

Example: 

_engraving/colors/voice1_

becomes....

_Voice 1 color_

**Screenshots**
Screen Shot 2022-04-27 at 8 54 00 PM

**Platform information**
OS: macOS 12.2
Arch.: x86_64
MuseScore version (64-bit): 4.0.0-2230826620
revision: github-musescore-musescore-b10e37c

### PR DESCRIPTION
**Pull request by iwoithe**
Resolves: #11440

**Screenshot**

image

---

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [x] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

File: src/engraving/internal/engravingconfiguration.cpp [hunk 1]
```diff
@@ -68,6 +69,7 @@ void EngravingConfiguration::init()
         Settings::Key key("engraving", "engraving/colors/voice" + std::to_string(voice + 1));
 
         settings()->setDefaultValue(key, Val(defaultVoiceColors[voice].toQColor()));
+        settings()->setDescription(key, qtrc("engraving", "Voice").toStdString() + " " + std::to_string(voice + 1) + " " + qtrc("engraving", "color").toStdString());
```
Comment (cbjeukendrup) [inline src/engraving/internal/engravingconfiguration.cpp:72]: The preferred way to do this is:
```suggestion
        settings()->setDescription(key, qtrc("engraving", "Voice %1 color").arg(voice + 1).toStdString());
```

**Review by igorkorsukov — APPROVED** [review]

**Comment by Jojo-Schmitz** [comment]
utest failure can get ignored, but a rebase would fix it

**Comment by DmitryArefiev** [comment]
Tested #11440 on Win10, Mac12, LinuxUbuntu 22.04 - **FIXED**
