### PR TITLE
Fix #9175 Cannot open multiple score parts at once

### LINKED ISSUE #9175: Parts Dialog: cannot open multiple part scores at once
**Describe the bug**
The user can multiselect scores... but can only open one at a time, which can be quite painful.

**See video**
https://www.dropbox.com/s/18pvp22xxmjvu0g/Parts_Can%27t_Open_Multiple.mov?dl=0

### PR DESCRIPTION
**Pull request by HemantAntony**
Resolves: https://github.com/musescore/MuseScore/issues/9175

After selecting multiple parts in "parts" dialog, you can now open all of them. Previously, you could open only one. Therefore, you would have to open all of them one-by-one, causing an inconvenience. So, I created a loop which iterates through the selected rows and opens them. I have also sorted the selected rows in the order in which they appear, so that when you open them, it opens in the correct order.

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

File: src/notation/view/partlistmodel.cpp [hunk 1]
```diff
@@ -279,14 +279,18 @@ void PartListModel::openSelectedParts()
...
     ExcerptNotationList newExcerpts;
     for (int index : rows) {
         newExcerpts.push_back(m_excerpts[index]);
     }
 
     masterNotation()->addExcerpts(newExcerpts);
 
-    context()->setCurrentNotation(m_excerpts[rows.last()]->notation());
+    for (int index : rows) {
+        context()->setCurrentNotation(m_excerpts[i]->notation());
```
Comment (RomanPudashkin) [inline src/notation/view/partlistmodel.cpp:292]: Better to use INotation::setOpened here:

 for (int index : rows) {
 m_excerpts[i]->notation()->setOpened(true);
 }
 
setCurrentNotation should be used only once (after that cycle with the last notation in the selected list) because it is quite expensive:
 
 context()->setCurrentNotation(m_excerpts[rows.last()]->notation());

Comment (HemantAntony) [reply src/notation/view/partlistmodel.cpp:292]: Ok will do that. Thanks!

**Review by RomanPudashkin — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
Tested #9175 on latest master build (Win10, Mac12, LinuxMint 20.2) - FIXED
