### PR TITLE
[4.7.0] Fix #32975: Playback of a Replaced Instrument Despite Selecting a Measure in a Different Staff

### LINKED ISSUE #32975: Playback of a Replaced Instrument Despite Selecting a Measure in a Different Staff - MU4.7 nightly
### Issue type

General playback bug

### Description with steps to reproduce

Steps
1. Open the file.
2. Replace the instrument in a staff using the right mouse button in the context menu “Staff/Instrument Properties...” (e.g., in staff 1, replace the clarinet with a trombone, oboe, or accordion).
3. Without saving, select (mark) a measure in a different staff and start playback.

Result
Playback occurs for both the selected staff and the staff of the replaced instrument.

* Windows 10
* MS Basic

My test file is attached.

### Supporting files, videos and screenshots

[Happy Christmas (War is Over)MU4-7.zip](https://github.com/user-attachments/files/26626217/Happy.Christmas.War.is.Over.MU4-7.zip)

### In which versions of MuseScore Studio is this issue present?

Version 4.7.0.260407044, Revision: a601bfc

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

Was broken between **23** and **30 Oct** in master builds

### Operating system

WIndows 10

### Additional context

Additional Information
This error does not occur with all newly selected instruments (e.g., trumpet or alto saxophone).
Replacing instruments in the Layout tab of the respective staff does not seem to be affected by this.

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Resolves: https://github.com/musescore/MuseScore/issues/32975

## Summary by CodeRabbit

* **Bug Fixes**
  * Playback now correctly detects changes to score parts and reloads tracks when parts are modified or restructured.

* **Refactor**
  * Simplified track-management behavior: automatic reconciliation of tracked instrument entries has been removed; part updates now only refresh solo/mute states rather than adding/removing tracks.

### CODE REVIEW

File: src/playback/internal/playbackcontroller.cpp [hunk 1]
```diff
@@ -1481,15 +1447,7 @@ void PlaybackController::setupSequenceTracks()
...
-            auto search = m_instrumentTrackIdMap.find(trackId);
-            if (search == m_instrumentTrackIdMap.cend()) {
-                removeNonExistingTracks();
-                addTrack(trackId, onAddFinished);
-            }
-        }
-
+    partList.onItemChanged(&m_seqAsyncReceiver, [this](const Part*) {
         updateSoloMuteStates();
     });
```
Comment (mathesoncalum) [inline src/playback/internal/playbackcontroller.cpp:1452]: This is perhaps something we can try in the master version of this PR, but I'm wondering whether this subscription can be removed since we also subscribe to `onItemChanged` in `setNotation`. There we call `onPartChanged`, which in turn calls `updateSoloMuteStates`.

The key difference in each case is `partList` - here we get it from `masterNotationParts`, whereas in `setNotation` we get it from `m_notation->parts()`.

**Review by mathesoncalum — APPROVED** [review]

File: src/playback/internal/playbackcontroller.cpp (hunk 1 above)
Comment (RomanPudashkin) [reply src/playback/internal/playbackcontroller.cpp:1452]: Yeah, I'll try in the master version

**Comment by zacjansheski** [comment]
Tested on MacOS Tahoe 26.2, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/32975 FIXED
