### PR TITLE
fixed #27362: Clicking and playing a bar no longer resets it to the start like it used to

### LINKED ISSUE #27362: Clicking and playing a bar no longer resets it to the start like it used to
### Issue type

General playback bug

### Description with steps to reproduce

1. Click a bar to highlight it
2. Start play back
3. Stop play back
4. Click the same bar again without deselecting it
5. No longer goes back to the beginning of this bar

### Supporting files, videos and screenshots

Its kinda annoying how now if I want to replay a bar. I have to either click off it and back on for it to reset, click the first note in the bar.

Reclicking on the bar during playback will behave as intended but it just makes it harder to listen now

### What is the latest version of MuseScore Studio where this issue is present?

4.5.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by Eism**
Resolves: #27362

it was broken after this changes https://github.com/musescore/MuseScore/commit/affa5dde#diff-7d6c43a2a0b297c944ac7ab8b3fb364815a25bc9cd7f8c132e1f3725cd6bf0b3R655

### CODE REVIEW

**Comment by zacjansheski** [comment]
Tested on MacOS 15, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/27362 FIXED

File: src/notation/view/notationviewinputcontroller.cpp [hunk 1]
```diff
@@ -1394,6 +1394,10 @@ EngravingItem* NotationViewInputController::resolveStartPlayableElement() const
 {
     EngravingItem* hitElement = hitElementContext().element;
 
+    if (playbackController()->isPlaying()) {
+        return hitElement;
```
Comment (cbjeukendrup) [inline src/notation/view/notationviewinputcontroller.cpp:1398]: What is the reason for these lines?

Comment (cbjeukendrup) [reply src/notation/view/notationviewinputcontroller.cpp]: Ah, I see 👍
