### PR TITLE
Fix #18187: Ensure tuplets are included in range selections

### LINKED ISSUE #18187: Tuplet bracket & number aren't included within range selection
### Issue type

UI bug

### Bug description

Came up first in https://musescore.org/en/node/325846

### Steps to reproduce

1. New score
2. Add a tupllet
3. Select the measure, or do a Ctrl+A

See that the tuplet bracket and number are not selected

To reset it it make invisible ettc, it needs to explicitly get selected

### Screenshots/Screen recordings

_No response_

### MuseScore Version

all

### Regression

No.

### Operating system

all

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mathesoncalum**
Resolves: #18187

### CODE REVIEW

File: src/engraving/dom/select.cpp [hunk 1]
```diff
@@ -620,6 +620,10 @@ void Selection::updateSelectedElements()
                         appendFiltered(el);
                     }
                 }
+                Tuplet* tuplet = cr->tuplet();
```
Comment (cbjeukendrup) [inline src/engraving/dom/select.cpp:623]: Does this also work for nested tuplets?

Comment (oktophonie) [reply src/engraving/dom/select.cpp:623]: Alas, no

Comment (mathesoncalum) [reply src/engraving/dom/select.cpp:623]: I _think_, this should be easy enough to accomodate (famous last words). Looking into it.

Comment (mathesoncalum) [reply src/engraving/dom/select.cpp:634]: @cbjeukendrup or @RomanPudashkin - latest version should accomodate nested tuplets

File: src/engraving/dom/select.cpp [hunk 2]
```diff
@@ -537,6 +537,17 @@ void Selection::appendChord(Chord* chord)
     }
 }
 
+void Selection::appendTupletHierarchy(Tuplet* innermostTuplet)
+{
+    appendFiltered(innermostTuplet);
```
Comment (cbjeukendrup) [inline src/engraving/dom/select.cpp:542]: Shouldn't we check `if (!mu::contains(m_el, innermostTuplet)`? Or is it only the first chord of a tuplet where `tuplet()` is set?

Comment (Jojo-Schmitz) [reply src/engraving/dom/select.cpp:542]: That'd result in only the outer and the __first__ inner tuplet to get selected

Comment (mathesoncalum) [reply src/engraving/dom/select.cpp:546]: @cbjeukendrup is right, I've pushed this tweak.

I tried to repro the above behaviour @Jojo-Schmitz but couldn't (nor can I see why this might happen). If you find it's present in the latest iteration please let me know!

Comment (Jojo-Schmitz) [reply src/engraving/dom/select.cpp:546]: I had that issue with my backport to 3.x

Comment (Jojo-Schmitz) [reply src/engraving/dom/select.cpp:546]: Oh, I see now, between your code and @cbjeukendrup's there's  `!`

**Review by cbjeukendrup — APPROVED** [review]
