### PR TITLE
Fix #19425 ensure measure properties dialog properly handles various selections

### LINKED ISSUE #19425: Crash after applying shortcut for Measure properties
### Issue type

Crash or freeze

### Bug description

Assign a shortcut to Measure properties, e.g. Ctrl + Alt + M
Select a note. Apply shortcut. Crash.

### Steps to reproduce

1. In Preferences > Shortcuts assign a shortcut to Measure properties, e.g. Ctrl + Alt + M
2. Select a note.
3. Apply shortcut.

### Screenshots/Screen recordings

_No response_

### MuseScore Version

MuseScore version (64-bit): 4.1.1-232071203, revision: -e4d1ddf

### Regression

No.

### Operating system

Windows 11

### Additional context

[MuseScore_230916_181459.log](https://github.com/musescore/MuseScore/files/12641535/MuseScore_230916_181459.log)

### PR DESCRIPTION
**Pull request by wizofaus**
Resolves: #19425

Measure properties dialog crashing when selection not valid (measure selected)

- [X] I signed the [CLA](https://musescore.org/en/cla)
- [X] The title of the PR describes the problem it addresses
- [X] Each commit's message describes its purpose and effects, and references the issue it resolves
- [X] If changes are extensive, there is a sequence of easily reviewable commits
- [X] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [X] There are no unnecessary changes
- [X] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

File: src/notation/view/widgets/measureproperties.cpp [hunk 1]
```diff
@@ -77,8 +77,13 @@ MeasurePropertiesDialog::MeasurePropertiesDialog(QWidget* parent)
     setFocus();
 
     qApp->installEventFilter(this);
+
+    if (!m_measure) {
+        deleteLater();
```
Comment (wizofaus) [inline src/notation/view/widgets/measureproperties.cpp:82]: tried various methods to ensure dialog wouldn't show at all if no valid measure selected, this was the only one that didn't crash (though it does cause the dialog frame to flicker briefly - note that the plan is to replace this dialog with the properties panel anyway)

Comment (Eism) [reply src/notation/view/widgets/measureproperties.cpp:82]: I propose to solve this problem in another way:
The NotationActionController determines whether a measure is selected and if it is not selected, then do not show the dialog, but show a warning that a measure is not selected. 

Also, there is assert in dev mode if m_measure isn't selected
`    IF_ASSERT_FAILED(measure) {
        return;
    }
    `

**Comment by wizofaus** [comment]
I looked at trying to do it like that and couldn't see a straightforward way of doing so, but agree it would be nicer

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by wizofaus** [comment]
Have updated to move code to find selected measure to NotationInteraction, and checked from NotationActionController.
At this stage however, I opted against showing a dialog (easy enough with `showErrorMessage(mu::notation::make_ret(Err::MeasureIsNotSelected).text());`) because it would make it inconsistent with other commands (there is a function canAddBoxes that returns this ret code, but it's never even used currently), and would require further code changes to support being able to toggle the error on/off which seemed excessively.

File: checkstyle.bat
Comment (cbjeukendrup) [inline checkstyle.bat:1]: Perhaps this file was not intended to be committed in this PR?

Comment (wizofaus) [reply checkstyle.bat:1]: Oops, yep, that's just for me! Though it is potentially useful for other Windows devs...

File: src/notation/view/widgets/measureproperties.cpp (hunk 1 above)
Comment (wizofaus) [reply src/notation/view/widgets/measureproperties.cpp]: I believe I've addressed this concerned now? The crash definitely still happens (I just lost work because of it).

**Comment by zacjansheski** [comment]
Tested and approved

**Review by RomanPudashkin — APPROVED** [review]
