### PR TITLE
Fix #10694: Hidden staves become visible on reopen

### LINKED ISSUE #10694: [MU4 Issue] Hidden staves become un-hidden on app re-open
**Describe the bug**
See this demo video: 

https://user-images.githubusercontent.com/86290556/156156500-d2a9213b-44f6-427c-b7c1-484b55bb86cb.mp4

**Expected behavior**
Staves hidden in the Instruments Panel should remain hidden until the user makes them visible again (even after closing and re-opening the project file or app)

**Platform information**
 - MacOS 12.1 (M1)
 - Windows 11

**Additional context**

### PR DESCRIPTION
**Pull request by HemantAntony**
Resolves: #10694

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

File: src/engraving/libmscore/staff.cpp [hunk 1]
```diff
@@ -816,6 +816,9 @@ void Staff::write(XmlWriter& xml) const
     if (_mergeMatchingRests) {
         xml.tag("mergeMatchingRests", _mergeMatchingRests);
     }
+    if (!visible()) {
+        xml.tag("isStaffVisible", visible());
```
Comment (RomanPudashkin) [inline src/engraving/libmscore/staff.cpp:820]: Can we use this tag instead?
xml.tag("invisible", isLinesInvisible(Fraction(0, 1)));

Comment (RomanPudashkin) [inline src/engraving/libmscore/staff.cpp:820]: Can we use this tag instead?
xml.tag("invisible", isLinesInvisible(Fraction(0, 1)));

Comment (shoogle) [reply src/engraving/libmscore/staff.cpp:820]: @RomanPudashkin, there is a difference between making a staff invisible (via the Instruments panel) and making just the staff *lines* invisible (via right-click Staff/Part Properties). Unfortunately the "invisible" tag is already being used a few lines above to make the lines invisible so it's not available to make the staff itself invisible, if that's what you were suggesting?

**Review by RomanPudashkin — APPROVED** [review]
