### PR TITLE
Fix #12316: Limit Gap values to 2 decimals in Inspector

### LINKED ISSUE #12316: Number values for frames allow too many digits after the decimal point
**Describe the bug**
Text frames can sometimes have values that are so long, they exceed the width of the text box. We need to limit these to two points after the decimal.

image

Here's another example of the default for a Symphony Orchestra template
image

**To Reproduce**
1. Open the Symphony Orchestra template
2. Click on the title frame
3. Observe the 'Gap above' and 'Gap below' value

### PR DESCRIPTION
**Pull request by HemantAntony**
Resolves: #12316 

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by Tantacrul** [comment]
Just tested. Seems to be working as expected! @RomanPudashkin / @Eism, if you are happy, can you merge?

Thanks @HemantAntony !

File: src/framework/global/val.cpp [hunk 1]
```diff
@@ -100,10 +100,8 @@ bool Val::toBool() const
         std::string str = std::get<std::string>(m_val);
         return str == VAL_TRUE;
     }
-    default:
-        return isNull() ? false : true;
     }
-    return false;
+    return isNull() ? false : true;
```
Comment (RomanPudashkin) [inline src/framework/global/val.cpp:104]: This will cause a warning because after this change not all possible types will be covered in the switch statement

Comment (HemantAntony) [reply src/framework/global/val.cpp:104]: I actually didn't get that warning. I was trying to fix an "unreachable" warning. I'll just delete the `return false;`

**Comment by Tantacrul** [comment]
Still seems to be working. @RomanPudashkin - if you are happy?

File: src/framework/global/val.cpp (hunk 1 above)
Comment (cbjeukendrup) [reply src/framework/global/val.cpp:104]: It differs per compiler. MSVC tends to complain about unreachable code if you put the return statement in the `default` case and also put something at the bottom of the function, while Clang is afraid that the function doesn't always return a value if you don't. The general solution would be like this:
```c++
    default:
        break;
    }
    return isNull() ? false : true;
```

**Comment by RomanPudashkin** [comment]
> Still seems to be working. @RomanPudashkin - if you are happy?

Waiting for my [comment](https://github.com/musescore/MuseScore/pull/12318#discussion_r916938854) to be resolved :)

**Comment by HemantAntony** [comment]
Sorry! Switching between branches is a bit of a pain. Hence I was putting it off :)

**Review by RomanPudashkin — APPROVED** [review]
