### PR TITLE
Fix #31689: Use one text section for both text and text lines

### LINKED ISSUE #31689: Multiple 'Text' sections in properties
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. Open a new score with two staves
2. Add staff text to the first staff
3. Add a hairpin to the second staff
4. Select all with Ctrl+A / Cmd+A
6. Open properties and see two separate text sections

There are perhaps other ways to reproduce this that I haven't found.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/fd3b120f-cae9-4902-827d-4b988a82c009

### In which versions of MuseScore Studio is this issue present?

Nightly

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

macOS 15

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mathesoncalum**
Resolves: #31689

The core changes here:
- When a `TextBase` property (`ALIGN`, `POSITION`, etc) is **_read_** on a `TextLineBase`, read the corresponding "begin" property (`BEGIN_TEXT_ALIGN`, `BEGIN_TEXT_POSITION`, etc). And when a `TextBase` property is _**set**_ on  a `TextLineBase`, set the corresponding properties for begin, continue, and end text.
- Currently `TextSettingsModel::requestElements()` will retrieve both "normal" text elements and text elements that are children of a `TextLineBase`/`TextLineSegment`. In the latter case now need to retrieve the `TextLineBases` instead (so that we can use the corresponding begin, continue, and end properties).

### CODE REVIEW

File: src/inspector/qml/MuseScore/Inspector/text/textsettingsmodel.cpp
Comment (miiizen) [inline src/inspector/qml/MuseScore/Inspector/text/textsettingsmodel.cpp]:
```suggestion
        if (item->isTextLineBase()) {
```

Comment (mathesoncalum) [reply src/inspector/qml/MuseScore/Inspector/text/textsettingsmodel.cpp]: Nice catch - done!

**Comment by zacjansheski** [comment]
Tested on MacOS Tahoe 26.2, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/31689 FIXED

File: src/inspector/qml/MuseScore/Inspector/abstractinspectormodel.h [hunk 1]
```diff
@@ -77,7 +77,6 @@ class AbstractInspectorModel : public QObject, public muse::async::Asyncable, pu
         SECTION_EMPTY_STAVES,
         SECTION_NOTATION,
         SECTION_TEXT,
-        SECTION_TEXT_LINES,
```
Comment (RomanPudashkin) [inline src/inspector/qml/MuseScore/Inspector/abstractinspectormodel.h:80]: It's still used in qml

Comment (mathesoncalum) [reply src/inspector/qml/MuseScore/Inspector/abstractinspectormodel.h:80]: Whoops - fixed!
