### PR TITLE
fix #13272 - prevent hang on parsing chord symbols

### LINKED ISSUE #13272: [MU4 Issue] Freezing and crash when entering capital letter b in chord symbol
**Description**
User can use capital letter mode accidentally for b (flat) when trying to enter Cb 

**To Reproduce**
1. Select note
2. Enter chord input mode (Ctr/Cmd+K)
4. Enter "cB" and hit Space

https://user-images.githubusercontent.com/90187801/189394263-910aa5da-ebb1-414e-b9e1-168556a07e78.mp4

**Platform information**
macOS, Windows, Linux

### PR DESCRIPTION
**Pull request by wizofaus**
Resolves: [*(direct link to the issue)*](https://github.com/musescore/MuseScore/issues/13272)

*(short description of the changes and the motivation to make the changes)*

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [x] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

File: src/framework/global/types/string.cpp [hunk 1]
```diff
@@ -722,6 +722,9 @@ StringList String::split(const std::regex& re, SplitBehavior behavior) const
 
 String& String::replace(const String& before, const String& after)
 {
+    if (before == after) {
+        return *this;
```
Comment (wizofaus) [inline src/framework/global/types/string.cpp:726]: Actually it's only in the case that before 'before' and 'after' are empty strings that it hangs, but this is  a worthwhile optimisation anyway.

**Comment by DmitryArefiev** [comment]
Tested briefly on Windows - NO CRASH

Will continue after CR from @igorkorsukov or @RomanPudashkin

**Review by igorkorsukov — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
Tested #13272 on Win10, Mac12, LinuxMint 20.2 - **FIXED**
