### PR TITLE
Fix #32262: Automatic mutes when hiding instruments [4.7.0]

### LINKED ISSUE #32262: 4.7 Beta: Toggle track mute by show/hide instruments in Layout panel not working
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. In 4.7 Testing build, ensure Preferences > Audio & Midi > Mixer > Toggle track mute by showing/hiding instruments in the Layout panel is checked.
2. Load a score with multiple instruments. Open the mixer. Press play and observe sound/metering for instruments.
3. Hide an instrument in Layout panel. Press play and observe sound/metering not muted for hidden instrument.

### Supporting files, videos and screenshots

This works in 4.6.5, but not in Testing or Master 6253a22.

Image

Image

### In which versions of MuseScore Studio is this issue present?

4.7 Beta and Master

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 15.7.4

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mathesoncalum**
Resolves: #32262

### CODE REVIEW

File: src/playback/internal/playbackcontroller.h [hunk 1]
```diff
@@ -255,6 +255,8 @@ class PlaybackController : public IPlaybackController, public muse::actions::Act
 
     muse::async::Channel<muse::audio::aux_channel_idx_t, std::string> m_auxChannelNameChanged;
 
+    std::shared_ptr<muse::async::Asyncable> m_partsNotifyReceiver = nullptr; //! HACK - see PlaybackController::setupSequenceTracks
```
Comment (igorkorsukov) [inline src/playback/internal/playbackcontroller.h]: I think it would be better to name it something like this: `m_seqAsyncReceiver` 
i.e. we need to show that this is for the sequencer 

We can simply use it by value
```
muse::async::Asyncable m_seqAsyncReceiver; 

partList.onItemChanged(&m_seqAsyncReceiver, [this, onAddFinished](const Part* part) {

}

```

Comment (mathesoncalum) [reply src/playback/internal/playbackcontroller.h]: Thanks @igorkorsukov - updated now

**Review by igorkorsukov — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
Tested #32262 on Win10, Mac13.7.8- **FIXED**
