### PR TITLE
Fix #29221: Only show welcome dialog in one instance of MuseScore Studio

### LINKED ISSUE #29221: Welcome screen should not appear when opening additional app instances
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. Open MS Studio alpha --> Welcome dialog is shown ✅
2. Create/open a score
3. Create/open a second score --> New app instance opens --> Welcome dialog is again shown ❌

**Expected:** Welcome dialog should only be shown on initial app opening

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/6c6a5889-2d27-40f0-804a-65c1c02b781c

### What is the latest version of MuseScore Studio where this issue is present?

MS Studio alpha

### Regression

No.

### Operating system

macOS 15.1

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mathesoncalum**
Resolves: #29221

### CODE REVIEW

File: src/appshell/internal/startupscenario.cpp [hunk 1]
```diff
@@ -327,7 +327,8 @@ void StartupScenario::onStartupPageOpened(StartupModeType modeType)
         configuration()->setWelcomeDialogLastShownIndex(-1); // reset
     }
 
-    if (configuration()->welcomeDialogShowOnStartup() && !museSoundsUpdateScenario()->hasUpdate()) {
+    const int numInstances = multiInstancesProvider()->instances().size();
```
Comment (cbjeukendrup) [inline src/appshell/internal/startupscenario.cpp]: I'm afraid this is going to give a compiler warning on Windows about int vs size_t

Comment (mathesoncalum) [reply src/appshell/internal/startupscenario.cpp]: Just noticed that 😅 Fixed

**Review by cbjeukendrup — APPROVED** [review]

**Comment by zacjansheski** [comment]
Tested on MacOS 15, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/29221 FIXED

**Comment by zacjansheski** [comment]
Issue does not appear to be resolved

https://github.com/user-attachments/assets/4942aecf-4d1c-4898-a17b-ccf217c9dfbf

**Comment by mathesoncalum** [comment]
> Issue does not appear to be resolved

Looks like this was meant for #29285 (I'm looking into it)
