### PR TITLE
Fix Shift+click selection between chord symbols and Roman numerals (Fixes #31410)

### LINKED ISSUE #31410: Shift clicking chord symbols also also selects roman numerals and vice versa.
### Issue type

Choose option...

### Description with steps to reproduce

1. click on a chord symbol 
2. shift+click on another chord symbol or apply "select similar" from context menu
3. roman numerals are also selected 

Same steps apply on roman numerals. 

I also discovered that the anchors don't stay relatively fixed as you move them around. (shown at the end of the video below)

### Supporting files, videos and screenshots
The video also shows aplying  behaviour of shift+click on lyrics and figured bass elements for refernece. 

https://github.com/user-attachments/assets/76b139d2-81f2-48b8-935c-71d8d0926350

### In which versions of MuseScore Studio is this issue present?

master

### Regression

No.

### Operating system

windows 11

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by pyonpyoco**
Resolves: #31410 

This PR fixes the selection behavior where chord symbols and Roman numeral analysis were selected together when using click / Shift+click.

After this change, chord symbols, Roman numerals, and Nashville notation are treated as separate selectable elements for default click and Shift+click operations, while keeping the existing selection model otherwise unchanged.

### Demo
https://github.com/user-attachments/assets/ff21677f-b2c1-483b-ae70-c1b87bf8be3b

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/muse_framework/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by pyonpyoco** [comment]
Thanks for the suggestion!
I added a subtype to the Harmony class and confirmed that this makes Shift+click and Select More behave consistently when selecting by subtype.
I didn’t add subtypeUserName() for now, since the UI already distinguishes the three harmony types correctly and I didn’t observe any issues. I kept the change minimal, but I’m happy to adjust this if needed.

https://github.com/user-attachments/assets/2cc9ea0c-1e4a-4838-a12a-41f63ae54ff7

File: src/engraving/dom/score.cpp [hunk 1]
```diff
@@ -3905,6 +3905,9 @@ void Score::selectSimilarInRange(EngravingItem* e)
     } else if (e->type() == ElementType::HAIRPIN_SEGMENT) {
         pattern.subtype = e->subtype();
         pattern.subtypeValid = true;
+    } else if (e->type() == ElementType::HARMONY) {
+        pattern.subtype = e->subtype();
+        pattern.subtypeValid = true;
```
Comment (XiaoMigros) [inline src/engraving/dom/score.cpp]:
```suggest
    } else if (e->isHairpinSegment() || e->isHarmony()) {
        pattern.subtype = e->subtype();
        pattern.subtypeValid = true;
```

**Review by XiaoMigros — CHANGES_REQUESTED** [review]

File: src/engraving/dom/score.cpp (hunk 1 above)
Comment (pyonpyoco) [reply src/engraving/dom/score.cpp]: Updated as suggested. Thanks!

**Comment by zacjansheski** [comment]
Tested on MacOS 15, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/31410 FIXED
