### PR TITLE
Fix crash on enter hairpins

### LINKED ISSUE #31542: Hairpin Crash Bug
### Issue type

Crash or freeze

### Description with steps to reproduce

With three staffs, the middle one with empty measures, selecting a range of notes across a single measure between staff 1 and 3 (across 2) then using a hotkey for a dynamic hairpin (as in 'shift+>' or 'shift+<') causes MuseScore to crash. 

Latest MuseScore version as of 20Dec2025

### Supporting files, videos and screenshots

[Score](https://musescore.com/user/36190628/scores/30360785?share=copy_link)
[Loom Screen Recording](https://www.loom.com/share/7c80293b64e4471fa12638e03d41c57d)
Image
This image shows the location, and selection, where I attempted to use a hotkey to enter a decrescendo hairpin:
Image
Image

### In which versions of MuseScore Studio is this issue present?

4.6.5

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11

### Additional context

This was originally reported on [MuseScore's Forums](https://musescore.org/en/node/388154#comment-1318142). The individual I spoke with confirmed it and advised me to post a report here.

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mike-spa**
Resolves: #31542

### CODE REVIEW

**Review by miiizen — APPROVED** [review]

**Comment by zacjansheski** [comment]
Tested on MacOS 15, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/31542 FIXED

File: src/engraving/editing/edit.cpp [hunk 1]
```diff
@@ -4289,6 +4296,27 @@ Hairpin* Score::addHairpin(HairpinType type, ChordRest* cr1, ChordRest* cr2)
...
+{
+    Hairpin* hairpin = Factory::createHairpin(this->dummy()->segment());
+    hairpin->setHairpinType(type);
+    if (type == HairpinType::CRESC_LINE) {
+        hairpin->setBeginText(u"cresc.");
+        hairpin->setContinueText(u"(cresc.)");
+    } else if (type == HairpinType::DIM_LINE) {
+        hairpin->setBeginText(u"dim.");
+        hairpin->setContinueText(u"(dim.)");
+    }
```
Comment (XiaoMigros) [inline src/engraving/editing/edit.cpp:4309]: Is this needed at all? If it is, the text should be set based on style values
