### PR TITLE
fix #9210 fix #10038 Score ordering

### LINKED ISSUE #9210: [MU4 Issue] Rearranging the instruments, leads to incorrect brackets
**Describe the bug**
Rearranging the instruments, leads to incorrect brackets

**To Reproduce**
1. Create a new Score "SATB Closed Score + Piano"
2. Drag the "women" under the "men" voice

**Expected behavior**
Set the brackets correct or remove them if they are not needed.

**Screenshots**
Bevor rearranging
Vorher

After rearranging
nachher

**Desktop (please complete the following information):**
 - OS: Windows 10

### LINKED ISSUE #10038: [MU4 Issue] Custom instrument order reverted to Orchestral when opening the Instruments panel
**Describe the bug**
Custom instrument order reverted to Orchestral when opening the Instruments panel.

**To Reproduce**
1. Create a score and add two instruments, for example a woodwind, say, alto saxophone, and a brass, say, cornet. Now cornet should be below alto saxophone by default.
2. Move cornet above alto saxophone. The instrument order type is changed to Custom. Then close the Instruments panel.
3. Reopen the Instruments panel, and see that the instrument order type is now displayed as Orchestral, but the order itself didn't change.
4. Add a new instrument, for example a string, say, contrabass. Cornet and alto saxophone are then reordered.

**Expected behavior**
The order type should not be reverted to Orchestral, and the instruments should not be reordered when adding new instruments if the type was set to Custom.

**Desktop (please complete the following information):**
 - OS: Windows 11

### PR DESCRIPTION
**Pull request by njvdberg**
Resolves: https://github.com/musescore/MuseScore/issues/9210
Resolves: https://github.com/musescore/MuseScore/issues/10038

If the instrument order is changed manually, a customized version of the existing score order is created instead of switching the "Custom" score order.
This effects the automatic creation of brackets and braces:
- For "Custom" score orders, no automatic creation of brackets and braces is performed. As a result, existing brackets remain.
- For "customized" score orders, all existing brackets and braces are removed and newly generated.

Key method in this is the method `ScoreOrder::isScore()` which returns true if the specified score (or instrument order) matches the score order.

After every change in the instrument order the score is checked again:
- If the new order matches the score order **and** the score order is a customized score order, use the standard, non customized, score order and remove the customized score order.
- If the new order doesn't match the score order **and** the score order is a standard, non customized, score order, create a new customized version of the score order and select this customized score order.

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

File: src/instrumentsscene/view/instrumentsonscorelistmodel.cpp [hunk 1]
```diff
@@ -153,17 +161,38 @@ void InstrumentsOnScoreListModel::loadOrders()
     TRACEFUNC;
 
     m_scoreOrders = repository()->orders();
```
Comment (RomanPudashkin) [inline src/instrumentsscene/view/instrumentsonscorelistmodel.cpp:163]: Please, add a check for emptiness here

File: src/instrumentsscene/view/instrumentsonscorelistmodel.cpp [hunk 2]
```diff
@@ -153,17 +161,38 @@ void InstrumentsOnScoreListModel::loadOrders()
...
     }
+
+    if (orderCustomized) {
+        doSetCurrentOrderIndex(createCustomizedScoreOrder(currentOrder));
+    }
+}
+
+int InstrumentsOnScoreListModel::resolveInstrumentSequenceNumber(const QString& instrumentId) const
+{
+    for (const InstrumentTemplate* templ : repository()->instrumentTemplates()) {
```
Comment (RomanPudashkin) [inline src/instrumentsscene/view/instrumentsonscorelistmodel.cpp:190]: Better to get this value

repository()->instrumentTemplates()

only once and reuse it twice

File: src/instrumentsscene/view/instrumentsonscorelistmodel.cpp [hunk 3]
```diff
@@ -321,16 +323,67 @@ const ScoreOrder& InstrumentsOnScoreListModel::currentScoreOrder() const
...
+
+bool InstrumentsOnScoreListModel::matchesScoreOrder() const
+{
+    QList<int> instrumentIndices;
+    for (const Item* item : items()) {
+        auto instrument = dynamic_cast<const InstrumentItem*>(item);
+        if (!instrument) {
+            continue;
+        }
+        instrumentIndices << currentScoreOrder().instrumentSortingIndex(instrument->id, instrument->isSoloist);
```
Comment (RomanPudashkin) [inline src/instrumentsscene/view/instrumentsonscorelistmodel.cpp:342]: Better to get this value outside of the loop and use it here (and in the return statement)

File: src/instrumentsscene/view/instrumentsonscorelistmodel.cpp [hunk 4]
```diff
@@ -321,16 +323,67 @@ const ScoreOrder& InstrumentsOnScoreListModel::currentScoreOrder() const
...
+    }
+
+    return currentScoreOrder().isScoreOrder(instrumentIndices);
+}
+
+void InstrumentsOnScoreListModel::verifyScoreOrder()
+{
+    bool matchingScoreOrder = matchesScoreOrder();
+
+    if (matchingScoreOrder == currentScoreOrder().customized) {
```
Comment (RomanPudashkin) [inline src/instrumentsscene/view/instrumentsonscorelistmodel.cpp:352]: Better to call currentScoreOrder() only once and reuse it where needed

File: src/engraving/libmscore/instrtemplate.h [hunk 5]
```diff
@@ -157,12 +157,12 @@ struct InstrumentGroup {
 //---------------------------------------------------------
 
 struct InstrumentIndex {
-    int groupIndex;
-    int instrIndex;
+    int groupIndex = 0;
+    int instrIndex = 0;
+    int templateCount = 0;
     InstrumentTemplate* instrTemplate;
```
Comment (RomanPudashkin) [inline src/engraving/libmscore/instrtemplate.h:163]: It would be nice to set instrTemplate to nullptr by default

File: src/engraving/libmscore/scoreorder.cpp [hunk 6]
```diff
@@ -175,6 +205,24 @@ bool ScoreOrder::isValid() const
...
+bool ScoreOrder::isCustom() const
+{
+    return id == QString("custom");
+}
+
+//---------------------------------------------------------
+//   getName
+//---------------------------------------------------------
+
+QString ScoreOrder::getName() const
```
Comment (RomanPudashkin) [inline src/engraving/libmscore/scoreorder.cpp:221]: Better to remove the get prefix. Just name() will be fine

File: src/instrumentsscene/view/instrumentspanelcontextmenumodel.cpp [hunk 7]
```diff
@@ -64,6 +64,10 @@ void InstrumentsPanelContextMenuModel::load()
         m_masterNotation->parts()->scoreOrderChanged().onNotify(this, [this] {
             updateOrderingMenu(m_masterNotation->parts()->scoreOrder().id);
         });
+
+        m_masterNotation->parts()->partsChanged().onNotify(this, [this] {
```
Comment (RomanPudashkin) [inline src/instrumentsscene/view/instrumentspanelcontextmenumodel.cpp:68]: Could you please explain why you need this connection? scoreOrderChanged() is not enough?

File: src/engraving/libmscore/scoreorder.cpp [hunk 8]
```diff
@@ -226,6 +291,89 @@ ScoreGroup ScoreOrder::getGroup(const QString family, const QString instrumentGr
...
+        }
+        prvIndex = curIndex;
+    }
+    return true;
+}
+
+bool ScoreOrder::isScoreOrder(const Score* score) const
+{
+    QList<int> indices;
+    for (Part* part : score->parts()) {
```
Comment (RomanPudashkin) [inline src/engraving/libmscore/scoreorder.cpp:370]: Please, add const for this pointer:

for (const Part* part : score->parts())

**Comment by RomanPudashkin** [comment]
Looks very good! Thank you!

File: src/instrumentsscene/view/instrumentsonscorelistmodel.cpp (hunk 1 above)
Comment (njvdberg) [reply src/instrumentsscene/view/instrumentsonscorelistmodel.cpp:163]: As a matter of fact, it should also test for a `CustomOrder` and add on if is missing.
Same change made in `src/instrumentsscene/view/instrumentspanelcontextmenumodel.cpp`.

File: src/instrumentsscene/view/instrumentsonscorelistmodel.cpp (hunk 2 above)
Comment (njvdberg) [reply src/instrumentsscene/view/instrumentsonscorelistmodel.cpp:190]: I see why, thanks!

File: src/instrumentsscene/view/instrumentsonscorelistmodel.cpp (hunk 3 above)
Comment (njvdberg) [reply src/instrumentsscene/view/instrumentsonscorelistmodel.cpp:342]: I always hoped the compiler would take care of this :smile:

File: src/engraving/libmscore/instrtemplate.h (hunk 5 above)
Comment (njvdberg) [reply src/engraving/libmscore/instrtemplate.h:163]: Done.

File: src/engraving/libmscore/scoreorder.cpp (hunk 6 above)
Comment (njvdberg) [reply src/engraving/libmscore/scoreorder.cpp:221]: This will cause a conflict with the member variable `name` of the same struct.

File: src/engraving/libmscore/scoreorder.cpp (hunk 8 above)
Comment (njvdberg) [reply src/engraving/libmscore/scoreorder.cpp:370]: Done

File: src/instrumentsscene/view/instrumentspanelcontextmenumodel.cpp (hunk 7 above)
Comment (njvdberg) [reply src/instrumentsscene/view/instrumentspanelcontextmenumodel.cpp:68]: This is a leftover of earlier versions and indeed it isn't required anymore.
Removed.

**Review by RomanPudashkin — APPROVED** [review]
