### PR TITLE
[MU4] Fix #10122: Instrument name does not update in parts dialog and its tab on replace

### LINKED ISSUE #10122: [MU4 Issue] Instrument name does not update in parts dialog and its tab on replace
(Updated by @Tantacrul, @DmitryArefiev )
**Describe the bug**
When opening some older scores, the 'Replace Instrument' feature does not work. However, it **does** work for new scores.

BUG№1 - **FIXED** in #13097
To Reproduce:
1. Open  [string quartet 2.zip](https://github.com/musescore/MuseScore/files/9594429/string.quartet.2.zip)
2. Open Violin I part
3. Go to score and replace the Violin I with another instrument, like a Flute, using the Instruments panel
4. Observe that the **instrument label in score/mixer** and **sounds do not update**.

https://user-images.githubusercontent.com/90187801/190918230-036284c9-7ec6-4971-9e1f-ade697bb5a60.mp4

BUG№2 (**STILL OCCURS**)
To Reproduce:
1. Open  [string quartet 2.zip](https://github.com/musescore/MuseScore/files/9594429/string.quartet.2.zip)
2. Open Violin I part
3. Go to score and replace the Violin I with another instrument, like a Flute, using the Instruments panel
4. Observe that the **instrument name in part, in its tab and in parts dialog do not update**.

https://user-images.githubusercontent.com/90187801/190918628-ed607a95-dde3-4545-a3eb-344fb7ff3031.mp4

**Expected behavior**
The instrument's name should be updated in the parts dialog and its tab

Initial video from bug report

https://user-images.githubusercontent.com/88136054/146490932-a6ced8f6-6d20-4c0c-9d38-c2142dcf0a55.mp4

**Desktop (please complete the following information):**
Win, Mac, Linux

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Resolves: https://github.com/musescore/MuseScore/issues/10122

### CODE REVIEW

**Comment by DmitryArefiev** [comment]
Tested **BUG№1** from #10122 on Win10, Mac12, LinuxMint 20.2 - **FIXED**

**Review by Eism — APPROVED** [review]

File: src/notation/internal/notationundostack.cpp [hunk 1]
```diff
@@ -136,17 +136,25 @@ void NotationUndoStack::commitChanges()
 
 void NotationUndoStack::lock()
 {
-    m_isLocked = true;
+    IF_ASSERT_FAILED(undoStack()) {
```
Comment (cbjeukendrup) [inline src/notation/internal/notationundostack.cpp:139]: @RomanPudashkin Now I get a crash here every time that I try to create a score by choosing instruments (not template). 
Problem seems to be that the `score()` of the (Master)Notation is not initialised yet.

Comment (RomanPudashkin) [reply src/notation/internal/notationundostack.cpp:139]: Sorry :( I'll check this problem
