### PR TITLE
Fix #16930 - Page Background Wallpaper is reset when restarting

### LINKED ISSUE #16930: Page Background Wallpaper is reset when restarting the program
### Issue type

Other type of issue

### Bug description

_No response_

### Steps to reproduce

1. Go to Edit/Preferences/Appearance
2. Scroll down and select 'Wallpaper' under the 'Paper' section.
3. Choose any image file (MuseScore's preinstalled ones or your own)
4. Make note of the new page background
5. Close and reopen MuseScore
6. The background is no longer present

### Screenshots/Screen recordings

image

### MuseScore Version

4.0.2

### Regression

Yes, this used to work in Musescore 3.x and now is broken

### Operating system

Windows 10

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by worldwideweary**
Resolves: #16930

So far so good here, but testing would be appreciated. The problem, AFAIS, was that the static wallpaper variable was not getting loaded on initialization because of the != last path check, yet that needs to be kept as it is or else there would be inefficient updating of the QPixMap when notation redraws. 

Result: wallpaper is actual at initialization for both background and foreground.

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

File: src/notation/internal/notationconfiguration.cpp [hunk 1]
```diff
@@ -266,7 +266,7 @@ const QPixmap& NotationConfiguration::backgroundWallpaper() const
 
     if (path.empty()) {
         wallpaper = QPixmap();
-    } else if (path != lastPath) {
+    } else if (path != lastPath || wallpaper.isNull()) {
```
Comment (cbjeukendrup) [inline src/notation/internal/notationconfiguration.cpp:269]: An alternative solution might be to initialise `lastPath` with an empty path instead of `path`, so that `path != lastPath` is true.
It seems to me that the disadvantage of checking `wallpaper.isNull()` is that if a wallpaper fails to load, we'll retry loading it every time this method is called, which is wasteful.

Comment (worldwideweary) [reply src/notation/internal/notationconfiguration.cpp:269]: That makes sense. Failing to load hopefully is a rare case, but I'll do a force push with a static default initialization of lastPath - the code already updates last path afterwards. 

P.S. Speaking of wasteful, it would be cool if you could give an examination of the problem over at issue #12753 (few second delay for search activation when not currently searching). Off topic here, but thought I'd mention it in passing. The "front-end" QML seems okay to me -  but something screwy going on with the architecture behind it or something.

**Review by cbjeukendrup — APPROVED** [review]

**Comment by zacjansheski** [comment]
Tested on Mac OS 11.6.5, Ubuntu 20.04.6, Windows 11
https://github.com/musescore/MuseScore/issues/16930 FIXED
