### PR TITLE
Fix measure repeat extender

### LINKED ISSUE #27305: Extenders on 4-measure repeats are not the correct width
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

Enabling extenders on 4-measure repeats (Format -> Style -> Measure repeats) can produce extenders of incorrect width. The extenders seem to always be 4 times the width of the second measure of the repeat, irrespective of the other measures.

### Supporting files, videos and screenshots

Image

Zip containing mscz file:
[extenders-on-4-measure-repeats-bug.zip](https://github.com/user-attachments/files/19408629/extenders-on-4-measure-repeats-bug.zip)

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.5.1-250800846, revision: github-musescore-musescore-603eca8

### Regression

I was unable to check

### Operating system

Windows 10

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mike-spa**
Resolves: #27305 

Just reusing the fuction which calculates this for mmRests.

### CODE REVIEW

**Review by ghost — APPROVED** [review]

File: src/engraving/rendering/score/tlayout.cpp [hunk 1]
```diff
@@ -4134,6 +4134,52 @@ void TLayout::layoutMeasureRepeat(const MeasureRepeat* item, MeasureRepeat::Layo
...
+        endMeasure = endMeasure->nextMeasure();
+    }
+    if (!endMeasure || endMeasure->system() != parentMeasure->system()) {
+        return;
+    }
+
+    // Reuse the function that calculates start and end pos for mmRests,
+    // except start and end point are on different measures
+    staff_idx_t staffIdx = item->staffIdx();
+    double xStart = MeasureLayout::getMeasureStartEndPos(startMeasure, startMeasure->first(SegmentType::ChordRest), staffIdx,
```
Comment (miiizen) [inline src/engraving/rendering/score/tlayout.cpp:4163]: You could store the result of this in a variable to save calling it twice.

Comment (mike-spa) [reply src/engraving/rendering/score/tlayout.cpp:4163]: Yeah but the second time is called on a different measure (the end measure) so it'd still be two calls

Comment (miiizen) [reply src/engraving/rendering/score/tlayout.cpp:4163]: 🤦 apologies

**Review by miiizen — APPROVED** [review]
