### PR TITLE
Fix #26640: Set default clefs when creating parts

### LINKED ISSUE #26640: Plugin: curScore.appendPart() always uses treble clef
### Issue type

Other type of issue

### Description with steps to reproduce

When a plugin calls curScore.appendPart() to create a new Part, the new staff is added with a treble clef, even if the specified instrument should use a bass clef.

Steps to reproduce:
1. Install the attached plugins by unzipping, then moving the "Test - Add Part" folder into your Plugins folder
2. In MuseScore, choose Plugins/Manage Plugins...
3. Enable the "Test - Add Piano" and "Test - Add Bass Guitar" plugins
4. Choose either of these plugins from the Plugins menu under Composing/arranging tools

Expected Results:
A new Piano or Bass Guitar part should be added, using treble and bass clefs on a grand staff for piano, or a single staff with bass clef for bass guitar.  This would be the same behavior if you press "i" and add that instrument to your score.

Actual Results:
The new parts are added, but all clefs are treble clef.

### Supporting files, videos and screenshots

[Test - Add Part.zip](https://github.com/user-attachments/files/18896256/Test.-.Add.Part.zip)

I made fancy plugins for easy testing, but the relevant code is simply:
`curScore.appendPart("piano");`
`curScore.appendPart("bass-guitar");`

Image

### What is the latest version of MuseScore Studio where this issue is present?

OS: macOS 12.7, Arch.: x86_64, MuseScore Studio version (64-bit): 4.6.0-250510304, revision: github-musescore-musescore-af80582

### Regression

No.

### Operating system

macOS 12.7.6 Monterey

### Additional context

Verified same behavior in 4.4.4 and 3.6.2.  The plugin API doesn't expose any information about what clefs are in use, or provide any way to change them (other than by inserting a clef change), so there is no workaround for this other than to instruct the user to manually change the clef.

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by XiaoMigros**
Resolves: #26640 

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [ ] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

File: src/engraving/dom/score.cpp [hunk 1]
```diff
@@ -4465,6 +4465,7 @@ void Score::appendPart(const InstrumentTemplate* t)
     part->initFromInstrTemplate(t);
     for (staff_idx_t i = 0; i < t->staffCount; ++i) {
         Staff* staff = Factory::createStaff(part);
+        staff->setDefaultClefType(part->instrument()->clefType(i));
```
Comment (cbjeukendrup) [inline src/engraving/dom/score.cpp]: Or should we even use `Staff::init`?

Comment (XiaoMigros) [reply src/engraving/dom/score.cpp]: That does seem simpler, if the tests pass...

**Review by cbjeukendrup — APPROVED** [review]
