### PR TITLE
Fix unit tests due to chords_std.xml not found

### LINKED ISSUE #22500: Unit tests (in GitHub CI)  don't seem to find chords_std.xml
### Issue type

Other type of issue

### Bug description

9: 09:59:45.456 | ERROR | main_thread     | ChordList::read | Cannot open chord description: /home/runner/work/MuseScore/MuseScore/build.install/share/mscore-4.4//styles/chords_std.xml
9: 09:59:45.456 | ERROR | main_thread     | ChordList::read | Cannot open chord description: /home/runner/work/MuseScore/MuseScore/build.install/share/mscore-4.4//styles/chords_std.xml

### Steps to reproduce

Check any unit test output from GitHub CI

### Screenshots/Screen recordings

image

### MuseScore Version

all

### Regression

Regression vs. 3.x

### Operating system

Linux (which is what the unit tests use)

### Additional context

This does clutter (some 1700 lines!) the unit test log (espt. its red color!) with lots of otherwise unneccessary error messages, making it easy to not see the tree in the forrest

Notice also the double / in the output, that'd be an easy fix though:
```cpp
diff --git a/src/engraving/dom/chordlist.cpp b/src/engraving/dom/chordlist.cpp
index 49dcbe6795..8ddcd824d9 100644
--- a/src/engraving/dom/chordlist.cpp
+++ b/src/engraving/dom/chordlist.cpp
@@ -1821,12 +1821,12 @@ bool ChordList::read(const String& name)
     if (ftest.isAbsolute()) {
         path = name;
     } else {
-        path = configuration()->appDataPath() + "/styles/" + name;
+        path = configuration()->appDataPath() + "styles/" + name;
     }

     // default to chords_std.xml
     if (!FileInfo::exists(path)) {
-        path = configuration()->appDataPath() + "/styles/chords_std.xml";
+        path = configuration()->appDataPath() + "styles/chords_std.xml";
     }

     if (name.isEmpty()) {
```
See #22501

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Resolves #22500

* Run install target before running unit tests, so chords_std.xml are actually found (cherry-picked from #22503).
* Fix unit tests in two Mu1 engreaving/import tests due to chords_std.xml now being found.
* Use debug log rather than error log, to fix erroneous error output in unit tests and vtests.
* Fix ENTITY parser, to fix an erroneous warning output (which actually pointed at a bug in said parser).

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
The unit test failure is expected, it needs #22503

**Comment by Jojo-Schmitz** [comment]
Next issue: Are these errors supposed to happen?
```
1: [ RUN      ] Global_IO_IODeviceTests.Open_ReadOnly
1: 11:03:02.942 | INFO  | main_thread     | GlobalModule::onPreInit | log path: /root/.local/share/muse_global_tests/logs/MuseScore_240421_110302.log
1: 11:03:02.942 | INFO  | main_thread     | GlobalModule::onPreInit | === Started MuseScore Studio 4.4.0, build: 241121040 ===
1: 11:03:02.943 | ERROR | main_thread     | IODevice::write | "ASSERT FAILED!": isOpenModeWriteable(), file: /home/runner/work/MuseScore/MuseScore/src/framework/global/io/iodevice.cpp, line: 200
1: [       OK ] Global_IO_IODeviceTests.Open_ReadOnly (220 ms)
1: [ RUN      ] Global_IO_IODeviceTests.Open_WriteOnly
1: 11:03:03.163 | INFO  | main_thread     | GlobalModule::onPreInit | log path: /root/.local/share/muse_global_tests/logs/MuseScore_240421_1[103](https://github.com/musescore/MuseScore/actions/runs/8772061759/job/24070551147#step:10:104)03.log
1: 11:03:03.163 | INFO  | main_thread     | GlobalModule::onPreInit | === Started MuseScore Studio 4.4.0, build: 24112[104](https://github.com/musescore/MuseScore/actions/runs/8772061759/job/24070551147#step:10:105)0 ===
1: 11:03:03.164 | ERROR | main_thread     | IODevice::read  | "ASSERT FAILED!": isOpenModeReadable(), file: /home/runner/work/MuseScore/MuseScore/src/framework/global/io/iodevice.cpp, line: 152
1: 11:03:03.316 | INFO  | main_thread     | GlobalModule::onPreInit | log path: /root/.local/share/muse_global_tests/logs/MuseScore_240421_110303.log
1: 11:03:03.316 | INFO  | main_thread     | GlobalModule::onPreInit | === Started MuseScore Studio 4.4.0, build: 241121040 ===
1: 11:03:03.317 | ERROR | main_thread     | IODevice::read  | "ASSERT FAILED!": isOpenModeReadable(), file: /home/runner/work/MuseScore/MuseScore/src/framework/global/io/iodevice.cpp, line: 152
1: 11:03:03.469 | INFO  | main_thread     | GlobalModule::onPreInit | log path: /root/.local/share/muse_global_tests/logs/MuseScore_240421_110303.log
1: 11:03:03.469 | INFO  | main_thread     | GlobalModule::onPreInit | === Started MuseScore Studio 4.4.0, build: 241121040 ===
1: 11:03:03.470 | ERROR | main_thread     | IODevice::read  | "ASSERT FAILED!": isOpenModeReadable(), file: /home/runner/work/MuseScore/MuseScore/src/framework/global/io/iodevice.cpp, line: 126
```

**Review by cbjeukendrup — APPROVED** [review]

File: src/framework/global/serialization/xmlstreamreader.cpp
Comment (cbjeukendrup) [inline src/framework/global/serialization/xmlstreamreader.cpp:1]: While this looks like it works, I'm not sure how elegant it is. I think we can avoid the usage of `String` and `.split` here, and do a bit more low-level parsing with just std::strings. If done well, that's more efficient and less sensitive to variations in whitespace (like, a double space instead of one).
See for example https://stackoverflow.com/questions/18675364/c-tokenize-a-string-with-spaces-and-quotes.

Comment (Jojo-Schmitz) [reply src/framework/global/serialization/xmlstreamreader.cpp:1]: Hmm, and I was so proud of the eleancy...

;-)

yes, of course a fully fledged parse would be much nicer. Will see what I can come up with.

Comment (Jojo-Schmitz) [reply src/framework/global/serialization/xmlstreamreader.cpp:1]: Except that it now crashes on vtest/scores/harmony-6.mscx :-(

Comment (Jojo-Schmitz) [reply src/framework/global/serialization/xmlstreamreader.cpp:1]: OK, strtok() doesn't like to be lied on about the constness of its 1st arg...

Comment (Jojo-Schmitz) [reply src/framework/global/serialization/xmlstreamreader.cpp:1]: If you like this one better I'll squash the last 2 commits

**Review by igorkorsukov — APPROVED** [review]

**Comment by Jojo-Schmitz** [comment]
@cbjeukendrup can you do another review of the latest version of my entity parser?

**Comment by cbjeukendrup** [comment]
Seems fine to me!

File: src/engraving/infrastructure/mscreader.cpp [hunk 1]
```diff
@@ -407,7 +407,7 @@ ByteArray MscReader::DirReader::fileData(const String& fileName) const
     muse::io::path_t filePath = m_rootPath + "/" + fileName;
     File file(filePath);
     if (!file.open(IODevice::ReadOnly)) {
-        LOGE() << "failed open file: " << filePath;
+        LOGD() << "failed open file: " << filePath;
```
Comment (cbjeukendrup) [inline src/engraving/infrastructure/mscreader.cpp:410]: Wait, this change is questionable. This message _may_ be relevant when debugging a problem for a user, and LOGD messages are not included in log files for release builds by default. So I suggest using `LOGE()` here.
(We could add a parameter to this method to tell whether the presence of this file is crucial, and based on that choose between LOGD and LOGE, but I don't think that's worth it.)

**Comment by Jojo-Schmitz** [comment]
Done

File: src/engraving/infrastructure/mscreader.cpp (hunk 1 above)
Comment (Jojo-Schmitz) [reply src/engraving/infrastructure/mscreader.cpp]: done

**Review by cbjeukendrup — APPROVED** [review]
