### PR TITLE
Fix #11776: Playback panel shows wrong tempo

### LINKED ISSUE #11776: [MU4 Issue] Play panel shows incorrect tempo
**Describe the bug**
When adding "Quarter note = 80 BPM" element from the palette, the play panel shows "♩= 79" in nightly build

**To Reproduce**
1. Create new score
2. Add "Quarter note = 80 BPM" element from tempo palette to the score
3. See play panel

**Expected behavior**
Play panel should show "♩= 80"

**Screenshots**
スクリーンショット (19)

**Platform information**
 - OS: Windows 11

**Additional context**
Doesn't occur in Private Alpha

### PR DESCRIPTION
**Pull request by HemantAntony**
Resolves: #11776

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

File: src/notation/internal/notationplayback.cpp [hunk 1]
```diff
@@ -299,7 +299,7 @@ const Tempo& NotationPlayback::tempo(tick_t tick) const
         return empty;
     }
 
-    m_currentTempo.valueBpm = static_cast<int>(score()->tempomap()->tempo(tick).toBPM().val);
+    m_currentTempo.valueBpm = std::round(score()->tempomap()->tempo(tick).toBPM().val);
```
Comment (Jojo-Schmitz) [inline src/notation/internal/notationplayback.cpp:302]: but `std::round()` does return a `double`, so that cast to `int` would still be needed (as `valueBpm` is an `int`), for the compiler not to warn, as far as I can tell?

Comment (HemantAntony) [reply src/notation/internal/notationplayback.cpp:302]: Yeah that's correct. I realized that after creating the PR and forgot to push the changes. Thanks! :)

Comment (Jojo-Schmitz) [reply src/notation/internal/notationplayback.cpp:302]: Strange enough neither MSVC nor MinGW do warn about it?!

Comment (HemantAntony) [reply src/notation/internal/notationplayback.cpp:302]: Yeah, that's probably correct. I figured it out because of a hunch and not because of a warning

**Comment by Tantacrul** [comment]
Tested. The tempo display problem is fixed. Thanks! @HemantAntony

**Review by RomanPudashkin — APPROVED** [review]
