### PR TITLE
Fix #27791: Hide instrument and undo does not open "eye" icon

### LINKED ISSUE #27791: Hide instrument and undo does not open "eye" icon
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

1. Make a score with flute and oboe
2. Hide flute in layout panel
3. Undo (must undo twice as logged in https://github.com/musescore/MuseScore/issues/13748 )
4. Eye does not reopen (regression of 4.4.4)

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/6671f952-ae5f-470b-8ec2-ceac0348eedb

### What is the latest version of MuseScore Studio where this issue is present?

OS: macOS 15.3, Arch.: arm64, MuseScore Studio version (64-bit): 4.5.2-251071031, revision: github-musescore-musescore-12988a5

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

MacOS15

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Resolves: https://github.com/musescore/MuseScore/issues/27791

### CODE REVIEW

File: src/instrumentsscene/view/parttreeitem.cpp [hunk 1]
```diff
@@ -66,10 +66,23 @@ const Part* PartTreeItem::part() const
...
+    m_ignoreVisibilityChange = true;
+    setIsVisible(m_part->show());
+    m_ignoreVisibilityChange = false;
+}
+
 void PartTreeItem::listenVisibilityChanged()
 {
     connect(this, &AbstractLayoutPanelTreeItem::isVisibleChanged, this, [this](bool isVisible) {
-        if (!m_isInited) {
+        if (!m_isInited || m_ignoreVisibilityChange) {
```
Comment (mathesoncalum) [inline src/instrumentsscene/view/parttreeitem.cpp:85]: As far as I can tell, `m_isInited` and `m_ignoreVisibilityChange` basically serve the same purpose (this is the only place where `m_isInited` is used).

I'd just combine them into a single `m_ignoreVisibilityChange` flag which is true by default, and set to false after `PartTreeItem::init`.

**Review by mathesoncalum — APPROVED** [review]

**Comment by zacjansheski** [comment]
When making an instrument visible in custom part, all eye icons are opened

https://github.com/user-attachments/assets/d20b0eec-7e93-4b59-b392-5748979d867a

**Comment by zacjansheski** [comment]
Tested on MacOS 15, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/27791 FIXED

**Review by mathesoncalum — APPROVED** [review]
