### PR TITLE
fix #12097 - ensure new/changed notes/rests are always scrolled into view

### LINKED ISSUE #12097: [MU4 Issue] If current measure moves to new system after changing durations it's not scrolled into view
**Describe the bug**
Quite often changing the duration of existing notes/rests in a measure or entering in new notes can cause it to become too wide and move to the next system. This is fine, but it should at least be automatically scrolled into view if so.
This is especially a problem with note entry.

**To Reproduce**
1. Create a new score using an ensemble template like Rock Band (only one system fitting on screen by default)
2. Click the "quaver" button (or hit the 4 key)
3. Select the last measure of the first system in, say, the Drum part
4. Enter a note (e.g. hit A)
5. Entered note (and containing measure) is no longer visible (it has moved to next system)

**Expected behavior**
Selected note/rest should remain visible after moving automatically to new system, as per v3.
NB the same occurs when "padding" a rest by changing its duration.

**Screenshots**

**Platform information**
 - Windows 10

**Additional context**

### PR DESCRIPTION
**Pull request by wizofaus**
Resolves: https://github.com/musescore/MuseScore/issues/12097

Ensure newly added or changed notes/rests are always kept in view

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

File: src/notation/internal/notationnoteinput.cpp [hunk 1]
```diff
@@ -254,10 +254,6 @@ void NotationNoteInput::putNote(const PointF& pos, bool replace, bool insert)
 
     notifyNoteAddedChanged();
     notifyAboutStateChanged();
-
-    if (mu::engraving::ChordRest* chordRest = score()->inputState().cr()) {
-        m_interaction->showItem(chordRest);
-    }
```
Comment (wizofaus) [inline src/notation/internal/notationnoteinput.cpp:260]: logic should apply to all actions (putNote/padNote/addNote)

**Review by RomanPudashkin — APPROVED** [review]
