### PR TITLE
Fix #22601: Include text alignment in line layout

### LINKED ISSUE #22601: Line component of TextLines ignores Text alignment
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

The line component of TextLine based elements (cresc. lines, ottavas, pedals, etc.) ignores the horizontal alignment of the text when calculating its length. This can lead to an ugly gap.

**Left-aligned (correct)**
image

**Center-aligned**
image

**Right-aligned**
image

### Steps to reproduce

1. Add a cresc. line to the score
2. Change the text alignment of the begin text

### Screenshots/Screen recordings

_No response_

### MuseScore Version

master

### Regression

No.

### Operating system

Windows 10

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by XiaoMigros**
Resolves: #22601

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [ ] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [x] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
It seems that something similar applies to the end text: 
Scherm­afbeelding 2024-04-27 om 18 37 57
The line continues below the text, while I think it should end before. But this also depends on the `endTextPlace` property, which should probably behave similar to `beginTextPlace`. 
It's difficult to test, because the UI for it is mostly missing in MS4's properties panel.

It would be good to also add a new VTest to this PR, ideally one that verifies all combinations of TextPlace and Alignment, for begin and end text.

File: src/engraving/rendering/dev/tlayout.cpp [hunk 1]
```diff
@@ -5911,7 +5911,15 @@ void TLayout::layoutTextLineBaseSegment(TextLineBaseSegment* item, LayoutContext
...
-            l = item->text()->pos().x() + item->text()->ldata()->bbox().width() + gapBetweenTextAndLine;
+            l = item->text()->pos().x() + gapBetweenTextAndLine;
+            switch (item->text()->align().horizontal) {
+            case AlignH::LEFT:
+                l += item->text()->ldata()->bbox().width();
+                break;
+            case AlignH::HCENTER:
+                l += item->text()->ldata()->bbox().width() / 2;
+                break;
+            }
```
Comment (Jojo-Schmitz) [inline src/engraving/rendering/dev/tlayout.cpp:5922]: I believe a default case is needed to avoid compiler warnings reg. unhandled cases?

Comment (Jojo-Schmitz) [reply src/engraving/rendering/dev/tlayout.cpp:5922]: Also: where is `AlignH::Right handled?

Comment (XiaoMigros) [reply src/engraving/rendering/dev/tlayout.cpp:5922]: > I believe a default case is needed to avoid compiler warnings reg. unhandled cases?

A few lines further up in this layout method, there is a switch with also no default case

Comment (XiaoMigros) [reply src/engraving/rendering/dev/tlayout.cpp:5922]: > Also: where is `AlignH::Right handled?

`AlignH::Right` does not need to be offset by the text width, since the text ends before point 0

**Comment by XiaoMigros** [comment]
> It seems that something similar applies to the end text:

Should the end text then also use the 'gap between text and line' property? currently there is no distance added at all

File: src/engraving/rendering/dev/tlayout.cpp (hunk 1 above)
Comment (Jojo-Schmitz) [reply src/engraving/rendering/dev/tlayout.cpp:5931]: > I believe a default case is needed to avoid compiler warnings reg. unhandled cases?

Right, but that handles all possible cases

Comment (Jojo-Schmitz) [reply src/engraving/rendering/dev/tlayout.cpp:5931]: > > I believe a default case is needed to avoid compiler warnings reg. unhandled cases?
> 
> A few lines further up in this layout method, there is a switch with also no default case

Right, but that handles all possible cases

File: src/engraving/rendering/dev/tlayout.cpp [hunk 2]
```diff
@@ -5949,21 +5966,23 @@ void TLayout::layoutTextLineBaseSegment(TextLineBaseSegment* item, LayoutContext
...
     if (!item->endText()->empty()) {
+        l2 = gapBetweenTextAndLine;
+        switch (item->endText()->align().horizontal) {
+        case AlignH::RIGHT:
+            l2 += item->endText()->ldata()->bbox().width();
+            break;
+        case AlignH::HCENTER:
+            l2 += item->endText()->ldata()->bbox().width() / 2;
+            break;
+        }
```
Comment (Jojo-Schmitz) [inline src/engraving/rendering/dev/tlayout.cpp:5977]: default case needed here too

File: src/engraving/rendering/dev/tlayout.cpp (hunk 1 above)
Comment (cbjeukendrup) [reply src/engraving/rendering/dev/tlayout.cpp:5931]: Simply add `default: break;`, to tell the compiler explicitly that you didn't forget the other two cases

Comment (Jojo-Schmitz) [reply src/engraving/rendering/dev/tlayout.cpp:5931]: Exactly my point. From the CI build logs:
```
2024-04-28T07:30:02.2925013Z ../src/engraving/rendering/dev/tlayout.cpp: In static member function ‘static void mu::engraving::rendering::dev::TLayout::layoutTextLineBaseSegment(mu::engraving::TextLineBaseSegment*, mu::engraving::rendering::dev::LayoutContext&)’:
2024-04-28T07:30:02.2993137Z ../src/engraving/rendering/dev/tlayout.cpp:5924:20: warning: enumeration value ‘RIGHT’ not handled in switch [-Wswitch]
2024-04-28T07:30:02.2994430Z  5924 |             switch (item->text()->align().horizontal) {
2024-04-28T07:30:02.2995009Z       |                    ^
2024-04-28T07:30:02.2996367Z ../src/engraving/rendering/dev/tlayout.cpp:5970:16: warning: enumeration value ‘LEFT’ not handled in switch [-Wswitch]
2024-04-28T07:30:02.2997694Z  5970 |         switch (item->endText()->align().horizontal) {
2024-04-28T07:30:02.3109675Z       |                ^
```

**Review by cbjeukendrup — APPROVED** [review]

**Comment by cbjeukendrup** [comment]
> Should the end text then also use the 'gap between text and line' property? currently there is no distance added at all

Yes, this makes sense to me. Doubtlessly, the next thing people will ask for is separate controls for begin/continue/end text gap, but that would be a separate feature request.

**Review by oktophonie — APPROVED** [review]
