### PR TITLE
[MU4] fix #8569 fix crash when switching between parts

### LINKED ISSUE #8569: [MU4 Issue] Crash if create a new part and switch to Main Score tab
**Describe the bug**
Crash if create a new part and switch to Main Score tab

**To Reproduce**
1 Open Parts dialog
2 Create New Part with default name
3 Switch to Main Score (on the score view)

**Expected behavior**
Main score should be visible

**Screenshots**
https://user-images.githubusercontent.com/71372310/124885145-a42a4e80-dfdb-11eb-819b-c5ffec9dbf1d.mp4

**Desktop (please complete the following information):**
Windows 10

### PR DESCRIPTION
**Pull request by wizofaus**
Resolves: https://github.com/musescore/MuseScore/issues/8569

Fixes crashes that can happen when callbacks get uninstalled while enumerating/executing them
 
- [ x ] I signed [CLA](https://musescore.org/en/cla)
- [ x ] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [ x ] I made sure the code compiles on my machine
- [ x ] I made sure there are no unnecessary changes in the code
- [ x ] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [ x ] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [ x ] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

File: thirdparty/deto_async/async/internal/abstractinvoker.cpp [hunk 1]
```diff
@@ -32,6 +33,10 @@ void AbstractInvoker::invoke(int type, const NotifyData& data)
     CallBacks callbacks = it->second;
 
     for (const CallBack& c : callbacks) {
+        if (!it->second.containsReceiver(c.receiver)) {
+            qDebug("Skipping removed receiver");
```
Comment (wizofaus) [inline thirdparty/deto_async/async/internal/abstractinvoker.cpp:37]: For the case callback uninstalls another when an Asyncable is deleted, e.g. during InspectorListModel::removeUnusedModels (called by setElementList, called from a currentNotationChanged callback).

**Review by igorkorsukov — APPROVED** [review]
