### PR TITLE
Fix #17638, ensure transpose dialog allows transposing just chord symbols

### LINKED ISSUE #17638: Chord symbols can't be transposed separately from its whole measure
### Issue type

Other type of issue

### Bug description

For now chord symbols can be transposed only when selecting whole measure with notes and chords and applying transposition 

### Steps to reproduce

1. Open the gp file 
[Layers, chords and meta.gp.zip](https://github.com/musescore/MuseScore/files/11511361/Layers.chords.and.meta.gp.zip)
2. Select a chord symbol
3. Set transposition  (e.g. to major second) and click Ok button
4. Pay attention to the symbol

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/101250347/5493c3e3-553b-486b-86f3-8ebf0f6ffa06

### MuseScore Version

MuseScore 4.1

### Regression

No.

### Operating system

macOS 13

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by wizofaus**
Resolves: #17638

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

File: src/notation/view/widgets/transposedialog.cpp [hunk 1]
```diff
@@ -52,7 +52,10 @@ TransposeDialog::TransposeDialog(QWidget* parent)
     bool rangeSelection = selection()->isRange();
     setEnableTransposeKeys(rangeSelection);
     setEnableTransposeToKey(rangeSelection);
-    setEnableTransposeChordNames(rangeSelection);
+    bool hasChordNames = std::any_of(selection()->elements().begin(), selection()->elements().end(), [](EngravingItem* item) {
+        return item->isHarmony();
+    });
+    setEnableTransposeChordNames(hasChordNames);
```
Comment (wizofaus) [inline src/notation/view/widgets/transposedialog.cpp:58]: would have been safe to simply always call with true, but this is a bit more sophisticated.  The underlying transpose logic works fine as is.

Comment (cbjeukendrup) [inline src/notation/view/widgets/transposedialog.cpp:58]: Couple of details:
- I'd create a local var for `selection()->elements()`
- hasChordNames -> hasChordSymbols
- could use const iterators
```suggestion
    bool rangeSelection = selection()->isRange();
    const std::vector<EngravingItem*>& elements = selection()->elements();
    setEnableTransposeKeys(rangeSelection);
    setEnableTransposeToKey(rangeSelection);
    bool hasChordSymbols = std::any_of(elements.cbegin(), elements.cend(), [](EngravingItem* item) {
        return item->isHarmony();
    });
    setEnableTransposeChordNames(hasChordSymbols);
```

Comment (wizofaus) [reply src/notation/view/widgets/transposedialog.cpp:58]: This is code that I assume will be replaced soon enough with a qml-based dialog. As it is, it would have been quite adequate just to have checkbox always checked/enabled, it doesn't do any harm.  And I deliberately called it "hasChordNames" to make the purpose clear (there are chord names present because there "harmony" elements exist in the selection).

**Comment by zacjansheski** [comment]
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/17638 FIXED

File: src/notation/view/widgets/transposedialog.cpp (hunk 1 above)
Comment (wizofaus) [reply src/notation/view/widgets/transposedialog.cpp:58]: (BTW, what do you mean by const iterators? Would I would like to do is use an iterator that points to a const Engraving* item, but I'm not entirely sure how to do that...)

Comment (cbjeukendrup) [reply src/notation/view/widgets/transposedialog.cpp:58]: > if I use cbegin()/cend(), surely it should be `[](const Engraving* item)`?

No; it would rather be `[](const (EngravingItem*)& item)` instead of `[]((EngravingItem*)& item)` (not sure if parentheses in type names are even valid, but this is just for illustration). I.e. since it's a list of pointers, the `const`-ness would apply to the pointers themselves and not to their pointees.

But by not writing the type as a reference but as a copy, which is fine for pointers, it's just a copy and we don't need to worry about whether the reference was const or not.

Still, using `[](const Engraving* item)` is possible anyway (even with non-const iterators) and makes sense in this case, to make clear that the lambda won't modify `item`.

And yes, such changes won't require re-testing.

My point about `chordNames` was that the synonym `chordSymbols` would make more sense because we use that terminology everywhere (except where we use "harmony").
