### PR TITLE
fix #10674 - ensure "select similar in range" and "select dialog" menu options work as expected

### LINKED ISSUE #10674: [MU4 Issue] Select submenu missing from context menu if range selection present
The context menu that appears on right-click an element is missing the "Select" submenu if a range selection is present.  This is an key regression, since losing that menu negates the ability to ever use the "Select: similar in the range" item that is normally present when there is no range, or to use the dialog.  BTW, do we really need the word "the" in "similar in the range"?  And if so, maybe we should add it "similar in same staff"?

To reproduce:

1. Make a range selection
2. Right-click a note

Result: contextual menu is missing the "Select" submenu

### PR DESCRIPTION
**Pull request by wizofaus**
Resolves: [*(direct link to the issue)*](https://github.com/musescore/MuseScore/issues/10674)

A number of behaviours around "select similar in range" and the "select dialog" weren't correct.

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

File: src/engraving/libmscore/score.cpp [hunk 1]
```diff
@@ -3345,7 +3345,7 @@ void Score::selectAdd(EngravingItem* e)
     SelState selState = _selection.state();
 
     if (_selection.isRange()) {
-        select(0, SelectType::SINGLE, 0);
```
Comment (wizofaus) [inline src/engraving/libmscore/score.cpp:3348]: this could have never done anything useful...

File: src/notation/inotationinteraction.h [hunk 2]
```diff
@@ -268,6 +268,8 @@ class INotationInteraction
 };
 
 using INotationInteractionPtr = std::shared_ptr<INotationInteraction>;
+
+EngravingItem* contextItem(INotationInteractionPtr);
```
Comment (wizofaus) [inline src/notation/inotationinteraction.h:272]: free function because C++ doesn't suppose extension methods...

File: src/notation/view/notationcontextmenumodel.cpp [hunk 3]
```diff
@@ -166,6 +165,8 @@ MenuItemList NotationContextMenuModel::makeElementItems()
 
     if (isSingleSelection()) {
         items << makeMenu(qtrc("notation", "Select"), makeSelectItems());
+    } else if (canSelectSimilarInRange()) {
+        items << makeMenu(qtrc("notation", "Select"), MenuItemList { makeMenuItem("select-similar-range"), makeMenuItem("select-dialog") });
     }
```
Comment (wizofaus) [inline src/notation/view/notationcontextmenumodel.cpp:170]: this might not be quite right actually, the select-dialog should probably be available even if there's a list selection (multiple individual elements selected) and you right-click on an element?

File: src/notation/view/widgets/selectnotedialog.cpp [hunk 4]
```diff
@@ -234,39 +234,38 @@ void SelectNoteDialog::apply() const
         return;
     }
 
-    EngravingItem* selectedElement = interaction->selection()->element();
+    EngravingItem* selectedElement = contextItem(interaction);
     if (!selectedElement) {
         return;
     }
 
-    FilterElementsOptions options = noteOptions();
```
Comment (wizofaus) [inline src/notation/view/widgets/selectnotedialog.cpp:242]: in reference-based languages (C#/Java etc.) this would have worked fine, but in C++ it's a slice!

File: src/notation/view/widgets/selectnotedialog.cpp [hunk 5]
```diff
@@ -234,39 +234,38 @@ void SelectNoteDialog::apply() const
...
+    FilterNotesOptions options = noteOptions();
 
     std::vector<EngravingItem*> elements = notationElements->elements(options);
     if (elements.empty()) {
         return;
     }
+    if (isInSelection()) {
```
Comment (wizofaus) [inline src/notation/view/widgets/selectnotedialog.cpp:248]: OK so all this code is the same as that in selectdialog.cpp - but a) it was already like that, I just had to add more duplicate code b) I assume this will be rewritten to use QtQuick/QML at some point.

**Comment by bkunda** [comment]
I am testing this PR now and will provide comments here

**Comment by bkunda** [comment]
Have tested this on Mac.
I like how the context menu options are now...well, contextual! (I.e. only the options relevant to the selection are shown). My only suggestion/request would be a slight tweak to the microcopy:

- Select > Similar
- Select > Similar on this staff
- Select > Similar in this range
- Select > More...

I don't think we need the repetition of the word "Select: xxx", and the label "Select dialog" is quite confusing (are we selecting a dialog?)

As far as the dialog interactions themselves go, it all seems to work as expected, although I can't figure out the "Action" section, in particular the "Add to selection", which seems to suggest that whatever the selection will be as a result of this dialog will be added to an existing selection, which I can't seem to get to work. Anyway, this might be more an interaction design issue with the existing dialog itself, and I'm not going to worry too much about it in the grand scheme of things at this stage.

One question @wizofaus: can these dialogs be accessed in any way other than via the context menu? 

Thanks so much for putting this together. @wizofaus if you can please fix up the menu labels I'll then ping one of our devs for a review soon :-)

**Comment by jeetee** [comment]
"Add to selection" is usually used when starting from a list selection rather than a range selection (if not, the end result will become a list selection of all that was in the range + the additional selected elements).

These different select options in MU3 can be triggered either via context menu or with a (non-default set) shortcut.

**Comment by wizofaus** [comment]
> Have tested this on Mac. I like how the context menu options are now...well, contextual! (I.e. only the options relevant to the selection are shown). My only suggestion/request would be a slight tweak to the microcopy:
> 
> * Select > Similar
> * Select > Similar on this staff
> * Select > Similar in this range
> * Select > More...
> 
> I don't think we need the repetition of the word "Select: xxx", and the label "Select dialog" is quite confusing (are we selecting a dialog?)
> 

I agree the menu labels seem odd, but I assume that was following some initial design (as it's different to v3).  If @Tantacrul is happy with your suggestion (it's essentially going back to what v3 had), I'm all for it.

In principle all these commands can be mapped to shortcut keys but for whatever reason they're not available currently (at least, "select similar in range" wasn't), and as I explained elsewhere there's a problem because at least that command and "select dialog" (select more...) depend on the last clicked-on element if there's more than 1 element selected.
But from memory they didn't work via shortcut keys in v3 either.

**Comment by wizofaus** [comment]
So I can easily change the sub-menu items to just have the text "Similar", "Similar on staff" etc. as requested - there's just a slight risk that in future if these items get moved elsewhere or if we allow users to customize where they're shown, they might be not make so much sense.
image


The next problem is that now that I've added support for accessing "Select > More..." when a *list* of individual elements are selected, the problem is you can't right-click on an individual element that's part of the list without deselecting it.  So if you've carefully selected 5 or 6 notes holding down CTRL, then want to use one of them as a reference point for adding/subtracting to the selection, right-clicking on it even while still holding down CTRL will deselect it.  I would say this behaviour is unexpected and doesn't match what either v3 or most other windows apps do.  I'd say that's out of scope for this issue, but there is another similar one I'll put a comment on.

**Comment by jeetee** [comment]
I agree that the list selection being dropped can be considered a separate issue; filed as #11008

**Comment by wizofaus** [comment]
Ok have pushed with menu labels changed, "select > more" now works when there's a list selection, and have hidden the unused "search in selection" radio button.

**Comment by bkunda** [comment]
> So I can easily change the sub-menu items to just have the text "Similar", "Similar on staff" etc. as requested - there's just a slight risk that in future if these items get moved elsewhere or if we allow users to customize where they're shown, they might be not make so much sense. image

Thanks for this. I'm not too worried about this because it's something we'll have to deal with if we re-design this feature.

**Comment by bkunda** [comment]
> The next problem is that now that I've added support for accessing "Select > More..." when a _list_ of individual elements are selected, the problem is you can't right-click on an individual element that's part of the list without deselecting it.

Yes this is a problem, and I now see you've already created a new PR to address it, so thank you!

**Comment by bkunda** [comment]
> Ok have pushed with menu labels changed, "select > more" now works when there's a list selection, and have hidden the unused "search in selection" radio button.

I've just checked this latest build on Mac and the labels still need correcting please:

"Similar in the same staff" should read "Similar on this staff"
"Similar in the range" should read "Similar in this range"

 Great that the "More" option now works on list selections! 🙏🏻

**Comment by Jojo-Schmitz** [comment]
Some simple codestyle fixes needed

**Comment by wizofaus** [comment]
BTW it turns out "Select > similar" doesn't work for slurs (and other similar items) when the grip handles are showing.  Looking into it though it's probably not strictly related to anything here.

**Comment by bkunda** [comment]
> BTW it turns out "Select > similar" doesn't work for slurs (and other similar items) when the grip handles are showing. Looking into it though it's probably not strictly related to anything here. However it is a trivial fix, might as well just add to this one seeing as it's related.

Good spot. I was going to suggest a separate issue, but seeing as how you're fixing it here, that saves work for everyone!
Many thanks 🙂

**Comment by RobFog** [comment]
Rebase needed.

**Comment by wizofaus** [comment]
I don't know what the hold up with getting this merged was. I'd rather hand it over to the core team TBH.

**Comment by wizofaus** [comment]
I did just re-test this after the rebase and it appears to be working fine...

**Comment by Tantacrul** [comment]
@bkunda - perhaps one last test + confirmation before recommending merge?

**Comment by bkunda** [comment]
Tested on MacOS. FIXED. 👍🏻

File: src/notation/internal/notationuiactions.cpp [hunk 6]
```diff
@@ -256,22 +256,22 @@ const UiActionList NotationUiActions::m_actions = {
...
     UiAction("select-similar-range",
              mu::context::UiCtxNotationOpened,
-             QT_TRANSLATE_NOOP("action", "Select: similar in the range"),
+             QT_TRANSLATE_NOOP("action", "Similar in this range"),
              QT_TRANSLATE_NOOP("action", "Select all similar elements in the range selection")
              ),
     UiAction("select-dialog",
              mu::context::UiCtxNotationOpened,
-             QT_TRANSLATE_NOOP("action", "Select dialog"),
+             QT_TRANSLATE_NOOP("action", "More..."),
```
Comment (Jojo-Schmitz) [inline src/notation/internal/notationuiactions.cpp:274]: Can we please have a real ellipsis here, a single 3-dot glyph rather than 3 single e dots?

Comment (Jojo-Schmitz) [reply src/notation/internal/notationuiactions.cpp:274]: See #11506
