### PR TITLE
Fix #21300: Correct tie positoning for dotted slashed notes

### LINKED ISSUE #21300: Incorrect tie position on dotted notes with slash noteheads
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

If a tie ends on a downstem dotted note, and that note has a slash head (e.g., when using rhythmic slash notation), the tie ends at the dot instead of the notehead.

### Steps to reproduce

1. Enter a half note tied to a dotted quarter
2. Change the notehead of the dotted quarter to slash (using Properties or Tools / Toggle rhythmic slash notation)

Result: the endpoint of the tie moves so that it extends to the dot instead of ending at the notehead.

Works as expected prior to 4.2, also works as expected for upstem notes.

### Screenshots/Screen recordings

image

### MuseScore Version

OS: Debian GNU/Linux 11 (bullseye), Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230938, revision: github-musescore-musescore-d757433

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Linux / Debian 11

### Additional context

Educated guess - might have been caused in https://github.com/musescore/MuseScore/pull/20239, perhaps where note width & center are calculated?  @mike-spa

### PR DESCRIPTION
**Pull request by XiaoMigros**
Resolves: #21300

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [ ] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

File: src/engraving/rendering/dev/slurtielayout.cpp [hunk 1]
```diff
@@ -1656,7 +1656,11 @@ double SlurTieLayout::noteOpticalCenterForTie(const Note* note, bool up)
         double singleSlashWidth = note->symBbox(SymId::noteheadSlashHorizontalEnds).width();
         double noteWidth = note->width();
         double center = 0.20 * note->spatium() + 0.5 * (noteWidth - singleSlashWidth);
-        return up ? note->shape().right() - center : note->shape().left() + center;
+        Shape noteShape =  note->shape();
+        noteShape.remove_if([&](ShapeElement& s) {
+            return s.item()->pos().x() + s.item()->width() > note->pos().x() + note->width();
```
Comment (MarcSabatella) [inline src/engraving/rendering/dev/slurtielayout.cpp:1661]: Yikes!  I was hoping it wouldn't need to be something so ugly.  There's no way to just get the note width excluding the dot more directly?

Comment (XiaoMigros) [reply src/engraving/rendering/dev/slurtielayout.cpp:1661]: This method is a little more foolproof and will account for elements other than dots as well (such as bends/chordlines perhaps)

Comment (XiaoMigros) [reply src/engraving/rendering/dev/slurtielayout.cpp:1661]: @mike-spa do you think `noteShape.removeTypes({ ElementType::NOTEDOT });` would suffice, instead?

Comment (MarcSabatella) [reply src/engraving/rendering/dev/slurtielayout.cpp:1661]: That's definitely a good goal; I'm just surprised there isn't a more straightforward way to get what we want, like just dealing with the notehead directly.  But given that it's a special case anyhow, I'm happy with whatever gets the job done!

Comment (cbjeukendrup) [inline src/engraving/rendering/dev/slurtielayout.cpp:1661]: I'm not 100% sure if the calculation is correct. As far as I know, the top left point of the bounding box is specified relatively to `pos()`.
So it seems correct when the top left point of the bounding box is `(0,0)`, but otherwise not. 
Maybe `s.item()->pos().x() + s.item()->bbox().right()` (and same for `note`) does the job? Please correct me if I'm wrong.

Comment (mike-spa) [inline src/engraving/rendering/dev/slurtielayout.cpp:1661]: Oof, no please 😅 I think it was an error on my part to use `note->shape()` for this, because the `shape()` method includes the sub-elements (e.g. note dots), but here we should be looking exclusively at the note _head_ (so it's silly to use `shape()` to include the sub-elements and then remove them). There is a specific method `Note::headWidth` which I think should be useful here. If that doesn't work, another possibility is to get the symId and use `symWidth`. Let me know if you find a way, otherwise I'll look into it myself :)

Comment (XiaoMigros) [reply src/engraving/rendering/dev/slurtielayout.cpp:1661]: Good to know that ditching the shape approach should work! Thanks for reviewing, I'll try to find a better solution...

Comment (MarcSabatella) [reply src/engraving/rendering/dev/slurtielayout.cpp:1661]: Thanks for confirming my initial sense!  My thought was that instead of note->shape().right() it should be note->pos()->x() + note->headWidth().  And then add or subtract center as before.

I guess note->shape()->left() might not be good either and should perhaps just be note->pos()->x().  I tried to come up with a case where this might matter.  Here's 4.2.1:

image

vs 4.1:

image

Comment (XiaoMigros) [reply src/engraving/rendering/dev/slurtielayout.cpp]: I decided to use the `bbox` method of the notes, I think that should be the most foolproof.

**Review by mike-spa — APPROVED** [review]

**Comment by MarcSabatella** [comment]
@bkunda can this be added to 4.3.1?  The bug here was a pretty serious regression in 4.2 that really impacts a lot of jazz scores, and I really hoped to see this fix included in 4.3.  The fix is very safe, only affecting the specific case of ties on dotted notes with slash heads.

**Comment by cbjeukendrup** [comment]
@MarcSabatella Here we go: https://github.com/musescore/MuseScore/pull/22899

**Comment by MarcSabatella** [comment]
Oh yes, thank you so much!
