### PR TITLE
[MU4] Fix #10593 Fix drag-and-drop of slurs

### LINKED ISSUE #10593: [MU4 Issue] Slur is positioned in a wrong place when added from the palettes by drag 'n' drop
https://user-images.githubusercontent.com/90187801/154445339-abf86105-9933-4ae7-95bc-d6006e4b0dd3.mp4

**Platform information**
 macOS, Windows, Linux

**Additional context**
Doesn't occur when adding slur with shortcut or adding slur from the palette by NOT drag 'n' drop
Doesn't occur in **MU3**

### PR DESCRIPTION
**Pull request by asattely**
Resolves: https://github.com/musescore/MuseScore/issues/10593

Slurs can be added by clicking on the palette or pressing the hotkey, but dragging and dropping slurs wasn't working. This PR fixes that, but I'm not 100% confident about my fix being 'correct'. I would love some input about where this fix should have gone, if I put it in the wrong place.

### CODE REVIEW

**Comment by DmitryArefiev** [comment]
Tested #10593 on Win10, Mac12, LinuxMint 20.2 - FIXED

**Review by oktophonie — APPROVED** [review]

File: src/notation/internal/notationinteraction.cpp [hunk 1]
```diff
@@ -1111,6 +1112,7 @@ bool NotationInteraction::drop(const PointF& pos, Qt::KeyboardModifiers modifier
     case ElementType::VIBRATO:
     case ElementType::PALM_MUTE:
     case ElementType::HAIRPIN:
+        //case ElementType::SLUR:
```
Comment (RomanPudashkin) [inline src/notation/internal/notationinteraction.cpp:1115]: It is better to remove all commented code. There is no need for it

File: src/notation/internal/notationinteraction.cpp [hunk 2]
```diff
@@ -1240,6 +1242,17 @@ bool NotationInteraction::drop(const PointF& pos, Qt::KeyboardModifiers modifier
         accepted = true;
     }
     break;
+    case ElementType::SLUR:
+    {
+        EngravingItem* el = dropTarget(m_dropData.ed);
```
Comment (RomanPudashkin) [inline src/notation/internal/notationinteraction.cpp:1247]: I'm curious how this worked before (for example, in MU3)... Because there may be a more general problem (for a lot of elements, not just slurs)

Comment (asattely) [reply src/notation/internal/notationinteraction.cpp:1247]: I looked into it and the MU3 code is completely different as far as I can tell. It looks like this code was written for MU4, and I wonder if dragging and dropping slurs worked at all since the move.

This problem could definitely affect other things but I made sure to test every spanner in the palette and they all seemed to work fine! If other problems are found we know where to look for the solution at least.

**Review by RomanPudashkin — APPROVED** [review]
