### PR TITLE
Fix #26353: Broken layout reset for Muse Sampler drumsets (percussion panel)

### LINKED ISSUE #26353: Percussion panel - reset layout doesn't work with Muse Sounds drumsets
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

1. Create a score with a percussion instrument
2. Switch to a Muse Sounds drumset in the mixer
3. Click Layout -> Reset layout in the percussion panel toolbar
4. Layout is incorrect

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/527932dd-77df-43ad-8020-4984d6d58098

### What is the latest version of MuseScore Studio where this issue is present?

Master

### Regression

No.

### Operating system

All

### Additional context

I am reasonably certain that the cause of this is `PercussionPanelModel::resetLayout` using the current `Instrument's` ID to resolve an `InstrumentTemplate`. This is a problem because the ID won't necessarily correlate to the sound chosen in the mixer.

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mathesoncalum**
Resolves: #26353

Slightly different approaches are required for "basic" and Muse Sampler drumsets when resolving the default layout.

### CODE REVIEW

File: src/notation/view/percussionpanel/percussionpanelmodel.cpp [hunk 1]
```diff
@@ -514,6 +512,45 @@ void PercussionPanelModel::resetLayout()
     undoStack->commitChanges();
 }
 
+Drumset PercussionPanelModel::defaultFluidDrumset() const
```
Comment (RomanPudashkin) [inline src/notation/view/percussionpanel/percussionpanelmodel.cpp:515]: The word "Fluid" should be dropped from the name

File: src/notation/view/percussionpanel/percussionpanelpadlistmodel.h [hunk 2]
```diff
@@ -77,7 +77,7 @@ class PercussionPanelPadListModel : public QAbstractListModel, public muse::Inje
 
     QList<PercussionPanelPadModel*> padList() const { return m_padModels; }
 
-    mu::engraving::Drumset constructDefaultLayout(const engraving::Drumset* templateDrumset) const;
+    mu::engraving::Drumset constructDefaultLayout(const engraving::Drumset templateDrumset) const;
```
Comment (RomanPudashkin) [inline src/notation/view/percussionpanel/percussionpanelpadlistmodel.h:80]:
```suggestion
    mu::engraving::Drumset constructDefaultLayout(const engraving::Drumset& templateDrumset) const;
```

**Review by RomanPudashkin — APPROVED** [review]

**Comment by zacjansheski** [comment]
Tested on MacOS 15, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/26353 FIXED
