### PR TITLE
[MU4] fix #10117: Unable to select a single object in range selection

### LINKED ISSUE #10117: [MU4 Issue] Unable to select a single object in range selection (missing MU3 functionality)
**To Reproduce**
1. Create a range selection (select whole bar with notes) 
2. Click on a single note - **nothing happens** (range selection remains)

See video to compare MU3 and MU4

https://user-images.githubusercontent.com/90187801/146401628-dd1fc5a8-1a14-4baa-9c38-ffac1d2c52b8.mp4

**Desktop**
 - OS: all

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Resolves: https://github.com/musescore/MuseScore/issues/10117

### CODE REVIEW

File: src/notation/view/notationviewinputcontroller.cpp [hunk 1]
```diff
@@ -501,20 +501,13 @@ void NotationViewInputController::mousePressEvent(QMouseEvent* event)
...
-    }
+    bool result = true;
 
-    Qt::MouseButton button = event->button();
-
-    bool result = hitElement && !hitElement->selected();
-
-    if (button == Qt::MouseButton::RightButton && result) {
+    if (event->button() == Qt::MouseButton::RightButton) {
         result &= !viewInteraction()->selection()->range()->containsPoint(clickLogicPos);
```
Comment (Eism) [inline src/notation/view/notationviewinputcontroller.cpp:511]: better 'result =' instead of 'result &='

**Review by Eism — APPROVED** [review]

File: src/notation/view/notationviewinputcontroller.cpp (hunk 1 above)
Comment (RomanPudashkin) [reply src/notation/view/notationviewinputcontroller.cpp]: fixed

**Comment by DmitryArefiev** [comment]
Tested #10117 on Win10, Mac12, LinuxMint 20.2 - FIXED      

Please merge into master
