### PR TITLE
Fix #30423: lyrics disappear after changing a note 

### LINKED ISSUE #30423: Changing note shouldn't erase lyric
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. Add a note
2. Add a lyric to it (Ctrl + L then type a lyric in)
3. Select the note
4. Press a letter A-G to replace the note with a different one
5. The lyric disappears

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/5da39202-5b13-4cd3-8939-d6a687146dc4

### In which versions of MuseScore Studio is this issue present?

Nightly

### Regression

No.

### Operating system

macOS 15

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by raquelviana878**
Resolves: #30423 

Previously, when writing a lyric to a note (by selecting a note and entering a lyric by pressing Ctrl + L), when the note was repitched (pressing A–G on the keyboard), the code would remove the original ChordRest object (which represents the note or rest in the score). However, any lyrics attached to that ChordRest were not explicitly preserved before removal. As a result, when the original note was deleted and a new one created, the lyrics were lost because they were still parented to the deleted object and not reattached to the new one.

The fix is as follows: before removing or replacing the original ChordRest, the code now iterates through any attached lyrics, creates deep copies of them using Factory::copyLyrics, and stores them in a temporary vector (lyricsToPreserve). After the new ChordRest is created, the preserved lyrics are reattached to it by setting their parent and track to the new ChordRest, and adding them back to the score with undoAddElement. Additionally, a flag (lyricsPreserved) ensures that lyrics are only reattached once, preventing duplication if multiple elements are created in the loop. If no lyrics were preserved, the temporary vector is cleaned up to avoid memory leaks. This ensures that lyrics are not lost or duplicated when a note is repitched.

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/muse_framework/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [x] I created a unit test or vtest to verify the changes I made (if applicable)

## Summary by CodeRabbit

* **Bug Fixes**
  * Lyrics now stay attached when a note is repitched (no duplication on repeated repitches).
  * Replacing a note with a rest correctly drops lyrics.
  * Multiple lyrics and their formatting are preserved through repitch operations.
  * Lyrics survive undo/redo of repitch actions without loss or duplication.
  * Repitching in another voice/track does not affect lyrics in voice 1.
  * No user-visible API changes.

### CODE REVIEW

File: src/engraving/editing/cmd.cpp [hunk 1]
```diff
@@ -1186,6 +1203,18 @@ Segment* Score::setNoteRest(Segment* segment, track_idx_t track, NoteVal nval, F
...
             undoAddCR(ncr, measure, tick);
+
+            if (shouldPreserveLyrics && !lyricsPreserved) {
+                // reattach the preserved lyrics to the first replacement ChordRest
+                // to ensure they are not duplicated during subsequent operations
+                lyricsPreserved = true;
+                for (Lyrics* lyric : lyricsToPreserve) {
+                    lyric->setParent(ncr);
+                    lyric->setTrack(ncr->track());
+                    undoAddElement(lyric);
```
Comment (miiizen) [inline src/engraving/editing/cmd.cpp]: And use `undoChangeParent` here
```suggestion
                    undoChangeParent(lyric, ncr, ncr->staffIdx());
```

File: src/engraving/editing/cmd.cpp [hunk 2]
```diff
@@ -1104,6 +1104,23 @@ Segment* Score::setNoteRest(Segment* segment, track_idx_t track, NoteVal nval, F
     Tuplet* tuplet = cr ? cr->tuplet() : nullptr;
     Measure* measure = nullptr;
     bool targetIsRest = cr && cr->isRest();
+
+    // preserve lyrics before the ChordRest is removed or replaced
+    std::vector<Lyrics*> lyricsToPreserve;
+    bool shouldPreserveLyrics = false;
+    if (!isRest && cr) {
+        auto& existingLyrics = cr->lyrics();
```
Comment (miiizen) [inline src/engraving/editing/cmd.cpp]: We don't need to make a deep copy of these items. At this point we should copy the vector of lyrics (ie. `lyricsToPreserve = cr->lyrics()`.

**Comment by raquelviana878** [comment]
@miiizen Thank you. I made those changes in the newest commit.

File: src/engraving/editing/cmd.cpp [hunk 3]
```diff
@@ -1239,6 +1259,9 @@ Segment* Score::setNoteRest(Segment* segment, track_idx_t track, NoteVal nval, F
     if (tie) {
         connectTies();
     }
+    if (!lyricsPreserved) {
```
Comment (miiizen) [inline src/engraving/editing/cmd.cpp]: And yes, we can get rid of this!

**Comment by raquelviana878** [comment]
@miiizen Thank you once again. That change is made in the newest commit.

**Comment by davidstephengrant** [comment]
Tested and approved on Ubuntu 24.04.4 LTS.
