### PR TITLE
[MU4] fix #8507 Fix crashes when searching palettes

### LINKED ISSUE #8507: [MU4 Issue] Crashes searching for palettes and closing scores
**Describe the bug**
Current MU4 build crashes when searching for palettes and when closing a score

**To Reproduce**
1. Create a new score
2. Search for a palette, or close the score (using X button)
3. Crash

**Expected behavior**
Preferably no crash

**Screenshots**

**Desktop (please complete the following information):**
Windows 10

**Additional context**
Stack trace for first crash was in 
BracketItem::setProperty/Score::setLayoutAll - BracketItem was invalid
For second was 
PlaybackController::setCurrentSequence() - notationPlayback() was empty (null).

### PR DESCRIPTION
**Pull request by wizofaus**
Resolves: https://github.com/musescore/MuseScore/issues/8507

Previous fix wasn't right

- [ x ] I signed [CLA](https://musescore.org/en/cla)
- [ x ] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [ x ] I made sure the code compiles on my machine
- [ x ] I made sure there are no unnecessary changes in the code
- [ x ] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [ x ] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [ x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

File: src/palette/internal/palette/palettecreator.cpp [hunk 1]
```diff
@@ -1099,7 +1099,7 @@ PalettePanel* PaletteCreator::newBracketsPalettePanel()
             { BracketType::LINE,   QT_TRANSLATE_NOOP("palette", "Line") } }
     };
 
-    static Staff bracketItemOwner(nullptr);
+    static Staff bracketItemOwner(gscore);
```
Comment (wizofaus) [inline src/palette/internal/palette/palettecreator.cpp:1102]: BTW I did try adding a staff to gscore if there wasn't one already and using that which avoids the need for another global variable here, but while it appeared to work OK, it's about 5 more lines of code and as it happens gscore is a global variable anyway, that's never freed (sure, the O/S will reclaim the memory for the MuseScore application, but what if another process repeatedly loads/unloads a dynamic link library that links to the engraving library?)

Comment (igorkorsukov) [reply src/palette/internal/palette/palettecreator.cpp:1102]: The time will come soon. when we put it all in order :)
