### PR TITLE
Fix #13741 - ensure changes to multi-measure rests trigger necessary layout in continuous/linear view

### LINKED ISSUE #13741: [MU4 Issue] In horizontal continuous view, writing into a multi-measure rest temporarily hides the rest
**Describe the bug**
When writing notes into a multi-measure rest while in horizontal continuous view, the measure with the multi-measure rest disappears until either continuous mode or multi-measure rests are deactivated.

**To Reproduce**
1. Create an empty score
2. Enable horizontal continuous view
3. Press `M` to enable multi-measure rests
4. Write something into the rest
5. The multi-measure rest is replaced by a single measure

**Expected behavior**
The same behaviour as in page view: The multi-measure rest stays but the number above the rest decreases.

**Video**
https://user-images.githubusercontent.com/12451842/195648959-47f902f7-6861-49d2-aef1-93e7d9aa9d88.mp4

**Platform information**
 - OS: Windows 10
 - MuseScore version: Tested on both the public alpha, and nightly version `2022-10-10 04:55`

### PR DESCRIPTION
**Pull request by wizofaus**
Resolves: #13741

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

File: src/engraving/rendering/dev/scorehorizontalviewlayout.cpp [hunk 1]
```diff
@@ -300,8 +300,8 @@ void ScoreHorizontalViewLayout::collectLinearSystem(LayoutContext& ctx)
                 MeasureLayout::removeSystemTrailer(m, ctx);
             }
 
-            if (m->tick() >= ctx.state().startTick() && m->tick() <= ctx.state().endTick()) {
-                // for measures in range, do full layout
+            if ((m->tick() >= ctx.state().startTick() && m->tick() <= ctx.state().endTick()) || m->mmRestCount()) {
+                // for measures in range (or multi-measure rests), do full layout
```
Comment (wizofaus) [inline src/engraving/rendering/dev/scorehorizontalviewlayout.cpp:304]: Not that checking `m->mmRest()` doesn't work, it's still `nullptr` at this point.  And while this may trigger more layout than would otherwise be necessary, I wouldn't think it's expected users would commonly need to make changes to MM rests in continuous view (I don't see any performance issues with the testing I did).

File: src/engraving/rendering/dev/measurelayout.cpp [hunk 2]
```diff
@@ -796,6 +796,9 @@ void MeasureLayout::createMultiMeasureRestsIfNeed(MeasureBase* currentMB, Layout
             }
             firstMeasure->setMMRestCount(0);
             ctx.mutState().setMeasureNo(mno);
+            if (lastMeasure->endTick() > ctx.state().endTick()) {
+                ctx.mutState().setEndTick(lastMeasure->endTick());
```
Comment (wizofaus) [inline src/engraving/rendering/dev/measurelayout.cpp:800]: if a multi-measure rest is removed, we need ensure the layout tick range covers all the underlying measures

File: src/engraving/rendering/dev/measurelayout.cpp [hunk 3]
```diff
@@ -855,14 +858,6 @@ void MeasureLayout::layoutMeasure(MeasureBase* currentMB, LayoutContext& ctx)
 
     measure->moveTicks(ctx.state().tick() - measure->tick());
 
-    if (ctx.conf().isLinearMode() && (measure->tick() < ctx.state().startTick() || measure->tick() > ctx.state().endTick())) {
-        // needed to reset segment widths if they can change after measure width is computed
-        //for (Segment& s : measure->segments())
-        //      s.createShapes();
-        ctx.mutState().setTick(ctx.state().tick() + measure->ticks());
-        return;
-    }
```
Comment (wizofaus) [inline src/engraving/rendering/dev/measurelayout.cpp:864]: can't see how this code could ever have done anything useful, and because of this early return the measure widths don't get correctly.

**Review by mike-spa — APPROVED** [review]

**Comment by zacjansheski** [comment]
Rests get offset when writing in Continuous View
(Ignore the MacOS permissions pop-ups)
https://github.com/musescore/MuseScore/assets/69917893/635b5b69-efec-459a-b2c8-15f5393db91e

**Comment by wizofaus** [comment]
Yep, that's a problem!  Investigating.

File: src/engraving/rendering/dev/measurelayout.cpp (hunk 3 above)
Comment (wizofaus) [reply src/engraving/rendering/dev/measurelayout.cpp:864]: Ok, unfortunately the early return *is* needed to prevent whole rests being misplaced (not centred). But there are other cases where it definitely breaks the layout.

**Comment by wizofaus** [comment]
Bit puzzling, one of the changes I made definitely seemed to be necessary to ensure when a 2-measure multi-measure rest got converted into two regular measures it repainted properly, but it was also triggering the issue with incorrect placement of whole rests.  Reverted the change, which fixed the rest placement, but the repainting still seems to be OK.  Could definitely use more testing.

**Comment by zacjansheski** [comment]
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/13741 FIXED
