### PR TITLE
Fix #21294: Style settings reset between scores

### LINKED ISSUE #21294: Style settings page should not be remembered when openning a new score during one MS session
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

_No response_

### Steps to reproduce

1. Open score
2. Open Style dialog
3. Select **Text styles>Title**
4. Click OK and close Style dialog
5. Close score
6. Open another score in the same MS instance (window)
7. Open Style dialog - it opens in **Text styles>Title** page 

**Expected result:** It should open the  default page (Score) for a new score (or specific page if it was triggered by selecting specific element and clicking Style in right click menu, see #20740)

https://github.com/musescore/MuseScore/assets/90187801/a0bc8a6b-5e93-46d7-bf05-83b6660972a4

### Screenshots/Screen recordings

_No response_

### MuseScore Version

4.2.1

### Regression

No.

### Operating system

all

### Additional context

The same in MS3.6.2

### PR DESCRIPTION
**Pull request by nasehim7**
Resolves: #21294 

This change includes:
- When no element is selected in the notation context menu and style menu is called, it shows default “score” setting.
- When score appearance style setting is clicked, shows default “score” setting.
- When style setting is clicked from the format menu, shows default “score” setting.
- No style setting is kept outside a score.

Video: https://github.com/musescore/MuseScore/issues/21294#issuecomment-1968022830

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
But this would have the effect that clicking "Format" > "Style" _never_ remembers the current page and always opens just score. So this change would be equivalent to simply removing the code for remembering the current page, right?

Instead, we want it to be reset at the moment that the user closes a score and opens a different one. I think the best way to achieve this would be to do something in NotationConfiguration (where the current page is stored); simply reset the current page value to an empty QString whenever the current notation project changes.

**Comment by nasehim7** [comment]
Ah yes! absolutely that makes more sense. On it :D

**Comment by nasehim7** [comment]
I see that `void NotationSwitchListModel::closeNotation(int index)` handles the closing of the notation. So inside this method, we can create an editStyleInstance which can call `setCurrentPageCode("score");` to reset the page value. Probably a 2 3 liner change. Also, it seems to me that only closeNotation() is used and not the other ones: `closeAllNotations` and `closeOtherNotations` which means in a single instance of MS, we can only have a single tab, correct? so we don't need to make any changes in any other method. Let me know if my understanding is correct?

**Comment by DmitryArefiev** [comment]
@nasehim7 Tested on Win/Mac

It works when you close the previous score with X using mouse, but **doesn't reset** Style tab when close score with **shortcut (Ctr+W)**


https://github.com/musescore/MuseScore/assets/90187801/6b3b2d40-131e-4dec-adb7-96a03f4b9d61

**Comment by nasehim7** [comment]
Ah I see! Thanks @DmitryArefiev for the catch. I was just going through the code to see how it is handled and it seems  `ShortcutsController::activate` function handles resolving the shortcut into the respective action code which in this case is "file-close" and sends it to `ActionDispatcher()` for taking the action. So just before it is sent to `ActionDispatcher()` we can reset the values of the 'edit-style' but this implementation needs to be done in the 'ShortcutController' with relevant header imported. Not sure if this would be the best approach to tackle this? What's your take on this @cbjeukendrup

**Comment by cbjeukendrup** [comment]
@nasehim7 There are two problems:
- creating an EditStyle instance just to reset the current page code is wasteful. Instead, it would be better to reset the stored value directly. 
- Code for closing a score should not be responsible for a detail like resetting the current style dialog page. Instead, some style-dialog-related object should listen to a notification that is emitted when closing a score, and reset the page in response to that. 

It turns out that both things are somewhat annoying to fix, and that is because the current page index is stored as a static member of EditStyle. Because it's static, there is not one single object that is responsible for it. That is problematic, because you need an object that registers itself for that notification and acts in response to it. 

What I would propose, is that you store the index as a non-static member of NotationConfiguration instead, and create the necessary getters and setters. NotationConfiguration _is_ namely an object that can register itself for notifications. The notification you need is `IGlobalContext::currentProjectChanged`. To find out how to work with it, look how IGlobalContext is accessed in existing code (using the INJECT macro) and search for "currentProjectChanged" in the codebase to see other places where it is used.

**Comment by nasehim7** [comment]
@cbjeukendrup Yes that makes absolute sense. Thanks for providing the direction, Casper. I was as well wondering this approach I did, feels more hacky. I have updated the PR with the asked changes now and here is the test I did on my machine. The last score exit is using the file close shortcut on Mac.

https://github.com/musescore/MuseScore/assets/18035782/00dc4175-b735-4829-b291-469193edab46

I hope the updated changes align well. Let me know your take. I also see that codestyle check failed, let me correct it meanwhile :D

File: src/notation/internal/notationconfiguration.cpp [hunk 1]
```diff
@@ -888,3 +892,27 @@ void NotationConfiguration::setStyleFileImportPath(const io::path_t& path)
...
+    m_lastSubPageRow = value;
+}
+
+void NotationConfiguration::resetStyleIndex()
+{
+    if (context()->currentProject() == nullptr) {
+        setLastPageRow(0);
+        setLastSubPageRow(0);
+    }
+}
```
Comment (nasehim7) [inline src/notation/internal/notationconfiguration.cpp:918]: I think the codestyle failed due to this -> no extra line at the end

File: src/notation/view/widgets/editstyle.cpp [hunk 2]
```diff
@@ -48,6 +48,8 @@
 #include "ui/view/widgetstatestore.h"
 #include "ui/view/widgetutils.h"
 
+#include "internal/notationconfiguration.h"
```
Comment (cbjeukendrup) [inline src/notation/view/widgets/editstyle.cpp:51]: This should not be necessary. Note that `configuration()` returns the configuration as type `INotationConfiguration`, rather than `NotationConfiguration`, so you only need to #include `inotationconfiguration.h`, which is indeed already done in `editstyle.h`.

File: src/notation/inotationconfiguration.h [hunk 3]
```diff
@@ -194,6 +194,14 @@ class INotationConfiguration : MODULE_EXPORT_INTERFACE
...
     virtual io::path_t styleFileImportPath() const = 0;
     virtual void setStyleFileImportPath(const io::path_t& path) = 0;
+
+    virtual int lastPageRow() const = 0;
+    virtual void setLastPageRow(int value) = 0;
+
+    virtual int lastSubPageRow() const = 0;
+    virtual void setLastSubPageRow(int value) = 0;
+
+    virtual void resetStyleIndex() = 0;
```
Comment (cbjeukendrup) [inline src/notation/inotationconfiguration.h:204]: Now that these are in INotationConfiguration, which is quite a widely-used class, their names are a bit too general. I'd recommend making them a bit more specific:
- `styleDialogLastPageIndex()` (and the corresponding setter and related things in `internal/notationconfiguration.h`)
- `styleDialogLastSubPageIndex()` (idem)
- `resetStyleDialogPageIndices()`

That way, it's immediately clear that these methods are about the style dialog, and not about who-knows-what-else.

File: src/notation/internal/notationconfiguration.cpp [hunk 4]
```diff
@@ -888,3 +892,31 @@ void NotationConfiguration::setStyleFileImportPath(const io::path_t& path)
...
+
+void NotationConfiguration::setLastSubPageRow(int value)
+{
+    m_lastSubPageRow = value;
+}
+
+void NotationConfiguration::resetStyleIndex()
+{
+    if (context()->currentProject() == nullptr) {
```
Comment (cbjeukendrup) [inline src/notation/internal/notationconfiguration.cpp:918]: I don't think we need this `if` condition. As far as I can see, it doesn't have much effect, and if there will ever be a way to change from one project directly to another, i.e. skipping the intermediate state of having no open project, then the reset should happen too.

**Review by cbjeukendrup — COMMENTED** [review]
This looks much better now, thanks very much! A few last minor suggestions.

**Comment by nasehim7** [comment]
@cbjeukendrup updated the PR with the requested changes. Hope it looks good now :D

File: src/notation/view/widgets/editstyle.cpp [hunk 5]
```diff
@@ -1141,11 +1141,11 @@ EditStyle::EditStyle(QWidget* parent)
     });
 
     connect(textStyles, &QListWidget::currentRowChanged, this, &EditStyle::textStyleChanged);
-    textStyles->setCurrentRow(s_lastSubPageRow);
+    textStyles->setCurrentRow(configuration()->styleDialogLastPageIndex());
```
Comment (cbjeukendrup) [inline src/notation/view/widgets/editstyle.cpp:1144]:
```suggestion
    textStyles->setCurrentRow(configuration()->styleDialogLastSubPageIndex());
```

**Review by cbjeukendrup — COMMENTED** [review]
Sorry, I spotted one more tiny but somewhat crucial thing :)

**Review by cbjeukendrup — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
Tested #21294 on Win10, Mac13.6, LinuxUbuntu22.04 - **FIXED**    

@nasehim7 Thanks for fixing!
