### PR TITLE
Fix elements collide after set to invisible

### LINKED ISSUE #30355: Making cues invisible in score overrides autoplacement in parts (clashes with barline)
### Issue type

Engraving

### Description with steps to reproduce

1. Add notes in score, set to invisible
2. Untick score-part synchronisation in part
3. Make notes visible in part
4. Notice how the note clashes on the barline or time signature change

### Supporting files, videos and screenshots

Image

### In which versions of MuseScore Studio is this issue present?

4.6.0

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS Sonoma 14.1

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mike-spa**
Resolves: #30355

The bug originated in #29837. I think we've established an implicit convention that the Chord is never set visible/invisible, only its invidivual elements are. Allowing the Chord to be set invisible caused it to not be added to the segment shape and go out of sync with the visibility of its individual elements. I've now made a different solution to the problem the original PR was solving and also prevented the property to be read/written altogether.

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Review by miiizen — APPROVED** [review]

File: src/engraving/rw/write/twrite.cpp [hunk 1]
```diff
@@ -391,6 +391,9 @@ void TWrite::writeProperty(const EngravingItem* item, XmlWriter& xml, Pid pid, b
     if (item->isStyled(pid)) {
         return;
     }
+    if (pid == Pid::VISIBLE && item->isChord()) {
```
Comment (cbjeukendrup) [inline src/engraving/rw/write/twrite.cpp]: I don't _love_ having such a special case in such a general method... is there really not a slightly more confined solution feasible?

Comment (mike-spa) [reply src/engraving/rw/write/twrite.cpp]: Yeah this is not particularly nice. And also not _stricly_ necessary now that I think of it, cause even if we do write this property by mistake (which shouldn't happen now, anyway), it will be neutralized by the check in TRead. Perhaps the nicer solution is to override Chord::getProperty to only return true. That should achieve the same result

**Review by cbjeukendrup — APPROVED** [review]
