### PR TITLE
Fix #18591 crash on dragging note with ornament

### LINKED ISSUE #18591: Crash after clicking and dragging note with ornament
### Issue type

Crash or freeze

### Bug description

_No response_

### Steps to reproduce

1. Open [4.0.2_1_parts_b.zip](https://github.com/musescore/MuseScore/files/12047995/4.0.2_1_parts_b.zip)
2. Go to Part (custom part)
3. On Flute staff, click several times and then drag left right note D5 in measure 2, beat 2 

Also can be reproduced in score with note with ornament but not so quickly

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/65fb55ff-9260-449a-bed5-e54c1d6e8d59

### MuseScore Version

5.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows10

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mike-spa**
Resolves: #18591
Resolves: #18594

### CODE REVIEW

File: src/engraving/layout/v0/tlayout.cpp [hunk 1]
```diff
@@ -3652,6 +3650,19 @@ void TLayout::layout(Ornament* item, LayoutContext& ctx)
...
 
+void TLayout::layoutTrillCueNote(Ornament* item, LayoutContext& ctx)
+{
+    Chord* cueNoteChord = item->cueNoteChord();
+
+    if (!cueNoteChord) {
+        return;
+    }
+
+    Note* cueNote = cueNoteChord->notes().front();
```
Comment (RomanPudashkin) [inline src/engraving/layout/v0/tlayout.cpp:3661]: Never write code like this. Always check for emptiness

Comment (mike-spa) [reply src/engraving/layout/v0/tlayout.cpp:3661]: Sorry, with chords I tend to forget because chords are not allowed to have zero notes (there are several other checks and asserts around the code to prevent that). You're right though, better be safe

File: src/engraving/layout/v0/tlayout.cpp [hunk 2]
```diff
@@ -3634,9 +3634,7 @@ void TLayout::layout(Ornament* item, LayoutContext& ctx)
         return;
     }
 
-    Note* cueNote = cueNoteChord->notes().front();
-    ChordLayout::layoutChords3(ctx.conf().style(), { cueNoteChord }, { cueNote }, item->staff(), ctx);
-    layout(cueNoteChord, ctx);
+    // CAUTION: assumes that cueNoteChord has been already laid out
```
Comment (RomanPudashkin) [inline src/engraving/layout/v0/tlayout.cpp:3637]: Can you call TLayout::layoutTrillCueNote here? This way we will have clearer dependencies in the code and won't need this comment

Comment (mike-spa) [reply src/engraving/layout/v0/tlayout.cpp:3637]: Unfortunately no, because it shouldn't _always_ be called (that's what was causing the crash). Basically, the Ornament layout gets called from two different places, one [here](https://github.com/mike-spa/MuseScore/blob/master/src/engraving/layout/v0/chordlayout.cpp#L1861C13-L1861C44) and the other [here](https://github.com/mike-spa/MuseScore/blob/master/src/engraving/layout/v0/chordlayout.cpp#L1003C13-L1003C37). In the first case, we should also layout the trill cue note, but in the second case we shouldn't (this was the cause of the crash). So I decided to split that part into its own separate function, and call it separately. The only other option would be to pass some bool flag here, which decides whether to call it or not, but that means I have to change the function signature of two layout functions (Articulation and Ornament), so I thought this way worked better.

Comment (RomanPudashkin) [reply src/engraving/layout/v0/tlayout.cpp:3637]: We should not call layoutTrillCueNote here, but have to perform other manipulations on the cueNoteChord geometry (like setPosX)? This is very confusing. Also, this comment is even more misleading because it assumes that we always call layoutTrillCueNote

1. all layout-related code for the cue note should be in one place (layoutTrillCueNote)
2. it should be explicitly called where it's needed and you should avoid such comments assuming that it has already been called somewhere

Comment (mike-spa) [reply src/engraving/layout/v0/tlayout.cpp]: ok, should be better now 👍

File: src/engraving/layout/v0/tlayout.cpp [hunk 3]
```diff
@@ -3602,28 +3602,32 @@ void TLayout::layout(NoteDot* item, LayoutContext&)
 
 void TLayout::layout(Ornament* item, LayoutContext& ctx)
 {
+    if (item->showCueNote()) {
```
Comment (RomanPudashkin) [inline src/engraving/layout/v0/tlayout.cpp:3605]: Why do you need this? This function should work regardless of showCueNote(). This check probably needs to be at a higher level

File: src/engraving/layout/v0/tlayout.cpp [hunk 4]
```diff
@@ -3602,28 +3602,32 @@ void TLayout::layout(NoteDot* item, LayoutContext&)
...
+        accidental->setMag(accidental->mag() * ornamentAccidentalMag);
+        layout(accidental, ctx);
+        Shape accidentalShape = accidental->shape();
+        double minVertDist = above ? accidentalShape.minVerticalDistance(item->bbox()) : Shape(item->bbox()).minVerticalDistance(
+            accidentalShape);
+        accidental->setPos(-0.5 * accidental->width(), above ? (-minVertDist - vertMargin) : (minVertDist + vertMargin));
     }
+}
 
+void TLayout::layoutTrillCueNote(Ornament* item, LayoutContext& ctx)
```
Comment (RomanPudashkin) [inline src/engraving/layout/v0/tlayout.cpp:3629]: With this name, it makes more sense to have Trill* as an argument (instead of Ornament*)

Comment (RomanPudashkin) [reply src/engraving/layout/v0/tlayout.cpp:3625]: Maybe rename this function to layoutOrnamentCueNote? Or add something like:

```
TLayout::layoutTrillCueNote(Ornament* item, LayoutContext& ctx) {
    IF_ASSERT_FAILED(item->isTrillType()) {
        return;
    }
    
    ...
}
```

**Review by RomanPudashkin — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
@zacjansheski Can you start testing on Mac and I'll continue on Win/Lin tomorrow? Thanks!

**Comment by zacjansheski** [comment]
Working well on MacOS 11.6.5
