### PR TITLE
Fix quarter tone bend on TAB

### LINKED ISSUE #31109: Quarter tone pre-bend can not be set on tablature only guitar
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

Open attached score or follow these steps to create it:
1. Create a score with an "Acoustic Guitar (tablature)" as the instrument
2. Enter a note
3. Add a pre-bend from the guitar palette to it
4. In the properties panel for the pre-bend, drag the endpoint down to 1/4th

**_Actual behavior:_** While the graph shows 1/4th, the score shows 1/2. Upon deselecting and reselecting the pre-bend, the graph is rest to 1/2 as well
**_Expected behavior:_** The pre-bend remains at 1/4th

**_Additional weirdness:_**
Add another Acoustic Guitar (standard staff) and a linked staff to it. Change the linked staff to Tablature, 6str common.
Enter the same note + bend on that linked tablature staff: now the pre-bend does remain at the 1/4th interval.

### Supporting files, videos and screenshots

[quarter-pre-bend.mscz.zip](https://github.com/user-attachments/files/23630652/quarter-pre-bend.mscz.zip)

### In which versions of MuseScore Studio is this issue present?

4.6.3

### Regression

I was unable to check

### Operating system

Linux, but presumably all

### Additional context

Discovered in https://musescore.org/en/node/386765

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mike-spa**
Resolves: #31109 

UPDATE. Microtonal bends work based on microtonal accidentals. If there is at least one notation staff, the information about accidentals propagates to TAB staff too. But if there isn't, TAB staves don't support any accidental logic, therefore microtonal bends don't work. This PR adds the "cent offset" information to notes themselves (as opposed to just inferring it from the accidental) which is anyway a necessary step to support microtonal music in future.

### CODE REVIEW

File: src/engraving/dom/guitarbend.cpp [hunk 1]
```diff
@@ -484,6 +484,9 @@ void GuitarBend::computeBendAmount()
     Note* startN = prevSlack ? prevSlack->startNote() : startNote();
     Note* endN = endNote();
 
+    Tpc startTpc = static_cast<Tpc>(startN->tpc1());
```
Comment (miiizen) [inline src/engraving/dom/guitarbend.cpp]: Unused - see warnings

File: src/engraving/editing/cmd.cpp [hunk 2]
```diff
@@ -2371,30 +2371,40 @@ void Score::changeAccidental(Note* note, AccidentalType accidental)
...
+        pitch = line2pitch(note->line(), clef, Key::C) + int(acc);
+        if (!note->concertPitch()) {
+            pitch += note->transposition();
+        }
     }
 
-    int tpc = step2tpc(step, acc);
+    int tpc = note->tpc();
+    if (!isTabClef) {
+        int step      = ClefInfo::pitchOffset(clef) - note->line();
```
Comment (miiizen) [inline src/engraving/editing/cmd.cpp]: Nitpick, but we can get rid of the whitespace here

**Review by miiizen — CHANGES_REQUESTED** [review]

**Comment by davidstephengrant** [comment]
This is still not working correctly.

Screenshot From 2026-02-04 12-28-39
1. Bend set to 3/4 in the Properties panel: draws as 1 1/4 in the score.

-----------------

Screenshot From 2026-02-04 12-31-40
2. Bend set to 1/4 in the Properties panel: draws as 3/4 in the score.

-----------------

Screenshot From 2026-02-04 12-33-35
3. Switch to standard staff type. Result: Expected 1/4 bend is drawn in score, but has changed to 3/4 in the properties panel.

-----------------

Screenshot From 2026-02-04 12-34-27
4. Set the bend interval to 1/4, and notice that spacing changes slightly, although the drawn accidental doesn't change.

-----------------

Screenshot From 2026-02-04 12-36-24
5. Change back to TAB staff. Both score and properties panel show 3/4 bend where 1/4 is expected.

File: src/engraving/dom/guitarbend.h [hunk 3]
```diff
@@ -45,8 +45,8 @@ enum class GuitarBendShowHoldLine : unsigned char {
     HIDE,
 };
 
-enum class QuarterOffset : unsigned char {
-    QUARTER_FLAT,
+enum class QuarterOffset {
```
Comment (cbjeukendrup) [inline src/engraving/dom/guitarbend.h]:
```suggestion
enum class QuarterOffset : signed char {
```

File: src/engraving/dom/note.cpp [hunk 4]
```diff
@@ -1289,6 +1289,7 @@ void Note::add(EngravingItem* e)
     break;
     case ElementType::ACCIDENTAL:
         m_accidental = toAccidental(e);
+        m_centOffset = Accidental::subtype2centOffset(toAccidental(e)->accidentalType());
```
Comment (miiizen) [inline src/engraving/dom/note.cpp:1293]: Is it worth changing all existing usage of `Accidental::subtype2centOffset` to use the note's `centOffset` property now? eg. in `Note::playingTuning` and `TLayout::layoutNoteAnchoredLine`?

Comment (mike-spa) [reply src/engraving/dom/note.cpp:1293]: Almost certainly yes, but I'd rather do that after the release so that we keep these changes as confined as possible for now

**Review by miiizen — APPROVED** [review]
Looks good! Also glad we're making a step in the right direction for better tuning support

**Comment by davidstephengrant** [comment]
There is still a problem changing staff type.

Screenshot From 2026-02-05 13-02-59
1. Set bend interval to 1/4.

------------------------

Screenshot From 2026-02-05 13-06-45
2. Switch to standard staff. RESULT: a regular semitone accidental is drawn, not the expected microtonal accidental.

------------------------

Screenshot From 2026-02-05 13-14-11
3. Undo _Set staff type_. RESULT: The bend has been changed to 1/2.

------------------------

Note: This only seems to happen when switching from TAB to standard staff type - not vice versa. I.e., explicitly setting a microtonal bend on a standard staff and switching to TAB appears to be working correctly.

**Review by miiizen — APPROVED** [review]
