### PR TITLE
Transpose tool will only transpose initial key signature …

### LINKED ISSUE #18404: Transpose action adds new key signature, if selection starts at begining of system
### Issue type

Engraving bug

### Bug description

If score has key signature, and selection starts at system begining, transpose action creates unwanted key signature.

### Steps to reproduce

1. create score with key signature (no C major score)
2. select first measure of system
3. Call transpose
4. see - Key Signature is added

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/1646034/88680c23-dce0-4c60-93f5-7b070bcf8f70

### MuseScore Version

all versions

### Regression

No.

### Operating system

Ubuntu 22.04

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by miiizen**
…on a system if there is a key

If the first key signature on a system is a change to the measure before, it will be transposed.  Otherwise it will be left untouched.

Resolves: #18404

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Review by oktophonie — APPROVED** [review]

**Comment by cbjeukendrup** [comment]
A rebase is needed

File: src/engraving/dom/keysig.cpp [hunk 1]
```diff
@@ -156,6 +157,15 @@ bool KeySig::isChange() const
     return staff()->currentKeyTick(keyTick) == keyTick;
 }
 
+bool KeySig::isFirstSystemKeySig()
```
Comment (RomanPudashkin) [inline src/engraving/dom/keysig.cpp:160]: Ideally, we should make this function static and remove it from this class (perhaps declare it inside utils.h or directly in transpose.cpp). We are trying to make the implementation of engraving items as simple as possible (so they won't implicitly use systems/measures/etc)

File: src/engraving/dom/utils.cpp [hunk 2]
```diff
@@ -1334,4 +1335,16 @@ String formatUniqueExcerptName(const String& baseName, const StringList& allExce
...
+bool isFirstSystemKeySig(const KeySig* ks)
+{
+    if (!ks) {
+        return false;
+    }
+    const System* sys = ks->measure()->system();
+    if (!sys) {
+        return false;
+    }
+    return ks->tick() == sys->firstMeasure()->tick();
```
Comment (cbjeukendrup) [inline src/engraving/dom/utils.cpp:1348]: I think it's preferable to check equality of the `.tick()` fractions directly instead of via `.ticks()`, because the conversion to integers is a bit more expensive and a lossy for fractions that are not multiples of 1/480 (although that won't likely be a problem for key signatures)

**Review by cbjeukendrup — APPROVED** [review]
I pushed some code review fixes (some unnecessary includes); if you're happy with those, I think it can be merged.

**Comment by miiizen** [comment]
@cbjeukendrup looks good to me!
