### PR TITLE
fix crashes on revoice of revoiced accessibility info

### LINKED ISSUE #16437: [MU4 Issue] Crash when changing pitch after undo
**Describe the bug**
App crashes when inputting an octave change after an undo.

**To Reproduce**
1. Create a new score from a template. I picked the Piano template.
2. Click on the first empty measure.
3. Type "C" twice to insert two C notes.
4. Press Ctrl+Z to undo inserting the second note.
5. Press Ctrl+Down to lower the first C by one octave.
6. App crashes

**Expected behavior**
I expect the app to change the octave without crashing.

**Screenshots**
image Click
image 'C' 'C'
image Ctrl+Z
image Ctrl+Down
*CRASH*

**Platform information**
 - OS: Windows 10

**Additional context**
OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

### PR DESCRIPTION
**Pull request by MarcSabatella**
Resolves: #16437
Resolves: #16887

MuseScore crashes on certain operations when attempting to trigger the screen reader to revoice certain changed information.  This PR solves the crash by avoiding the bad pointer dereference.  The revoicing continues to not be correct in these cases (as it would have been anyhow), but it's certainly better than a crash.

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

File: src/framework/accessibility/internal/accessibilitycontroller.cpp [hunk 1]
```diff
@@ -352,8 +356,9 @@ void AccessibilityController::triggerRevoicingOfChangedName(IAccessible* item)
         if (m_lastFocused) {
             m_lastFocused->setState(State::Focused, false);
         }
-
-        m_itemForRestoreFocus->setState(State::Focused, true);
+        if (m_itemForRestoreFocus) {
```
Comment (Eism) [inline src/framework/accessibility/internal/accessibilitycontroller.cpp:359]: please add empty lines before and after block

Comment (MarcSabatella) [reply src/framework/accessibility/internal/accessibilitycontroller.cpp:359]: Noted, and I'll make that change if we go with this type of solution.

This still isn't a good fix, though.  It solves the crash but produces very strange screen reader output as noted in https://github.com/musescore/MuseScore/issues/16437#issuecomment-1610561150.  I'd like to do better, but I am still not sure how.

But because crashing is way worse than occasionally misleading screen reader info, I'll update the PR to add the space, squash the commits, and take it out of draft status so we can consider merging for now and hopefully finding something better later.

**Comment by MarcSabatella** [comment]
Even if it's not ideal, it definitely leaves us better off than before.  No actual change to the basic flow; we just avoid the crash.  So FWIW, I recommend merging then continuing the investigation as time permits.  4.1.0 version to follow...

**Comment by DmitryArefiev** [comment]
@MarcSabatella  Thanks for fixing! And one more question: what app are you using for Video capture on Linux?

**Comment by MarcSabatella** [comment]
Thanks for testing!  For me I don't need the screen reader *enabled*, but I do have QT_ACCESSIBILITY set so the accessibility system is enabled within QT by default even with no screen reader running.  Merely unsetting that variable doesn't make the crash go away, but maybe it would if I rebooted with it unset.

For screen recordings, I either use gifcap.dev (for GIF, obviously), or Screencastify.  Both are web-based so they run just about anywhere.  Recently I've also been using the facility built into my Chromebook, which is where my Linux subsystem runs.

BTW, I wonder also if it will turn out that https://github.com/musescore/MuseScore/issues/18286 is triggered by the same issue, since the log at least sometimes mentions the accessibility controller.  Bit of a longshot, but it would be nice to have just discovered a bug I also just fixed :-)

**Comment by DmitryArefiev** [comment]
> For screen recordings, I either use gifcap.dev (for GIF, obviously), or Screencastify. Both are web-based so they run just about anywhere. Recently I've also been using the facility built into my Chromebook, which is where my Linux subsystem runs.

Thanks! I'll try those. Mine that goes with Ubuntu doesn't want to work normally ((

> BTW, I wonder also if it will turn out that https://github.com/musescore/MuseScore/issues/18286 is triggered by the same issue, since the log at least sometimes mentions the accessibility controller. Bit of a longshot, but it would be nice to have just discovered a bug I also just fixed :-)

I see Casper already fixed that in #18295. I've tested briefly on Win, it looks fine!
