### PR TITLE
fixed #13698: MuseScore crashes after closing score

### LINKED ISSUE #13698: MU4 crash in Linux
**Description:**
Today I experienced a crash running the Nightly build from Oct, 10th.
Upon closing the open file it crashed (after refusing to save changes to the open file) with the following message:

/tmp/.mount_MuseSc7ltvD2/AppRun: Zeile 26: 44217 Speicherzugriffsfehler "${APPDIR}/bin/mscore-portable-nightly" "$@"

OS: Ubuntu 20.04
Appimage
=== Started MuseScore 4.0.0-Development, build number 3216906122 ===

Logfile from that session attached.

**To Reproduce**
1. Open first score (Pachelbel)
2. Play it by clicking the play button
3. While playing open the mixer (F10)
4. Press CTRL-S to save the score
5. Close the score (click the X)
6. Open second score (Schumann from 3.6.0)
7. Play it by clicking the play button
8. Close the score by clicking the X and click "Don't save"
9. Crash (app disappeared completely)

I could reproduce the crash once but no luck afterwards so I am not sure whether the steps above lead to the crash. The only sure thing is step 9 (closing the changed score from Schumann).

[MS4.zip](https://github.com/musescore/MuseScore/files/9756126/MS4.zip)

Klaus

### PR DESCRIPTION
**Pull request by Eism**
Resolves: #13698
Resolves: #12815

### CODE REVIEW

**Comment by HemantAntony** [comment]
@Eism My issue (#13764) still occurs

**Comment by DmitryArefiev** [comment]
Tested #13698 on Win10, Mac12, **LinuxMint 20.2** - **FIXED**

File: src/framework/global/thirdparty/deto_async/async/internal/abstractinvoker.cpp [hunk 1]
```diff
@@ -192,3 +198,16 @@ void AbstractInvoker::removeQInvoker(QInvoker* qi)
     std::lock_guard<std::mutex> lock(m_qInvokersMutex);
     m_qInvokers.remove(qi);
 }
+
+bool AbstractInvoker::containsReceiver(Asyncable* receiver) const
```
Comment (vpereverzev) [inline src/framework/global/thirdparty/deto_async/async/internal/abstractinvoker.cpp:202]: Feels like this can hit the performance?

One other thing, I thought we're removing the necessary callbacks at destruction point of a receiver? @igorkorsukov FYI

Comment (Eism) [reply src/framework/global/thirdparty/deto_async/async/internal/abstractinvoker.cpp:202]: I implemented this solution after discussing with Igor, we came to the conclusion that this is the best solution at the moment. Usually, an Invoker doesn't have many receivers.

> One other thing, I thought we're removing the necessary callbacks at destruction point of a receiver?

Yes, we remove all callbacks in the destructor of the receiver. The problem is that we delete the receiver after passing this receiver to the Invoker. At the time of the creation of the Invoker, the receiver was valid; when the callback was called, the receiver is destroyed.

**Review by RomanPudashkin — APPROVED** [review]
