### PR TITLE
Fix #32117: Crash involving chord symbols and history panel

### LINKED ISSUE #32117: Crash using the history panel after chord symbol input/navigation
### Issue type

Crash or freeze

### Description with steps to reproduce

1. Add a chord symbol
2. Hit `Space` to advance the input cursor
3. Use the history panel to undo
**RESULT:** crash

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/b7f84dbd-a1ad-4a33-8f1e-666348815dec

### In which versions of MuseScore Studio is this issue present?

MuseScore Studio version (64-bit): 4.7.0-260209121, revision: github-musescore-musescore-eb2311f

### Regression

No.

### Operating system

Ubuntu 24.04.3 LTS, Arch.: x86_64

### Additional context

A similar (the same?) crash is reproducible already in 4.0.0, but using the undo button rather than the History panel.

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mathesoncalum**
Resolves: #32117

`UndoStack::undo` has some logic where we return early if there are no text edits to undo. This means the undo stack's index never changes in `NotationUndoStack::undoRedoToIndex` and we get caught in an infinite loop.

There are a few ways we could approach this, but the easiest option is simply to end the text editing whenever we use `NotationInteraction::undoRedoToIndex`.

### CODE REVIEW

File: src/notation/internal/notationinteraction.cpp [hunk 1]
```diff
@@ -4631,6 +4631,9 @@ void NotationInteraction::redo()
 
 void NotationInteraction::undoRedoToIndex(size_t idx)
 {
+    if (isTextEditingStarted()) {
```
Comment (RomanPudashkin) [inline src/notation/internal/notationinteraction.cpp]: Perhaps we should end any form of element editing here, not just text editing. What do you think?

Comment (mathesoncalum) [reply src/notation/internal/notationinteraction.cpp]: Yeah I think that's sensible - updated now.

**Comment by davidstephengrant** [comment]
Tested and approved on Ubuntu 24.04.4 LTS.
