### PR TITLE
Correct off-by-one error in `SpannerFilter::isPlayable`

### LINKED ISSUE #12869: [MU4 Issue] Pedal playback not working for "pedal change"
**Describe the bug**
The standard "pedal change" marking \_\_\_/\\\_\_\_ does not work; it lifts the pedal off but does not return it to the on position

**To Reproduce**
1. Piano score
2. Add four quarter notes C D E D to first measure and again to the second
3. Add a |___/ pedal marking from the first C to the second
4. Add a \\___| pedal marking from the second C to the end of the measure
5. Play

*Result**
Pedal lifts in bar 2 but does not re-engage

**Expected behavior**
Second measure should have pedal engaged just like the first

**Screenshots**
image

**Platform information**
 - OS: Linux

**Additional context**
The old-style Ped___* markings work fine because they don't overlap.  The issue seems to only occur on the pedal changes - the places where the end of one pedal coincides the the start of the next to create the characteristic pedal change \_\_\_/\\\_\_\_.  If I were to guess, I'd say the pedal off and on messages are simply being sent in the wrong order.

### LINKED ISSUE #16757: Pedal incorrectly applied to note after end of pedal (if there is only one note after end of pedal)
### Issue type

General playback bug

### Steps to reproduce

Enter this and play it with **MS Basic**. The last note gets held indefinitely.

image

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/4ec5ae27-00d4-417b-9aca-fbd3cff3bdd2

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

### Regression

Doesn't happen in **MS3**

### Operating system

Win 11

### Additional context

It seems that pedal playback through MIDI is currently implemented to end a CC64 value of 127 or 0 at the start of each note, and that when the bug triggers, 0 is sent correctly to lift the pedal, but immediately 127 is sent on the note after the pedal ends, leading it the pedal being held down incorrectly. Another manifestation of this same bug is to make the note after the pedal staccato, and a note after it, and note that the staccato doesn't actually play because it gets pedaled.

I ran into this issue with Pianoteq VST when working on a score, but I can't find a simple reproduction that breaks VST playback yet.
Note that there is no problem when using MuseSounds. There is also no problem when exporting MIDI as exporting doesn't produce the unnecessary CC64 events.

### PR DESCRIPTION
**Pull request by bluebear94**
This immediately fixes #16757, which occurred when a chord right after the end of a pedal line was counted as intersecting its duration.

This commit also reverts the subtraction by `Constants::DIVISION / 4` for the duration of a pedal line ending in an angled hook. This subtraction was introduced in order to fix #12869, but it has caused other issues such as #16001 and is probably unneeded given the fix to `isPlayable`.

Resolves: #16757
Resolves: #16001
Resolves: https://github.com/musescore/MuseScore/issues/19322
Resolves: https://github.com/musescore/MuseScore/issues/18835

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes – ~~TODO, mainly due to tooling. Adds `.cache` and `compile_commands.json` to `.gitignore` since clangd expects a `compile_commands.json` file in either `.` or `build/` and creates a `.cache` directory in `build`. Also specifies the path to the Uncrustify config for VSCode. These can be moved to a separate PR if desired.~~ moved to #18767
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by bluebear94** [comment]
Is this PR still being looked at? It’s been a few months since I submitted it. Is there anything else I need to do myself?

File: src/engraving/playback/filters/spannerfilter.cpp [hunk 1]
```diff
@@ -42,7 +42,7 @@ bool SpannerFilter::isPlayable(const EngravingItem* item, const RenderingContext
     int spannerTo = spannerFrom + spannerDurationTicks;
 
     if (spannerDurationTicks == 0
-        || spannerTo < ctx.nominalPositionStartTick
+        || spannerTo <= ctx.nominalPositionStartTick
```
Comment (Jojo-Schmitz) [inline src/engraving/playback/filters/spannerfilter.cpp:45]: This is the off-by-1 error

File: src/engraving/playback/filters/spannerfilter.cpp [hunk 2]
```diff
@@ -56,13 +56,6 @@ int SpannerFilter::spannerActualDurationTicks(const Spanner* spanner, const int
         return spanner->endSegment()->tick().ticks() - spanner->tick().ticks() - 1;
     }
 
-    if (spanner->type() == ElementType::PEDAL) {
-        const Pedal* pedal = toPedal(spanner);
-        if (pedal->endHookType() == HookType::HOOK_45) {
-            return nominalDurationTicks - Constants::DIVISION / 4;
-        }
-    }
-
```
Comment (Jojo-Schmitz) [inline src/engraving/playback/filters/spannerfilter.cpp:65]: But what is this about?

File: src/engraving/playback/filters/spannerfilter.cpp [hunk 3]
```diff
@@ -56,13 +56,6 @@ int SpannerFilter::spannerActualDurationTicks(const Spanner* spanner, const int
         return spanner->endSegment()->tick().ticks() - spanner->tick().ticks() - 1;
```
Comment (cbjeukendrup) [inline src/engraving/playback/filters/spannerfilter.cpp:56]: It might be worthwhile to check if this adjustment and the adjustments for SLUR below are also still necessary, given the fix in `isPlayable`. (The fix in `isPlayable` looks good to me.)

Comment (bluebear94) [reply src/engraving/playback/filters/spannerfilter.cpp]: Yep, the `TRILL` case is indeed unnecessary.

**Review by cbjeukendrup — APPROVED** [review]

**Comment by cbjeukendrup** [comment]
Don't worry about the "failed" vtests; that's because this branch is apparently not fully up-to-date with the master branch, but that's not a problem for merging.

**Comment by Jojo-Schmitz** [comment]
Also fixes #19322

**Comment by RomanPudashkin** [comment]
@zacjansheski these issues need to be retested:
https://github.com/musescore/MuseScore/issues/14137
https://github.com/musescore/MuseScore/issues/13957

**Comment by cbjeukendrup** [comment]
By the way, I've prepared a unit test for this which I will add once this PR is merged

**Comment by zacjansheski** [comment]
Tested on Mac OS 11.6.5, Ubuntu 20.04.6, Windows 11
https://github.com/musescore/MuseScore/issues/16757 FIXED
https://github.com/musescore/MuseScore/issues/16001 FIXED
https://github.com/musescore/MuseScore/issues/19322 FIXED
https://github.com/musescore/MuseScore/issues/18835 FIXED
No regression found relevent to https://github.com/musescore/MuseScore/issues/13957

**Comment by cbjeukendrup** [comment]
@RomanPudashkin shall we merge this now?
