### PR TITLE
Don't create mmRest on an irregular measure if it doesn't have a full measure rest

### LINKED ISSUE #28091: Empty pseudo-pickup measure shown as multimeasure rest in part
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

This only happens in certain cases, and the key seems to be a combination of mutlimeasure rests enabled, minimum number of empty measures set to 1, a measure with fewer beats than the time signature calls for, but *not* set to exclude from the measure count.  The first two conditions are the default for parts.  Pickups created normally through the new score wizard will be set to exclude from measure count an d thus you won't see this, but if you create the pickup later by deleting beats from a measure but forget to exclude from measure count, you see the bug.  So for example:

1. New score, treble template, 4/4, no pickup
2. enter a single quarter rest into the first measure
3. delete the other three beats (Ctrl+Delete) to create the pseudo-pickup
4. generate parts
5. view part

Result: the empty  pseudo-pickup shows as a multimeasure rest.  It breaks the multimeasure rest for the other empty measures, so that much is good, but it should be showing a quarter rest, and does it you do go back and set Exclude from measure count.

### Supporting files, videos and screenshots

Score:

Image

Part:

Image

Result after excluding pickup from measure count:

Image

### What is the latest version of MuseScore Studio where this issue is present?

OS: Debian GNU/Linux 12 (bookworm), Arch.: x86_64, MuseScore Studio version (64-bit): 4.6.0-251350318, revision: github-musescore-musescore-fd5ca26

### Regression

No.

### Operating system

Debian 12

### Additional context

Same bug going back to MU3 - but, the default for "minimum number of empty measures" was only recently lowered from 2 to 1.  So people probably never ran into this until that change, because you'd have to go out of your way to lower that setting.  Now it happens by default any time someone creates a pickup without the exclude option.

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mike-spa**
Resolves: #28091

The problem is that the pickup measure in Musescore is not really flagged as a pickup measure, it's just a measure that is a) at the beginning of the score, b) shortened, c) excluded from the measure count. This poses a problem in terms of what rules you want to follow for creating mmRests without affecting other unintended cases. 

This solution is what probably makes most sense.

### CODE REVIEW

**Review by ghost — APPROVED** [review]

File: src/engraving/rendering/score/measurelayout.cpp [hunk 1]
```diff
@@ -601,6 +601,8 @@ static bool validMMRestMeasure(const LayoutContext& ctx, const Measure* m)
                 if (s->element(track)) {
                     if (!s->element(track)->isRest()) {
                         return false;
+                    } else if (m->isIrregular() && !toRest(s->element(track))->isFullMeasureRest()) {
```
Comment (miiizen) [inline src/engraving/rendering/score/measurelayout.cpp]: We could put this in a variable for a bit more clarity

**Review by miiizen — APPROVED** [review]

**Review by miiizen — APPROVED** [review]
