### PR TITLE
Fix measure number edits not retained

### LINKED ISSUE #29594: Measure numbers don't retain customizations on staff visibility change
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. Create a new score with a piano.
2. In Format -> Style -> Measure numbers, select Every 5 measures and On all staves.
3. Select a measure number in the bass clef and uncheck Visible in the Properties panel.
4. Toggle the bass clef staff visibility in the Layout panel off and back on.
5. Observe the measure number is now visible.
6. Repeat 3-5 but change the offset under Appearance button. Observe the offsets revert to default.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/f2e0d1ec-fdfd-45a4-bb7d-005e6f10c096

### What is the latest version of MuseScore Studio where this issue is present?

8/29/25 nightly. OS: macOS Sequoia (15.6), Arch.: arm64, MuseScore Studio version (64-bit): 4.6.0-252410405, revision: github-musescore-musescore-c892561

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

macOS Sequoia (15.6)

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mike-spa**
Resolves: #29594

In my previous implementation, measure numbers that weren't shown were removed from the score, and if they happened to be shown again new ones were created, hence customizations were lost. Now instead of removing measure numbers that don't show we just exclude them from Measure::scanElements.

All other changes are just code cleanup.

### CODE REVIEW

**Review by ghost — APPROVED** [review]

File: src/engraving/dom/cmd.cpp [hunk 1]
```diff
@@ -1423,6 +1423,7 @@ Fraction Score::makeGap(Segment* segment, track_idx_t track, const Fraction& _sd
         SelectionFilter filter;
         // chord symbols can exist without chord/rest so they should not be removed
         filter.setFiltered(ElementsSelectionFilterTypes::CHORD_SYMBOL, false);
+        filter.setFiltered(ElementsSelectionFilterTypes::FRET_DIAGRAM, false);
```
Comment (miiizen) [inline src/engraving/dom/cmd.cpp:1426]: This looks leftover from a previous PR

File: src/engraving/dom/measure.cpp [hunk 2]
```diff
@@ -594,19 +594,31 @@ bool Measure::showsMeasureNumberInAutoMode()
...
+    case MeasureNumberMode::AUTO:
+        return showMeasureNumberInAutoMode();
+    case MeasureNumberMode::SHOW:
         return true;
-    } else if (m_noMode == MeasureNumberMode::HIDE) {
+    case MeasureNumberMode::HIDE:
         return false;
-    } else {
-        return showsMeasureNumberInAutoMode();
+    default:
```
Comment (miiizen) [inline src/engraving/dom/measure.cpp:620]: You should be able to remove the default case as all values are handled above

**Review by miiizen — APPROVED** [review]
