### PR TITLE
Fix #23492: Add error message when attempting to copy partial tuplet/tremolo

### LINKED ISSUE #23492: Copy paste of 3rd "leg" of triplet does not work, copies previous contents of clipboard
### Issue type

UI bug (incorrect info or interface appearance)

### Bug description

copy paste bug with triplets. I am trying to copy the voicing on the 3rd leg of a triplet. I use shift to highlight the 4 notes. When I paste, what gets pasted is something that was previously on the clipboard as you can see by the fact that it's pasting a chord which doesn't even exist at the point of the copy.

EDITORIAL COMMENT - YOU MAKE IT TOO HARD TO ADD ATTACHMENTS. Please support your native file format!!!!

And/or rar and other common formats...

### Steps to reproduce

create 1/4 note triplets as I have in the supplied chord. Copy the 3rd leg of one of the triplets and attempt to paste it into the first leg of another triplet. I use the menu in the video but normally I use ctrl-c / ctrl-v for the copy and the paste

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/6884133/35e02b1d-2f17-4996-b20f-75685aded7cd

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.2-241630831, revision: github-musescore-musescore-22b46f2

### Regression

I don't know

### Operating system

windows 11

### Additional context

[Diminished Dominants with compound triplet rhythms.zip](https://github.com/user-attachments/files/16116495/Diminished.Dominants.with.compound.triplet.rhythms.zip)

### PR DESCRIPTION
**Pull request by mathesoncalum**
Resolves: #23492

As suggested in the original issue thread, the main problem here is that we don't message the user when partially copying a tuplet or tremolo between notes (see `Selection::canCopy` and related methods) - we just silently fail. The changes in this PR ensure that warning messages are displayed for these cases (see below, a copy pass maybe needed).

partialtuplet
partialtremolo
...

The other part of this can be traced all the way back to #5486. There _is_ actually a warning dialog when trying to _paste_ into a tuplet, but the changes in that PR mean that we skip it _whenever we try to paste to the **first**_ `ChordRest` _in a tuplet_. The reasoning there is that we might want to paste from the start of the tuplet (and overwrite the tuplet in the process).

### CODE REVIEW

File: src/engraving/dom/select.cpp [hunk 1]
```diff
@@ -1375,74 +1375,83 @@ std::vector<Note*> Selection::noteList(track_idx_t selTrack) const
...
             }
             e = tuplet;
             tuplet = tuplet->tuplet();
         }
-    } else if (cr->isChord()) {
-        rv = false;
-        Chord* chord = toChord(cr);
-        if (chord->tremoloTwoChord()) {
-            rv = chord->tremoloTwoChord()->chord2() == chord;
+        return MsError::MS_NO_ERROR;
```
Comment (cbjeukendrup) [inline src/engraving/dom/select.cpp]: If there is a non-problematic tuplet, we might still need to check for a problematic tremolo. I'm thinking of cursed edge cases like this:
Image

Comment (mathesoncalum) [reply src/engraving/dom/select.cpp]: Updated now 👍

**Comment by zacjansheski** [comment]
"Do not show this message again" is not honored


https://github.com/user-attachments/assets/271452ae-c5ea-4299-bd81-ed4ada1a6905

**Comment by zacjansheski** [comment]
Actually that seems like a wide-spread behavior, same with, splitting tuplet messages in master, so not a reason to block this PR

Screenshot 2025-11-14 at 11 54 31 AM

**Comment by zacjansheski** [comment]
Assuming the above note should be addressed separately....

Tested on MacOS 15, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/23492 FIXED

**Comment by mathesoncalum** [comment]
Indeed it's a separate issue @zacjansheski - looks like it happens for some other warning dialogs too

Merging now.
