### PR TITLE
[4.7.0] VST: fix blank view when moving/resizing on Windows

### LINKED ISSUE #29711: VST window flickers when resizing (Windows only)
### Issue type

VST bug

### Description with steps to reproduce

Flickering while dragging was fixed in #29701 (#29397), but **when resizing it still occurs** (and sometimes it gets stuck when resizing)

Not all VSTs are effected

Occurs with **BBC SO, Analog Lab5**

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/5d5c9693-823a-49dd-81a9-59f003be1013

### What is the latest version of MuseScore Studio where this issue is present?

4.6.0-252450632

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

Windows 10

### Additional context

This is related to the **new VST view** (which is default for 4.6)

Image

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Also resolves: https://github.com/musescore/MuseScore/issues/29711

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved rendering stability for VST plugin windows on Windows by preventing unnecessary background erases and reducing redundant redraws when plugin windows move or resize, eliminating flicker and excessive repaints.

### CODE REVIEW

File: src/framework/vst/qml/Muse/Vst/vstview.cpp [hunk 1]
```diff
@@ -80,7 +84,7 @@ static FIDString currentPlatformUiType()
 }
 
 VstView::VstView(QQuickItem* parent)
-    : QQuickItem(parent), muse::Contextable(muse::iocCtxForQmlObject(this))
+    : QQuickItem(parent), QAbstractNativeEventFilter(), muse::Contextable(muse::iocCtxForQmlObject(this))
```
Comment (igorkorsukov) [inline src/framework/vst/qml/Muse/Vst/vstview.cpp:87]: Nitpick: no need to call

**Review by igorkorsukov — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
Tested #29711 on Win10 - **FIXED**
