### PR TITLE
Fix page margins and gaps

### LINKED ISSUE #30986: Space between pages (and side margin when opening score) has become smaller
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

The space between pages in page view, and the space around the score when you just open it, has decreased as a result of the engraving::DPI change. This space was namely a hardcoded number.

### Supporting files, videos and screenshots

Before: 

Image

After:

Image

### In which versions of MuseScore Studio is this issue present?

master (4.7)

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

\*

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mike-spa**
Resolves: #30986

### CODE REVIEW

File: src/notation/internal/notationpainting.cpp [hunk 1]
```diff
@@ -163,8 +163,9 @@ void NotationPainting::paintPageSheet(Painter* painter, const Page* page, const
         return;
     }
 
+    const double strokeWidth = 0.07 * DPMM;
     painter->setBrush(BrushStyle::NoBrush);
-    painter->setPen(Pen(configuration()->borderColor(), configuration()->borderWidth()));
+    painter->setPen(Pen(configuration()->borderColor(), strokeWidth));
```
Comment (cbjeukendrup) [inline src/notation/internal/notationpainting.cpp:168]: I wonder if there are any other places where NotationConfiguration::borderWidth is used that need the same treatment

**Review by cbjeukendrup — APPROVED** [review]

File: src/notation/internal/notationpainting.cpp (hunk 1 above)
Comment (mike-spa) [reply src/notation/internal/notationpainting.cpp:168]: From a quick search, it doesn't seems so (as in, borderWidth appears everywhere but not in other bits of notation painting)
