### PR TITLE
Fix #8172: Replaced instruments updated

### LINKED ISSUE #8172: [MU4 Issue] Replaced Instrument in Parts dialog displayed as it was before replace
**Describe the bug**
If user replace instrument via Instruments panel and go to Parts dialog he will see instruments as they were before replacing. 

**To Reproduce**
1. Create a score
2. Open Instruments tab in Instruments Panel
3. Click on option button (gear icon) from the Instruments panel near Instrument 
4. Click "Replace instrument" button
5. Proceed untill replaced instrument displays in the Instruments panel
6. Open Parts dialog

**Expected behavior**
Replaced instruments should be displayed in Parts dialog

**Screenshots**

https://user-images.githubusercontent.com/71372310/119557334-babc7380-bda8-11eb-8102-11a43dc9334d.mp4

**Desktop (please complete the following information):**
Windows 10

### PR DESCRIPTION
**Pull request by HemantAntony**
Resolves: [#8172](https://github.com/musescore/MuseScore/issues/8172)

This commit now updates the instruments panel and parts dialog to
display the part name of new instrument.

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [ ] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by HemantAntony** [comment]
If you were to replace two instruments with the same instrument, the part name would be the same in the instruments panel. Also, the mixer panel doesn't get updated because I didn't which function to use. I know something similar to this occurs when you delete a part. Then the mixer gets updated. But I couldn't find out the function that was used.

**Comment by HemantAntony** [comment]
I'm still working on this

**Comment by HemantAntony** [comment]
This pr is ready for review

File: src/notation/internal/notationparts.cpp [hunk 1]
```diff
@@ -571,14 +571,15 @@ void NotationParts::replaceInstrument(const InstrumentKey& instrumentKey, const
     TRACEFUNC;
 
     Part* part = partModifiable(instrumentKey.partId);
+    QString newInstrumentPartName = notation::formatInstrumentTitle(newInstrument.trackName(), newInstrument.trait());
```
Comment (RomanPudashkin) [inline src/notation/internal/notationparts.cpp:574]: 1. Please, move this line closer to 
score()->undo(new Ms::ChangePart(...))

2. You can remove notation::, because NotationParts is already in that namespace

**Comment by DmitryArefiev** [comment]
Hi @HemantAntony 

I've tested #8172 on Windows10 and found one case when instrument name is note updated in Part dialog if the part of that instrument was opened (but not active) during replacement process. Please see the video:


https://user-images.githubusercontent.com/90187801/146224870-11e513f6-8a98-492f-a88d-49466aeacd73.mp4



Can it be done within the current PR or it's better to log a new one? 

Thanks!

**Comment by HemantAntony** [comment]
> Hi @HemantAntony
> 
> I've tested #8172 on Windows10 and found one case when instrument name is note updated in Part dialog if the part of that instrument was opened (but not active) during replacement process. Please see the video:
> 
>  bandicam.2021-12-15.18-16-53-876.mp4 
> Can it be done within the current PR or it's better to log a new one?
> 
> Thanks!

I think I will create a new issue and pr to solve this. It might take time. Also, I might not be able to solve it

**Review by RomanPudashkin — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
> I think I will create a new issue and pr to solve this. It might take time. Also, I might not be able to solve it

@HemantAntony Good. Thank you!
