### PR TITLE
[MusicXML] Improve tempo import from Dorico

### LINKED ISSUE #27961: Metronomes from Dorico are read as invisible
### Issue type

Import/export issue

### Description with steps to reproduce

Opening a musicxml exported from Dorico reads the metronomes as invisible.
So for example, if you export again to musicxml the metronomes are gone.
This was working fine on MuseScore 3 but now fails on 4.

### Supporting files, videos and screenshots

[Ave Verum.musicxml.zip](https://github.com/user-attachments/files/20070289/Ave.Verum.musicxml.zip)

Image

### What is the latest version of MuseScore Studio where this issue is present?

4.5.2.251141402

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

macOS 13

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by rettinghaus**
As shown in #27961 Dorico separates the tempo change from the text (direction) in MusicXML. That led to problems with some lost text or (meaningless) text with separated invisible tempo changes. 

This PR adds a check for Dorico style tempo changes and adds the tempo change to the following `direction`. 

### Before:

grafik

### After:

grafik

closes #27961

### CODE REVIEW

File: src/importexport/musicxml/internal/musicxml/import/importmusicxmlpass2.h [hunk 1]
```diff
@@ -556,6 +556,7 @@ class MusicXmlParserDirection
 
     double totalY() const { return m_defaultY + m_relativeY; }
     muse::String placement() const;
+    const void setBpm(const double bpm) { m_tpoSound = bpm; }
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/import/importmusicxmlpass2.h:559]: Seems you'd need to drop that 1st `const`

**Review by miiizen — APPROVED** [review]
