### PR TITLE
Fix #8871: Reorder instruments panel on mouse release

### LINKED ISSUE #8871: [MU4 Issue] Reorder Instruments panel on mouse release
**Describe the bug**
When reordering the instruments in the new Instrumentspanel (e.g. SATB down and piano up) the changes are applied to the score at the same time. This works quite well for small scores! However, if it's a large score with several pages, moving the instruments is quite choppy. 

**To Reproduce**
1. Open a big Score (with many Instruments and Notes)
2. Try to reoder instruments

**Expected behavior**
Apply the changes to the score only when releasing the mouse button. So you could just drag the instrument to the right place and when you release the mouse button the score is "recalculated".
@Tantacrul Maybe even with a small dialog window with progress indicator or at least a hint "Layout is being recalculated" or something similar?

### PR DESCRIPTION
**Pull request by mathesoncalum**
Resolves: #8871

### CODE REVIEW

**Comment by zacjansheski** [comment]
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/8871 FIXED

(Will log "recalculating" dialogue need as separate issue)

File: src/instrumentsscene/view/abstractinstrumentspaneltreeitem.h [hunk 1]
```diff
@@ -66,7 +66,13 @@ class AbstractInstrumentsPanelTreeItem : public QObject
     Q_INVOKABLE virtual bool canAcceptDrop(const QVariant& item) const;
     Q_INVOKABLE virtual void appendNewItem();
 
-    virtual void moveChildren(int sourceRow, int count, AbstractInstrumentsPanelTreeItem* destinationParent, int destinationRow);
+    virtual IDList notationIdsToMove(int sourceRow, int count) const;
```
Comment (RomanPudashkin) [inline src/instrumentsscene/view/abstractinstrumentspaneltreeitem.h:69]: childIdListToMove (or something like that)

Comment (RomanPudashkin) [reply src/instrumentsscene/view/abstractinstrumentspaneltreeitem.h:69]: As far as I can tell, you only need 1 function instead of notationIdsToMove and notationMoveParams:

1. call it buildMoveParams
2. it takes the same arguments as notationMoveParams
3. it will return this structure:

```
struct MoveParams {
    IDList childIdListToMove;
    ID destinationParentId;
    notation::INotationParts::InsertMode insertMode = INotationParts::InsertMode::Before;
}
```

File: src/instrumentsscene/view/instrumentspaneltreemodel.h [hunk 2]
```diff
@@ -166,6 +169,10 @@ private slots:
     QHash<NotationKey, QList<ID> > m_sortedPartIdList;
 
     bool m_instrumentsPanelVisible = true;
+
+    bool m_dragInProgress = false;
+    bool m_activeDragIsStave;
```
Comment (RomanPudashkin) [inline src/instrumentsscene/view/instrumentspaneltreemodel.h:174]: = false;

File: src/instrumentsscene/view/abstractinstrumentspaneltreeitem.cpp [hunk 3]
```diff
@@ -106,9 +106,14 @@ void AbstractInstrumentsPanelTreeItem::appendNewItem()
 {
 }
 
+MoveParams AbstractInstrumentsPanelTreeItem::buildMoveParams(int, int, AbstractInstrumentsPanelTreeItem*, int) const
+{
```
Comment (RomanPudashkin) [inline src/instrumentsscene/view/abstractinstrumentspaneltreeitem.cpp:110]: Please add here the UNREACHABLE macro

File: src/instrumentsscene/view/abstractinstrumentspaneltreeitem.h [hunk 4]
```diff
@@ -32,6 +32,11 @@
 #include "notation/iexcerptnotation.h"
 
 namespace mu::instrumentsscene {
+struct MoveParams {
+    IDList childIdListToMove;
+    ID destinationParentId;
+    notation::INotationParts::InsertMode insertMode = notation::INotationParts::InsertMode::Before;
+};
```
Comment (RomanPudashkin) [inline src/instrumentsscene/view/abstractinstrumentspaneltreeitem.h:39]: Please add an empty line

**Review by RomanPudashkin — APPROVED** [review]

**Comment by zacjansheski** [comment]
Order does not update when moving with arrows after a click and drag


https://github.com/musescore/MuseScore/assets/69917893/06b8757e-9377-4abc-aeff-b836dcb69528

**Comment by mathesoncalum** [comment]
Nice catch @zacjansheski - should be fixed now.

**Comment by zacjansheski** [comment]
I get a crash in parts when reordering with arrows.
Does not occur in master.

https://github.com/musescore/MuseScore/assets/69917893/6ef1d401-2c9c-4ee0-8e69-07cf6884e29b

**Comment by zacjansheski** [comment]
[PartReorderCrash.zip](https://github.com/musescore/MuseScore/files/13310616/PartReorderCrash.zip)

**Comment by zacjansheski** [comment]
Tested on Mac OS 14, Ubuntu 20.04.6, Windows 11
https://github.com/musescore/MuseScore/issues/8871 FIXED

**Review by RomanPudashkin — APPROVED** [review]
