### PR TITLE
Fix selection deletion crash

### LINKED ISSUE #33003: Musescore crashing when trying to delete with "del" or "backspace" key
### Issue type

Crash or freeze

### Description with steps to reproduce

1. Select notes 
2. deselect chord symbol
3. press "del" or "backspace"
4. crash!

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/cba0dcc9-e4c2-4002-ad23-4fd4155a370b

### In which versions of MuseScore Studio is this issue present?

4.6.3

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

### Additional context

This happens on a piano-only sheet. I don't know if it's relevan but the sheed used to have another instrument (acoustic bass) that I deleted after adding.

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by silasvorne**
Check pointer before de-reference to prevent crash.

Resolves: #33003 

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/muse_framework/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved application stability by adding validation checks when removing grace chord elements, preventing potential crashes.

### CODE REVIEW

File: src/engraving/dom/chord.cpp [hunk 1]
```diff
@@ -799,9 +799,11 @@ void Chord::remove(EngravingItem* e)
     case ElementType::CHORD:
     {
         auto i = std::find(m_graceNotes.begin(), m_graceNotes.end(), toChord(e));
-        Chord* grace = *i;
-        grace->setGraceIndex(i - m_graceNotes.begin());
-        m_graceNotes.erase(i);
+        if (i != m_graceNotes.end()) {
```
Comment (mike-spa) [inline src/engraving/dom/chord.cpp]: This check is fine for safety and it should fix the crash, so I think this is the only bit of this PR that is safe to merge in 4.7.

File: src/engraving/editing/edit.cpp [hunk 2]
```diff
@@ -3990,9 +3990,7 @@ void Score::cmdDeleteSelection()
                                                staff2track(selection().staffStart()), staff2track(selection().staffEnd()),
                                                selectionFilter(), selection().rangeContainsMultiNoteChords());
     } else {
-        // deleteItem modifies selection().elements() list,
-        // so we need a local copy:
-        std::vector<EngravingItem*> el = selection().elements();
+        std::list<EngravingItem*> el = selection().uniqueElements();
```
Comment (mike-spa) [inline src/engraving/editing/edit.cpp]: This area of code is too risky to change in 4.7 so I would ask you to remove it from this PR.

It also feels like a hack: uniqueElements() is meant to avoid linked copies in the list, but the grace note isn't a linked copy, it's just inserted in the list twice, so that's the actual problem we should fix.

File: src/engraving/dom/chord.cpp (hunk 1 above)
Comment (mike-spa) [reply src/engraving/dom/chord.cpp]: It would be better as an assertion though.
```
IF_ASSERT_FAILED(i != m_graceNotes.end()) {
// do notthing
}
// rest of the code
```

File: src/engraving/editing/edit.cpp (hunk 2 above)
Comment (silasvorne) [reply src/engraving/editing/edit.cpp]: Yes, this change does carry a high risk for 4.7, even though all tests have passed. I will remove this change.

Comment (silasvorne) [reply src/engraving/editing/edit.cpp]: However, I would still like to point out that using duplicate elements here has caused other issues, such as being unable to restore the state after deleting and then undoing. I will continue investigating this issue.

Comment (mike-spa) [reply src/engraving/editing/edit.cpp]: Yes, it may be that using uniqueElements() is a good idea here, but I would like to also resolve the core problem i.e. avoid inserting the grace note twice in the elements() list. And it's better to do it on master and keep only the minimal crash fix on the 4.7 branch as we're very close to relase :)

Comment (silasvorne) [reply src/engraving/editing/edit.cpp]: Sure, I completely agree.

File: src/engraving/dom/chord.cpp (hunk 1 above)
Comment (silasvorne) [reply src/engraving/dom/chord.cpp]: Seems assertion is also enable in Release mode ?

Comment (silasvorne) [reply src/engraving/dom/chord.cpp]: I have to remove the test case due to the assertion.

File: src/engraving/dom/chord.cpp [hunk 3]
```diff
@@ -799,6 +799,9 @@ void Chord::remove(EngravingItem* e)
     case ElementType::CHORD:
     {
         auto i = std::find(m_graceNotes.begin(), m_graceNotes.end(), toChord(e));
+        IF_ASSERT_FAILED(i != m_graceNotes.end()) {
+            // do nothing
```
Comment (mike-spa) [inline src/engraving/dom/chord.cpp]: I'm sorry, my `// do nothing` suggestion was just a shorthand. Here I think you actually need to `break` out of the switch

**Review by mike-spa — APPROVED** [review]

**Comment by davidstephengrant** [comment]
This no longer crashes upon deletion, but there still seems to be some underlying issue deleting a selection including grace note(s).

1. Create some notes, preceded by a grace note.
2. Range-select the notes.
3. `Ctrl+Click` the last note in the selection to exclude it.
4. Delete.
5. Close the score
**RESULT:** CRASH

[Screencast from 2026-04-27 15-54-29.webm](https://github.com/user-attachments/assets/8b1394f8-3014-4a97-a521-d8fe79813a11)

------------------------------------

**Undo** after step 4 above does not reset the grace note as expected. Instead it draws with a straight flag, and the spacing to the following note is off. Closing the score after Undo still causes MSS to crash.

[Screencast from 2026-04-27 15-55-15.webm](https://github.com/user-attachments/assets/1eb4fa31-cb8a-42e4-b9ca-db43486f7907)

**Comment by silasvorne** [comment]
Yes, the fact that the state cannot be restored via undo is a known issue. 
Grace note duplication indeed causes other problems as well. 
This fix is merely the most direct and minimal solution for the crash triggered by deletion.

**Comment by RomanPudashkin** [comment]
@davidstephengrant please open a separate issue for this crash

**Comment by silasvorne** [comment]
Hi @RomanPudashkin @mike-spa 
I have a question regarding the branching strategy that I'd like to consult with you about. For changes submitted to version 4.7, will they be merged into the master branch altogether after the 4.7 release?
