### PR TITLE
Spacing tweaks

### LINKED ISSUE #27133: Spacing ratio not honored correctly
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. Enter a mixture of note values in a measure - 32nd, 16th, 8th
2. Set spacing ratio to 2.0

Result: each note has the same space, when the 8ths should have twice as much as the 16th etc.

This is a result of the change in the spacing algorithm to be more "top down" (or, I suppose, "middle out" - starting from the quarter note and calculating up or down from there).  Apparently, the default spacing for the quarter note is less than eight times the default minimum note distance, so 32nd notes can't get their "proper" size as defined by the ratio.

Workaround for the practical cases where one might care about this: reduce minimum note distance.  A value of 0.2sp seems to work reasonably well to allow the 2.0 ratio to achieve more or less equal measure widths in "most" cases where one might care about this.  It would of course produce very dense scores if you didn't *also* add system breaks, but the use cases for equal measure widths almost invariably also involve fixing system layout - typically at four bars per system.

I would propose, though, making the nominal quarter note spacing configurable.  This would allow one that much more control over the results.  We could even have pre-4.5 scores default to a larger value for compatibility if we wanted.  Or, for a more "automatic" solution, have the nominal quarter note spacing automatically increase - to at least four times minimum note distance - as the spacing ratio approaches 2.0.

### Supporting files, videos and screenshots

Image

Here is a "typical" passage of four bars rendered with ratio 2.0 and the default minimum note distance - you can see by the alignment between systems that the widths are not in fact equal:

Image

Here is the same example with minimum note distance of 0.2sp:

Image

### What is the latest version of MuseScore Studio where this issue is present?

OS: Debian GNU/Linux 12 (bookworm), Arch.: x86_64, MuseScore Studio version (64-bit): 4.5.0-250721848, revision: github-musescore-musescore-7c55023

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Debian 12

### Additional context

Works more as expected in 4.4.4:

Image

Sixteenths aren't twice 32nds, but I understand that is by design.

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mike-spa**
Tweaks spacing calculations. 

Additionally, removes the "Page" and "Measure" style pages, and moves the related settings into a new page called "Spacing", divided in "Vertical spacing" and "Horizontal spacing" respectively.

Resolves: https://github.com/musescore/MuseScore/issues/27133

### CODE REVIEW

File: src/engraving/style/style.cpp [hunk 1]
```diff
@@ -613,6 +613,11 @@ void MStyle::read(XmlReader& e, compat::ReadChordListHook* readChordListHook)
         }
     }
 
+    if (m_version == 450) {
```
Comment (cbjeukendrup) [inline src/engraving/style/style.cpp:618]: Why `== 450` instead of `< 460`?

Comment (mike-spa) [reply src/engraving/style/style.cpp:618]: Because we want this change to be specific to 450 :) Basically, this makes sure that 450 files look the same, while the normal default will look more similar to 440 and early

**Review by ghost — APPROVED** [review]

File: src/notation/view/widgets/editstyle.cpp [hunk 2]
```diff
@@ -878,8 +878,8 @@ EditStyle::EditStyle(QWidget* parent)
 
     // Define string here instead of in the .ui file to avoid MSVC compiler warning C4125, which would
     // be triggered by the decimal digit immediately following a non-ASCII character (curly quote).
-    oneMeasureRepeatShow1->setText(muse::qtrc("EditStyleBase", "Show ‘1’ on 1-measure repeats"));
-    singleMMRestShowNumber->setText(muse::qtrc("EditStyleBase", "Show number ‘1’"));
+    oneMeasureRepeatShow1->setText(muse::qtrc("EditStyleBase", "Show â€˜1â€™ on 1-measure repeats"));
```
Comment (miiizen) [inline src/notation/view/widgets/editstyle.cpp]: Uncrustify junk!

File: src/notation/view/widgets/editstyle.cpp [hunk 3]
```diff
@@ -1473,7 +1473,7 @@ void EditStyle::setHeaderFooterToolTip()
           + QString("</i></td></tr></table><p>")
           + muse::qtrc("notation/editstyle", "Available metadata tags and their current values")
           + QString("<br />")
-          + muse::qtrc("notation/editstyle", "(in File > Project properties…):")
+          + muse::qtrc("notation/editstyle", "(in File > Project propertiesâ€¦):")
```
Comment (miiizen) [inline src/notation/view/widgets/editstyle.cpp]: More uncrustify junk

File: src/notation/view/widgets/editstyle.ui [hunk 4]
```diff
@@ -14729,45 +14747,10 @@ followed by dashes</string>
   <tabstop>resetAutoplaceVerticalAlignRange</tabstop>
   <tabstop>minVerticalDistance</tabstop>
   <tabstop>resetMinVerticalDistance</tabstop>
-  <tabstop>scrollArea_page</tabstop>
```
Comment (miiizen) [inline src/notation/view/widgets/editstyle.ui:14732]: You'll need to reset the tab order on the new "Spacing" page using the "Edit Tab Order" button in the design view

**Review by miiizen — CHANGES_REQUESTED** [review]

**Review by miiizen — APPROVED** [review]
