### PR TITLE
Fix #30726: Welcome dialog & updater bug

### LINKED ISSUE #30726: Welcome dialog appears when auto-updater has finished downloading
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. Open 4.6.2 -> the update notification for 4.6.3 appears
2. Click "Install update"
3. As soon as the download is finished, the Welcome dialog appears, obscuring the dialog that MuseScore has to be closed to complete the update

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/ed322b81-b3b4-44df-a8ca-eb53b83396fc

### In which versions of MuseScore Studio is this issue present?

4.6.x

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

\* / macOS

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mathesoncalum**
Resolves: #30726

### CODE REVIEW

File: src/framework/stubs/update/updatescenariostub.cpp [hunk 1]
```diff
@@ -40,7 +40,9 @@ bool UpdateScenarioStub::hasUpdate() const
     return false;
 }
 
-muse::Ret UpdateScenarioStub::showUpdate()
+muse::async::Promise<muse::Ret> UpdateScenarioStub::showUpdate()
 {
-    return muse::make_ok();
+    return muse::async::make_promise<Ret>([](auto, auto) {
+        return muse::async::Promise<muse::Ret>::dummy_result();
```
Comment (cbjeukendrup) [inline src/framework/stubs/update/updatescenariostub.cpp]: Even though it's an unused stub, let's either resolve or reject

**Comment by zacjansheski** [comment]
Tested on MacOS 15, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/30726 FIXED
