### PR TITLE
Fix #26527: Crash with instrument changes and multi-measure rests (plus refactor)

### LINKED ISSUE #26527: Instrument changes and multi-measure rests
### Issue type

Crash or freeze

### Description with steps to reproduce

1. Create a new score with only 2 staves. 
2. Place an instrument change (any instrument) in the top staff anywhere in the piece. 
3. Toggle multi-measure rests ON (shortcut: M). Make sure the instrument change is sitting on top of a multi-measure rest. 
4. Close the score. 
5. Reopen the score. 

Expected behavior: Reopen the score as usual
Actual behavior: Crashes the program

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/b06ba3e6-9d25-4fd0-9912-fbdbd8a4fa2a

### What is the latest version of MuseScore Studio where this issue is present?

4.4.4

### Regression

I was unable to check

### Operating system

macOS 14.6.1

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mathesoncalum**
Resolves: #26527

The problem here is that we were only checking `channel->channel() != -1` - looks like we should also check the upper bound. If we don't, the later call to `m_midiMapping[channel->channel()]` will give us garbage data (which eventually causes problems in `reorderMidiMapping`).

The reason why the channel index is invalid in the first place is a little bit unclear to me. It looks like it gets invalidated in `removeDeletedMappings` when `channelExists` evaluates to false (so we pop the mapping from the `m_midiMapping` vector). For the purposes of fixing this crash this shouldn't matter, though. If `channelExists` evaluates to false in `doUpdateMidiMapping` we'll simply assign a new one.

The refactor aims to make things a little more robust & readable (there is a slight tradeoff with some data coupling in `doUpdateMidiMapping`, though).

### CODE REVIEW

File: src/engraving/dom/midimapping.cpp [hunk 1]
```diff
@@ -274,57 +274,68 @@ int MasterScore::updateMidiMapping()
...
-                    midiChannel = nm % 16;
-                }
+    return maxport;
+}
 
-                if (midiPort > maxport) {
-                    maxport = midiPort;
-                }
+void MasterScore::doUpdateMidiMapping(int& maxport, std::set<int>& occupiedMidiChannels, unsigned int& searchMidiMappingFrom,
+                                      Part* part, InstrChannel* channel, bool useDrumset)
```
Comment (RomanPudashkin) [inline src/engraving/dom/midimapping.cpp:289]: channel should be const (and part ideally)

**Review by RomanPudashkin — APPROVED** [review]

File: src/engraving/dom/midimapping.cpp (hunk 1 above)
Comment (mathesoncalum) [reply src/engraving/dom/midimapping.cpp:289]: I'm not sure we can (not without significant changes anyway) - the later call to `addMidiMapping` requires these to be mutable. I did notice that `const` was dropped from `instr` though, so I've re-introduced that.

**Comment by zacjansheski** [comment]
Tested on MacOS 15, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/26527 FIXED
