### PR TITLE
Fix #18764: Disallow kerning of noteheads over dots in the same voice

### LINKED ISSUE #18764: Improve trill cue note layout of dotted notes
### Issue type

Engraving bug

### Bug description

Trill cue notes should be placed right to the augmentation dots.

image
image

### Steps to reproduce

Create trills on some dotted notes and change the trill intervals, see the position of the cue notes.

### Screenshots/Screen recordings

_No response_

### MuseScore Version

4.1.0-231731239

### Regression

No.

### Operating system

Windows 10

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Nekotizimo**
Resolves: #18764

Added `computeNoteDotKerningType` as another special case in deciding kerning. Dots are still allowed to kern with other objects after it, like other notes and grace notes. I'm not sure if this should be allowed since to me it creates a similar visual clutter as trill cue notes did before, but perhaps this needs more consideration.

Before: 
Screenshot 2024-07-28 at 6 32 12 PM

After:
Screenshot 2024-07-28 at 6 32 16 PM

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

File: src/engraving/rendering/dev/horizontalspacing.h [hunk 1]
```diff
@@ -22,6 +22,9 @@
 #ifndef MU_ENGRAVING_HORIZONTALSPACINGUTILS_DEV_H
 #define MU_ENGRAVING_HORIZONTALSPACINGUTILS_DEV_H
 
+#include <dom/notedot.h>
+
+
```
Comment (cbjeukendrup) [inline src/engraving/rendering/dev/horizontalspacing.h:27]: This change looks unnecessary / unintended

Comment (Nekotizimo) [reply src/engraving/rendering/dev/horizontalspacing.h]: oops, removed

**Comment by oktophonie** [comment]
It would be better to disallow kerning over dots universally.
There are exceptions where some may be okay, for example where intervals get large (and stems are up, and there are no ledger lines):
image
But as a general solution it would be much better to just disallow it all circumstances.

**Comment by XiaoMigros** [comment]
I assume disabling auto-place for the note-dots would allow for kerning on specific occasions anyway

**Comment by Nekotizimo** [comment]
Now notes do not kern over dots if they are in the same voice. It does seem like disabling auto-place allows kerning over dots to some degree, but I think situations where that would be desirable are relatively rare. It probably only matters for double-or-more dots, where manual adjustments might be needed.

Default placement now: 

Screenshot 2024-08-03 at 12 32 56 PM
Screenshot 2024-08-03 at 12 33 05 PM

Accidentals are unaffected:
Screenshot 2024-08-03 at 12 33 12 PM

These cases are also unaffected because dots in one voice can be kerned by notes in other voices (in most cases probably)
Screenshot 2024-08-03 at 11 48 34 PM

**Review by oktophonie — APPROVED** [review]

File: src/engraving/rendering/dev/horizontalspacing.cpp [hunk 2]
```diff
@@ -608,6 +610,17 @@ KerningType HorizontalSpacing::computeNoteKerningType(const Note* note, const En
     return KerningType::KERNING;
 }
 
+KerningType HorizontalSpacing::computeNoteDotKerningType(const NoteDot* noteDot, const EngravingItem* item2)
```
Comment (mike-spa) [inline src/engraving/rendering/dev/horizontalspacing.cpp:613]: I don't think it's necessary to make special function for this. Unless I'm mistaken, if you just add `ElementType::NOTE_DOT` to the function `isSameVoiceKerningLimited` you'll get the same result more simple and more efficiently.

**Comment by RomanPudashkin** [comment]
@Nekotizimo please rebase your PR. There should only be 1 commit

**Review by oktophonie — APPROVED** [review]
