### PR TITLE
Fix #20780: Crash on PDF export (Master)

### LINKED ISSUE #20780: Sudden abort of pdf export
### Issue type

Crash or freeze

### Bug description

_No response_

### ### 
[ysaye sonatas.zip](https://github.com/musescore/MuseScore/files/13802322/ysaye.sonatas.zip)

### Screenshots/Screen recordings

When exporting pdf from this score, Musescore crashes after a second.

### MuseScore Version

4.2

### Regression

Yes, this worked in MuseScore 4.1.1

### Operating system

Windows 11

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mathesoncalum**
Resolves: #20780

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
This fix in itself looks fine to me, but I wonder if there isn't any more fundamental problem and whether we should fix that. 
I namely did some debugging for this crash a few days ago, and I seem to recall that chordRest() was nullptr because explicitParent() was a Barline and not a ChordRest. Looking at the constructors of Articulation, that seems not a usual situation. That could mean two things:
- We should either prevent the situation from occurring, or support it properly (of which your PR does the latter)
- Perhaps I was just seeing garbage in the debugger (i.e. meaningless values) as a result of read-after-delete, which means it's a memory management issue. That's unlikely though, because in that case Address Sanitizer should have complained but it didn't. 


So, I guess this PR is just fine, but I would like to hear some opinions from the engraving team about whether the situation is valid at all. @mike-spa Could you comment?

File: src/engraving/dom/articulation.cpp [hunk 1]
```diff
@@ -662,6 +662,15 @@ bool Articulation::isOnCrossBeamSide() const
     return chord->beam() && (chord->beam()->cross() || chord->staffMove() != 0) && (up() == chord->up());
 }
 
+staff_idx_t Articulation::vStaffIdx() const
+{
+    ChordRest* cr = chordRest();
+    if (!cr) {
+        return mu::nidx;
```
Comment (mike-spa) [inline src/engraving/dom/articulation.cpp:669]: Ok, two things :)
1) Here I would return `staffIdx()`, not `mu::nidx`, because the articulation still has a valid staff even though its parent isn't a ChordRest.
2) I did some investigation. @cbjeukendrup is right: the crash happens because the articulation (in this case a string down bow) has a BarLine as parent. This is how it got written into the file 
image

I found that this can happen if you drag&drop an articulation onto a barline (or select the barline and click the articulation from the palette). This operation shouldn't be allowed: fermatas are basically the only thing that can go on a barline. So I would go to Barline::acceptDrop and remove ARTICULATION from the accepted items. This should prevent the problem from occuring again. I would also ask maybe @DmitryArefiev or @zacjansheski if they could do some more testing around this type of situation (dropping items on barlines) to see that the problem doesn't involve other stuff too :)

**Comment by mathesoncalum** [comment]
Cheers @cbjeukendrup @mike-spa - pushed those changes and assigning @zacjansheski now.

**Review by cbjeukendrup — APPROVED** [review]

**Comment by zacjansheski** [comment]
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/20780 FIXED
