### PR TITLE
fixed #16774: Update announcement popup (for new releases) has poor UX / UI

### LINKED ISSUE #16774: Update announcement popup (for new releases) has poor UX / UI
### Issue type

UI bug

### Bug description

This is how the current announcement popup for 4.0.2 appears to the user:

image

Problems:

1. The title is weak. '**MuseScore 4.0.2 release**'. It should say '**A new version of MuseScore is available!**'
2. The scrollbar overlaps the text (see image above)
3. Headers in the description have bad formatting (showing three ###). These should use an appropriate text style
4. Text formatting is hard to read. For example the image below shows that bullet points are not indented and line spacing is too consistent, so different points are hard to distinguish from each other (this needs a design fix)
image

### Steps to reproduce

1. You'll need to install an earlier version of MuseScore to see this announcement.

### Screenshots/Screen recordings

_No response_

### MuseScore Version

4.0.2

### Regression

No.

### Operating system

MacOS

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Eism**
Resolves: #16774

The idea is to convert from markdown to HTML on the CI side and overwrite the data in the "body" in json. Old versions will receive the HTML version of the text and display it correctly in the dialog. The original markdown text will be stored in json under the key "bodyMarkdown" for the new versions of MuseScore.

For testing need to enable `checkForUpdateTestingMode` in `DevTools->Settings`

On this branch
image

4.0.2
image

### CODE REVIEW

**Review by igorkorsukov — APPROVED** [review]

File: src/update/internal/updateservice.cpp [hunk 1]
```diff
@@ -154,11 +154,14 @@ mu::RetVal<ReleaseInfo> UpdateService::parseRelease(const QByteArray& json) cons
...
     QJsonObject release = jsonDoc.object();
-    result.val.title = release.value("name").toString().toStdString();
-    result.val.notes = release.value("bodyMarkdown").toString().toStdString();
 
     QString tagName = release.value("tag_name").toString();
-    result.val.version = tagName.replace("v", "").toStdString();
+    QString version = tagName.replace("v", "");
+    result.val.version = version.toStdString();
+
+    result.val.notes = QString("### " + qtrc("update", "MuseScore") + " %1\n\n%2")
```
Comment (cbjeukendrup) [inline src/update/internal/updateservice.cpp:162]: I don't think this should be translatable. But if you think it should be, then we should include the version number in the translatable string, so `qtrc("update", "MuseScore %1")`

**Comment by Tantacrul** [comment]
@bkunda @oktophonie - I'll leave the sign off on this one to you.

**Review by bkunda — APPROVED** [review]

**Comment by bkunda** [comment]
Tested on macOS. Fixed.
