### PR TITLE
Fix #17068 Add new function for visibility of staff without unhiding …

### LINKED ISSUE #17068: [Instruments panel] Staves cannot be unhidden without first unhiding the associated instrument
### Issue type

Other type of issue

### Bug description

@bkunda  My expectation for this case is that the user is able to make visible in parts one (or more if available) of instrument staves, but it could be discussed if you don't agree.

@abariska my proposed solution is in the [comment below](https://github.com/musescore/MuseScore/issues/17068#issuecomment-1493335028).

Could be linked with https://github.com/musescore/MuseScore/issues/17066 and https://github.com/musescore/MuseScore/issues/17067

### Steps to reproduce

1. Open any score with 2+ instruments
2. Open a part
3. Make visible and invisible back one hidden instrument (if https://github.com/musescore/MuseScore/issues/17066 not fixed yet)
4. Expand the instrument drop-down
5. Try to make visible specific staves

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/101250347/228572815-43918737-2a37-49d1-85bc-4b975681d723.mp4

### MuseScore Version

MuseScore 4.0.2 

### Regression

No.

### Operating system

macOS 13

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vashutangri**
Resolves: #17068 

Added new function setIsVisibleFromStaffTreeItem to allow staves to be unhidden without unhiding the associated instrument first. 

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [x] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

File: src/instrumentsscene/view/abstractinstrumentspaneltreeitem.cpp [hunk 1]
```diff
@@ -258,6 +258,12 @@ void AbstractInstrumentsPanelTreeItem::setIsVisible(bool isVisible)
     }
 }
 
+void AbstractInstrumentsPanelTreeItem::setIsVisibleFromStaffTreeItem(bool isVisible)
+{
+    m_isVisible = isVisible;
```
Comment (Jojo-Schmitz) [inline src/instrumentsscene/view/abstractinstrumentspaneltreeitem.cpp:263]: As requested by a user on Discord, better add:
```
    if (m_isVisible == isVisible) {
        return;
    }
```
to avoid unneeded signaling

Comment (vashutangri) [reply src/instrumentsscene/view/abstractinstrumentspaneltreeitem.cpp:266]: Added to the function

File: src/instrumentsscene/view/abstractinstrumentspaneltreeitem.cpp [hunk 2]
```diff
@@ -258,6 +258,15 @@ void AbstractInstrumentsPanelTreeItem::setIsVisible(bool isVisible)
     }
 }
 
+void AbstractInstrumentsPanelTreeItem::setIsVisibleFromStaffTreeItem(bool isVisible)
+{
+    if(m_isVisible == isVisible) {
```
Comment (Jojo-Schmitz) [inline src/instrumentsscene/view/abstractinstrumentspaneltreeitem.cpp:263]: There's a space missing ;-)

File: src/instrumentsscene/view/abstractinstrumentspaneltreeitem.cpp [hunk 3]
```diff
@@ -258,6 +258,15 @@ void AbstractInstrumentsPanelTreeItem::setIsVisible(bool isVisible)
...
 
+void AbstractInstrumentsPanelTreeItem::setIsVisibleFromStaffTreeItem(bool isVisible)
+{
+    if (m_isVisible == isVisible) {
+        return;
+    }
+    m_isVisible = isVisible;
+    emit isVisibleChanged(isVisible);
+}
+
```
Comment (cbjeukendrup) [inline src/instrumentsscene/view/abstractinstrumentspaneltreeitem.cpp:269]: This new method is now almost completely a copy of the normal `setIsVisible` method. It would be better to merge the methods into one, and add an extra `bool setChildren` parameter, that will determine whether children items should be made visible or invisible too. 

Because `setIsVisible` is used as a setter for a Q_PROPERTY, the new parameter will need to have a default value of `true`.

Comment (vashutangri) [reply src/instrumentsscene/view/abstractinstrumentspaneltreeitem.cpp:269]: Okay, I'll do that. Just allow me a little time :D

File: src/instrumentsscene/view/stafftreeitem.cpp [hunk 4]
```diff
@@ -29,11 +29,14 @@ using namespace mu::notation;
 StaffTreeItem::StaffTreeItem(IMasterNotationPtr masterNotation, INotationPtr notation, QObject* parent)
     : AbstractInstrumentsPanelTreeItem(InstrumentsTreeItemType::ItemType::STAFF, masterNotation, notation, parent)
 {
-    connect(this, &AbstractInstrumentsPanelTreeItem::isVisibleChanged, [this](bool isVisible) {
+    connect(this, &AbstractInstrumentsPanelTreeItem::isVisibleChanged, [this](bool isVisible)
+    {
```
Comment (cbjeukendrup) [inline src/instrumentsscene/view/stafftreeitem.cpp:33]: This change seems unnecessary

File: src/instrumentsscene/view/stafftreeitem.cpp [hunk 5]
```diff
@@ -29,11 +29,14 @@ using namespace mu::notation;
...
         if (!m_isInited) {
             return;
         }
-
+        if (isVisible && !this->parentItem()->isVisible()) {
+            this->parentItem()->setIsVisible(true, false);
+        }
         this->notation()->parts()->setStaffVisible(id(), isVisible);
     });
```
Comment (cbjeukendrup) [inline src/instrumentsscene/view/stafftreeitem.cpp:41]: It would be great to add some newlines here for readability:
```suggestion

        if (isVisible && !this->parentItem()->isVisible()) {
            this->parentItem()->setIsVisible(true, false);
        }

        this->notation()->parts()->setStaffVisible(id(), isVisible);
    });
```

**Review by cbjeukendrup — COMMENTED** [review]
It's almost perfect now! I have only two stylistic remarks. (Yes, it's a bit nitpicky, but good code style is important to keep the code nice to work with.)

File: src/instrumentsscene/view/stafftreeitem.cpp (hunk 5 above)
Comment (vashutangri) [reply src/instrumentsscene/view/stafftreeitem.cpp:41]: Hey, thank you for the suggestion. Couldn't get back before due to some college work :( I've made the changes :D

**Review by cbjeukendrup — APPROVED** [review]

**Comment by abariska** [comment]
🟢 **TESTED**
