### PR TITLE
Fix #23089: Copy/pasting of trills

### LINKED ISSUE #23089: Trills do not copy/paste in master
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

When copy/pasting a trill or using "R" the trill does not appear.

### Steps to reproduce

Write a whole note with a trill
Copy and Paste that measure.  Or select measure and press "R"
Trill will not appear

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/1f45c92e-786f-4859-9367-5299cf8f0fc2

### MuseScore Version

OS: macOS 14.4, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-241560302, revision: github-musescore-musescore-2ce1f78

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Mac OS 14

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mathesoncalum**
Resolves: #23089
(Tiny) partial revert of #21633

### CODE REVIEW

**Review by mike-spa — APPROVED** [review]

**Comment by zacjansheski** [comment]
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/23089 FIXED

File: src/engraving/rw/write/twrite.cpp [hunk 1]
```diff
@@ -3394,6 +3394,19 @@ void TWrite::writeSegments(XmlWriter& xml, WriteContext& ctx, track_idx_t strack
             }
         }
 
+        // write spanners whose end tick lies outside the clip region
+        if (clip) {
+            for (Spanner* s : spanners) {
+                if ((s->tick2() == endTick)
+                    && !s->isSlur()
+                    && (s->track2() == track || (s->track2() == muse::nidx && s->track() == track))
+                    && (!clip || s->tick() >= sseg->tick())
```
Comment (cbjeukendrup) [inline src/engraving/rw/write/twrite.cpp:3403]: (Tiny remark: `!clip || ` in this line is redundant)
