### PR TITLE
[MU4] Fix #10406: Cannot drag elements from 'Master Palette' to 'Palettes'

### LINKED ISSUE #10406: Cannot drag elements from 'Master Palette' to 'Palettes'
**Describe the bug**

1. Cannot drag items from the **Master Palette** into **Palettes**
2. **Master Palette** window can get hidden behind main window (existing MS3 bug)

(See video)

https://user-images.githubusercontent.com/21022311/151660315-ee3ee2bc-3dc1-43cc-b95c-ba8151665f6e.mov

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Resolves: https://github.com/musescore/MuseScore/issues/10406

### CODE REVIEW

File: src/framework/uicomponents/view/topleveldialog.cpp [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+#include "topleveldialog.h"
+
+#include <QApplication>
+
+using namespace mu::uicomponents;
+
+TopLevelDialog::TopLevelDialog(QWidget* parent)
+    : QDialog(parent)
+{
+    setAttribute(Qt::WA_NativeWindow, true);
```
Comment (cbjeukendrup) [inline src/framework/uicomponents/view/topleveldialog.cpp:32]: I recall this window attribute was specific to the VST editors, because their content needs to be attached to a native window. I don't expect it will be necessary for all top level dialogs.

Comment (RomanPudashkin) [reply src/framework/uicomponents/view/topleveldialog.cpp]: Thank you! Fixed. But unfortunately, I had to remove the setTransientParent call from the constructor (now it will be called from TopLevelDialog::event). In the constructor, this call causes the crash of the application if the WA_NativeWindow attribute is not set.
