### PR TITLE
fixed #20578: ARM appimages removed after release

### LINKED ISSUE #20578: 4.2.0 ARM appimages removed after release
### Issue type

Other type of issue

### Bug description

Arm appimages were posted prior to yesterday on 4.2 release. Today they are gone.

### Steps to reproduce

Go to latest release page

### Screenshots/Screen recordings

_No response_

### MuseScore Version

4.2.0

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Linux

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Eism**
Resolves: #20578

The idea is to add a new field to the resulting JSON and handle this new field in the newer versions of MuseScore. The older versions will only work with the old field and process the list with a single MuseScore version per platform.

I've created a release with arm and aarch builds(from the latest release) for testing. To access it, you'll need to enable 'allowUpdateOnPreRelease' in the settings in DevTools -> Settings.

### CODE REVIEW

File: src/framework/global/internal/systeminfo.h [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+ *
+ * This program is distributed in the hope that it will be useful,
+ * but WITHOUT ANY WARRANTY; without even the implied warranty of
+ * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+ * GNU General Public License for more details.
+ *
+ * You should have received a copy of the GNU General Public License
+ * along with this program.  If not, see <https://www.gnu.org/licenses/>.
+ */
+#ifndef SYSTEMINFO_H
```
Comment (RomanPudashkin) [inline src/framework/global/internal/systeminfo.h:22]: MU_GLOBAL_SYSTEMINFO_H

File: src/framework/global/internal/systeminfo.h [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+class SystemInfo : public ISystemInfo
+{
+public:
+    SystemInfo();
+
+    CpuArchitecture cpuArchitecture() const override;
+    ProductType productType() const override;
+
+private:
+    std::map<std::string, Val> m_params;
```
Comment (RomanPudashkin) [inline src/framework/global/internal/systeminfo.h:41]: std::unordered_map might be better here

File: src/framework/network/networktypes.h [hunk 3]
```diff
@@ -24,6 +24,7 @@
 
 #include <QVariantMap>
 #include <QNetworkRequest>
+#include <QIODevice>
```
Comment (RomanPudashkin) [inline src/framework/network/networktypes.h:27]: Looks like we can use this instead:

class QIODevice;

File: src/update/internal/updateservice.cpp [hunk 4]
```diff
@@ -163,19 +150,64 @@ mu::RetVal<ReleaseInfo> UpdateService::parseRelease(const QByteArray& json) cons
...
+    return result;
+}
+
+std::string UpdateService::platformFileSuffix() const
+{
+    switch (systemInfo()->productType()) {
+    case ISystemInfo::ProductType::Windows: return "msi";
+    case ISystemInfo::ProductType::MacOS: return "dmg";
+    case ISystemInfo::ProductType::Linux: return "appimage";
+    default:
```
Comment (RomanPudashkin) [inline src/update/internal/updateservice.cpp:182]: It's better to avoid the default section

File: src/framework/global/internal/systeminfo.cpp [hunk 5]
```diff
@@ -0,0 +1,63 @@
...
+}
+
+SystemInfo::CpuArchitecture SystemInfo::cpuArchitecture() const
+{
+    return static_cast<CpuArchitecture>(m_params.at("cpuArchitecture").toInt());
+}
+
+SystemInfo::ProductType SystemInfo::productType() const
+{
+    return static_cast<ProductType>(m_params.at("productType").toInt());
```
Comment (RomanPudashkin) [inline src/framework/global/internal/systeminfo.cpp:62]: It's better to add global constant strings and use them

**Review by RomanPudashkin — APPROVED** [review]
