### PR TITLE
Bar number improvements

### LINKED ISSUE #29436: Measure numbers don't follow staff visibility or position
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

In 4.5.2, measure numbers show/hide with the staff as expected, but in 4.6 measure numbers don't hide (and move position) when the staff is hidden.
 
1. Create a score with multiple instruments and multiple staves in each instrument.
2. Enable measure number display.
3. Hide a staff from the second instrument.
4. Observe the measure number still is displayed and moved to the top instrument's staff.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/4ef3261c-b867-429d-9207-6cc4629123a4

### What is the latest version of MuseScore Studio where this issue is present?

OS: macOS Sequoia (15.6), Arch.: arm64, MuseScore Studio version (64-bit): 4.6.0-252340405, revision: github-musescore-musescore-28ffb89

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

macOS Sequoia 15.6.1

### Additional context

Bug also confirmed by FrancRos31 on MuseScore Discord.

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mike-spa**
Resolves: #29436 
Resolves: issue with score and layout panel updates connected to measure numbers from internal testing

### CODE REVIEW

**Review by ghost — APPROVED** [review]

File: src/notation/internal/notationparts.cpp [hunk 1]
```diff
@@ -860,6 +860,12 @@ void NotationParts::moveSystemObjects(const ID& sourceStaffId, const ID& destina
         score()->undoChangeStyleVal(Sid::systemObjectsBelowBottomStaff, false);
     }
 
+    AutoOnOff showMeasNumOnScrStaff = srcStaff->getProperty(Pid::SHOW_MEASURE_NUMBERS).value<AutoOnOff>();
```
Comment (miiizen) [inline src/notation/internal/notationparts.cpp]: Is this a typo - should it be `showMeasNumOnSrcStaff`?

**Review by miiizen — APPROVED** [review]
