### PR TITLE
Fix #25851: Crash when deleting multiple staves

### LINKED ISSUE #25851: Crash when erasing additional staves at once
Edited by @DmitryArefiev based on comments below

### Issue type

Crash or freeze

### Description with steps to reproduce

1. Create empty score from treble clef template
2. Add two new staves to piano instrument (see video by author)
3. Select them both and press delete button
4. Crash

(Can be reproduced on Organ instrument without adding new staves)

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/f513e3d0-6141-419f-a873-cd4eaaf1ab47

### What is the latest version of MuseScore Studio where this issue is present?

4.4.4, 4.5 nightly

### Regression

Yes, this used to work in **MuseScore 4.4.0**

### Operating system

all

### Additional context

_No response_

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mathesoncalum**
Resolves: #25851

Problem number 1 - using `cmdRemoveStaff` causes our staff indexes to update. This means that the indexes stored in `staffIndicesToRemove` become outdated, and we crash the next time we call `cmdRemoveStaff` with an invalid index.

Problem number 2 - `Staff` objects are deleted/nullified when we call `cmdRemoveStaff` & `apply`. This leads to a crash when we call `notifyAboutStaffRemoved` with a null pointer.

It's worth noting that #24207 has re-emerged, and problem number 2 seems to be the cause (re-resolved in this PR).

Once again, as mentioned [here](https://github.com/musescore/MuseScore/pull/24221#issue-2488908541), when testing this PR we should check that the requirements of #10526 haven't been broken by these changes.

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
Another option would probably be to just revert 2fee030a0bbe3c4bcb677a8e39e92a1dc14bc4a2. Maybe that's better, because I don't know if it's okay to call `notifyAboutStaffRemoved` before `apply`. It seems that there are no listeners for the notification caused by `notifyAboutStaffRemoved`, so it wouldn't matter much in practice right now, but still I feel not entirely comfortable about it.

File: src/notation/internal/notationparts.cpp [hunk 1]
```diff
@@ -196,32 +196,14 @@ std::vector<Staff*> NotationParts::staves(const IDList& stavesIds) const
     }
 
     for (Staff* staff : score()->staves()) {
-        if (muse::contains(stavesIds, staff->id())) {
+        if (std::find(stavesIds.cbegin(), stavesIds.cend(), staff->id()) != stavesIds.cend()) {
```
Comment (cbjeukendrup) [inline src/notation/internal/notationparts.cpp:199]: This doesn't make any difference right?

Comment (mathesoncalum) [reply src/notation/internal/notationparts.cpp]: Whoops you're right - un-reverted now 😁

**Review by cbjeukendrup — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
Tested #25851 on Win10, Mac13.6, LinuxUbuntu24.04.1 LTS - **FIXED**  

> Once again, as mentioned https://github.com/musescore/MuseScore/pull/24221#issue-2488908541, when testing this PR we should check that the requirements of https://github.com/musescore/MuseScore/pull/10526 haven't been broken by these changes.

All seems to be working as in master
