### PR TITLE
fix #12548 - fix non-functional custom-tuplet command

### LINKED ISSUE #12548: [MU4 Issue] Add / Tuplets / Other is non-functional
**Describe the bug**
The dialog box for Add / Tuplets / Other appears, but no matter what duration had been selected and no matter what choices you make in this dialog, no tuplet is actually created.

**To Reproduce**
1. New score, 4/4, treble staff
2. Measure 1, Note input mode
3. Select quarter note duration
4. Add / Tuplets / Other
5. Hit OK
6. 

**Expected behavior**
A tuplet is created

**Actual behavior**
No tuplet is created; the dialog closes having done nothing

**Platform information**
 - OS: Linux

**Additional context**
Same result if you try doing this from Normal mode.  Also, sometimes the dialog just doesn't appear.

### PR DESCRIPTION
**Pull request by wizofaus**
Resolves: [*(direct link to the issue)*](https://github.com/musescore/MuseScore/issues/12548)

*(short description of the changes and the motivation to make the changes)*

- [ x] I signed [CLA](https://musescore.org/en/cla)
- [ x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [ x] I made sure the code compiles on my machine
- [ x] I made sure there are no unnecessary changes in the code
- [ x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [ x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [ x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

File: src/notation/internal/notationactioncontroller.cpp [hunk 1]
```diff
@@ -164,7 +164,7 @@ void NotationActionController::init()
     registerAction("septuplet", [this]() { putTuplet(7); }, &Controller::noteOrRestSelected);
     registerAction("octuplet", [this]() { putTuplet(8); }, &Controller::noteOrRestSelected);
     registerAction("nonuplet", [this]() { putTuplet(9); }, &Controller::noteOrRestSelected);
-    registerAction("custom-tuplet", &Controller::putTuplet);
```
Comment (wizofaus) [inline src/notation/internal/notationactioncontroller.cpp:167]: Default "enabler" is that the notation window is active, which *isn't* true when this is sent from the tuplet dialog.

**Review by RomanPudashkin — APPROVED** [review]

**Comment by boryskuzmenko** [comment]
🟢 **TESTED on macOS 12, Win 11, Ubuntu 20**

Please, merge to master
