### PR TITLE
fix #13357 leading zeros on video duration

### LINKED ISSUE #13357: [MU4 Issue] "Learn" video durations displayed in non-standard format
**Describe the bug**
Video durations like 1:03 are displayed as 1:3

**To Reproduce**
1. Go Learn
2. Check duration of Muse Sounds video
3. See error: it displays as 1:3

**Expected behavior**
Should display as 1:03

**Screenshots**
image

**Platform information**
 - OS: Linux

**Additional context**
Same is visible for the "Four part writing" tutorial on the Advanced tab: "9:7"

### PR DESCRIPTION
**Pull request by jeetee**
Resolves: #13357 

Pre-applied modulo to determine leading zero necessity

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [N/A] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by jeetee** [comment]
This PR enforces double digits on both minutes and seconds. Perhaps it should be enhanced to only do double digits on minutes if there are hours to display? If so, I'll amend the commit.

File: src/learn/view/learnpagemodel.cpp [hunk 1]
```diff
@@ -134,9 +134,13 @@ QVariantList LearnPageModel::playlistToVariantList(const Playlist& playlist) con
     auto formatDuration = [](int durationSecs) {
         int seconds = durationSecs;
         int minutes = seconds / 60;
+        seconds -= minutes * 60;
         int hours = minutes / 60;
+        minutes -= hours * 60;
 
-        return (hours > 0 ? QString::number(hours) + ":" : "") + QString::number(minutes % 60) + ":" + QString::number(seconds % 60);
+        return (hours > 0 ? QString::number(hours) + ":" : "")
+               + ((minutes < 10) ? "0" : "") + QString::number(minutes) + ":"
```
Comment (Eism) [inline src/learn/view/learnpagemodel.cpp:142]: Or you can use QString::rightJustified like 
QString::number(seconds % 60).rightJustified(2, '0')

Comment (jeetee) [reply src/learn/view/learnpagemodel.cpp:142]: Wasn't aware of `rightJustified` but sure, that could be used as well.

Do we want this for minutes if hours == 0 too, or not?

Comment (jeetee) [reply src/learn/view/learnpagemodel.cpp:142]: Doesn't make sense for hours though imho, as there is never anything preceding it.
As such I'd only right justify if there is something before it (so always for seconds and for minutes only if there are hours). This would follow the model of many existing video sites (YouTube, Vimeo, ...)

Perhaps @bkunda has an opinion here?

Comment (Eism) [reply src/learn/view/learnpagemodel.cpp:142]: @jeetee yes, it makes sense with hours (like in YouTube).
Please fix this and we will merge your PR.

Comment (jeetee) [reply src/learn/view/learnpagemodel.cpp]: updated using rightJustified and following YouTube format logic in [d96e05e](https://github.com/musescore/MuseScore/pull/13992/commits/d96e05e0bb55abc5c2c534862c03cd1b2880f818)

**Review by Eism — APPROVED** [review]

**Comment by jeetee** [comment]
vtest failures are not related to this change

**Comment by Eism** [comment]
@jeetee Rebase needed to fix vtests

**Comment by jeetee** [comment]
> @jeetee Rebase needed to fix vtests

Does this mean that the vtests reference is not generated based on the PR master base commit? Not sure how easy it would be to make that so, so that vtests then effectively only test changes covered by the PR itself.

**Comment by cbjeukendrup** [comment]
The VTest compares [a merge commit from the PR with the base branch] with [the base branch of the PR, as retrieved by `github.event.pull_request.base.sha`]. I'm not sure what the latter means exactly and the documentation is absent or not findable, but it's probably the SHA of the base branch at the moment that you last pushed the PR branch.

**Comment by jeetee** [comment]
Opened a discussion at https://github.com/community/community/discussions/39880 for the base.sha possible issue/bug so that this topic is moved outside of this PR.
