### PR TITLE
Fix #24254: Allow manual XML formatting in headers/footers

### LINKED ISSUE #24254: Formatting header/footer text doesn't work any longer
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. Take the score from https://musescore.org/en/node/367489
2. See the header:
    image
3. Check Format > Style > Header/Footer and see:
     ```xml
      <font size="18"/><font face="Arial"/><b><i>$:workNumber:</i></b>
     ```
4. Open the same score with 4.3.2 and see:
    image

### Supporting files, videos and screenshots

see above

### What is the latest version of MuseScore Studio where this issue is present?

4.4/master

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11, but probably all others too

### Additional context

n/a

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mathesoncalum**
Resolves: #24254

The competing requirements make this a little treacherous. On the one hand we want these text boxes to accomodate XML formatting per the linked issue, but we don't want this to get in the way of most use cases (hence why we ignore character entities, for example - see #6515).

The idea with this change is to delay the replacement of text macros and perform two rounds of formatting. The first round will apply formatting according to the `TextStyleType` plus any manual XML formatting the user has specified, while the second round will replace the macros and apply their unique formatting (if any).

These changes are a bit quirky and not the most aesthetically pleasing, but this feels somewhat inevitable when dealing with TextBase-adjacent stuff...

### CODE REVIEW

File: src/engraving/dom/textbase.cpp [hunk 1]
```diff
@@ -1840,7 +1840,7 @@ void TextBase::createBlocks(LayoutData* ldata) const
                 state = 1;
                 token.clear();
             } else if (c == '&') {
-                state = 2;
+                state = 2; // why?
```
Comment (cbjeukendrup) [inline src/engraving/dom/textbase.cpp:1843]: Was this intended to be committed? 
(I think state 2 means entity parsing mode, i.e. `&amp;`, right?)

Comment (mathesoncalum) [reply src/engraving/dom/textbase.cpp:1843]: Whoops, nope - that was a note to self 😅

**Review by cbjeukendrup — APPROVED** [review]
Looks good, well done!

**Comment by zacjansheski** [comment]
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/24254 FIXED
