### PR TITLE
Fix #25702: Update shortcut definitions in "Playback settings" context without restarting

### LINKED ISSUE #25702: Shortcut definitions in "Playback settings" context menu don't update until restart
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

If you change any shortcuts that correspond to an option in the Playback settings context menu, the shortcut shown next to the option in the menu will not update until you restart MuseScore Studio.
Frame 7

1. Open Preferences > Shortcuts
2. Type in "MIDI"
3. Assign a shortcut to "Enable MIDI preferences" (if there is not one already)
4. Open the playback settings menu in the top bar
5. See that the shortcut is not listed (or it's not changed, if a shortcut existed previously)

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/9c158452-2e64-44c2-8ceb-2cdfb7814264

### What is the latest version of MuseScore Studio where this issue is present?

4.4.3 and nightlies

### Regression

No.

### Operating system

macOS 15.1

### Additional context

_No response_

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by pacebes**
Resolves: #25702 

This PR updates the shortcuts definition in Toolbars and Menus when the shortcuts definition changes. A fix for " _UiAction::operator==(const UiAction& other) const :_ " within uiaction.h has been included to make this PR work

- [X] I signed the [CLA](https://musescore.org/en/cla)
- [X] The title of the PR describes the problem it addresses
- [X] Each commit's message describes its purpose and effects, and references the issue it resolves
- [X] If changes are extensive, there is a sequence of easily reviewable commits
- [X] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [X] There are no unnecessary changes
- [X] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by avvvvve** [comment]
Looks good to me, thanks!

**Review by avvvvve — APPROVED** [review]

File: src/framework/uicomponents/view/abstracttoolbarmodel.cpp [hunk 1]
```diff
@@ -322,3 +326,19 @@ ToolBarItem& AbstractToolBarModel::item(const ToolBarItemList& items, const Acti
...
+
+    for (ToolBarItem* toolBarItem : m_items) {
+        if (!toolBarItem) {
+            continue;
+        }
+
+        UiAction action = toolBarItem->action();
+        action.shortcuts = screg->shortcut(action.code).sequences;
+
+        toolBarItem->setAction(action);
```
Comment (cbjeukendrup) [inline src/framework/uicomponents/view/abstracttoolbarmodel.cpp:342]: It looks like it would be necessary to update the ToolbarItem's `menuItems` too. Probably the best way to do that is by creating another method that takes a `std::vector<MenuItem*>` and updates those menu items, and recurses over those items' subitems.

File: src/framework/uicomponents/view/abstractmenumodel.cpp [hunk 2]
```diff
@@ -315,3 +319,30 @@ MenuItem& AbstractMenuModel::menu(MenuItemList& items, const QString& menuId)
     static MenuItem dummy;
     return dummy;
 }
+
+void AbstractMenuModel::updateShortcutsMenuItem(MenuItem* menuItem)
+{
+    auto screg = shortcutsRegister();
```
Comment (cbjeukendrup) [inline src/framework/uicomponents/view/abstractmenumodel.cpp:325]: This can just be inlined (i.e. no need for a variable).
Alternatively, if you want to call it less often, you could do the recursion a bit differently: instead of `MenuItem*`, let the recursive method take a `const std::vector<MenuItem*>&`

Comment (cbjeukendrup) [reply src/framework/uicomponents/view/abstractmenumodel.cpp]: Sorry, I wasn't aware of the mixed use of `QList` and `std::vector`. The conversion seems more cumbersome than the `shortcutsRegister` calls. Those are very lightweight anyway. So I've pushed another amendment myself.

**Comment by zacjansheski** [comment]
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/25702 FIXED
