### PR TITLE
[MU4] Fix #14582: Massive memory use trying to do Select All

### LINKED ISSUE #14582: [MU4 Issue] Massive memory use trying to do Select All
**Describe the bug**
When trying to use Ctrl+A to select all on a large score, more than 2 GB of memory use is added for the MU4 task. Deselecting and selecting again then continues to add more and more memory.

**To Reproduce**
1. Load attached score: 
[S4-piano.zip](https://github.com/musescore/MuseScore/files/10037758/S4-piano.zip)
2. Open Task Manager and note memory usage for MU4 process
3. Use Ctrl+A to try and select everything in the score
4. Watch memory usage in Task Manager rise
5. Deselect score by clicking in blank space
6. Repeat from step 3 (as long as your computer can take it)

**Platform information**
Using latest nightly build
OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.0-223210402, revision: github-musescore-musescore-089ce9f

**Additional context**
Using MuseSounds grand piano with no effects for playback.
Here's a video of the leak in action: https://youtu.be/Ae9sC93_cNM

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Resolves: https://github.com/musescore/MuseScore/issues/14582

### CODE REVIEW

File: src/notation/internal/notationinteraction.cpp [hunk 1]
```diff
@@ -734,9 +734,7 @@ void NotationInteraction::doSelect(const std::vector<EngravingItem*>& elements,
         }
     }
 
-    for (EngravingItem* element: elements) {
-        score()->select(element, type, staffIndex);
-    }
+    score()->select({ elements }, type, staffIndex);
```
Comment (cbjeukendrup) [inline src/notation/internal/notationinteraction.cpp:737]: Why is `{ elements }` here between braces? Is it to deliberately copy the vector before passing it to `score()->select(…)`, or is it a typo? :)

Comment (RomanPudashkin) [reply src/notation/internal/notationinteraction.cpp]: thank you! fixed

**Review by Eism — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
Tested on Win10, Mac12, LinuxUbuntu 22.04 - **PASS**
