### PR TITLE
Fix #21056: Don't add empty whole measure rests to second+ voices

### LINKED ISSUE #21056: Empty measure gets whole rest added in second voice
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

When changing duration of notes and rests in two voices, a whole rest in voice 2 could be automatically added to the following empty measure.

### Steps to reproduce

Empty score 4/4, one staff with two empty measures  - by default filled with whole rest in voice 1.
In the first measure select voice 2, quarter note, enter C1 four times.
Select note 3, change it to quarter rest.
Change this quarter rest to half rest - the following measure has full rests in voices 1 and 2.

### MuseScore Version

4.2.0

### Regression

No; v3 also

### Operating system

Windows 11

### PR DESCRIPTION
**Pull request by XiaoMigros**
Resolves: #21056

When changing note lengths in voices 2-4, a whole measure rest no longer gets added to the next measure. Historically this may have been needed for note input but it seems to work fine without.

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [ ] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

File: src/engraving/dom/cmd.cpp [hunk 1]
```diff
@@ -1752,14 +1751,6 @@ void Score::changeCRlen(ChordRest* cr, const Fraction& dstF, bool fillWithRest)
                 }
             }
         }
-        Measure* m  = cr1->measure();
-        Measure* m1 = m->nextMeasure();
-        if (m1 == 0) {
-            break;
-        }
-        Segment* s = m1->first(SegmentType::ChordRest);
-        expandVoice(s, track);
```
Comment (cbjeukendrup) [inline src/engraving/dom/cmd.cpp:1761]: Isn't it just the call to `expandVoice` that should be removed? Judging from what `flist` seems to be, it does seem crucial to move on to the next measure.

Comment (XiaoMigros) [reply src/engraving/dom/cmd.cpp:1761]: From what I can tell, moving to the next measure functions the same as it has previously. Maybe I am missing something?

Comment (cbjeukendrup) [reply src/engraving/dom/cmd.cpp:1761]: Sorry, my comment was a bit ambiguous. I meant: it seems important that each iteration of this loop uses a ChordRest/Segment from the next measure. 

With "moving to the next measure", I was referring to this code:
```
        Measure* m  = cr1->measure();
        Measure* m1 = m->nextMeasure();
        if (m1 == 0) {
            break;
        }
        Segment* s = m1->first(SegmentType::ChordRest);
        …
        cr1 = toChordRest(s->element(track));
```
which ensured that cr1 is from a different measure on each iteration of the loop.

Comment (cbjeukendrup) [reply src/engraving/dom/cmd.cpp:1761]: It seems that this can lead to a corruption:
1. Create this situation:
    Scherm­afbeelding 2024-02-12 om 03 34 03
    (second measure is copy of first, with the first two rests deleted)
2. Select the last rest of the first measure, and press '7' to turn that into a whole rest.
    The second measure gets corrupted:
    Scherm­afbeelding 2024-02-12 om 03 37 41
    Corruption info: "Voice too long: voice 2. Found: 5/4. Expected: 4/4."
    (weirder cases can be created by using different time signatures for example, like 3/8)

**Review by oktophonie — APPROVED** [review]

**Review by cbjeukendrup — APPROVED** [review]
