### PR TITLE
fix #9841 ensure properties panel values are updated while using mouse

### LINKED ISSUE #9841: [MU4 Issue] "Height" text edit field for vertical frames shows incorrect value
**Describe the bug**
There are a couple of related parts to this issue:
1. Changes made to the **Height** text edit field for vertical frames do not affect the actual frame height until only _after_ the user has manually adjusted the frame height with the grip handle. 
2. Manual adjustments to the height of a vertical frame only appear in the properties panel after the frame has been deselected and reselected.

https://user-images.githubusercontent.com/86290556/143019796-59786d69-e973-420d-982d-7214bfd114a8.mp4

**Expected behavior**
There should be a real time interface between the **Height** text field in the **Properties** panel and the corresponding vertical frame. 
Moreover, the user should be able adjust the frame height using either the text edit field or the grip handle, and in either case the frame height should be altered accordingly with the correct height value rendered in the text edit field. 

**Desktop (please complete the following information):**
 - MacOS 11.6 (M1)
 - Windows 11

### PR DESCRIPTION
**Pull request by wizofaus**
Resolves: [*(direct link to the issue)*](https://github.com/musescore/MuseScore/issues/9841) - or at least, the only part I could see was a problem...

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

File: src/inspector/models/notation/lines/hairpinsettingsmodel.h [hunk 1]
```diff
@@ -47,7 +47,6 @@ class HairpinSettingsModel : public TextLineSettingsModel
     void loadProperties() override;
     void resetProperties() override;
     void requestElements() override;
-    void updatePropertiesOnNotationChanged() override;
```
Comment (wizofaus) [inline src/inspector/models/notation/lines/hairpinsettingsmodel.h:50]: just inherits from textlinesettingsmodel

File: src/inspector/models/notation/frames/textframesettingsmodel.cpp [hunk 2]
```diff
@@ -69,6 +69,11 @@ void TextFrameSettingsModel::resetProperties()
     m_frameBottomMargin->resetToDefault();
 }
 
+void TextFrameSettingsModel::updatePropertiesOnNotationChanged()
+{
+    loadProperties();
+}
```
Comment (wizofaus) [inline src/inspector/models/notation/frames/textframesettingsmodel.cpp:75]: couldn't actually see how you could use the mouse/keyboard to modify text frame properties on the score but I'm assuming it's possible

**Comment by wizofaus** [comment]
Build failed due to transient network errors outside my control, and I don't seem to have any ability to relaunch.

**Review by RomanPudashkin — APPROVED** [review]
