### PR TITLE
Fix #19169: Smooth panning now limited to Continuous view (horizontal).

### LINKED ISSUE #19169: Smooth panning should work only in Continuous view (horizontal)
### Steps to reproduce

1. Select Preferences>Advanced>Smooth panning
2. Open a score in **Page view** or **Continuous view (vertical)**
3. Playback (see MS3 for reference)

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/ff499db6-36eb-4a3d-be04-29f771d8cca2

### MuseScore Version

4.2.0 master

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 10

### Additional context

#18718

### PR DESCRIPTION
**Pull request by mathesoncalum**
Resolves: #19169

### CODE REVIEW

File: src/notation/view/abstractnotationpaintview.cpp [hunk 1]
```diff
@@ -1289,7 +1289,8 @@ void AbstractNotationPaintView::movePlaybackCursor(midi::tick_t tick)
     }
 
     if (configuration()->isAutomaticallyPanEnabled()) {
-        if (configuration()->isSmoothPanning() && adjustCanvasPositionSmoothPan(newCursorRect)) {
+        if ((notation()->viewMode() == engraving::LayoutMode::LINE) && configuration()->isSmoothPanning()
+            && adjustCanvasPositionSmoothPan(newCursorRect)) {
```
Comment (RomanPudashkin) [inline src/notation/view/abstractnotationpaintview.cpp:1293]: it would be great to move adjustCanvasPositionSmoothPan to a separate if to slightly simplify this condition

**Review by RomanPudashkin — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
Tested #19169 on Win10, Mac13 - **FIXED**
