### PR TITLE
Make lyric lines selectable and editable

### LINKED ISSUE #30516: Lyric hyphens collide with barlines
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

Enter lyrics on a score where the barlines pass through where the lyrics are.
If there are hyphens, they often crash into the barlines

Image

### Supporting files, videos and screenshots

There is no way to shift the hyphens away from the barlines, nor is there an "avoid barlines" setting for lyric hyphens.  I think I would prefer being able to move the hyphens individually because our editors have specific ideas about where they should be in relation to barlines.

This is the Sib example file I used to make the above sample:

Image

### In which versions of MuseScore Studio is this issue present?

4.5.0 - 4.6.2

### Regression

I was unable to check

### Operating system

Windows 11

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### LINKED ISSUE #31398: Make lyric extension lines editable
1. Clicking on a lyric extension line should select it
2. Visibility toggle should work on it
3. In Properties, the heading would be: **Lyrics extension line**
4. We’d only show this options in Properties

Image

### PR DESCRIPTION
**Pull request by miiizen**
Resolves: #30516
Resolves: #31398 

This PR makes lyrics lines selectable in the score. Their position can be changed via offset in properties or by dragging. They can be made short or longer without reanchoring the start/end points. 
Thickness is also now configurable.

https://github.com/user-attachments/assets/1bf18ca9-fe30-4dbd-86fe-d3516de13dee

### CODE REVIEW

File: src/engraving/dom/line.cpp [hunk 1]
```diff
@@ -596,14 +596,6 @@ void LineSegment::rebaseAnchors(EditData& ed, Grip grip)
         return;
     }
 
-    if (isTrillSegment()) {
-        EngravingItem* startElement = spanner()->startElement();
-        if (startElement && startElement->isChord() && toChord(startElement)->staffMove() != 0) {
-            // This trill is on a cross-staff chord. Don't try to rebase its anchors when dragging.
-            return;
-        }
-    }
```
Comment (mike-spa) [inline src/engraving/dom/line.cpp:605]: Good one, thanks for the tidy up

File: src/engraving/dom/line.cpp [hunk 2]
```diff
@@ -771,6 +763,8 @@ void LineSegment::dragGrip(EditData& ed)
         }
     }
 
+    undoChangeProperty(Pid::GENERATED, false);
```
Comment (mike-spa) [inline src/engraving/dom/line.cpp]: This feels like a slightly weird place to do this, because:
- I think it's already handled somewhere at a lower level, EngravingObject::undoChangeProperty if I'm not mistaken. In other words any time any property is edited the element is also automatically un-flagged as generated, so I'm not 100% sure this is needed.
- If it only applies to lyrics lines should it perhaps go there, instead?

File: src/engraving/dom/lyrics.cpp [hunk 3]
```diff
@@ -91,7 +91,13 @@ TranslatableString Lyrics::subtypeUserName() const
 
 void Lyrics::add(EngravingItem* el)
 {
-    LOGD("Lyrics::add: unknown element %s", el->typeName());
+    if (el->isLyricsLine()) {
+        LyricsLine* separator = toLyricsLine(el);
+        m_separator = separator;
+        score()->addUnmanagedSpanner(separator);
```
Comment (mike-spa) [inline src/engraving/dom/lyrics.cpp:97]: Have you actually understood what "unmanaged spanners" are? Cause I never had the time to properly look into it so I really never did 😅

File: src/engraving/dom/lyrics.cpp [hunk 4]
```diff
@@ -591,4 +596,10 @@ void Lyrics::removeInvalidSegments()
         }
     }
 }
+
+void mu::engraving::PartialLyricsLine::setIsEndMelisma(bool val)
+{
+    m_isEndMelisma = val;
+    styleChanged();
```
Comment (mike-spa) [inline src/engraving/dom/lyrics.cpp]: Why `styleChanged()`? It looks a bit unrelated. If it's just about resetting some properties I'd consider doing that directly

File: src/engraving/dom/lyricsline.cpp [hunk 5]
```diff
@@ -40,24 +40,28 @@ namespace mu::engraving {
...
-    : SLine(ElementType::LYRICSLINE, parent, ElementFlag::NOT_SELECTABLE)
+    : SLine(ElementType::LYRICSLINE, parent)
 {
-    setGenerated(true);             // no need to save it, as it can be re-generated
     setDiagonal(false);
-    setLineWidth(style().styleS(Sid::lyricsDashLineThickness));
+    initElementStyle(&lyricsLineElementStyle);
     setAnchor(Spanner::Anchor::SEGMENT);
     m_nextLyrics = 0;
+    setGenerated(true);             // no need to save it, as it can be re-generated
```
Comment (mike-spa) [inline src/engraving/dom/lyricsline.cpp:54]: GENERATED is also a flag I believe, so you could add the flag to the constructor's arguments instead of setting it here

File: src/engraving/dom/utils.cpp [hunk 6]
```diff
@@ -1847,4 +1847,33 @@ std::vector<EngravingItem*> filterTargetElements(const Selection& sel, Engraving
     }
     return result;
 }
+
+Lyrics* searchNextLyrics(Segment* s, staff_idx_t staffIdx, int verse, PlacementV p)
```
Comment (mike-spa) [inline src/engraving/dom/utils.cpp:1870]: I am not a big fan of this utils class, as it ends up containing a miscellaneous of things that are completely unrelated to each other, whereas I've always felt that most of these utiliy functions could just be in their related DOM class, perhaps as static functions. But let's rethink about that another time, I've no problem with this staying here for now.

**Review by mike-spa — COMMENTED** [review]
Really great job, only minor comments

File: src/engraving/dom/lyrics.cpp (hunk 3 above)
Comment (miiizen) [reply src/engraving/dom/lyrics.cpp:97]: No not really! We could probably remove this distinction at this point.

File: src/engraving/dom/lyricsline.cpp (hunk 5 above)
Comment (miiizen) [reply src/engraving/dom/lyricsline.cpp:54]: Generated needs to be set to true after `initElementStyle` as any call to `undoChangeProperty` sets generated to false. The base class constructor where flags are set is called first.

**Comment by iainhallam** [comment]
Looks great! Is there any way to have the length snap to metrical boundaries, just like hairpins do? Then multiple parts could all be the same length, rather than approximately the same length.
