### PR TITLE
Fix #27168: Crash after note input from MIDI keyboard on deleted staff

### LINKED ISSUE #27168: Crash after note input from MIDI keyboard on deleted staff
### Issue type

Crash

### Description with steps to reproduce

1. MIDI keyboard should be connected as input device
2. Select staff 
3. Press N
4. Delete staff
5. Press any key on MIDI keyboard

(Case 2)

1. Delete all staves in score
2. Press any key on MIDI keyboard

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/05ca8651-ed4e-45bd-ada4-68caf8d79607

### What is the latest version of MuseScore Studio where this issue is present?

4.5.0

### Regression

Yes, this used to work in **MuseScore 4.4.4**

### Operating system

Windows, Mac

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Resolves: https://github.com/musescore/MuseScore/issues/27168

### CODE REVIEW

File: src/notation/internal/notationmidiinput.cpp [hunk 1]
```diff
@@ -173,35 +179,31 @@ void NotationMidiInput::startNoteInputIfNeed()
 void NotationMidiInput::addNoteEventsToInputState()
 {
     NoteValList notes;
-    bool useWrittenPitch = configuration()->midiUseWrittenPitch().val;
+
+    INotationNoteInputPtr noteInput = m_notationInteraction->noteInput();
+    const NoteInputState& state = noteInput->state();
+    const staff_idx_t staffIfx = state.staffIdx();
```
Comment (mathesoncalum) [inline src/notation/internal/notationmidiinput.cpp:185]: Typo? (`staffIfx`)

**Review by mathesoncalum — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
Tested #27168 on Win10, Mac13.7.2 - **FIXED**
