### PR TITLE
Cross beam spacing improvement

### LINKED ISSUE #16682: Inconsistencies with cross-stave spacing
### Issue type

UI bug

### Bug description

> This relates to general 10 from the discussion https://github.com/musescore/MuseScore/discussions/16674

This is the first half of the point raised in the discussion for this issue.

When working with cross staff notation, semi-quavers appear poorly spaced on the beam.

Consider the following screenshot
harp-layout-1

When compared to the same pattern notated on the same stave, the spacing on the beam is clearer and less "scrunched together".
semi-quaver-spacing

### Steps to reproduce

1 Create a new score with piano and any other instrument
2. Write a series of semi-quaver [chords]? over 1 or more bars on the piano. Use a single stave
3. Move every second note to the other stave. It doesn't matter which way round this is
4. Convert the other instruments to quaver rests

### Screenshots/Screen recordings

_No response_

### MuseScore Version

4.0.1

### Regression

I don't know

### Operating system

Ubuntu Studio 22.10

### Additional context

Rename this score to `.mscz`
[spacing-1.mscz.zip](https://github.com/musescore/MuseScore/files/10906800/spacing-1.mscz.zip)

### PR DESCRIPTION
**Pull request by mike-spa**
Resolves: https://github.com/musescore/MuseScore/issues/16682

Allow the spacing adjustment to be made even if another chord is present on a different voice/staff, as long as that chord is longer than the cross-beamed ones.

### CODE REVIEW

**Review by ghost — APPROVED** [review]

File: src/engraving/rendering/score/horizontalspacing.cpp [hunk 1]
```diff
@@ -879,11 +879,13 @@ HorizontalSpacing::CrossBeamSpacing HorizontalSpacing::computeCrossBeamSpacing(S
         if (!thisCR->visible() || thisCR->isFullMeasureRest() || (thisCR->isRest() && toRest(thisCR)->isGap())) {
             continue;
         }
-        if (!thisCR->beam()) {
+        Beam* beam = thisCR->beam();
+        if (!beam && thisCR->actualTicks() <= thisSeg->ticks()) {
```
Comment (miiizen) [inline src/engraving/rendering/score/horizontalspacing.cpp:883]: Should this be `<` like below? Can we guarantee that there is no other chord in this segment if `thisCR->actualTicks() == thisSeg->ticks()`?

Comment (mike-spa) [reply src/engraving/rendering/score/horizontalspacing.cpp:883]: Yes good catch, that was intended to be `<=`, but in the meantime I've realized this check was unnecessary to begin with. This is very fiddly territory in general. The difficulty is that we are altering the spacing in the presence of cross-staff beams (because cross-staff beams require equidistant stems, as opposed to equidistant noteheads) but we don't want this to have an adverse effect on the spacing of other notes on the same segments. My previous implementation was very restrictive in that it was preventing the cross-staff spacing adjustment any time the segment contained any other chord other than the cross-beamed one. But we realized we can be more lenient and still allow the correction to happen if that chord is longer than the duration of the segment itself (hence the `<=` check).

image

**Review by miiizen — APPROVED** [review]
