### PR TITLE
Fix #13535: Page number selection should be disabled

### LINKED ISSUE #13535: [MU4 Issue] Page numbers should not be selectable
**Describe the bug**
Page numbers are currently selectable, exposing a range of settings in the Properties panel that don't actually get saved to the score (changing these settings has a visible effect on the selected page numbers initially, but all changes are then lost when the score is closed and reopened again). 

See this discussion in [#12756](https://github.com/musescore/MuseScore/issues/12756#issuecomment-1257848021) for more info. 

**Expected behavior**
As a short-term solution, page numbers should not be selectable at all in order to avoid misleading the user. A more elegant solution could possibly be investigated for a 4.x release.

**Platform information**
 - MacOS, Win

### PR DESCRIPTION
**Pull request by HemantAntony**
Resolves: #13535

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

File: src/engraving/libmscore/score.cpp [hunk 1]
```diff
@@ -3320,8 +3320,15 @@ void Score::deselect(EngravingItem* el)
 
 void Score::select(EngravingItem* e, SelectType type, staff_idx_t staffIdx)
 {
-    // Move the playhead to the selected element's preferred play position.
     if (e) {
+        if (e->type() == ElementType::TEXT) {
```
Comment (RomanPudashkin) [inline src/engraving/libmscore/score.cpp:3324]: We have a special flag for such situations. You should use it instead of adding local solutions to this method

Screenshot 2022-09-30 at 11 09 39

**Comment by bkunda** [comment]
@HemantAntony there is a context menu that can still be triggered on right-click, which provides no usable options. 
Can this also be hidden too? 

Screenshot 2022-09-30 at 11 08 48 am

File: src/engraving/libmscore/text.cpp [hunk 2]
```diff
@@ -42,7 +42,7 @@ static const ElementStyle defaultStyle {
 //---------------------------------------------------------
 
 Text::Text(EngravingItem* parent, TextStyleType tid)
-    : TextBase(ElementType::TEXT, parent, tid)
+    : TextBase(ElementType::TEXT, parent, tid, tid == TextStyleType::HEADER ? ElementFlag::NOT_SELECTABLE : ElementFlag::NOTHING)
```
Comment (cbjeukendrup) [inline src/engraving/libmscore/text.cpp:45]: and what about footer? Probably should check for TextStyleType::FOOTER too.

**Comment by bkunda** [comment]
Thanks @HemantAntony, all works fine now. 
🟢 Ready to merge from my end. 
@RomanPudashkin @cbjeukendrup

**Comment by RomanPudashkin** [comment]
@HemantAntony please rebase it

**Review by RomanPudashkin — APPROVED** [review]

**Comment by HemantAntony** [comment]
@RomanPudashkin rebased
