### PR TITLE
[4.6.5] Fix #31486: No sound when clicking the next note with mouse

### LINKED ISSUE #31486: No sound when clicking the next note with mouse
### Issue type

General playback bug

### Description with steps to reproduce

https://github.com/user-attachments/assets/3dc85d6a-8c6f-4f8d-bf5d-7d9ce20c7988

### Supporting files, videos and screenshots

1

### In which versions of MuseScore Studio is this issue present?

4.6.5/4.7 nightly builds

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

Windows 10

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Resolves: https://github.com/musescore/MuseScore/issues/31486
Ports: https://github.com/musescore/MuseScore/pull/31490
Also see: https://github.com/musescore/MuseScore/pull/31503

### CODE REVIEW

File: src/notation/view/notationviewinputcontroller.cpp [hunk 1]
```diff
@@ -940,6 +942,11 @@ void NotationViewInputController::handleLeftClick(const ClickContext& ctx)
     }
 
     if (ctx.hitElement->isPlayable()) {
+        if (EngravingItem* playbackStartElement = resolveStartPlayableElement()) {
+            playbackController()->seekElement(playbackStartElement);
+            shouldSeek = false;
```
Comment (igorkorsukov) [inline src/notation/view/notationviewinputcontroller.cpp:947]: For the master, we need to think about how to do this better, which confuses me:
* For some cases we do it like this
```
some action 
seek to PlayableElement by DEFER 
```
* For another case we do this
```
seek to PlayableElement
some action 
```

Maybe it can be done like this for all cases
```
seek to PlayableElement (remove DEFER, instead )
some action 
```

If it really is different for different cases, then we probably need to remove the DEFER and clearly do it for different cases as needed. 

(This is only about possible changes in the master)

**Comment by DmitryArefiev** [comment]
Tested #31486 on Win10, Mac13.7.8, LinuxUbuntu24.04.3 LTS - **FIXED**
