### PR TITLE
Fix #28125: Crash removing selected measure numbers via Style dialog

### LINKED ISSUE #28125: Crash removing selected measure numbers via Style dialog (and Undo)
### Issue type

Crash or freeze

### Description with steps to reproduce

If you select a measure number and remove it via the measure numbers section of the style dialog, clicking OK will cause MuseScore to instantly crash.

Case 1 (all OSs)

1. Make a new score and right click a measure number at the left of the page.
2. Click on “Style...” in the pop up menu. (the measure number becomes highlighted)
3. Uncheck “Measure numbers”, click OK.
4. **Undo**
5. MuseScore will crash.

Case 2 (on **macOS** and **Linux**)

1. Make a new score and right click a measure number at the left of the page.
2. Open **Properties** panel
3. Click on “Style...” in the pop up menu. (the measure number becomes highlighted)
4. Uncheck “Measure numbers”, click OK.
5. MuseScore will crash.

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/d2947c62-f54c-431d-881b-b9b62d5a93b5

### What is the latest version of MuseScore Studio where this issue is present?

4.5.2

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 13.7.2

### Additional context

From trying to narrow it down myself, it seems that it crashes only if the number is selected first. No matter how you reach the style dialog, either by right-clicking the measure number or by going to Format > Style > Measure numbers, **if the number is selected it will crash**, but won't if it is not selected.
Also, in the same style dialog changing from the numbers appearing on "every system" to "interval" will have the same result.

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Resolves: https://github.com/musescore/MuseScore/issues/28125

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
Likely fixes the crash from https://github.com/musescore/MuseScore/pull/29055#issuecomment-3155242699

**Comment by RomanPudashkin** [comment]
Tested by @bkunda and @its-not-nice, approved

File: src/inspector/models/abstractinspectormodel.cpp [hunk 1]
```diff
@@ -814,7 +793,7 @@ void AbstractInspectorModel::beginCommand(const muse::TranslatableString& action
 
     //! NOTE prevents unnecessary updating of properties
     //! after changing their values in the inspector
-    m_updatePropertiesAllowed = false;
+    m_shouldUpdateOnScoreChange = false;
```
Comment (cbjeukendrup) [inline src/inspector/models/abstractinspectormodel.cpp:796]: @RomanPudashkin It seems we never set it to `true` again. Isn't that a problem?

Comment (RomanPudashkin) [reply src/inspector/models/abstractinspectormodel.cpp:796]: Yeah, there is a bug... Maybe we should set it to true in AbstractInspectorModel::endCommand() after commitChanges()

Comment (cbjeukendrup) [reply src/inspector/models/abstractinspectormodel.cpp:796]: Yeah, that seems a good solution indeed. I could verify that that doesn't break the purpose, i.e. updates from "inside" the model are still ignored.
