### PR TITLE
Fix #27056: wrong layout ordering when excerpt exists

### LINKED ISSUE #27056: Layout (Instruments) panel is not updated properly after adding new instrument (after open all parts)
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. Create score from Orchestral template
2. Open all part
3. Add Flute
4. Notice it appears at the bottom in Layout panel

All fine after reopening score

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/c077e896-7023-42c0-b8b8-4f2222978d6b

### What is the latest version of MuseScore Studio where this issue is present?

4.5

### Regression

No.

### Operating system

Windows 10

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by prodoelmit**
Resolves: #27056

`LayoutPanelTreeModel` receives masterParts that are already sorted as they are in score. So there is no need to try to reorder them based on some other criteria. 

(Though I'm not completely sure about it, so please let me know if I've missed something)

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [ ] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

File: src/instrumentsscene/view/layoutpaneltreemodel.cpp [hunk 1]
```diff
@@ -401,7 +401,8 @@ void LayoutPanelTreeModel::load()
     m_rootItem = new RootTreeItem(m_masterNotation, m_notation, this);
 
     async::NotifyList<const Part*> masterParts = m_masterNotation->parts()->partList();
-    sortParts(masterParts);
+    // We get parts from score where it's already well-ordered
+    //sortParts(masterParts);
```
Comment (RomanPudashkin) [inline src/instrumentsscene/view/layoutpaneltreemodel.cpp]: The user can reorder instruments in a part independently of the main score. The layout panel will also display the custom part order. This change breaks it: now the layout panel always shows the main score order ignoring the custom part order (on screenshot, Oboes should be above Flutes in the panel)

Screenshot 2025-09-17 at 14 28 26

Comment (prodoelmit) [reply src/instrumentsscene/view/layoutpaneltreemodel.cpp]: @RomanPudashkin thanks for explanation! I'll check how I can fix it better

Comment (prodoelmit) [reply src/instrumentsscene/view/layoutpaneltreemodel.cpp]: Pushed two commits. 

First one (58d6542) simply ignores reordering only for master score. 
Second (7b24d00) uses order of parts in excerpt's score to sort partList from master score. This way we get full list of parts but in locally correct order - all without storing any additional storing mechanisms (custom ordering list can be safely removed if this way is ok)

**Comment by DmitryArefiev** [comment]
Tested #27056 on Win10, Mac13.7.8 - **FIXED**

File: src/instrumentsscene/view/layoutpaneltreemodel.cpp [hunk 2]
```diff
@@ -442,6 +451,49 @@ void LayoutPanelTreeModel::load()
...
+
+    std::vector<ID> referenceIdOrder;
+    referenceParts.reserve(referenceParts.size());
+
+    for (const Part* part : referenceParts) {
+        referenceIdOrder.push_back(part->id());
+    }
+
+    LOGI("-----");
+    LOGI("Reference order:");
```
Comment (RomanPudashkin) [inline src/instrumentsscene/view/layoutpaneltreemodel.cpp]: @prodoelmit could you please remove all these logs?

Comment (prodoelmit) [reply src/instrumentsscene/view/layoutpaneltreemodel.cpp]: Yeah sure. If second way is ok for you, I'll prepare cleaned version

**Comment by prodoelmit** [comment]
@RomanPudashkin, cleaned it. 

While cleaning, I've also noticed couple bad decisions:

* Using usual `sort` may cause resorting of parts not enabled in part's view. Switched to `stable_sort` instead
* Comparing raw iterators isn't guaranteed by standard, so I've switched to comparing `std::distance`
