### PR TITLE
fix #20932: Save bracket colors

### LINKED ISSUE #20932: bracket color not saved
### Issue type

Opening/saving issue

### Bug description

The color information of brackets is not saved. 

### Steps to reproduce

1. add brackets to score
2. assign color to brackets
3. save score
4. reopen score

### Screenshots/Screen recordings

image

### MuseScore Version

4.2

### Regression

I don't know

### Operating system

macOS

### Additional context

Looking at the xml bracket is stored as a single bracket element with always four attributes. No place to put color.
 
`<bracket type="0" span="4" col="0" visible="1"/>`

### PR DESCRIPTION
**Pull request by rettinghaus**
Resolves: #20932

Extending the written attributes for each BracketItem by color if needed.

### CODE REVIEW

File: src/engraving/rw/write/twrite.cpp [hunk 1]
```diff
@@ -2805,12 +2805,20 @@ void TWrite::write(const Staff* item, XmlWriter& xml, WriteContext& ctx)
...
     for (const BracketItem* i : item->brackets()) {
+        XmlWriter::Attributes attrs;
         BracketType a = i->bracketType();
+        attrs.push_back({ "type", static_cast<int>(a) });
         size_t b = i->bracketSpan();
+        attrs.push_back({ "span", b });
         size_t c = i->column();
+        attrs.push_back({ "col", c });
         bool v = i->visible();
+        attrs.push_back({ "visible", v });
```
Comment (cbjeukendrup) [inline src/engraving/rw/write/twrite.cpp]: Let's avoid repeated `push_back`, like this:
```c++
XmlWriter::Attributes attrs {
    { "..." , ... },
    { "..." , ... },
};

File: src/engraving/rw/write/twrite.cpp [hunk 2]
```diff
@@ -2805,12 +2805,20 @@ void TWrite::write(const Staff* item, XmlWriter& xml, WriteContext& ctx)
...
+        if (i->color() != ctx.configuration()->defaultColor()) {
+            attrs.push_back({ "color", String::fromStdString(i->color().toString()) });
+        }
         if (a != BracketType::NO_BRACKET || b > 0) {
```
Comment (cbjeukendrup) [inline src/engraving/rw/write/twrite.cpp]: Let's do these checks at the top of the block, with `continue`

**Comment by rettinghaus** [comment]
@cbjeukendrup I've added a vtest, which fails as expected.
