### PR TITLE
Fix #13022: Crash when entering notes in unpitched instruments

### LINKED ISSUE #13022: [MU4 Issue] Crash when enter Note Input mode on unpitched percussion staves
**To Reproduce**
1. Click measure on **unpitched percussion stave**
2. Press N

https://user-images.githubusercontent.com/90187801/186890687-48890240-55cd-472f-9490-562f87f636c6.mp4

**Platform information**
macOS, Windows, Linux]

**Additional context**
Recent builds

### PR DESCRIPTION
**Pull request by HemantAntony**
Resolves: #13022

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by HemantAntony** [comment]
@RomanPudashkin I don't know if this is a good fix :)

File: src/engraving/libmscore/stem.cpp [hunk 1]
```diff
@@ -121,11 +121,15 @@ void Stem::layout()
...
-    // This way the bbox of the stem covers also the beam position. Hugely helps with all the collision checks.
-    double beamCorrection = chord()->beam() ? _up * score()->styleMM(Sid::beamWidth) * mag() / 2 : 0.0;
     // compute line and bounding rectangle
-    RectF rect(m_line.p1(), m_line.p2() + PointF(0.0, beamCorrection));
+    RectF rect(m_line.p1(), m_line.p2());
+    Chord* ch = chord();
+    if (ch) {
+        // HACK: if there is a beam, extend the bounding box of the stem (NOT the stem itself) by half beam width.
+        // This way the bbox of the stem covers also the beam position. Hugely helps with all the collision checks.
+        double beamCorrection = ch->beam() ? _up * score()->styleMM(Sid::beamWidth) * mag() / 2 : 0.0;
```
Comment (mike-spa) [inline src/engraving/libmscore/stem.cpp:130]: You can do this more simply by changing just one line of code:
`double beamCorrection = (chord() && chord()->beam()) ? _up * score()->styleMM(Sid::beamWidth) * mag() / 2 : 0.0;`

**Review by mike-spa — APPROVED** [review]
