### PR TITLE
fix #12153 - remove logic to change user-specified tempo

### LINKED ISSUE #12153: [MU4 Issue] New score with compound time has incorrect tempo
**Describe the bug**
Depending on the time signature and tempo mark picked when creating a new score, sometimes it uses the wrong value for the tempo.

**To Reproduce**
1. Go to 'Home'
2. Click on 'New Score'
3. Add an instrument and click next
4. Change the time signature to '6 8'
5. Change the tempo to 'dotted crochet = 60'
6. Click 'Done'
7. Observe the tempo on the score is 'dotted crochet = 40'

**Expected behavior**
It should be 'dotted crochet = 60'.
The tempo used on the score should be the same as what is selected in the new score wizard, regardless of the time signature.

**Screenshots**
image  
image  

**Platform information**
 - OS: Windows
 - Version: `MuseScoreNightly-202206240438-master-c8ce0c4-x86_64`

### PR DESCRIPTION
**Pull request by wizofaus**
Resolves: [*(direct link to the issue)*](https://github.com/musescore/MuseScore/issues/12153)

*(short description of the changes and the motivation to make the changes)*

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

File: src/notation/internal/masternotation.cpp [hunk 1]
```diff
@@ -333,53 +333,6 @@ void MasterNotation::applyOptions(mu::engraving::MasterScore* score, const Score
...
-        case 128:
-            if (ts.numerator() % 3 == 0) {
-                bpm *= 6;
-            } else {
-                bpm *= 16;
-            }
-            break;
-        default:
-            break;
-        }
```
Comment (wizofaus) [inline src/notation/internal/masternotation.cpp:382]: I can't find or think of a single case where this makes sense...

**Review by RomanPudashkin — APPROVED** [review]

File: src/notation/internal/masternotation.cpp (hunk 1 above)
Comment (olivercoad) [reply src/notation/internal/masternotation.cpp:382]: My guess is perhaps the original intention was something to do with this notion of [ticksPerBeat](https://github.com/musescore/MuseScore/blob/9daf58b89b9edcac9a15098fb37921f44a159220/src/notation/internal/notationinteraction.cpp#L4400)

**Comment by boryskuzmenko** [comment]
🟢 **FIXED**
Tested on macOS 12, Win 11, Ubuntu 20

Please, merge to master
