### PR TITLE
fixed #16104: No indication when error occurs while saving a file. 4.1

### LINKED ISSUE #16104: [MU4 Issue] No indication when error occurs while saving a file
**Describe the bug**
Users have reported that sometimes nothing happens when saving, nor when clicking "Save" in the "Do you want to save" dialog. The dialog just disappears, but the score stays unsaved, and MuseScore doesn't close.

**Proposed solution**
We should show a dialog that saving failed, preferably with detailed information about why, so that the user can do something about it.

Came up in:
- Discord (https://discord.com/channels/818804595450445834/818804809784229898/1068615895938773013)
- https://musescore.org/en/node/340287

### PR DESCRIPTION
**Pull request by Eism**
see https://github.com/musescore/MuseScore/pull/17369

### CODE REVIEW

File: src/framework/global/io/file.cpp [hunk 1]
```diff
@@ -86,23 +86,27 @@ bool File::remove()
...
+            setError(ret.code(), ret.text());
+        }
+
+        return ret;
     }
 
     if (!exists()) {
         if (m == OpenMode::ReadOnly) {
-            m_error = Error::ReadError;
+            setError(int(Err::FSReadError), "Opening non-existent file called on a read-only mode");
```
Comment (Jojo-Schmitz) [inline src/framework/global/io/file.cpp:99]: Shouldn't this be translatable?

File: src/project/internal/projectactionscontroller.cpp [hunk 2]
```diff
@@ -1141,7 +1142,7 @@ bool ProjectActionsController::askIfUserAgreesToSaveProjectWithErrors(const Ret&
 
     switch (static_cast<Err>(ret.code())) {
     case Err::NoPartsError:
-        warnScoreWithoutPartsCannotBeSaved();
+        warnScoreCouldnotBeSaved(trc("project/save", "Please add at least one instrument to enable saving."));
```
Comment (Jojo-Schmitz) [inline src/project/internal/projectactionscontroller.cpp:1145]: shouldn't this be translatable?

File: src/framework/global/io/file.cpp (hunk 1 above)
Comment (Jojo-Schmitz) [reply src/framework/global/io/file.cpp:99]: Also the string shpuld IMHO rather be "Opening non-existent file in a read-only mode"
