### PR TITLE
Fix #12376: Selected group becomes unselected when genre is changed

### LINKED ISSUE #12221: [MU4 Issue] Scrollbar colides with dropdown list in the New Score Wizard > Time Signature
**Describe the bug**

There's a scrollbar that appears over a dropdown list.
Also, is the scrollbar needed? Will there be more options there?
Scrolling with the mouse doesn't seem to work either way, only dragging the scrollbar.

**To Reproduce**

1. Open the New Score Wizard to create a new score
2. Add an instrument and click "Next"
3. Click "Time Signature"
4. Move your cursor to the right side of the pop-up
5. See the scroll bar

**Expected behavior**

Either the scrollbar placed more to the right, or not any scrollbar.

**Video**

https://user-images.githubusercontent.com/88064903/176571584-22cb5f24-d39f-4202-9bb5-41fcffd2810e.mp4

**Platform information**
 - OS: macOS Mojave 10.14.6
 - Tested on MuseScoreNightly-202206290442-master-9d40605.dmg | 2022-06-29 04:55 | 194M |

### LINKED ISSUE #12376: [MU4 Issue] Selected group becomes unselected when genre is changed in New Score Dialog and Instruments Dialog
**Describe the bug**
When you select an group and then you select a different genre in the New Score Dialog or the Instruments Dialog, the selected group becomes unselected

**To Reproduce**
1. Go to New Score Dialog
2. Click on a Group (eg: Keyboards)
3. Change the Genre to something else (eg: All instruments)
4. Keyboards become unselected

**Expected behavior**
The group should not be unselected when you change genres

**Screenshots**

https://user-images.githubusercontent.com/88136054/178723338-4386fab9-2b4f-476e-a56c-c900aefdcec8.mp4

**Platform information**
 - OS: Windows 11

### PR DESCRIPTION
**Pull request by HemantAntony**
Resolves: #12376 

*(short description of the changes and the motivation to make the changes)*

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by Tantacrul** [comment]
Tested it just now. It indeed fixes:

- https://github.com/musescore/MuseScore/issues/12221
- https://github.com/musescore/MuseScore/issues/12338
- https://github.com/musescore/MuseScore/issues/12376

@RomanPudashkin / @Eism: if you are happy, can this be merged?

File: src/instrumentsscene/view/instrumentlistmodel.cpp [hunk 1]
```diff
@@ -521,9 +539,9 @@ void InstrumentListModel::setCurrentGroup(const QString& groupId)
     loadInstruments();
 }
 
-void InstrumentListModel::doSetCurrentGroup(const QString& groupId)
+void InstrumentListModel::doSetCurrentGroup(const QString& groupId, bool compareWithCurrentGroup)
 {
-    if (m_currentGroupId == groupId) {
+    if (m_currentGroupId == groupId && compareWithCurrentGroup) {
```
Comment (RomanPudashkin) [inline src/instrumentsscene/view/instrumentlistmodel.cpp:544]: This code looks weird. Please explain why you need it

**Comment by RomanPudashkin** [comment]
Could you please move the first three commits to a separate PR (these changes can be merged right now)? https://github.com/musescore/MuseScore/issues/12376 requires much more testing/code-review

**Comment by HemantAntony** [comment]
@RomanPudashkin did that: #12393

File: src/instrumentsscene/view/instrumentlistmodel.cpp (hunk 1 above)
Comment (HemantAntony) [reply src/instrumentsscene/view/instrumentlistmodel.cpp:544]: Well the reason why was because if you were to just call `doSetCurrentGroup()` without my modification, the function would just check whether the current and the next groups are same. However, there are cases where the groups can be the same, but the index would vary. Index means the position of the group in the list

So if you don't consider that, then this will happen:

https://user-images.githubusercontent.com/88136054/178957159-c5386e21-22e2-48e0-8161-cbfc3aa1f28d.mp4


But now that you mention it, I think I should just add a check to see if the index is also the same inside the function rather than doing it outside the function.

File: src/instrumentsscene/view/instrumentlistmodel.cpp [hunk 2]
```diff
@@ -244,12 +244,18 @@ void InstrumentListModel::loadGroups()
...
+            currentGroupInNewGenre = true;
+            break;
+        }
+    }
+    if (!currentGroupInNewGenre && !isSearching()) {
+        setCurrentGroupIndex(0);
     }
 
-    doSetCurrentGroup(NONE_GROUP_ID);
+    emit currentGroupIndexChanged();
```
Comment (cbjeukendrup) [inline src/instrumentsscene/view/instrumentlistmodel.cpp:258]: Is this `emit` necessary? the signal is already emitted in `doSetCurrentGroup`, isn't it?

Comment (HemantAntony) [reply src/instrumentsscene/view/instrumentlistmodel.cpp:258]: The thing is, when you change the genre, `m_currentGroupId` remains same. But there is a chance that the index can change which is why emit that signal. In the following case, the index of "Keyboards" change:
[Screencast from 22-07-23 02:19:19 PM IST.webm](https://github.com/musescore/MuseScore/assets/88136054/fe1a1f76-0c9c-4dfb-9b69-13e4e511c905)

So you need to emit the changed signal, so the new index can be calculated

**Review by cbjeukendrup — APPROVED** [review]

**Comment by zacjansheski** [comment]
I found this weird issue and I am wondering if it has to do with my system.  I couldn't do it on the nightly, just on this build.  Only on my MacOS

Some of theses steps might not be necessary, but I think it might have to do with selecting a genre that makes the group disappear
1. Open new score wizard
2. Select Marching Genre
3. Select Percussion - Marching
4. Change Genre to Electronic Music
5. Select Electronic
6. Open Genre menu and close
7. Select Genre window again, it is behind the new score window

https://github.com/musescore/MuseScore/assets/69917893/204bb399-d4c6-4b5b-bedc-e06e5272029e

**Comment by zacjansheski** [comment]
The issue above is unrelated to this PR 

Tested on Mac OS 11.6.5, Ubuntu 20.04.6, Windows 11
https://github.com/musescore/MuseScore/issues/12376 FIXED
