### PR TITLE
Fix #25992: lower breath mark position

### LINKED ISSUE #25992: Questionable position of the breath mark for the 2nd voice
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

At the moment, the breath mark for the 2nd voice is not located outside the staff, but within. This causes a number of inconveniences and poor readability. 
Most likely, the breath mark for the 2nd voice should be located under the staff:
Снимок экрана (795)

### Supporting files, videos and screenshots

Take a look at the following example. Here, the breath mark collides with the tie, which clearly should not be and would not be if the breath mark were located outside the staff.

https://github.com/user-attachments/assets/452af561-044d-4d92-8665-c40a91d8e306

### What is the latest version of MuseScore Studio where this issue is present?

4.4.4 243461245, revision: 2232670

### Regression

I was unable to check

### Operating system

Windows 11

### Additional context

_No response_

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by rettinghaus**
Resolves: #25992

Bildschirmfoto 2026-03-18 um 15 50 34

### CODE REVIEW

**Comment by miiizen** [comment]
This looks good to me. Could you fix the code style please?

**Comment by davidstephengrant** [comment]
This looks good, but the position of breath marks for voice 2 or 4 will change when opening existing scores. These may well already have been manually offset to (visually) fix the issue. @miiizen Can do something for migrating older files?

**Comment by miiizen** [comment]
@davidstephengrant yes we can - I'd like to get my current offsets work merged first though.

File: src/engraving/rendering/score/tlayout.cpp [hunk 1]
```diff
@@ -1481,13 +1481,15 @@ void TLayout::layoutBreath(const Breath* item, Breath::LayoutData* ldata, const
         return;
     }
 
-    const double voiceOffset = item->placeBelow() ? item->staff()->staffHeight(item->tick()) : 0.0;
+    double voiceOffset = item->placeBelow() ? item->staff()->staffHeight(item->tick()) : 0.0;
```
Comment (Jojo-Schmitz) [inline src/engraving/rendering/score/tlayout.cpp]: Why loosing the `const`?

**Comment by Jojo-Schmitz** [comment]
Seems `chantCaesura` below needs some special treatment too?
image
Shouldn't it rather look like this (1sp or `symHeight()` down)?
image

Maybe something like this:
```cpp
    double voiceOffset = item->placeBelow() ? item->staff()->staffHeight(item->tick()) : 0.0;
    if (item->isCaesura()) {
        if (item->placeBelow() && (item->symId() == SymId::chantCaesura)) {
            voiceOffset += item->symHeight(item->symId());
        }
        ldata->setPosY(item->spatium() + voiceOffset);
...
```

**Comment by rettinghaus** [comment]
The problem with `chantCaesura` is, that the glyph is positioned matching the upper line of the `chantStaff` glyph in [SMuFL](https://w3c.github.io/smufl/latest/tables/medieval-and-renaissance-staves.html), just like all the _[pausae](https://de.wikipedia.org/wiki/Pausa_(Neume))_. So even trying to use `symHeight` will look odd. 

Since this glyph isn't available in Leland, it would probably be better to remove it from the palette.

Also, it should be clarified on SMuFL side, why there is this offset in the first place …

**Comment by Jojo-Schmitz** [comment]
The glyph for `chantCaesura`being missing from Leland is no reason at all to remove it from the palette, which IIRC uses Bravura anyway (and exactly for that reason, it is complete by definition).
And IMHO the image I provided looks OK, doesn't it?
Here enlarged:
image

An alternative would be to not move it down at all, draw the one for voice 2 and 4 at the same place as the one for voice 1 and 3

Or just leave it for another day and file a separate issue for it

**Comment by rettinghaus** [comment]
Ok, I've added a extra rule for `chantCaesura`:

breathmarks-1

Still I think this should be better adjusted on SMuFL side.

**Comment by Jojo-Schmitz** [comment]
Looks goot to me!

> Still I think this should be better adjusted on SMuFL side.

Same argument goes for the Emmentaler `breathMarkComma` special case and that is even in our hands.

**Comment by davidstephengrant** [comment]
Tested and approved on Ubuntu 24.04.4 LTS.

**Review by miiizen — APPROVED** [review]
