### PR TITLE
Fix 12287: Fixing tremolo positions for stemless notes

### LINKED ISSUE #11899: Crashes on score with stemless notation
Hi, not sure this is the correct place to report this.

 I am trying to open a file created in MS3.6 with MS4 but it crashes before opening. The file contains stemless notation, empty text frames (a box surrounding the notes created through staff text with empty content and a rectangular frame) and lines stretching across multiple lines. I also have a lot of hidden content (mostly rests from empty bars).
After some testing (I deleted elements one by one to see what stops loading the file) the crash seems to be caused by stemless notation. However, if I set my my score to display stems and add some other stemless notation to a different staff in MS3 the file opens correctly

### PR DESCRIPTION
**Pull request by asattely**
Resolves: https://github.com/musescore/MuseScore/issues/12287
(and also incidentally resolves the stemless notation crash mentioned in https://github.com/musescore/MuseScore/issues/11899)

Tremolo whole notes are now calculated as if the whole notes had stems, with some adjustment so that the tremolo will never be over the top of the notehead.
image

This also fixes #11899, which contained a regression due to the beams refactor #11788.

### CODE REVIEW

File: src/engraving/libmscore/chord.cpp [hunk 1]
```diff
@@ -1585,9 +1585,9 @@ int Chord::calc4BeamsException(int stemLength) const
 
 double Chord::calcDefaultStemLength()
 {
-    if (!_stem) {
+    /*if (!_stem) {
```
Comment (RomanPudashkin) [inline src/engraving/libmscore/chord.cpp:1588]: You should either remove this code or uncomment it

File: src/engraving/libmscore/tremolo.h [hunk 2]
```diff
@@ -42,6 +42,9 @@ enum class TremoloStyle : signed char {
 
 class Tremolo final : public EngravingItem
 {
+    // TODO: This should be a style setting, to replace tremoloStrokeLengthMultiplier
+    const double stemGapSp = 0.65;
```
Comment (RomanPudashkin) [inline src/engraving/libmscore/tremolo.h:46]: Please declare this in cpp. Also, it should be `static constexpr`

**Comment by asattely** [comment]
Done and done!

**Review by RomanPudashkin — APPROVED** [review]

File: src/engraving/libmscore/tremolo.cpp [hunk 3]
```diff
@@ -360,9 +372,6 @@ void Tremolo::layoutTwoNotesTremolo(double x, double y, double h, double spatium
     //---------------------------------------------------
     //   Step 1: Calculate the position of the tremolo (x, y)
     //---------------------------------------------------
-
-    y += (h - bbox().height()) * .5;
```
Comment (Jojo-Schmitz) [inline src/engraving/libmscore/tremolo.cpp:364]: This removal causes a MSVC compiler warning C4100 reg. "unreferenced formal parameter"  `double h`.
