### PR TITLE
fixed #10597: Dialogs icon

### LINKED ISSUE #10597: [MU4 Issue] Many dialog windows have missing app icon in the title bar on Windows
**Describe the bug**
Many dialog windows have missing app icon in title bar on Windows:
- "Do you want to save changes.." dialog
- New Score
- Parts
- Instruments
- Export
- Preferences
- Workspaces
- Create new workspaces
- Insert measures
- About MuseScore
- About MusicXML
- Check for update
- Revert to factory settings
- All dialogs from Diagnostic tab
- Migration dialog (import of previous version scores) 
- Error message dialog when trying to add text to a not single selected note
(Maybe I missed some dialogs..)

MU4
MU4 1
MU4 2

But some dialogs have app icon:
MU4 5

**Platform information**
 Windows (Win10)

**Additional context**
Doesn't occur in **MU3**

### PR DESCRIPTION
**Pull request by Eism**
Resolves: #10597

### CODE REVIEW

File: src/framework/uicomponents/view/popupwindow/popupwindow_qquickview.cpp [hunk 1]
```diff
@@ -63,6 +63,7 @@ void PopupWindow_QQuickView::init(QQmlEngine* engine, bool isDialogMode, bool is
     // dialog
     if (isDialogMode) {
         m_view->setFlags(Qt::Dialog);
+        m_view->setIcon(QIcon(uiConfiguration()->appIconPath().toString()));
```
Comment (cbjeukendrup) [inline src/framework/uicomponents/view/popupwindow/popupwindow_qquickview.cpp:66]: Wouldn't it be safer to set it app-wide? https://doc.qt.io/qt-6/qguiapplication.html#windowIcon-prop
Or does that not work?

Comment (Eism) [reply src/framework/uicomponents/view/popupwindow/popupwindow_qquickview.cpp:66]: Yes, this is of course preferable, I tried QGuiApplication::setWindowIcon, but it didn't work

**Comment by DmitryArefiev** [comment]
Tested #10597 on **Win10**, Mac13.6, LinuxUbuntu24.04.2 LTS - **FIXED**

**Review by RomanPudashkin — APPROVED** [review]
