### PR TITLE
Fix #29454 corruption when modifying second staff

### LINKED ISSUE #29454: Modifying second staff causes file corruption
### Issue type

File corruption

### Description with steps to reproduce

1. Open attached file Concerto_okay.mscz
2. Note that a second staff has been added under "Violino Solo"
3. Make any change to the new second staff.  For example, in measure 1 change the rests to eighth notes
4. File becomes corrupted:  **"Incomplete measure: Part score: Violin, measure 1, staff 2. Found: 5/4. Expected: 3/4."**
5. If you undo the change the file is okay and can be saved.
(See Concerto_corrupted.mscz for delta)

It looks like the issue occurs because of the open part

Problem exists in nightly build from 8/23/2025.

### Supporting files, videos and screenshots

Image

Image5

Image

Image

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 10 Version 22H2 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.6.0-252360408, revision: github-musescore-musescore-c8d5b25

### Regression

I was unable to check

### Operating system

Edition	Windows 10 Home Version	22H2 Installed on	‎12/‎5/‎2020 OS Build	19045.6218

### Additional context

[Concerto.zip](https://github.com/user-attachments/files/21958883/Concerto.zip)

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mike-spa**
Resolves: #29454 

When adding a new stave to the instrument, the operation was done independently in the score and in each part. The staves themselves were then linked across score and parts, but the contained full-measure rests were not. As a result, newly entered notes or rests were entered and synced correctly, but operations made on the exising rests (such as shortening the full-measure rest by selecting it and pressing a duration key) were not synced, which resulted in rests of wrong durations overfilling the measure in the part and causing the corruption.

The solution is to avoid adding the new stave independently in each part, but rather adding it to the main score and then doing a full clone of it the same way we do when creating parts.

EDIT Also worth clarifying: a file that's already corrupted, or even just saved after adding the new stave, cannot be fixed, cause all the links will be missing. This PR prevents the corruption from happening on new files.

### CODE REVIEW

File: src/notation/internal/notationparts.cpp [hunk 1]
```diff
@@ -611,6 +611,29 @@ bool NotationParts::appendStaff(Staff* staff, const ID& destinationPartId)
     return true;
 }
 
+bool NotationParts::appendStaffLinkedToMaster(Staff* staff, Staff* masterSourceStaff, const muse::ID& destinationPartId)
+{
+    TRACEFUNC;
+
+    IF_ASSERT_FAILED(staff && masterSourceStaff) {
+        return true;
```
Comment (mathesoncalum) [inline src/notation/internal/notationparts.cpp]: Why return true?

Comment (mike-spa) [reply src/notation/internal/notationparts.cpp]: Cause it's a mistake 😂 Thanks!

**Review by ghost — APPROVED** [review]

**Review by mathesoncalum — APPROVED** [review]
