### PR TITLE
Fix #18907 Accidental shows in TAB

### LINKED ISSUE #18907: Accidental is displayed on Tab staff when was added in Standard staff mode (or linked stave)
### Issue type

Engraving bug

### Bug description

It can't be reproduce in MU4.1

### Steps to reproduce

1. Create a score with guitar (Standard staff)
2. Add a note with accidental 
3. Change the staff type to Tab (or add a linked staff with Tab staff type)

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/101250347/f6e8d2b7-eef7-48d1-8568-917b3baa8eb4

### MuseScore Version

OS: macOS 13.4, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-232150302, revision: github-musescore-musescore-e5babf1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS 13

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mike-spa**
Resolves: #18907

### CODE REVIEW

File: src/engraving/rendering/dev/chordlayout.cpp [hunk 1]
```diff
@@ -1429,6 +1444,10 @@ void ChordLayout::layoutChords1(LayoutContext& ctx, Segment* segment, staff_idx_
     const track_idx_t partStartTrack = part ? part->startTrack() : startTrack;
     const track_idx_t partEndTrack = part ? part->endTrack() : endTrack;
 
+    if (isTab) {
+        skipAccidentals(segment, startTrack, endTrack);
```
Comment (igorkorsukov) [inline src/engraving/rendering/dev/chordlayout.cpp:1448]: And where is `acc->setSkipDraw(true);` set back in `acc->setSkipDraw(false);`?

**Comment by igorkorsukov** [comment]
It was not possible to find out why it used to work as it should, but now it doesn’t, what has changed?

File: src/engraving/rendering/dev/chordlayout.cpp (hunk 1 above)
Comment (mike-spa) [reply src/engraving/rendering/dev/chordlayout.cpp:1448]: Good point. I'll add it

**Review by igorkorsukov — APPROVED** [review]

**Review by abariska — APPROVED** [review]
