### PR TITLE
fix #26453: change tie import exclusion

### LINKED ISSUE #26453: Some ties crossing measures lost in MusicXML import
### Issue type

Import/export issue

### Description with steps to reproduce

Open the attached .mscz score, you can see that the chord is arpeggiated, with each quarter note tied into the chord in the second measure.

Export the file to MusicXML (or open the second attached file), then open it back in MuseScore:  only the last tie is left, the first three ties have disappeared.

Note that the ties are correctly written in the MusicXML, but they are discarded at import time.

#### Correct/expected result
Correct score

#### Obtained result after MusicXML import
Incorrect score after MusicXML export/import

#### Files
  - mscz: [test_musescore_ties_parsing.mscz.zip](https://github.com/user-attachments/files/18765193/test_musescore_ties_parsing.mscz.zip)
  - MusicXML: [test_musescore_ties_parsing.musicxml.zip](https://github.com/user-attachments/files/18765198/test_musescore_ties_parsing.musicxml.zip)

(Remove the `.zip` in the filenames)

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore Studio version (64-bit): 4.4.4-243461245, revision: github-musescore-musescore-2232670

### Regression

I was unable to check

### Operating system

OS: Pop!_OS 22.04 LTS, Arch.: x86_64 (AppImage version)

### Additional context

According to the following code, MuseScore seems to consider ties across bar lines not between directly successive notes as engraving errors, so skips them, but I believe that this is a valid case.
https://github.com/musescore/MuseScore/blob/f2e8da3a1b5b43eb9ec05bb1fbf8ce7b026111b6/src/importexport/musicxml/internal/musicxml/import/importmusicxmlpass2.cpp#L8707-L8710

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by rettinghaus**
Resolves: #26453

Just extends the exclusion rule for ties to accept all ties within a measure distance.

### CODE REVIEW

File: src/importexport/musicxml/internal/musicxml/import/importmusicxmlpass2.cpp [hunk 1]
```diff
@@ -8708,7 +8708,8 @@ static void addTie(const Notation& notation, Note* note, const track_idx_t track
             const Chord* startChord = startNote ? startNote->chord() : nullptr;
             const Chord* endChord = note->chord();
             const Measure* startMeasure = startChord ? startChord->measure() : nullptr;
-            if (startMeasure == endChord->measure() || (startChord && startChord->tick() + startChord->actualTicks() == endChord->tick())) {
+            if (startMeasure == endChord->measure()
+                || (startChord && startChord->tick() + startChord->measure()->ticks() >= endChord->tick())) {
                 // only connect if they're in the same bar, or there are no notes/rests in the same voice between them
```
Comment (miiizen) [inline src/importexport/musicxml/internal/musicxml/import/importmusicxmlpass2.cpp:8713]: If you could update the comment, that would be great!

**Review by miiizen — APPROVED** [review]
