### PR TITLE
Extend MusicXML color support

### LINKED ISSUE #17841: MusicXML import and export - Tie position above/below doesn't save in musicxml
### Issue type

Other type of issue

### Bug description

This is musescore file (both slur and tie explicitly positioned "below")
image

This is musicxml exported and opened in Musescore:
The position for slur saved correctly, but not for tie
image

If I open exported musicxml in text editor, there is "placement" attribute in slur element:
```xml
<slur type="start" placement="below" number="1"/>
```
and it's missing on tied element:
```xml
<tied type="start"/>
```
If I add placement attribute to the tied element, Musescore still cannot recognize it and will keep tie auto positioned.

### Steps to reproduce

1. Add two notes with a tie.
2. Change tie position
3. Export file to musicxml format
4. Open musicxml

### Screenshots/Screen recordings

_No response_

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231462149, revision: github-musescore-musescore-2be9061

### Regression

I don't know

### Operating system

OS: Windows 10 Version 2009

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rettinghaus**
This PR brings a major update to MusicXML support. Focusing on color, it brings some other addition and fixes.

Color support in detail:

  * color import/export for accidentals
  * color import/export for articulations
  * color import/export for barlines
  * color import/export for clefs
  * color import/export for fermatas
  * color import/export for figured bass
  * color import/export for hairpins
  * color import/export for keys
  * color import/export for ornaments
  * color import/export for pedal lines
  * color import/export for slurs and ties
  * color import/export for time signatures
  * color import/export for voltas
  * color export for arpeggios
  * color export for breath marks and caesuras
  * color export for chord symbols
  * color export for dynamics
  * color export for fingerings
  * color export for metronome
  * color export for rehearsal marks
  * color export for text lines
  * color export for tremolo
  * color export for jumps and markers

Further improvements:
  * import/export of curlew fermata
  * import/export of tuplet placement
  * improve import/export of barlines
  * improve import/export of accidental brackets
  * improve pedal style
  * improve figured bass
  * unify tie and slur handling
  * export WideDashed line style
  * export circled rehearsal marks
  * fix color for glissandos and slides
  * fix export of tempo change lines
  * fix export of dynamics extenders
  * new tests added

Fixes #17841

Also addresses most of #18159 (except for special text).
Also addresses `cresc.`/`dim.` line issue from #18158.

### CODE REVIEW

File: src/importexport/musicxml/internal/musicxml/exportxml.cpp [hunk 1]
```diff
@@ -3300,6 +3303,7 @@ void ExportMusicXml::chordAttributes(Chord* chord, Notations& notations, Technic
         if (mxmlTechn != "") {
             notations.tag(_xml, a);
             technical.tag(_xml);
+            mxmlTech += color2xml(a);
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/exportxml.cpp:3306]: `mxmlTechn`!

**Comment by RomanPudashkin** [comment]
Please rebase your PR. There should only be one commit. Thanks!

**Comment by rettinghaus** [comment]
@RomanPudashkin done.

**Review by RomanPudashkin — APPROVED** [review]

File: src/importexport/musicxml/internal/musicxml/exportxml.cpp [hunk 2]
```diff
@@ -4905,6 +4916,9 @@ void ExportMusicXml::hairpin(Hairpin const* const hp, staff_idx_t staff, const F
             } else {
                 tag += "\"diminuendo\"";
             }
+            if (hp->lineColor() != engravingConfiguration()->defaultColor()) {
+                tag += QString(" color=\"%1\"").arg(QString::fromStdString(hp->lineColor().toString()).toUpper());
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/exportxml.cpp:4920]: Exporting hairpin color, but not importing it?

File: src/importexport/musicxml/internal/musicxml/exportxml.cpp [hunk 3]
```diff
@@ -941,7 +941,9 @@ static void glissando(const Glissando* gli, int number, bool start, Notations& n
         break;
     }
     tagName += QString(" number=\"%1\" type=\"%2\"").arg(number).arg(start ? "start" : "stop");
-    tagName += color2xml(gli);
+    if (gli->lineColor() != engravingConfiguration()->defaultColor()) {
+        tagName += QString(" color=\"%1\"").arg(QString::fromStdString(gli->lineColor().toString()).toUpper());
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/exportxml.cpp:945]: I believe this could be done in color2xml(), check my backport to 3.x

File: src/importexport/musicxml/internal/musicxml/exportxml.cpp (hunk 2 above)
Comment (Jojo-Schmitz) [reply src/importexport/musicxml/internal/musicxml/exportxml.cpp:4920]: I believe this could be done in color2xml(), check my backport to 3.x

Comment (rettinghaus) [reply src/importexport/musicxml/internal/musicxml/exportxml.cpp:4920]: just noticed during testing that the existing implementation for glissando didn't work, so I fixed it. Happy to add import for hairpins.

File: src/importexport/musicxml/internal/musicxml/exportxml.cpp (hunk 3 above)
Comment (rettinghaus) [reply src/importexport/musicxml/internal/musicxml/exportxml.cpp:945]: indeed the more elegant solution, thanks.

Comment (Jojo-Schmitz) [reply src/importexport/musicxml/internal/musicxml/exportxml.cpp:945]: Pretty close to your earlier attempt

File: src/importexport/musicxml/internal/musicxml/exportxml.cpp [hunk 4]
```diff
@@ -659,7 +659,9 @@ static std::shared_ptr<mu::engraving::IEngravingConfiguration> engravingConfigur
 
 static QString color2xml(const EngravingItem* el)
 {
-    if (el->color() != engravingConfiguration()->defaultColor()) {
+    if (el->isSLine()) {
+        return QString(" color=\"%1\"").arg(((SLine*)el)->lineColor().name().toUpper());
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/exportxml.cpp:663]: This is needed as there is no `toSLine()` macro...

File: src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp [hunk 5]
```diff
@@ -3348,7 +3360,11 @@ void MusicXMLParserDirection::wedge(const QString& type, const int number,
         if (niente == "yes") {
             h->setHairpinCircledTip(true);
         }
-        starts.append(MusicXmlSpannerDesc(h, ElementType::HAIRPIN, number));
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:3351]: Sure this line can get dropped?

Comment (rettinghaus) [reply src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:3351]: sorry …

Comment (Jojo-Schmitz) [reply src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:3351]: And I'm not sure whether it needs before or after the color setting

Comment (Jojo-Schmitz) [reply src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:3351]: Or whether it matter at all

**Comment by Jojo-Schmitz** [comment]
I beliebe a unit and/or vtest is needed

File: src/importexport/musicxml/internal/musicxml/exportxml.cpp [hunk 6]
```diff
@@ -725,6 +727,11 @@ static QString slurTieLineStyle(const SlurTie* s)
     if (!lineType.isEmpty()) {
         rest = QString(" line-type=\"%1\"").arg(lineType);
     }
+    if (s->slurDirection() != engraving::DirectionV::AUTO) {
+        rest += QString(" type=\"start\" placement=\"%1\"")
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/exportxml.cpp:731]: That first part, `" type=\"start\""`needs to be written in any case, only the `placement`part is dependant of `slurDirection`. And the unit tests need to get adjusted for that.

**Comment by Jojo-Schmitz** [comment]
Maybe you can use this score as a test file
[color-test.zip](https://github.com/musescore/MuseScore/files/12497933/color-test.zip)

**Comment by Jojo-Schmitz** [comment]
Please see also my #17842, which collides/overlaps with this here

File: src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp [hunk 7]
```diff
@@ -6268,12 +6270,10 @@ static void addTie(const Notation& notation, Score* score, Note* note, const tra
             tie->setColor(color);
         }
 
-        if (orientation == "over") {
+        if (orientation == "over" || placement == "above") {
             tie->setSlurDirection(DirectionV::UP);
-        } else if (orientation == "under") {
+        } else if (orientation == "under" || placement == "below") {
             tie->setSlurDirection(DirectionV::DOWN);
-        } else if (orientation == "auto") {
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:6235]: why dropping the detection oa "auto"? Now in thsioe cases an error gets looged

Comment (rettinghaus) [reply src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:6235]: Because there is no value "auto", see https://www.w3.org/2021/06/musicxml40/musicxml-reference/data-types/over-under/

**Comment by rettinghaus** [comment]
@Jojo-Schmitz Yes, I stumbled upon #17842 yesterday. Would you be fine to close that one in favor of this here? I think my implementation is a bit nicer and cleans up the attribute structure of the MusicXML.

File: src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp (hunk 7 above)
Comment (Jojo-Schmitz) [reply src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:6235]: Ah, I see

File: src/importexport/musicxml/internal/musicxml/exportxml.cpp [hunk 8]
```diff
@@ -724,6 +726,11 @@ static QString slurTieLineStyle(const SlurTie* s)
     if (!lineType.isEmpty()) {
         rest = QString(" line-type=\"%1\"").arg(lineType);
     }
+    if (s->slurDirection() != engraving::DirectionV::AUTO) {
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/exportxml.cpp:729]: Can you add ` || configuration()->musicxmlExportLayout()` here (like #17842 does)?

File: src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp [hunk 9]
```diff
@@ -5768,10 +5799,15 @@ static void addSlur(const Notation& notation, SlurStack& slurs, ChordRest* cr, c
...
             newSlur->setTick(Fraction::fromTicks(tick));
             newSlur->setStartElement(cr);
+            const QColor color { notation.attribute("color") };
+            if (color.isValid()) {
+                newSlur->setColor(color);
+            }
             const auto pl = notation.attribute("placement");
-            if (pl == "above") {
+            const auto dir = notation.attribute("orientation");
+            if (pl == "above" || dir == "over") {
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:5808]: I like this way better than my #17842, but it is a different order, here the 1st (placement) wins, in mine the last (orientation) wins, so could you change the order?

File: src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp [hunk 10]
```diff
@@ -5768,10 +5799,15 @@ static void addSlur(const Notation& notation, SlurStack& slurs, ChordRest* cr, c
...
                 newSlur->setSlurDirection(DirectionV::UP);
-            } else if (pl == "below") {
+            } else if (pl == "below" || dir == "under") {
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:5810]: same here

File: src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp [hunk 11]
```diff
@@ -6228,12 +6265,15 @@ static void addTie(const Notation& notation, Score* score, Note* note, const tra
         tie->setStartNote(note);
         tie->setTrack(track);
 
-        if (orientation == "over") {
+        const QColor color { notation.attribute("color") };
+        if (color.isValid()) {
+            tie->setColor(color);
+        }
+
+        if (orientation == "over" || placement == "above") {
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:6273]: Here the order is the same as in my #17842, but different from your slur handling

File: src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp [hunk 12]
```diff
@@ -6228,12 +6265,15 @@ static void addTie(const Notation& notation, Score* score, Note* note, const tra
...
             tie->setSlurDirection(DirectionV::UP);
-        } else if (orientation == "under") {
+        } else if (orientation == "under" || placement == "below") {
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:6275]: same here

File: src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp (hunk 9 above)
Comment (Jojo-Schmitz) [reply src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:5808]: Or is the difference in slur and tie handling on purpose?

Comment (Jojo-Schmitz) [reply src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:5808]: In any case, please make it dependant of 
```cpp
 if (configuration()->musicxmlImportLayout()) {
```

File: src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp (hunk 11 above)
Comment (Jojo-Schmitz) [reply src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:6273]: This too should be dependant of
```cpp
 if (configuration()->musicxmlImportLayout()) {
```

**Comment by Jojo-Schmitz** [comment]
Please also include my testSlurTieDirection.xml unit test file

File: src/importexport/musicxml/tests/data/testTrackHandling.xml [hunk 13]
```diff
@@ -699,7 +699,7 @@
         <type>quarter</type>
         <stem>down</stem>
         <notations>
-          <slur type="start" placement="below" number="1"/>
+          <slur type="start" orientation="under" placement="above" number="1"/>
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/tests/data/testTrackHandling.xml:702]: ??? under __and__ above?

Comment (rettinghaus) [reply src/importexport/musicxml/tests/data/testTrackHandling.xml:702]: whooops, sorry.

File: src/importexport/musicxml/internal/musicxml/exportxml.cpp [hunk 14]
```diff
@@ -660,6 +660,8 @@ static QString color2xml(const EngravingItem* el)
 {
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/exportxml.cpp:660]: As color can be seen as belonging to layout, it might make sense to make this depandant of `configuration()->musicxmlExportLayout()`

Comment (rettinghaus) [reply src/importexport/musicxml/internal/musicxml/exportxml.cpp:660]: Yes, I was wondering the same. What about line-style?

Comment (Jojo-Schmitz) [reply src/importexport/musicxml/internal/musicxml/exportxml.cpp:660]: Same, I guess.
For color and export it'd be easy, but for color import it is not

Comment (Jojo-Schmitz) [reply src/importexport/musicxml/internal/musicxml/exportxml.cpp:660]: But needed in àddColorAttr()` below too

File: src/importexport/musicxml/internal/musicxml/exportxml.cpp [hunk 15]
```diff
@@ -724,6 +726,11 @@ static QString slurTieLineStyle(const SlurTie* s)
     if (!lineType.isEmpty()) {
         rest = QString(" line-type=\"%1\"").arg(lineType);
     }
+    if (s->slurDirection() != engraving::DirectionV::AUTO || configuration()->musicxmlExportLayout()) {
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/exportxml.cpp:729]: `ExportMusicXml::`missing here

Comment (rettinghaus) [reply src/importexport/musicxml/internal/musicxml/exportxml.cpp:729]: Yeah, thanks.

**Comment by Jojo-Schmitz** [comment]
I don't understend where the `Musicxml_Tests.voltaHiding1` failure comes from.
Nor the other failures

But my PR fails the exact same way after a rebase, soi I guess the default about MusicXML layout has changed (and ISTR to have seen such a changed, pretty recently)

**Comment by Jojo-Schmitz** [comment]
See fbc108e3

File: src/importexport/musicxml/tests/musicxml_tests.cpp [hunk 16]
```diff
@@ -769,6 +770,11 @@ TEST_F(Musicxml_Tests, restsNoType) {
 TEST_F(Musicxml_Tests, restsTypeWhole) {
     mxmlIoTestRef("testRestsTypeWhole");
 }
+TEST_F(Musicxml_Tests, slurTieDirection) {
+    setValue(PREF_IMPORT_MUSICXML_IMPORTLAYOUT, Val(true));
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/tests/musicxml_tests.cpp:774]: this is the new default anyhow

File: src/importexport/musicxml/tests/musicxml_tests.cpp [hunk 17]
```diff
@@ -769,6 +770,11 @@ TEST_F(Musicxml_Tests, restsNoType) {
...
+    mxmlIoTest("testSlurTieDirection");
+    setValue(PREF_IMPORT_MUSICXML_IMPORTLAYOUT, Val(false));
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/tests/musicxml_tests.cpp:776]: and this causes subsequent tests to fail

File: src/importexport/musicxml/tests/data/testTrackHandling.xml (hunk 13 above)
Comment (Jojo-Schmitz) [reply src/importexport/musicxml/tests/data/testTrackHandling.xml:702]: still/again?

File: src/importexport/musicxml/internal/musicxml/exportxml.cpp [hunk 18]
```diff
@@ -724,6 +734,11 @@ static QString slurTieLineStyle(const SlurTie* s)
     if (!lineType.isEmpty()) {
         rest = QString(" line-type=\"%1\"").arg(lineType);
     }
+    if (s->slurDirection() != engraving::DirectionV::AUTO) {
+        rest += QString(" orientation=\"%1\"").arg(s->up() ? "over" : "under");
+        rest += QString(" placement=\"%1\"").arg(s->up() ? "above" : "below");
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/exportxml.cpp:739]: I believe my PR had them the other way round?

File: src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp [hunk 19]
```diff
@@ -5761,18 +5792,31 @@ static void addSlur(const Notation& notation, SlurStack& slurs, ChordRest* cr, c
             if (cr->isGrace()) {
                 newSlur->setAnchor(Spanner::Anchor::CHORD);
             }
-            if (lineType == "dotted") {
-                newSlur->setStyleType(SlurStyleType::Dotted);
-            } else if (lineType == "dashed") {
-                newSlur->setStyleType(SlurStyleType::Dashed);
+            if (lineType == "dashed") {
+                tie->setStyleType(SlurStyleType::Dashed);
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:5796]: `newSlur`, not `tie`

File: src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp [hunk 20]
```diff
@@ -5761,18 +5792,31 @@ static void addSlur(const Notation& notation, SlurStack& slurs, ChordRest* cr, c
...
+            } else if (lineType == "dotted") {
+                tie->setStyleType(SlurStyleType::Dotted);
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:5798]: here too

File: src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp [hunk 21]
```diff
@@ -5761,18 +5792,31 @@ static void addSlur(const Notation& notation, SlurStack& slurs, ChordRest* cr, c
...
+            } else if (lineType == "solid") {
+                tie->setStyleType(SlurStyleType::Solid);
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:5800]: and here

File: src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp [hunk 22]
```diff
@@ -5761,18 +5792,31 @@ static void addSlur(const Notation& notation, SlurStack& slurs, ChordRest* cr, c
...
+                const auto orientation = notation.attribute("orientation");
+                const auto placement = notation.attribute("placement");
+                if (orientation == "over" || placement == "above") {
+                    newSlur->setSlurDirection(DirectionV::UP);
+                } else if (orientation == "under" || placement == "below") {
+                    newSlur->setSlurDirection(DirectionV::DOWN);
+                } else if (orientation == "" || placement == "") {
+                    // ignore
+                } else {
+                    logger->logError(QString("unknown slur orientation: %1").arg(orientation), xmlreader);
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:5818]: `logger->logError(QString("unknown slur orientation/placement: %1/%2").arg(orientation).arg(placement), xmlreader);`

File: src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp [hunk 23]
```diff
@@ -6228,22 +6273,29 @@ static void addTie(const Notation& notation, Score* score, Note* note, const tra
...
-        } else if (lineType == "dashed") {
+        if (configuration()->musicxmlImportLayout()) {
+            if (orientation == "over" || placement == "above") {
+                tie->setSlurDirection(DirectionV::UP);
+            } else if (orientation == "under" || placement == "below") {
+                tie->setSlurDirection(DirectionV::DOWN);
+            } else if (orientation == "" || placement == "") {
+                // ignore
+            } else {
+                logger->logError(QString("unknown tied orientation: %1").arg(orientation), xmlreader);
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:6289]: `logger->logError(QString("unknown tied orientation/placement: %1/%2").arg(orientation).arg(placement), xmlreader);`

File: src/importexport/musicxml/tests/data/testTrackHandling.xml [hunk 24]
```diff
@@ -1809,7 +1809,7 @@
         <stem>up</stem>
         <staff>1</staff>
         <notations>
-          <slur type="start" placement="above" number="1"/>
+          <slur type="start" orientation="over" number="1"/>
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/tests/data/testTrackHandling.xml:1812]: Needs both or none

File: src/importexport/musicxml/tests/data/testTrackHandling.xml [hunk 25]
```diff
@@ -1884,7 +1884,7 @@
         <stem>down</stem>
         <staff>1</staff>
         <notations>
-          <slur type="start" placement="below" number="1"/>
+          <slur type="start" orientation="under" number="1"/>
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/tests/data/testTrackHandling.xml:1887]: here too

File: src/importexport/musicxml/tests/data/testTrackHandling.xml [hunk 26]
```diff
@@ -2007,7 +2007,7 @@
         <stem>down</stem>
         <staff>2</staff>
         <notations>
-          <slur type="start" placement="below" number="1"/>
+          <slur type="start" orientation="under" number="1"/>
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/tests/data/testTrackHandling.xml:2010]: and here

File: src/importexport/musicxml/tests/data/testTrackHandling.xml [hunk 27]
```diff
@@ -2555,7 +2555,7 @@
         <type>quarter</type>
         <stem>up</stem>
         <notations>
-          <slur type="start" placement="above" number="1"/>
+          <slur type="start" orientation="over" number="1"/>
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/tests/data/testTrackHandling.xml:2558]: and here

File: src/importexport/musicxml/tests/data/testTrackHandling.xml [hunk 28]
```diff
@@ -2624,7 +2624,7 @@
         <type>quarter</type>
         <stem>down</stem>
         <notations>
-          <slur type="start" placement="below" number="1"/>
+          <slur type="start" orientation="under" number="1"/>
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/tests/data/testTrackHandling.xml:2627]: and here

**Comment by Jojo-Schmitz** [comment]
Import of slur and tie color doesn't work fully, it does show in the slur/tie's properties, but not in the score, very strange
Import of accidentals color doesn't work at all

**Comment by rettinghaus** [comment]
Yes, I noticed the strange thing with bows. Will investigate accidentals further.

File: src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp [hunk 29]
```diff
@@ -3786,6 +3807,9 @@ static void addKey(const KeySigEvent key, const bool printObj, Score* score, Mea
         keysig->setTrack(staffIdx * VOICES);
         keysig->setKeySigEvent(key);
         keysig->setVisible(printObj);
+        if (keyColor != QColor::Invalid) {
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:3810]: `.isValid()`

File: src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp [hunk 30]
```diff
@@ -4057,6 +4086,9 @@ void MusicXMLParserPass2::clef(const QString& partId, Measure* measure, const Fr
 
     Clef* clefs = Factory::createClef(s);
     clefs->setClefType(clef);
+    if (clefColor != QColor::Invalid) {
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:4089]: `.isValid()`

File: src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp [hunk 31]
```diff
@@ -4173,6 +4207,9 @@ void MusicXMLParserPass2::time(const QString& partId, Measure* measure, const Fr
                 Segment* s = measure->getSegment(SegmentType::TimeSig, tick);
                 TimeSig* timesig = Factory::createTimeSig(s);
                 timesig->setVisible(printObject);
+                if (timeColor != QColor::Invalid) {
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:4210]: `.isValid()`

File: src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp [hunk 32]
```diff
@@ -1034,8 +1034,12 @@ static void addArticulationToChord(const Notation& notation, ChordRest* cr)
     const SymId articSym = notation.symId();
     const QString dir = notation.attribute("type");
     const QString place = notation.attribute("placement");
+    const QColor color { notation.attribute("color") };
     Articulation* na = Factory::createArticulation(cr);
     na->setSymId(articSym);
+    if (color.isValid()) {
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:1040]: If we treat it as layout on export, we should on import too 

Here and all similar occurernces

File: src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp [hunk 33]
```diff
@@ -3348,6 +3364,11 @@ void MusicXMLParserDirection::wedge(const QString& type, const int number,
         if (niente == "yes") {
             h->setHairpinCircledTip(true);
         }
+        QColor color = QColor::Invalid;
+        color.setNamedColor(_e.attributes().value("color").toString());
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:3368]: `const QColor color { _e.attributes().value("color").toString() };`

Here and all similar occurences

File: src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp (hunk 32 above)
Comment (rettinghaus) [reply src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:1040]: On second thought, I really don't believe it is a part of the _layout_. (And it ist very easy to get rid of in the exported file.)

File: src/importexport/musicxml/internal/musicxml/exportxml.cpp [hunk 34]
```diff
@@ -712,18 +714,26 @@ static QString slurTieLineStyle(const SlurTie* s)
...
+    case SlurStyleType::Dashed:
+        lineType = "dashed";
+        break;
     case SlurStyleType::Dotted:
         lineType = "dotted";
         break;
-    case SlurStyleType::Dashed:
-        lineType = "dashed";
+    case SlurStyleType::Solid:
+        lineType = "solid";
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/exportxml.cpp:724]: I'd rather let it fall trough here, not writing the "solid" at all, being the default

File: src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp [hunk 35]
```diff
@@ -3654,8 +3674,8 @@ static Volta* findRedundantVolta(const track_idx_t track, const Measure* measure
 //   doEnding
 //---------------------------------------------------------
 
-void MusicXMLParserPass2::doEnding(const QString& partId, Measure* measure, const QString& number,
-                                   const QString& type, const QString& text, const bool print)
+void MusicXMLParserPass2::doEnding(const QString& partId, Measure* measure, const QString& number, const QString& type, const QString& text,
+                                   const bool print)
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:3678]: Why this chage?

File: src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp [hunk 36]
```diff
@@ -5761,18 +5791,31 @@ static void addSlur(const Notation& notation, SlurStack& slurs, ChordRest* cr, c
...
                 newSlur->setAnchor(Spanner::Anchor::CHORD);
             }
-            if (lineType == "dotted") {
-                newSlur->setStyleType(SlurStyleType::Dotted);
-            } else if (lineType == "dashed") {
+            if (lineType == "dashed") {
                 newSlur->setStyleType(SlurStyleType::Dashed);
+            } else if (lineType == "dotted") {
+                newSlur->setStyleType(SlurStyleType::Dotted);
+            } else if (lineType == "solid") {
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:5798]: here trest an empty string the same
```cpp
} else if (lineType="" || lineType == "solid") {
```
Or just rely on `lineType's initialisation further up

File: src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp [hunk 37]
```diff
@@ -6228,22 +6272,29 @@ static void addTie(const Notation& notation, Score* score, Note* note, const tra
...
+            } else {
+                logger->logError(QString("unknown tied orientation/placement: %1/%2").arg(orientation).arg(placement), xmlreader);
+            }
+        }
+
+        if (lineType == "dashed") {
             tie->setStyleType(SlurStyleType::Dashed);
+        } else if (lineType == "dotted") {
+            tie->setStyleType(SlurStyleType::Dotted);
+        } else if (lineType == "solid") {
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:6296]: See above, treat an empty sting as meaning solid

File: src/importexport/musicxml/internal/musicxml/exportxml.cpp [hunk 38]
```diff
@@ -712,18 +714,27 @@ static QString slurTieLineStyle(const SlurTie* s)
...
     case SlurStyleType::Dashed:
+        [[fallthrough]];
+    case SlurStyleType::WideDashed:
         lineType = "dashed";
         break;
+    case SlurStyleType::Dotted:
+        lineType = "dotted";
+        break;
+    case SlurStyleType::Solid:
+        [[fallthrough]];
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/exportxml.cpp:726]: `// FALLTHROUGH ` is more universal. But not needed here

File: src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp (hunk 35 above)
Comment (rettinghaus) [reply src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:3678]: ask uncrustify, I don't know …

**Comment by rettinghaus** [comment]
@Jojo-Schmitz accidental colors are not imported, because we completely ignore the `accidental` element at the moment.

**Comment by Jojo-Schmitz** [comment]
Slur/tie color is still not working apparently

File: src/importexport/musicxml/internal/musicxml/exportxml.cpp [hunk 39]
```diff
@@ -1325,12 +1334,28 @@ static void defaults(XmlWriter& xml, const MStyle& s, double& millimeters, const
     // TODO: also write default system layout here
     // when exporting only manual or no breaks, system-distance is not written at all
 
+    {
+        xml.startElement("appearance");
+        xml.tag("line-width", { { "type", "light barline" } }, s.styleD(Sid::barWidth) * 10);
```
[the remark this answers is not in the document]
Comment (Jojo-Schmitz) [reply src/importexport/musicxml/internal/musicxml/exportxml.cpp:1339]: I see, thanks. MusicXML has quite a frew more of the3se appearance settings, and as far as I cn tall all with MuseScore counterparts, check my PR

[the remark this answers is not in the document]
Comment (rettinghaus) [reply src/importexport/musicxml/internal/musicxml/exportxml.cpp:1339]: Yeah, why not export them all. Thanks!

File: src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp [hunk 40]
```diff
@@ -5761,18 +5808,32 @@ static void addSlur(const Notation& notation, SlurStack& slurs, ChordRest* cr, c
...
             newSlur->setTick(Fraction::fromTicks(tick));
             newSlur->setStartElement(cr);
-            const auto pl = notation.attribute("placement");
-            if (pl == "above") {
-                newSlur->setSlurDirection(DirectionV::UP);
-            } else if (pl == "below") {
-                newSlur->setSlurDirection(DirectionV::DOWN);
+            const QColor color { notation.attribute("color") };
+            if (color.isValid()) {
+                newSlur->setColor(color);
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:5823]: I believe adding `newSlur->setPropertyFlags(engraving::Pid::COLOR, engraving::PropertyFlags::UNSTYLED);` here would fix that strange partial import

File: src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp [hunk 41]
```diff
@@ -6228,22 +6290,29 @@ static void addTie(const Notation& notation, Score* score, Note* note, const tra
...
-            tie->setSlurDirection(DirectionV::DOWN);
-        } else if (orientation == "auto") {
-            // ignore
-        } else if (orientation == "") {
-            // ignore
-        } else {
-            logger->logError(QString("unknown tied orientation: %1").arg(orientation), xmlreader);
+        const QColor color { notation.attribute("color") };
+        if (color.isValid()) {
+            tie->setColor(color);
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:6295]: I believe adding `tie->setPropertyFlags(engraving::Pid::COLOR, engraving::PropertyFlags::UNSTYLED);` here would fix that strange partial import

File: src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp (hunk 40 above)
Comment (rettinghaus) [reply src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:5823]: No, it doesn't work there either. The color gets exported but not shown. It's a different MuseScore error.

Comment (Jojo-Schmitz) [reply src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:5823]: Ah!

Comment (Jojo-Schmitz) [reply src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:5823]: Hmm, it does work, after import, save, close, reopen

Comment (rettinghaus) [reply src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:5823]: Weird.

File: src/importexport/musicxml/internal/musicxml/exportxml.cpp [hunk 42]
```diff
@@ -2001,7 +2001,8 @@ void ExportMusicXml::barlineRight(const Measure* const m, const track_idx_t stra
     const Measure* mmRLst = mmR1->isMMRest() ? mmR1->mmRestLast() : 0;   // last measure of replaced sequence of empty measures
     // note: use barlinetype as found in multi measure rest for last measure of replaced sequence
     BarLineType bst = m == mmRLst ? mmR1->endBarLineType() : m->endBarLineType();
-    bool visible = m->endBarLineVisible();
+    const bool visible = m->endBarLineVisible();
+    const QString color = color2xml(m->endBarLine());
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/exportxml.cpp:2005]: `m->endBarLine()` can return `0`, and with that `color2xml()` crashes. Probably best to fix it there rather than here.

File: src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp [hunk 43]
```diff
@@ -3624,6 +3625,7 @@ void MusicXMLParserPass2::barline(const QString& partId, Measure* measure, const
     while (_e.readNextStartElement()) {
         if (_e.name() == "bar-style") {
             barStyle = _e.readElementText();
+            barlineColor = _e.attributes().value("color").toString();
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:3628]: I believe this is the wrong order, causing color import not to work
At least with that it works for double and end-barlines

**Comment by Jojo-Schmitz** [comment]
I'll do a detailed review tomorrow, esp. in comparison to my 3.x counterpart, which has a few more additions for coloring elements, but currently isn't fully working.
Seems I need a 3.x counterpart for `xmlRaw()`...

File: src/importexport/musicxml/tests/musicxml_tests.cpp [hunk 44]
```diff
@@ -47,11 +47,12 @@ extern engraving::Err importCompressedMusicXml(MasterScore*, const QString&);
 
 static const String XML_IO_DATA_DIR("data/");
 
-static const std::string MODULE_NAME("importexport");
+static const std::string MODULE_NAME("iex_musicxml");
 
 static const std::string PREF_EXPORT_MUSICXML_EXPORTBREAKS("export/musicXML/exportBreaks");
 static const std::string PREF_IMPORT_MUSICXML_IMPORTBREAKS("import/musicXML/importBreaks");
 static const std::string PREF_EXPORT_MUSICXML_EXPORTLAYOUT("export/musicXML/exportLayout");
+static const std::string PREF_IMPORT_MUSICXML_IMPORTLAYOUT("import/musicXML/importLayout");
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/tests/musicxml_tests.cpp:55]: Not needed (anymore). But probably doesn't harm either

File: src/importexport/musicxml/internal/musicxml/exportxml.cpp [hunk 45]
```diff
@@ -1322,15 +1331,62 @@ static void defaults(XmlWriter& xml, const MStyle& s, double& millimeters, const
...
+        xml.tag("line-width", { { "type", "slur tip" } }, s.styleD(Sid::SlurEndWidth) * 10);
+        xml.tag("line-width", { { "type", "staff" } }, s.styleD(Sid::staffLineWidth) * 10);
+        xml.tag("line-width", { { "type", "stem" } }, s.styleD(Sid::stemWidth) * 10);
+        xml.tag("line-width", { { "type", "tie middle" } }, s.styleD(Sid::SlurMidWidth) * 10);
+        xml.tag("line-width", { { "type", "tie tip" } }, s.styleD(Sid::SlurEndWidth) * 10);
+        xml.tag("line-width", { { "type", "tuplet bracket" } }, s.styleD(Sid::tupletBracketWidth) * 10);
+        xml.tag("line-width", { { "type", "wedge" } }, s.styleD(Sid::hairpinLineWidth) * 10);
+        // note size values in percent
+        xml.tag("note-size", { { "type", "cue" } }, s.styleD(Sid::smallNoteMag) * 100);
+        xml.tag("note-size", { { "type", "grace" } }, s.styleD(Sid::graceNoteMag) * 100);
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/exportxml.cpp:1380]: What about adding ```cpp
            // distance values in tenth
            xml.tag("distance type=\"beam\"", s->styleD(Sid::beamDistance) * 10);
            xml.tag("distance type=\"hyphen\"", s->styleP(Sid::lyricsDashPad) * 10); // Or lyricsDashMinDistance or lyricsDashMaxDistance?
´´´

File: src/importexport/musicxml/internal/musicxml/exportxml.cpp [hunk 46]
```diff
@@ -1730,10 +1786,11 @@ static void ending(XmlWriter& xml, Volta* v, bool left)
...
     QString voltaXml = QString("ending number=\"%1\" type=\"%2\"").arg(number, type);
     voltaXml += ExportMusicXml::positioningAttributes(v, left);
-    if (!v->visible()) {
-        voltaXml += " print-object=\"no\"";
-    }
     if (left) {
+        if (!v->visible()) {
+            voltaXml += " print-object=\"no\"";
+        }
+        voltaXml += color2xml(v);
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/exportxml.cpp:1793]: Maybe put this into an else branch? Ccolored but invisble doesn't make too much sense, does it?

File: src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp [hunk 47]
```diff
@@ -5204,7 +5255,16 @@ FiguredBass* MusicXMLParserPass2::figuredBass()
 {
     FiguredBass* fb = Factory::createFiguredBass(_score->dummy()->segment());
 
-    bool parentheses = _e.attributes().value("parentheses") == "yes";
+    const bool parentheses = _e.attributes().value("parentheses") == "yes";
+    const bool printObject = _e.attributes().value("print-object") != "no";
+    const QString placement = _e.attributes().value("placement");
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:5260]: a `.toString() `missing here?

Comment (rettinghaus) [reply src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp:5260]: indeed! thanks

File: src/importexport/musicxml/internal/musicxml/exportxml.cpp (hunk 46 above)
Comment (rettinghaus) [reply src/importexport/musicxml/internal/musicxml/exportxml.cpp:1793]: Well, it can be invisible BUT colored. Otherwise we would lose information.

File: src/importexport/musicxml/internal/musicxml/exportxml.cpp (hunk 45 above)
Comment (rettinghaus) [reply src/importexport/musicxml/internal/musicxml/exportxml.cpp:1380]: For the latter one I wasn't sure what the correct corresponding value would be. Maybe even `lyricsDashMaxDistance`? That's why I didn't add either.

File: src/importexport/musicxml/internal/musicxml/exportxml.cpp (hunk 46 above)
Comment (Jojo-Schmitz) [reply src/importexport/musicxml/internal/musicxml/exportxml.cpp:1793]: True, so I rest my case ;-)

File: src/importexport/musicxml/tests/musicxml_tests.cpp (hunk 44 above)
Comment (rettinghaus) [reply src/importexport/musicxml/tests/musicxml_tests.cpp]: Removed, thanks!

File: src/importexport/musicxml/internal/musicxml/exportxml.cpp (hunk 45 above)
Comment (Jojo-Schmitz) [reply src/importexport/musicxml/internal/musicxml/exportxml.cpp:1380]: `beamDistance` though seems pretty clear

Comment (Jojo-Schmitz) [reply src/importexport/musicxml/internal/musicxml/exportxml.cpp:1380]: Also this:
```cpp
xml.tag("note-size type=\"grace-cue\"", s->styleD(Sid::graceNoteMag) * s->styleD(Sid::smallNoteMag) * 100);
```

Comment (rettinghaus) [reply src/importexport/musicxml/internal/musicxml/exportxml.cpp:1380]: Couldn't find a value for `beamDistance`. It is also not loaded from engraving defaults: 
[ "beamSpacing" handled separately](https://github.com/musescore/MuseScore/blob/64cebb064fe444cb90caad6c7236990655714a8a/src/engraving/internal/engravingfont.cpp#L437)

Comment (oktophonie) [reply src/importexport/musicxml/internal/musicxml/exportxml.cpp:1380]: `beamDistance` (which is not in the SMuFL spec) was removed in 4.0

**Comment by Jojo-Schmitz** [comment]
Further possible additions (for export at least): caesuras/breaths, jumps and markers

**Comment by rettinghaus** [comment]
@Jojo-Schmitz arpeggios are already handled.

**Comment by Jojo-Schmitz** [comment]
Import of arpeggion color doesn't seem to work though

**Comment by Jojo-Schmitz** [comment]
Why did you remove the export of system defaults?

**Comment by rettinghaus** [comment]
@Jojo-Schmitz I'm working on an implementation that also handles the import. PR is coming soonish.

**Comment by Jojo-Schmitz** [comment]
rebase needed

**Review by oktophonie — APPROVED** [review]

File: src/importexport/musicxml/tests/musicxml_tests.cpp [hunk 48]
```diff
@@ -659,9 +667,6 @@ TEST_F(Musicxml_Tests, keysig1) {
 TEST_F(Musicxml_Tests, keysig2) {
     mxmlIoTest("testKeysig2");
 }
-TEST_F(Musicxml_Tests, layout) {
-    mxmlIoTest("testLayout", true);
```
Comment (RomanPudashkin) [inline src/importexport/musicxml/tests/musicxml_tests.cpp:663]: @rettinghaus @Jojo-Schmitz why did you remove these unit-tests?

"testLayout"
"testNoteheads2"
"testSystemDistance"
"testSystemDividers"

Comment (rettinghaus) [reply src/importexport/musicxml/tests/musicxml_tests.cpp:663]: Must have happened during rebasing after #19972. I'll fix this.

Comment (rettinghaus) [reply src/importexport/musicxml/tests/musicxml_tests.cpp]: @RomanPudashkin fixed and ready to merge.
