### PR TITLE
Fix #23144: Don't enable arrange section unless element has `Page` ancestor

### LINKED ISSUE #23144: Crash when sending bracket to back
### Issue type

Crash or freeze

### Bug description

Sending a system bracket to the back via the properties pane reliably crashes MuseScore

### Steps to reproduce

1. Create a new score with a bracket (e.g. Piano, any ensemble template)
2. Select the bracket
3. Select "appearance" in the properties panel
4. Click "Send to back"
5. Crash!

### Screenshots/Screen recordings

_No response_

### MuseScore Version

4.3.1

### Regression

No

### Operating system

Windows 11

### Additional context

Using master, this is the stack trace on crash:

'MuseScore4.exe' (Win32): Loaded 'C:\Windows\System32\sxs.dll'. 
Exception thrown at 0x0000000140ABA381 in MuseScore4.exe: 0xC0000005: Access violation reading location 0x00000000000000B8.

[1;31m10:24:44.045 | ERROR | main_thread     | crashCallback   | Oops! Application crashed with signal: [11] SIGSEGV-Invalid memory reference[0m

MuseScore4.exe!mu::engraving::Page::scanElements(mu::engraving::Spanner * data) Line 243
	at C:\MS4\src\engraving\dom\page.cpp(243)
MuseScore4.exe!mu::engraving::Page::elements() Line 477
	at C:\MS4\src\engraving\dom\page.cpp(477)
MuseScore4.exe!mu::inspector::AppearanceSettingsModel::allElementsInPage() Line 162
	at C:\MS4\src\inspector\models\general\appearance\appearancesettingsmodel.cpp(162)
MuseScore4.exe!mu::inspector::AppearanceSettingsModel::pushToBackInOrder() Line 215
	at C:\MS4\src\inspector\models\general\appearance\appearancesettingsmodel.cpp(215)
MuseScore4.exe!mu::inspector::AppearanceSettingsModel::qt_metacall() Line 239
	at C:\MS4\builds\Win-Qt6.2.4-msvc2019_64-VS17-RelWithDebInfo\src\inspector\inspector_autogen\include_RelWithDebInfo\SSI7ORFQR4\moc_appearancesettingsmodel.cpp(239)
Qt6Core.dll!QMetaObject::metacall(QObject * object, QMetaObject::Call cl, int idx, void * * argv) Line 322
	at C:\Users\qt\work\qt\qtbase\src\corelib\kernel\qmetaobject.cpp(322)

### PR DESCRIPTION
**Pull request by mathesoncalum**
Resolves: #23144

The “arrange/stacking” system (to front, to back, etc.) requires the selected item to have a `Page` ancestor. Brackets, however, can exist on multiple pages simultaneously and thus do not have one (we use the dummy element instead).

This PR disables the arrange section for items that do not have a page ancestor, making the crash unreachable. This may be something to revisit if the implementation of brackets or stacking changes.

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
Does this also work well when selecting a bracket _and_ an element of another type, e.g. using Ctrl/Cmd+click?

Perhaps something similar to what we do for the offset property (`m_elementsForOffsetProperty`) would be a good solution.

**Comment by mathesoncalum** [comment]
> Does this also work well when...
Yeah I tested this and it does seem to work (doesn't crash and the stacking of other items changes as expected).

**Comment by mathesoncalum** [comment]
Though you do raise a good point about keeping it in line with other disabled property items, which are greyed-out instead of invisible. I'll tweak the solution.

**Comment by cbjeukendrup** [comment]
Also, Brackets are a bit special: there is a BracketItem class that "describes" brackets in general and doesn't belong to any page/system; and there is a Bracket class that represents an "instance" of a bracket on a specific system and thus does have a page. 

Normally, we would use the Bracket class, because that is what's selected. But the problem is that Brackets are frequently deleted and recreated during layout, so using them in the inspector causes crashes. Therefore, we use BracketItem instead, but that means that some properties cannot really be used. 

(If it already works, that's good, but I still thought it would be nice to explain this 🙂)

**Comment by cbjeukendrup** [comment]
Another thought, actually it seems somewhat fragile to take the `page` of the first element of the list only. That might produce weird results when multi-selecting elements from different pages, and it seems not ideal that the result depends on the order in which the elements are selected.

File: src/inspector/models/general/appearance/appearancesettingsmodel.h [hunk 1]
```diff
@@ -41,6 +41,7 @@ class AppearanceSettingsModel : public AbstractInspectorModel
     Q_PROPERTY(PropertyItem * offset READ offset CONSTANT)
     Q_PROPERTY(bool isSnappedToGrid READ isSnappedToGrid WRITE setIsSnappedToGrid NOTIFY isSnappedToGridChanged)
     Q_PROPERTY(bool isVerticalOffsetAvailable READ isVerticalOffsetAvailable NOTIFY isVerticalOffsetAvailableChanged)
+    Q_PROPERTY(bool isArrangeSectionAvailable READ page NOTIFY isArrangeSectionAvailableChanged)
```
Comment (Eism) [inline src/inspector/models/general/appearance/appearancesettingsmodel.h:44]: please create a separate method `isArrangeSectionAvailable` for read

File: src/inspector/models/general/appearance/appearancesettingsmodel.cpp [hunk 2]
```diff
@@ -142,7 +148,10 @@ void AppearanceSettingsModel::loadProperties(const PropertyIdSet& propertyIdSet)
     }
 
     if (muse::contains(propertyIdSet, Pid::Z)) {
-        loadPropertyItem(m_arrangeOrder);
+        loadPropertyItem(m_arrangeOrder, m_elementsForArrangeProperty);
+        if (m_arrangeOrder) {
+            m_arrangeOrder->setIsEnabled(!m_elementsForArrangeProperty.empty());
```
Comment (mathesoncalum) [inline src/inspector/models/general/appearance/appearancesettingsmodel.cpp:153]: I was wondering whether this should instead take place inside the early return of `AbstractInspectorModel::loadPropertyItem` (if `elements` is empty, disable the property item). Feels like it could be a slightly risky change, though...

Comment (cbjeukendrup) [reply src/inspector/models/general/appearance/appearancesettingsmodel.cpp:153]: I think that would make sense, and I can't imagine it will have catastrophic consequences.

**Review by Eism — APPROVED** [review]

**Comment by zacjansheski** [comment]
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/23144 FIXED
