### PR TITLE
Fix errors in header distances calculation

### LINKED ISSUE #26823: Clef spacing regression
### Issue type

Engraving bug (incorrect score rendering)

### Description
Image

4.5/master

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

Any

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mike-spa**
Resolves: #26823

### CODE REVIEW

File: src/engraving/dom/segment.cpp [hunk 1]
```diff
@@ -2847,13 +2847,17 @@ bool Segment::goesBefore(const Segment* nextSegment) const
     }
 
     if (thisIsClef && (nextIsKeySig || nextIsTimeSig)
-        && rtick() == Fraction(0, 1) && nextSegment->rtick() == Fraction(0, 1) && !nextIsHeader) {
+        && rtick()
+        == Fraction(0,
+                    1) && nextSegment->rtick() == Fraction(0, 1) && !nextIsHeader && thisMeasureIsStartRepeat && prevMeasureIsEndRepeat) {
```
Comment (cbjeukendrup) [inline src/engraving/dom/segment.cpp:2852]: Something happened here in terms of formatting...

**Review by ghost — APPROVED** [review]

**Review by miiizen — APPROVED** [review]
