### PR TITLE
Fix #23208 - crash pressing ESC while viewing color selection dialog

### LINKED ISSUE #23208: MuseScore crashes to desktop when pressing ESC whilst picking a screen color in the color picker
### Issue type
Crash or freeze

### Intro
I originally reported this bug [in the forums](https://musescore.org/en/node/365116). @Jojo-Schmitz [asked](https://musescore.org/en/node/365116#comment-1245923) me to report it on GitHub, so here I am.

**Thank you very much!**

### Issue type
Crash

### Bug description
When trying to Pick a Screen Color, in the Color Picker, then pressing the ESC key without selecting any color, MuseScore crashes and closes, without any error message.

**Explanation:**
I want to pick a Fill Color for a Staff Text box in my score.
I go to its properties, and click "Fill Color". The color picker pops up.
I click "Pick a screen color". The cursor changes to a big "+" sign, for picking any color on the screen. Also, beneath the "Pick Screen Color" button a notice appears, saying: "Cursor at xxx yyy; Press ESC to cancel".
I regret, I don't want to pick any color - I want to cancel. I click ESC, the "+" cursor stays as it is (I can still move the cursor freely), but something weird happens: In the "Properties" palette, most of the buttons disappear, and after 1-2 seconds the whole MuseScore app crashes and closes without any message.

### Steps to reproduce

1. Open any score.
2. Add a Staff Text and click it.
3. In the properties sidebar click "> show more", then click "Fill color".
4. In the color picker, click "Pick Screen Color".
5. Press ESC on your keyboard.

### Severity
Minor.

### Score file:
[staff text color picker crash.mscz](https://musescore.org/sites/musescore.org/files/2024-06/staff%20text%20color%20picker%20crash_1.mscz)

### Screenshots/Screen recordings
https://github.com/musescore/MuseScore/assets/25561013/3aab72eb-55e3-4143-a815-c17d277ecb67 (video has no audio because audio is not needed)

### MuseScore Version
4.3.1-241490900

### Regression
I don't know

### Operating system
Windows 10

### Additional context
**Log File:** [MuseScore_240610_213213.txt](https://musescore.org/sites/musescore.org/files/2024-06/MuseScore_240610_213213_1.txt)

MuseScore Studio version (64-bit): 4.3.1-241490900,
revision: [026c26b](https://github.com/musescore/musescore/commit/026c26b)

OS:			Windows 10 Pro 
Version:		22H2
OS build:		19045.4412
Architecture:	x86_64
System type:	64-bit operating system, x64-based processor

Processor:	AMD Ryzen 7 2700X Eight-Core Processor, 3.70 GHz
Installed RAM:	32.0 GB
GPU:		NVIDIA GeForce RTX 4070 Ti
Drive:		Hard-disk drive

### PR DESCRIPTION
**Pull request by wizofaus**
Resolves: #23208 

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

File: src/framework/global/internal/interactive.cpp [hunk 1]
```diff
@@ -237,7 +237,9 @@ io::paths_t Interactive::selectMultipleDirectories(const QString& title, const i
 
 QColor Interactive::selectColor(const QColor& color, const QString& title)
 {
+    shortcutsRegister.get()->setActive(false);
     QColor selectedColor = QColorDialog::getColor(color, nullptr, title);
+    shortcutsRegister.get()->setActive(true);
```
Comment (wizofaus) [inline src/framework/global/internal/interactive.cpp:242]: would be nicer to guarantee this would happen even if getColor throws an exception, but in general the codebase doesn't really make use of that sort of pattern. Is it likely we'd continue using the QColorDialog in the long term, vs QML-based dialogs?

File: src/framework/global/internal/interactive.h [hunk 2]
```diff
@@ -29,12 +29,14 @@
...
 
 #include "../iinteractive.h"
+#include "shortcuts/ishortcutsregister.h"
 
 namespace muse {
 class Interactive : public IInteractive, public Injectable, public async::Asyncable
 {
     Inject<muse::ui::IInteractiveProvider> provider{ this };
     Inject<muse::ui::IMainWindow> mainWindow{ this };
+    Inject<shortcuts::IShortcutsRegister> shortcutsRegister = { this };
```
Comment (wizofaus) [inline src/framework/global/internal/interactive.h:39]: copied & pasted from elsewhere, so it seems we've used two different conventions for initialising - should I change them all? Or just this one to match this file?

**Comment by Eism** [comment]
Most likely the problem will be resolved if we use qml dialogs instead of widget as I did for the file opening dialogs in this commit https://github.com/musescore/MuseScore/pull/13847/commits/7512c3b109022a967fad32381e11e6808dd9fc20

**Comment by Eism** [comment]
Ok, I created a tech task of switching to qml dialog https://github.com/musescore/MuseScore/issues/23244
We can merge this workaround after testing

File: src/framework/global/internal/interactive.h (hunk 2 above)
Comment (Eism) [reply src/framework/global/internal/interactive.h:39]: > should I change them all
yes, please

Comment (wizofaus) [reply src/framework/global/internal/interactive.h:39]: done

**Comment by zacjansheski** [comment]
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/23208 FIXED

**Review by RomanPudashkin — APPROVED** [review]

**Comment by nCuky** [comment]
Thank you! Many respects for the quick fix
