### PR TITLE
fixed #29805: Correct default palette fretboard diagrams to match 4.5.2

### LINKED ISSUE #29805: 'Em' fretboard diagram is wrong
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. Type Em chord symbol
2. Add fretboard diagram

See that it looks like the diagram on the left; the correct diagram is on the right:

Image

Note for @Eism, the diagram in the file I gave you was the correct one for Em, so I'm not sure what happened in the parsing.

### Supporting files, videos and screenshots

See above

### What is the latest version of MuseScore Studio where this issue is present?

Nightly

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

macOS 15

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by Eism**
Resolves: #29805

The problem was that for Em(no3rd) and Em we calculated the same key and stored the diagram info under that key. Since Em appears in the score before Em(no3rd), saving the data under the calculated key overwrote the previous one.

Now we store a list of diagrams available for a given key, and when selecting a diagram from this list, we pick the one with the chord symbol that has the shorter name (Em). In the future, we can improve this algorithm.

### CODE REVIEW

**Review by avvvvve — APPROVED** [review]

File: src/engraving/dom/fret.cpp [hunk 1]
```diff
@@ -134,6 +139,29 @@ static HarmonyMapKey createHarmonyMapKey(const String& harmony, const NoteSpelli
     return HarmonyMapKey(keys, rootTpc, bassTpc);
 }
 
+static DiagramInfo resolveDiagram(const std::vector<DiagramInfo>& diagrams)
+{
+    auto isSimpler = [](const DiagramInfo& a, const DiagramInfo& b) {
+        const String harmonyNameA = a.harmonyName;
```
Comment (RomanPudashkin) [inline src/engraving/dom/fret.cpp]: const String&
