### PR TITLE
Fix #9218: Fix transparent .png file export

### LINKED ISSUE #9218: [MU4 Issue] Exported PNGs always have transparent background
**Describe the bug**

Exported PNGs always have transparent background, even when "Transparent background" is unchecked.

**To Reproduce**
1. Create or open a score
2. Go to File > Export
3. For "Format", select "PNG images"
4. Make sure "Transparent background" is unchecked

**Expected behavior**

If the transparent background checkbox is unchecked, the background should not be transparent. I'd expect the background to be white by default.

**Screenshots**

https://user-images.githubusercontent.com/5659171/134218962-db0eb07d-8b7f-4278-9525-2cdce14b0f78.mov

If you go through this process with this file: 
[accidental-test.mscz.zip](https://github.com/musescore/MuseScore/files/7205082/accidental-test.mscz.zip)

here's the output:

accidental-test-1

**Desktop (please complete the following information):**
 - OS: macOS 11.6

### PR DESCRIPTION
**Pull request by HemantAntony**
Before this commit, when exported in .png format, exported .png files always used to have
a transparent background whether transparent option was checked or not.
This commit has solved this bug. Also, the default value of transparent background has been changed from true to false

Resolves: https://github.com/musescore/MuseScore/issues/9218

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by HemantAntony** [comment]
Also, should the transparent option be unchecked by default? I would also like to point out that the png export isn't perfect. Look at the right side
TestImage-1

**Comment by cbjeukendrup** [comment]
Personally, I would say, export with white background by default, so yes, the transparent option is unchecked by default. But doubtlessly others think different about that...

And about that image, it seems to crop the image to the topmost/leftmost/rightmost/bottommost elements, instead of keeping the margins and the shape of the page. I think that is definitely not what we want, thanks for pointing that out!

**Comment by cbjeukendrup** [comment]
@igorkorsukov Could you please add the vtests label? The only difference is that the ref images have a transparent background and with this PR they get a white background. That seems desirable to me, isn't it?

**Comment by Jojo-Schmitz** [comment]
IIRC it had been asked for, for the benefit of those using a dark mode when viewing those PNGs copy/pasted from the vtests into GitHub comments?

**Comment by HemantAntony** [comment]
Please don't merge yet. I'm still working on this

File: src/importexport/imagesexport/internal/pngwriter.cpp [hunk 1]
```diff
@@ -69,7 +69,7 @@ mu::Ret PngWriter::write(INotationPtr notation, Device& destinationDevice, const
     RectF pageRect = page->abbox();
 
     if (TRIM_MARGIN_SIZE >= 0) {
-        QMarginsF margins(TRIM_MARGIN_SIZE, TRIM_MARGIN_SIZE, TRIM_MARGIN_SIZE, TRIM_MARGIN_SIZE);
+        QMarginsF margins(TRIM_MARGIN_SIZE + 230, TRIM_MARGIN_SIZE + 420, TRIM_MARGIN_SIZE + 220, TRIM_MARGIN_SIZE + 340);
```
Comment (RomanPudashkin) [inline src/importexport/imagesexport/internal/pngwriter.cpp:72]: These hardcoded margins look odd. They may cause some problems in the feature because this code will be used for MuseScore.com. Please, remove them and I'll merge your PR after that. It is better to create a separate issue for the margins problem and solve it in a separate PR

**Review by RomanPudashkin — APPROVED** [review]
