### PR TITLE
Fix #18618 - Zero overscroll when canvas' [limit scroll area to page borders] enabled

### LINKED ISSUE #18618: View: Page Width still shows some blank margin space
### Issue type

UI bug

### Bug description

This would sometimes happen in 3.6.2  when using "horizontal" scrolling while having unchecked "Limit scroll area to page borders". Personally, I use Vertical and enable the limitation and there are no gaps:

nogap

MuseScore 4/4.1 still has gaps with horizontal + limited scrolling, so there's some screen estate not being used:
greyspot

Not much, but still something. This should be like how it was in version 3

### Steps to reproduce

Preferences → Canvas → Vertical + Limit enabled.

Result shows some border gaps which shouldn't exist.  Seems to be on the left-hand side, but maybe it changes on occasion depending on something: If zoomed into the score so that there are no borders/gaps showing, triggering [page-width] seems to give the gap on RHS instead of the LHS. 

### MuseScore Version

4.1

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

LNX-XFCE

### PR DESCRIPTION
**Pull request by worldwideweary**
Resolves: #18618 

Figured I'd check this out. When **_limit scrolling area_** is enabled, MS4 should act similarly to MS2/3 in that there were no "margins" outside of the page so that all screen estate is used for the notation page itself.

It's most appropriate, especially when Page Width zoom level is engaged.

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

File: src/notation/view/abstractnotationpaintview.cpp [hunk 1]
```diff
@@ -33,7 +33,7 @@ using namespace mu::draw;
 using namespace mu::notation;
 
 static constexpr qreal SCROLL_LIMIT_OFF_OFFSET = 0.75;
-static constexpr qreal SCROLL_LIMIT_ON_OFFSET = 0.02;
+static constexpr qreal SCROLL_LIMIT_ON_OFFSET = 0.00;
```
Comment (cbjeukendrup) [inline src/notation/view/abstractnotationpaintview.cpp:36]: I'd just write `0.0` inline, and get rid of this constant. (And while at it, SCROLL_LIMIT_OFF_OFFSET could perhaps use a better name, like `SCROLL_LIMIT_OFF_OVERSCROLL_FACTOR`.)

Comment (worldwideweary) [reply src/notation/view/abstractnotationpaintview.cpp:36]: "There are no unnecessary changes" ;-)

One **force-push** for the sake of approval comin' up.

**Review by cbjeukendrup — APPROVED** [review]

**Comment by zacjansheski** [comment]
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/18618 FIXED
