### PR TITLE
fix #18143 gliss line direction for 8va and microtonal notes

### LINKED ISSUE #18143: Microtonal accidentals should affect glissando angle
### Issue type

Engraving bug

### Bug description

Currently, standard accidentals applied to notes change the angle of glissando lines accordingly, microtonal accidentals do not.  

This is currently done by checking the pitch of both notes on the same line/space [here](https://github.com/musescore/MuseScore/blob/master/src/engraving/layout/v0/tlayout.cpp#L2203), but microtonal accidentals don't have an effect.  

### Steps to reproduce

1. Place two notes of the same pitch one after the other
2. Add a microtonal accidental to one of the notes
3. Add a glissando lines between the notes.  It remains a horizontal line.

### Screenshots/Screen recordings

Standard accidentals change gliss. angle
image

Microtonal accidentals don't
image

### MuseScore Version

4.0.2

### Regression

No.

### Operating system

Windows 11

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sammik**
Resolves: #18143

For 8va sounding pitch is relevant (no display pitch)

For microtonality, program compares tunning value of note, or if it is not present, search for microtonal accidental of note

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Review by oktophonie — APPROVED** [review]

File: src/engraving/layout/v0/tlayout.cpp [hunk 1]
```diff
@@ -2200,7 +2200,24 @@ void TLayout::layout(Glissando* item, LayoutContext& ctx)
 
     // AVOID HORIZONTAL LINES
 
-    int upDown = (0 < (anchor2->pitch() - anchor1->pitch())) - ((anchor2->pitch() - anchor1->pitch()) < 0);
+    // for microtonality read tuning, or check note accidental
+    double tune1 = anchor1->tuning();
+    double tune2 = anchor2->tuning();
+    AccidentalType acc1 = anchor1->accidentalType();
+    AccidentalType acc2 = anchor2->accidentalType();
+    if (tune1 == 0 && Accidental::isMicrotonal(acc1)) {
```
Comment (RomanPudashkin) [inline src/engraving/layout/v0/tlayout.cpp:2208]: Please use RealIsNull instead of tune1 == 0 (same for tune2 == 0)

**Comment by sammik** [comment]
@RomanPudashkin done

vtests as axpected
before:
gliss-4-1 ref

after:
gliss-4-1

**Review by RomanPudashkin — APPROVED** [review]
