### PR TITLE
Fix #23063: (import) MusicXML alter element not exported

### LINKED ISSUE #23063: MusicXML alter element not exported
### Issue type

Import/export issue

### Bug description

The [MusicXML alter element](https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/alter/) is not exported when a note has a tuning.

### Steps to reproduce

- Load the [attached score](https://github.com/user-attachments/files/15526465/rast-tetrachord.zip)
- Verify that E in measure 1 is tuned -50 cents
- Export to MusicXML
- Examine the exported E note in measure 1: the `<alter>` element is missing. It should show:
```
<alter>-0.5</alter>
```

### Screenshots/Screen recordings

_No response_

### MuseScore Version

4.3.1-241490902, revision: github-musescore-musescore-026c26b

### Regression

I don't know

### Operating system

Pop!_OS 22.04 LTS

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by pacebes**
Resolves: #23063

Imports a MusicXML exported with alter elements 

- [X] I signed the [CLA](https://musescore.org/en/cla)
- [X] The title of the PR describes the problem it addresses
- [X] Each commit's message describes its purpose and effects, and references the issue it resolves
- [X] If changes are extensive, there is a sequence of easily reviewable commits
- [X] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [X] There are no unnecessary changes
- [X] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

File: src/importexport/musicxml/internal/musicxml/importmxmlnotepitch.cpp [hunk 1]
```diff
@@ -143,6 +143,11 @@ void MxmlNotePitch::pitch(muse::XmlStreamReader& e)
                 if (ok2 && (std::abs(altervalue) < 2.0) && (m_accType == AccidentalType::NONE)) {
                     // try to see if a microtonal accidental is needed
                     m_accType = microtonalGuess(altervalue);
+
+                    // If it's not a microtonal accidental we will use tuning
+                    if (m_accType == AccidentalType::NONE) {
+                        m_tuning = 100 * altervalue;
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/importmxmlnotepitch.cpp:149]: I'd initialize it (to `0,0')  further abone, where `alter` etc. are initialized too

Comment (pacebes) [reply src/importexport/musicxml/internal/musicxml/importmxmlnotepitch.cpp:150]: Done

**Review by miiizen — APPROVED** [review]
