### PR TITLE
Fix crash when deleting staff with selected element (#32542)

### LINKED ISSUE #32542: Deleting a staff while an object from it is selected, then opening the instrument menu (or Undo), causes a crash (Linux only)
### Issue type

Crash or freeze

### Description with steps to reproduce

1. add an instrument and add a second staff to that instrument
2. place a note somewhere in the second staff and select it
3. from the Layout tab, select that staff, and press delete to delete it
4. press I to open the instrument menu, and observe that the program instantly crashes

Also see https://github.com/musescore/MuseScore/issues/32542#issuecomment-4046443004

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/baa33151-c10a-440c-a69c-d4fc5c327787

### In which versions of MuseScore Studio is this issue present?

4.6.3, 4.6.5, 4.7 nightly

### Regression

Yes, this used to work in MuseScore 4.5.2

### Operating system

Fedora 43 (Linux 6.18.12 x86_64), LinuxUbuntu24.04.3 LTS

### Additional context

Does not happen in MS3, but staffs were managed via the instrument menu instead of a separate tab

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by CubikingChill**
Resolves #32542 

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/muse_framework/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by CubikingChill** [comment]
Personally I tested the x86 build and didn't observe any crash when doing the 2 repro sequences in the linked issue. Undo/redo seems fine for me. Would be grateful if more people can test.

My limited understanding of the codebase limits my imagination, thus I can only think of the current fix. While this guard is quite minimal and sustainable, I wonder if there are even better approach. Unfortunately my

File: src/engraving/accessibility/accessibleitem.cpp [hunk 1]
```diff
@@ -192,6 +192,10 @@ QString AccessibleItem::accessibleName() const
         return QString();
     }
 
+    if (!m_element->part()) {
+        return QString();
+    }
```
[the remark this answers is not in the document]
Comment (shoogle) [reply src/engraving/accessibility/accessibleitem.cpp]: This fixes the crash for me, but it's not clear why because `m_element->part()` isn't used in this function.

You should look for where it _does_ get used (maybe in `m_element->screenReaderInfo()` or `m_element->visible()`) and add the null check on `part()` there instead.

But first you should try doing a [null check on root](https://github.com/musescore/MuseScore/pull/32706/changes#r3037033784). That might fix the problem without checking `m_element->part()`.

File: src/engraving/accessibility/accessibleitem.cpp
Comment (shoogle) [inline src/engraving/accessibility/accessibleitem.cpp]: This line should be:

```C++
.arg((root && root->isRangeSelection()) ? ("; " + muse::qtrc("engraving", "selected")) : "");
```

I.e. add a null check on`root`.

File: src/engraving/accessibility/accessibleitem.cpp [hunk 2]
```diff
@@ -203,8 +203,8 @@ QString AccessibleItem::accessibleName() const
                    .arg(m_element->screenReaderInfo().toQString())
                    .arg(m_element->visible() ? "" : " " + muse::qtrc("engraving", "invisible"))
                    .arg(!barsAndBeats.isEmpty() ? ("; " + barsAndBeats) : "")
-                   .arg(root->isRangeSelection() ? ("; " + muse::qtrc("engraving", "selected")) : "");
-
+                   .arg((root && root->isRangeSelection()) ? ("; " + muse::qtrc("engraving", "selected")) : "");
+
```
[the remark this answers is not in the document]
Comment (shoogle) [reply src/engraving/accessibility/accessibleitem.cpp]: @CubikingChill, please delete the whitespace on this empty line.

[the remark this answers is not in the document]
Comment (shoogle) [reply src/engraving/accessibility/accessibleitem.cpp]: @coderabbitai, what's your config option to suppress your last comment?

> Seems like the humans are having a chat. I'll hop back into my burrow for now. If you need me again, just tag @coderabbitai in a new comment, and I'll come hopping out!

**Comment by CubikingChill** [comment]
Sorry I was busy back then so I went to do sth else after the commit. I was gonna test it now but thanks for the insights. I know this is part of 4.7 so I will work more frequently

**Comment by CubikingChill** [comment]
Thanks for the advice. Briefly tested on linux x86. I think now both behaviour and code quality looks good.

File: src/engraving/dom/note.cpp [hunk 3]
```diff
@@ -3364,6 +3364,10 @@ String Note::accessibleInfo() const
 
 String Note::screenReaderInfo() const
 {
+    if (!part()) {
+        return String();
+    }
+
     const Instrument* instrument = part()->instrument(chord()->tick());
```
Comment (shoogle) [inline src/engraving/dom/note.cpp]: When a "getter" method is called multiple times, it's better to store the result in a variable and then use it everywhere instead of calling the getter.

So you should do:

```C++
const Part* part = part();

if (!part) {
    return String();
}

const Instrument* instrument = part->instrument(chord()->tick());
```

(The same should have been done with `staff()`, `chord()` and `pitch()`, but that's not your fault and you don't have to change it.)

**Review by shoogle — COMMENTED** [review]
This fixes it for me, thanks! I just have a minor nitpick about the code.

File: src/engraving/dom/note.cpp (hunk 3 above)
Comment (CubikingChill) [reply src/engraving/dom/note.cpp]: I can just create a new commit with all the improvements. Shall I do that or would that be off topic?

Comment (shoogle) [reply src/engraving/dom/note.cpp]: It's close enough to be on-topic, so you can do it in the same commit if you like.

```C++
const Part* part = part();

if (!part) {
    return String(); // part is nullptr on Linux after an instrument is deleted.
}

const Fraction tick = tick();
const Chord* chord = chord();
const Instrument* instrument = part->instrument(tick);

IF_ASSERT_FAILED(chord && instrument) {
    return QString();
}

// ...

else if (const Drumset* d = instrument->drumset(); d && instrument->useDrumset()) {
    pitchName = d->translatedName(m_pitch);
} else if (const Staff* staff = staff(); staff && staff->isTabStaff(tick)) {
    pitchName = muse::mtrc("engraving", "%1; String: %2; Fret: %3")
        .arg(tpcUserName(true, true), String::number(string() + 1), String::number(fret()));
}

// ...
```

Notice that `pitch()` can be replaced by `m_pitch` because it's a member of this class.

File: src/engraving/dom/note.cpp
Comment (shoogle) [inline src/engraving/dom/note.cpp]: You can improve performance slightly by testing for null `drumset` before checking the staff type.

```C++
else if (drumset && staff()->isDrumStaff(tick())) {
    pitchName = drumset->translatedName(pitch());
}
```

That avoids doing the `tick()` lookup unless it's absolutely needed.

But even better, you can replace `staff()->isDrumStaff(tick())` with `instrument->useDrumset()` because that's what it calls internally and you already have an `instrument` object.

```C++
else if (const Drumset* d = instrument->drumset(); d && instrument->useDrumset()) {
    pitchName = d->translatedName(m_pitch);
} else if (const Staff* staff = staff(); staff && staff->isTabStaff(tick)) {
    pitchName = muse::mtrc("engraving", "%1; String: %2; Fret: %3")
        .arg(tpcUserName(true, true), String::number(string() + 1), String::number(fret()));
}
```

Like I suggested [above](https://github.com/musescore/MuseScore/pull/32706/changes#r3037608885).

Comment (CubikingChill) [reply src/engraving/dom/note.cpp]: Ok. I think I will use another commit tho because it does not directly address the linked issue.

**Comment by shoogle** [comment]
@CubikingChill, what is [your username](https://musescore.org/en/user) on MuseScore.org for the account you used to sign the [CLA](https://github.com/musescore/MuseScore/pull/32706)?

**Comment by CubikingChill** [comment]
> @CubikingChill, what is [your username](https://musescore.org/en/user) on MuseScore.org for the account you used to sign the [CLA](https://github.com/musescore/MuseScore/pull/32706)?

Full name: Antonio Chiu
E-Mail: yukchiuantonio@gmail.com

Is there a problem?

**Comment by shoogle** [comment]
@CubikingChill, you need to log in or create a free account [here](https://musescore.com/) and then fill in the CLA form [here](https://musescore.org/en/cla). Once you have done this, tell me the username of the account you used to fill in the form.

**Comment by CubikingChill** [comment]
image

Oh, sorry I misunderstood. My username is cubifbgaming. I think I have signed the CLA.

**Comment by shoogle** [comment]
Yes, you have. Thanks for confirming the username.

**Comment by CubikingChill** [comment]
> Yes, you have. Thanks for confirming the username.

Just to let you know that the email I used to commit locally is another organisation email which is not permenant. Does that matter?
