### PR TITLE
Fix #25371: Check if a previous selection exists before trying to restore it

### LINKED ISSUE #25371: After openening score, navigating with Left/Right arrow starts from the title frame instead on notes
### Issue type

Accessibility issue (e.g. for keyboard-only or screen reader users)

### Description with steps to reproduce

1. Open score
2. Navigate with right arrow - the title frame is selected instead of the first note or rest

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/98ea79db-b42d-4218-8899-fa89e55a81e1

### What is the latest version of MuseScore Studio where this issue is present?

4.5 nightly

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

all

### Additional context

If you navigate with Alt+Right arrow, the first frame should be selected.

Only navigation without Alt should skip the frame and go straight to the first note or rest.

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mathesoncalum**
Resolves #25371

Caused by #24157 where we restore a previous selection if the selection is currently null. This caused a problem in newly opened scores where there is no previous selection (so we revert to selecting the first item in the score).

The proposed fix is pretty simple - check if a previous selection exists before trying to restore it.

### CODE REVIEW

**Review by shoogle — APPROVED** [review]
Works well, thanks!

File: src/notation/internal/notationactioncontroller.h [hunk 1]
```diff
@@ -78,6 +78,8 @@ class NotationActionController : public muse::actions::Actionable, public muse::
     INotationUndoStackPtr currentNotationUndoStack() const;
     INotationMidiInputPtr currentNotationMidiInput() const;
 
+    mu::engraving::Score* score() const;
```
Comment (Eism) [inline src/notation/internal/notationactioncontroller.h:81]: let's rename to currentNotationScore
in general, such a method should not be in this class :) ideally, these manipulations should soon be moved somewhere else, but for now, let's just rename the method

**Review by Eism — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
Tested #25371 on Win10, Mac13.6, LinuxUbuntu24.04.1 LTS - **FIXED**
