### PR TITLE
Fix #15726: Some elements are lost when changing time signature

### LINKED ISSUE #15726: [MU4 Issue] Glissandi are lost when changing time signature
**To Reproduce**
1. Create a score with glissandi
2. Change the time signature
-> the glissandos are lost, even when there seems to be no good reason for that (i.e. when the notes just stay in one measure and don't need to be broken and tied etc.)

**Additional context**
Same in MS3.6.2

### PR DESCRIPTION
**Pull request by pacebes**
Resolves: #15726 

- This PR keeps the follogin elements when changing time signature:
-- Glisando && Bends 
-- Spacers 
-- Jumps and Markers
-- Voltas
- BarLines and Breaks support were included in a [previous PR ](https://github.com/musescore/MuseScore/pull/30499)

- [X] I signed the [CLA](https://musescore.org/en/cla)
- [X] The title of the PR describes the problem it addresses
- [X] Each commit's message describes its purpose and effects, and references the issue it resolves
- [X] If changes are extensive, there is a sequence of easily reviewable commits
- [X] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [X] There are no unnecessary changes
- [X] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

File: src/engraving/dom/range.h [hunk 1]
```diff
@@ -143,10 +151,34 @@ class ScoreRange
     void backupRepeats(Segment* first, Segment* last);
     void restoreRepeats(Score* score, const Fraction& tick) const;
 
+    void backupSpacers(Segment* first, Segment* last);
+    void restoreSpacers(Score* score, const Fraction& tick) const;
+    void deleteSpacers();
+
+    bool endOfMeasure(EngravingItem* e) const;
```
Comment (mike-spa) [inline src/engraving/dom/range.h]: A more descriptive name like `isEndOfMeasureElement` would be better

File: src/engraving/dom/range.h [hunk 2]
```diff
@@ -143,10 +151,34 @@ class ScoreRange
...
+    void restoreVolta(Score* score, const Fraction& tick, Volta* v) const;
+
     friend class TrackList;
 
+    struct SpacerBackup
+    {
+        Fraction sPosition;
+        staff_idx_t staffIdx;
+        Spacer* s = nullptr;
+    };
```
Comment (mike-spa) [inline src/engraving/dom/range.h]: Just cosmetics, but I would find it more readable if all the definitions related to one type of objects we close together (see e.g. BarlinesBackup, followed by the vector and all the barlines related functions)

File: src/engraving/dom/range.cpp [hunk 3]
```diff
@@ -1117,7 +1290,7 @@ void ScoreRange::restoreRepeats(Score* score, const Fraction& tick) const
             Fraction mTick = m->tick();
             if (startEndRepeat.isStartRepeat && startEndRepeat.sPosition == mTick) {
                 m->undoChangeProperty(Pid::REPEAT_START, true);
-            } else if (!startEndRepeat.isStartRepeat && startEndRepeat.sPosition == mTick) {
+            } else if (!startEndRepeat.isStartRepeat && startEndRepeat.sPosition == m->endTick()) {
```
Comment (mike-spa) [inline src/engraving/dom/range.cpp:1293]: Also thanks for these corrections 👍

**Review by mike-spa — APPROVED** [review]
