### PR TITLE
[MU4] Fix #10972: Tempo. Eights are played straight when Swing tempo mark is placed on the score

### LINKED ISSUE #10972: [MU4 Issue] Tempo. Eights are played straight when Swing tempo mark is placed on the score
**To Reproduce**
1. Open any score
2. Put a Swing tempo mark to the score
3. Play the score

**Expected behavior**
Eights are played with swing effect when Swing tempo mark is placed on the score

**Screenshots**

https://user-images.githubusercontent.com/101250347/160894818-697abfc8-19dc-41db-b882-b56864a17bc5.mov

**Platform information**
 - OS: [macOS, Windows]

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Resolves: https://github.com/musescore/MuseScore/issues/10972

### CODE REVIEW

File: src/engraving/libmscore/staff.h [hunk 1]
```diff
@@ -59,8 +59,10 @@ enum class Key;
 //---------------------------------------------------------
 
 struct SwingParameters {
-    int swingUnit;
-    int swingRatio;
+    int swingUnit = 0;
+    int swingRatio = 0;
+
+    bool isValid() const { return swingRatio >= 50 && swingUnit != 0; }
```
Comment (cbjeukendrup) [inline src/engraving/libmscore/staff.h:65]: The `>= 50` should not be necessary, since some people desire to have "reversed" swing, see for example https://musescore.org/en/node/333867. Note that the "TripletFeel" element (added as part of the GP import task) has such a "reversed" swing option, so we should also support the playback of it. 

(We might need to tweak the formula in `Swing::swingAdjustParams`, but it looks like we don't need to.)

Comment (RomanPudashkin) [reply src/engraving/libmscore/staff.h]: fixed

**Comment by boryskuzmenko** [comment]
🟢 **TESTED on macOS 12, Win 11, Ubuntu 20**

Please, merge to master

**Review by vpereverzev — APPROVED** [review]
