### PR TITLE
Fix #20146 - issues with home key on slurs

### LINKED ISSUE #20146: Home key or fn+left arrow do not move screen to start of score when a slur/tie is selected
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

When a slur/tie is selected, the end or fn+right arrow takes the focus to the end of the score as expected, but home or fn+left arrow does not go to the beginnning of the score

### Steps to reproduce

1. Create a slur/tie
2. Select the slur/tie
3. Try to use home or fn+left arrow

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/5cb0fa4f-1a97-411b-a406-d6e9312939cc

### MuseScore Version

OS: macOS 14.1, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233260301, revision: github-musescore-musescore-acb1bad

### Regression

No.

### Operating system

All

### Additional context

Until recently this actually caused a crash, that was fixed, but the actual functionality still needs to be fixed.

### PR DESCRIPTION
**Pull request by wizofaus**
Resolves: #20146 

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

File: src/engraving/dom/slur.cpp [hunk 1]
```diff
@@ -83,7 +83,7 @@ static ChordRest* searchCR(Segment* segment, track_idx_t startTrack, track_idx_t
 
 bool SlurSegment::isEditAllowed(EditData& ed) const
 {
-    if (ed.key == Key_Home && !ed.modifiers) {
+    if (ed.key == Key_Home && !ed.modifiers && ed.hasCurrentGrip()) {
```
Comment (wizofaus) [inline src/engraving/dom/slur.cpp:86]: fixes the "reported" problem, that Home key can effectively be swallowed by a selected slur, even if no grips selected.

File: src/engraving/dom/slur.cpp [hunk 2]
```diff
@@ -120,9 +122,15 @@ bool SlurSegment::edit(EditData& ed)
 
     if (ed.key == Key_Home && !ed.modifiers) {
         if (ed.hasCurrentGrip()) {
-            ups(ed.curGrip).off = PointF();
+            startEditDrag(ed);
```
Comment (wizofaus) [inline src/engraving/dom/slur.cpp:125]: ensures operation is undoable

File: src/engraving/dom/slur.cpp [hunk 3]
```diff
@@ -120,9 +122,15 @@ bool SlurSegment::edit(EditData& ed)
...
+            if (ed.curGrip == Grip::SHOULDER) {
```
Comment (wizofaus) [inline src/engraving/dom/slur.cpp:126]: "shoulder" is a special case grip where any offset applied to it is actually transferred to the other curve points, so resetting those should give essentially the expected behaviour in most cases

File: src/engraving/dom/slur.cpp [hunk 4]
```diff
@@ -120,9 +122,15 @@ bool SlurSegment::edit(EditData& ed)
...
+                ups(Grip::BEZIER1).off = PointF();
+                ups(Grip::BEZIER2).off = PointF();
+            } else {
+                ups(ed.curGrip).off = PointF();
+            }
             renderer()->layoutItem(sl);
-            triggerLayout();
+            endEditDrag(ed);
```
Comment (wizofaus) [inline src/engraving/dom/slur.cpp:133]: commit to undo stack & calls triggerLayout

File: src/engraving/dom/slurtie.cpp [hunk 5]
```diff
@@ -57,6 +57,43 @@ SlurTieSegment::SlurTieSegment(const SlurTieSegment& b)
...
+
+bool SlurTieSegment::edit(EditData& ed)
+{
+    if (!isEditAllowed(ed)) {
+        return false;
+    }
+
+    if (ed.key == Key_Home && !ed.modifiers) {
+        if (ed.hasCurrentGrip()) {
+            startEditDrag(ed);
```
Comment (Eism) [inline src/engraving/dom/slurtie.cpp:82]: Looks like it isn't necessary, usually NotationInteraction does it before editing

File: src/engraving/dom/slur.cpp (hunk 2 above)
Comment (Eism) [reply src/engraving/dom/slur.cpp]: I see that in the master the undo/redo works without this code

Comment (wizofaus) [reply src/engraving/dom/slur.cpp]: Not when I tested it!  To be clear, it requires you adjust a handle position, ensure handle is selected and press Home, then undo, which should cause it to return to the adjusted position - NOT the original position.  After all, you could perform another action between adjusting handle and using home to reset it.

**Comment by wizofaus** [comment]
It definitely doesn't work properly on master currently, nor can I see how it ever did.
________________________________

File: src/engraving/dom/slur.cpp (hunk 2 above)
Comment (Eism) [reply src/engraving/dom/slur.cpp]: Okay, it works without this code for normal moves, so It is interesting why it doesn’t work for Home and we need to add this code here.

Comment (wizofaus) [reply src/engraving/dom/slur.cpp]: Because other key strokes are handled by NotationInteraction::handleKeyPress( ) where it does use startEditDrag( ) and endEditDrag( ).

Comment (Eism) [reply src/engraving/dom/slur.cpp]: If we move this code out of edit and move it to editDrag, will everything work as expected?
```
    bool handled = m_editData.element->edit(m_editData); // will return false for Home key
    if (!handled) {
        handled = handleKeyPress(event); // calls startEditDrag/editDrag/endEditDrag
    }
```

Comment (wizofaus) [reply src/engraving/dom/slur.cpp]: No, because for the undo & redo to work correctly you must first call startEditDrag(), *then* reset the values, then call endEditDrag().

Comment (Eism) [reply src/engraving/dom/slur.cpp]: we do it in `handleKeyPress`
(for other contributors to know why this PR is not approved and merged)

Comment (wizofaus) [reply src/engraving/dom/slur.cpp]: Ok, well, thanks for letting me know, but I would have been happy to modify my PR to make this change if that's what was agreed by all as being the best way to proceed...

Comment (wizofaus) [reply src/engraving/dom/slur.cpp]: So somebody else is implementing this and we should abandon this PR? @Eism

**Comment by wizofaus** [comment]
Have rebased off latest master (no conflicts, but it had been a while).  Still not sure what @Eism you are suggesting we do here.

**Review by Eism — APPROVED** [review]

**Comment by Eism** [comment]
Ok, I see that what I assumed doesn't work that way. I approved

**Comment by zacjansheski** [comment]
https://github.com/musescore/MuseScore/issues/20146 is still an issue in this PR for me

**Comment by wizofaus** [comment]
Ok I've confirm that the Home key on the Numeric Keypad isn't working properly - because when hitting that key it does appear to have "modifiers" set.
So basically, if you use the Home Key on the numeric keypad, it *always* returns to the top the score, whereas if you use the Home key separate from the numeric keypad, the behaviour depends on whether there's a handle selected.
I would suggest that definitely isn't expected, hopefully easy to fix!

**Comment by wizofaus** [comment]
Ok pushed again, now both Home keys should do the same thing - if there's an active handle on a slurtie selected, it resets the handle position, otherwise it binds to the whatever shortcut action you have for "Home" (normally return to top of score).
Note that with the mouse, clicking on a slurtie always selects a handle by default, you can then drag the score with the mouse to deselect the handle without deselecting the slur (there's probably a better way, but that's the easiest one I could find).

**Comment by zacjansheski** [comment]
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/20146 FIXED

**Comment by wizofaus** [comment]
Sorry what else do you need me to do here @Eism ?  Just wondering why it hasn't been merged...
