### PR TITLE
[4.7.0] Audio API section: various fixes

### LINKED ISSUE #31663: [ASIO support] When switching WASAPI>ASIO>WASAPI, System default should be selected when back to WASAPI
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

https://github.com/user-attachments/assets/788d6b90-3457-46d8-a1a9-6142cab08e0b

Another case: when disconnecting ASIO device before next MSS run

https://github.com/user-attachments/assets/d0dfa690-91d8-4699-98c1-914d36e0a5dc

### In which versions of MuseScore Studio is this issue present?

4.7 nightly

### Regression

No.

### Operating system

Windows 10

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### LINKED ISSUE #31664: [ASIO support] ASIO API should not be selected if ASIO device is missing (or give a warning message)
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

https://github.com/user-attachments/assets/d5864b2c-cbf5-4fb2-8e5e-e839d8e40a5d

### Supporting files, videos and screenshots

1

### In which versions of MuseScore Studio is this issue present?

4.7 nightly

### Regression

No.

### Operating system

Windows 10

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by RomanPudashkin**
Resolves: https://github.com/musescore/MuseScore/issues/31663
Resolves: https://github.com/musescore/MuseScore/issues/31664

## Summary by CodeRabbit

* **New Features**
  * Interactive warning shown when switching to an audio driver with no output devices; selection reverts to the previous driver when confirmed.
  * Improved UI label: "Audio API" renamed to "Audio driver".

* **Bug Fixes**
  * More reliable default audio-device selection during driver initialization.
  * Clarified warning and log messages for driver/device state.
  * Minor performance improvements when enumerating MIDI devices.

### CODE REVIEW

File: src/framework/audio/driver/platform/win/asio/asioaudiodriver.cpp [hunk 1]
```diff
@@ -427,7 +427,12 @@ bool AsioAudioDriver::open(const Spec& spec, Spec* activeSpec)
         return false;
     }
 
-    const char* name = spec.deviceId.c_str();
+    AudioDeviceID deviceId = spec.deviceId;
+    if (deviceId == DEFAULT_DEVICE_ID) {
+        deviceId = defaultDevice();
+    }
```
Comment (igorkorsukov) [inline src/framework/audio/driver/platform/win/asio/asioaudiodriver.cpp:432]: This logic should probably be shared across all drivers?

Comment (RomanPudashkin) [reply src/framework/audio/driver/platform/win/asio/asioaudiodriver.cpp:432]: We already have it for all drivers (unless I'm missing something)

**Review by igorkorsukov — APPROVED** [review]

**Comment by bkunda** [comment]
One observation: 
1. Start with default driver (WASAPI) with no connected ASIO device
2. Select Audio driver > ASIO: _warning dialog is triggered_ (expected)
3. Click OK in warning dialog: _Audio driver resets to WASAPI_ (expected)
4. Switch on/connect ASIO device: _Windows recognises the device and enables it_ (expected)
5. Select Audio driver > ASIO: _warning dialog is triggered_ (not expected: ASIO driver should be enabled since the device is now active)

In this case, the ASIO driver can only be selected after restarting MuseScore Studio.

**Comment by bkunda** [comment]
Second observation: When selecting ASIO as the driver, the device field remains empty, even if there's only one available device. 

Is it possible to enable an available device as soon as ASIO is selected? If there's only one, enable it. If there's more than one, just pick one :-) 

https://github.com/user-attachments/assets/f157b961-450b-4eb0-a613-1b10103e589c

**Comment by RomanPudashkin** [comment]
Approved by @bkunda
