### PR TITLE
[MU4] fix #7706 fix drag & drop memory leaks

### LINKED ISSUE #7706: [MU4 Issue] Memory leaks after drag & drop elements to a score
**Describe the bug**
There are several memory allocations (see _new ScoreCallbacks()_) in NotationInteraction. But we never delete those resources

More details:
https://github.com/musescore/MuseScore/pull/7630

**To Reproduce**

**Expected behavior**
We should free the allocated memory

### PR DESCRIPTION
**Pull request by wizofaus**
Resolves: https://github.com/musescore/MuseScore/issues/7706

Lots of unnecessary new-ing (and no deleting!) when dragging & dropping

- [ x ] I signed [CLA](https://musescore.org/en/cla)
- [ x ] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [ x ] I made sure the code compiles on my machine
- [ x ] I made sure there are no unnecessary changes in the code
- [ x ] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [ x ] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [ x ] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

File: src/engraving/libmscore/element.h [hunk 1]
```diff
@@ -135,9 +135,10 @@ class ElementEditData;
 class EditData
 {
     QList<ElementEditData*> data;
+    MuseScoreView* view_ { 0 };
 
 public:
-    MuseScoreView* view              { 0 };
```
Comment (wizofaus) [inline src/engraving/libmscore/element.h:140]: Not sure why uncrustify doesn't complain about publicly settable pointer fields!

File: src/notation/internal/notationinteraction.cpp [hunk 2]
```diff
@@ -72,9 +73,8 @@ NotationInteraction::NotationInteraction(Notation* notation, INotationUndoStackP
         }
     });
 
-    m_dragData.ed.view = new ScoreCallbacks();
-    m_dropData.ed.view = new ScoreCallbacks();
-    m_gripEditData.view = new ScoreCallbacks();
+    m_dragData.ed = Ms::EditData(&m_scoreCallbacks);
+    m_dropData.ed = Ms::EditData(&m_scoreCallbacks);
```
Comment (wizofaus) [inline src/notation/internal/notationinteraction.cpp:77]: Tiny bit inefficient but this only gets created rarely

File: src/engraving/libmscore/cmd.cpp [hunk 3]
```diff
@@ -3876,7 +3876,7 @@ void Score::cmdPitchUp()
     if (el && el->isLyrics()) {
         cmdMoveLyrics(toLyrics(el), Direction::UP);
     } else if (el && (el->isArticulation() || el->isTextBase())) {
-        el->undoChangeProperty(Pid::OFFSET, el->offset() + PointF(0.0, -MScore::nudgeStep* el->spatium()), PropertyFlags::UNSTYLED);
+        el->undoChangeProperty(Pid::OFFSET, el->offset() + PointF(0.0, -MScore::nudgeStep * el->spatium()), PropertyFlags::UNSTYLED);
```
Comment (wizofaus) [inline src/engraving/libmscore/cmd.cpp:3879]: this came from uncrustify...

**Comment by vshalkevich** [comment]
@wizofaus 
CI_utests / run_tests (pull_request)
Test failed. Maybe there are any critical issues

File: src/notation/internal/notationinteraction.cpp (hunk 2 above)
Comment (igorkorsukov) [reply src/notation/internal/notationinteraction.cpp:77]: A bit unreliable, potential crash is possible if we pass a reference to a member of one class to another class. (for example, if in the future `m_dragData` and `m_scoreCallbacks` are swapped in the .h file and there will be some call to `m_scoreCallbacks` in the `EditData` destructor)
Maybe it's better to do a `shared_ptr`?
It will also be more correct semantically - the semantics of the code will "say" that `m_scoreCallbacks` is a shared object.

**Comment by wizofaus** [comment]
This is just following the pattern used elsewhere.  The objects all have the same lifetime/owner, so there's no risk of a crash unless an EditData object is copied and allowed to live longer than its parent - making the copy constructor private would probably be a good idea.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Review by igorkorsukov — APPROVED** [review]

**Comment by vshalkevich** [comment]
seems fine for me
