### PR TITLE
Fix crash in Measure & Staff/Part properties dialogs via keyboard

### LINKED ISSUE #20580: Measure and Staff/Part properties dialogs don't work via keyboard (and crash)
### Issue type

Crash or freeze

### Bug description

This is a sneaky one. When opened via the keyboard, the dialogs appear to work properly right up until you click the OK button.

When you click OK in:

- **Staff/Part properties:** MuseScore crashes.
- **Measure properties:** The dialog closes as you would expect, but the score is **not** updated to reflect whatever changes you made in the dialog.

Also, both dialogs crash if you try to use the next/previous staff/measure buttons in the bottom left of the dialogs.

### Steps to reproduce

1. Select a note or rest.
2. Press Shift+Right to create a range selection.
3. Press the Menu key or Shift+10 shortcut.
4. Choose **Measure properties** or **Staff/Part properties**.
5. Make some changes and click OK, or use the next/previous measure/staff buttons in the bottom left of the dialog.

### Screenshots/Screen recordings

Staff/Part properties | Measure properties
---|---
image | image

### MuseScore Version

Master and 4.2

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

### Additional context

Fix on the way.

### PR DESCRIPTION
**Pull request by shoogle**
Crash occurs when dialogs are opened via the keyboard.

Resolves #20580.

### CODE REVIEW

**Review by RomanPudashkin — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
Tested #20580 on Win10, Mac13.6, LinuxMint21 - **FIXED**

File: src/notation/view/widgets/measureproperties.cpp [hunk 1]
```diff
@@ -94,6 +94,13 @@ void MeasurePropertiesDialog::initMeasure()
     mu::engraving::Measure* measure = mu::engraving::toMeasure(context.element);
```
Comment (wizofaus) [inline src/notation/view/widgets/measureproperties.cpp:94]: this isn't reliable - can return garbage if context.element isn't a measure

**Comment by wizofaus** [comment]
This fix didn't fully resolve the issue, have put up another PR that should
