### PR TITLE
[MU4] Fix #8263 ensure score refreshed after adding attached elements from palette

### LINKED ISSUE #8263: [MU4 Issue] Accidentals added to trill line don't show immediately
**Describe the bug**
After adding a trill line to a note, then selecting the trill line and adding an accidental, it doesn't appear immediately, only after some other change that triggers a refresh.
NB same also happens adding accidentals to notes.

**To Reproduce**
1. Add a trill line to a note
2. Select the trill line
3. Add an accidental from the palette
4. No accidental appears
5. Change the note in some other way (or save/close/re-open etc.)
6. Accidental appears as expected

**Desktop (please complete the following information):**
Window 10 MSVC 2019 build.

**Additional context**
Has been reported by users since 3.2.2, and on Mac etc.

Doesn't *always* happen in 3.2.6, but I can't figure out when it does and doesn't.

### PR DESCRIPTION
**Pull request by wizofaus**
Resolves: https://github.com/musescore/MuseScore/issues/8263

Accidentals weren't appearing after adding them from the palette to notes or trill lines

- [ x ] I signed [CLA](https://musescore.org/en/cla)
- [ x ] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [ x ] I made sure the code compiles on my machine
- [ x ] I made sure there are no unnecessary changes in the code
- [ x ] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [ x ] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [ x ] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

**Comment by wizofaus** [comment]
This took me far too long to figure out (at least 2 hours, including build issues)   The  whole way accidentals and trill lines are handled really threw me - specifically the Trill::treeChild( ) and Accidental::treeParent( ) overrides that are in scoretree.cpp (and not trill.cpp!).  There seems to be a lot of "special case" logic here that I'm not sure I understand the reason for.  Also I found that the button in the Inspector to bring up the "accidentals" properties dialog doesn't work (for adding brackets etc.) - this is true in general, not just trill line accidentals. It seems somewhat similar to the Change Time Signature issue.

**Comment by MarcSabatella** [comment]
I don’t know the changes made for 4.0, but to me there shouldn’t be a need to modify a basic function like this that is called on every drop - should be more a matter of making sure the operation that actually adds the accidental triggers a layout.  But maybe things have changed.  Just be sure this doesn’t adversely affect performance of other drops - that they don’t trigger full score relayout  unnecessarily.

**Comment by wizofaus** [comment]
> I don’t know the changes made for 4.0, but to me there shouldn’t be a need to modify a basic function like this that is called on every drop - should be more a matter of making sure the operation that actually adds the accidental triggers a layout. But maybe things have changed. Just be sure this doesn’t adversely affect performance of other drops - that they don’t trigger full score relayout unnecessarily.

This function specifically only supports drops when new elements are added to the score, but the problem was nothing was triggering the bsp tree to be re-built in that case.  All drop actions that add new elements to the score need to do this, and I don't know all the other cases this gets triggered (though it does get triggered adding an accidental to a note via the palette, and that didn't have the same refresh issue, so I can look at how it works in that case).  I certainly can't notice any performance issues but I haven't tried with a really really big score.

**Comment by wizofaus** [comment]
> > I don’t know the changes made for 4.0, but to me there shouldn’t be a need to modify a basic function like this that is called on every drop - should be more a matter of making sure the operation that actually adds the accidental triggers a layout. But maybe things have changed. Just be sure this doesn’t adversely affect performance of other drops - that they don’t trigger full score relayout unnecessarily.
> 
> This function specifically only supports drops when new elements are added to the score, but the problem was nothing was triggering the bsp tree to be re-built in that case. All drop actions that add new elements to the score need to do this, and I don't know all the other cases this gets triggered (though it does get triggered adding an accidental to a note via the palette, and that DOES have the same problem). I certainly can't notice any performance issues but I haven't tried with a really really big score.
> 
> The only thing I'd still like to check is why it sometimes _does_ work in 3.6.2 without this change. There is no trigger of a bsp tree rebuild when adding items from the palette, and yet it still repaints correctly which doesn't seem possible.

Ok so in 3.6.2 the tree gets rebuilt because of:
```
        page->rebuildBspTree()

 	MuseScore3.exe!Ms::LayoutContext::collectPage() Line 4875	C++
 	MuseScore3.exe!Ms::LayoutContext::layout() Line 5049	C++
 	MuseScore3.exe!Ms::Score::doLayoutRange(const Ms::Fraction & st, const Ms::Fraction & et) Line 5035	C++
 	MuseScore3.exe!Ms::Score::update(bool resetCmdState) Line 302	C++
 	MuseScore3.exe!Ms::Score::endCmd(bool rollback) Line 262	C++
>	MuseScore3.exe!Ms::Palette::applyPaletteElement(Ms::Element * element, QFlags<enum Qt::KeyboardModifier> modifiers) Line 797	C++
```

now to figure out why it doesn't do that in 4.0

**Comment by wizofaus** [comment]
> > > I don’t know the changes made for 4.0, but to me there shouldn’t be a need to modify a basic function like this that is called on every drop - should be more a matter of making sure the operation that actually adds the accidental triggers a layout. But maybe things have changed. Just be sure this doesn’t adversely affect performance of other drops - that they don’t trigger full score relayout unnecessarily.
> > 
> > 
> > This function specifically only supports drops when new elements are added to the score, but the problem was nothing was triggering the bsp tree to be re-built in that case. All drop actions that add new elements to the score need to do this, and I don't know all the other cases this gets triggered (though it does get triggered adding an accidental to a note via the palette, and that DOES have the same problem). I certainly can't notice any performance issues but I haven't tried with a really really big score.
> > The only thing I'd still like to check is why it sometimes _does_ work in 3.6.2 without this change. There is no trigger of a bsp tree rebuild when adding items from the palette, and yet it still repaints correctly which doesn't seem possible.
> 
> Ok so in 3.6.2 the tree gets rebuilt because of:
> 
> ```
>         page->rebuildBspTree()
> 
>  	MuseScore3.exe!Ms::LayoutContext::collectPage() Line 4875	C++
>  	MuseScore3.exe!Ms::LayoutContext::layout() Line 5049	C++
>  	MuseScore3.exe!Ms::Score::doLayoutRange(const Ms::Fraction & st, const Ms::Fraction & et) Line 5035	C++
>  	MuseScore3.exe!Ms::Score::update(bool resetCmdState) Line 302	C++
>  	MuseScore3.exe!Ms::Score::endCmd(bool rollback) Line 262	C++
> >	MuseScore3.exe!Ms::Palette::applyPaletteElement(Ms::Element * element, QFlags<enum Qt::KeyboardModifier> modifiers) Line 797	C++
> ```
> 
> now to figure out why it doesn't do that in 4.0

The plot thickens - in 4.0 Score.update( ) is called when notifyAboutDropChanged() is called, but by that time it seems the CmdState has lots its layoutRange so nothing actually happens.

**Comment by wizofaus** [comment]
> > > > I don’t know the changes made for 4.0, but to me there shouldn’t be a need to modify a basic function like this that is called on every drop - should be more a matter of making sure the operation that actually adds the accidental triggers a layout. But maybe things have changed. Just be sure this doesn’t adversely affect performance of other drops - that they don’t trigger full score relayout unnecessarily.
> > > 
> > > 
> > > This function specifically only supports drops when new elements are added to the score, but the problem was nothing was triggering the bsp tree to be re-built in that case. All drop actions that add new elements to the score need to do this, and I don't know all the other cases this gets triggered (though it does get triggered adding an accidental to a note via the palette, and that DOES have the same problem). I certainly can't notice any performance issues but I haven't tried with a really really big score.
> > > The only thing I'd still like to check is why it sometimes _does_ work in 3.6.2 without this change. There is no trigger of a bsp tree rebuild when adding items from the palette, and yet it still repaints correctly which doesn't seem possible.
> > 
> > 
> > Ok so in 3.6.2 the tree gets rebuilt because of:
> > ```
> >         page->rebuildBspTree()
> > 
> >  	MuseScore3.exe!Ms::LayoutContext::collectPage() Line 4875	C++
> >  	MuseScore3.exe!Ms::LayoutContext::layout() Line 5049	C++
> >  	MuseScore3.exe!Ms::Score::doLayoutRange(const Ms::Fraction & st, const Ms::Fraction & et) Line 5035	C++
> >  	MuseScore3.exe!Ms::Score::update(bool resetCmdState) Line 302	C++
> >  	MuseScore3.exe!Ms::Score::endCmd(bool rollback) Line 262	C++
> > >	MuseScore3.exe!Ms::Palette::applyPaletteElement(Ms::Element * element, QFlags<enum Qt::KeyboardModifier> modifiers) Line 797	C++
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > now to figure out why it doesn't do that in 4.0
> 
> In 4.0 notifyAboutDropChanged() is calling NotationParts::updatePartTitles( ) and in that case the CmdState is reset, and I believe it's because of this that the layout is not refreshing properly.

Ok I have an alternative fix that instead of calling `notifyAboutDropChanged()` directly just sets a flag to call it after `apply()` is called, which seems to work fine in the cases I've tested too.

File: src/notation/internal/notationinteraction.cpp [hunk 1]
```diff
@@ -1389,7 +1394,7 @@ void NotationInteraction::applyDropPaletteElement(Ms::Score* score, Ms::Element*
         }
         dropData.dropElement = 0;
 
-        notifyAboutDropChanged();
```
Comment (wizofaus) [inline src/notation/internal/notationinteraction.cpp:1392]: This was the main culprit - calling this before apply() means the cmdState gets reset and hence endCmd() doesn't update the score as required.
I'm still not convinced this is quite right though as now there are two serialized calls to startCmd()/endCmd() for each add-from-palette operation (previously they were nested), which might cause an issue with undo - but the undo/redo stack is already unstable in MU4 so hard to know if it's caused an issue.

**Comment by wizofaus** [comment]
Is there a hold up getting this merged?  Without this fix adding almost anything from the palettes appears to do nothing (because the score isn't updating properly).

**Comment by wizofaus** [comment]
Should also fix https://github.com/musescore/MuseScore/issues/7882

**Comment by wizofaus** [comment]
BTW this also fixes the issue where the score becomes corrupted and MuseScore crashes after changing the time signature.

File: src/notation/internal/notationinteraction.cpp [hunk 2]
```diff
@@ -26,6 +26,7 @@
 #include <QRectF>
 #include <QPainter>
 #include <QClipboard>
+#include <QApplication>
```
Comment (wizofaus) [inline src/notation/internal/notationinteraction.cpp:29]: Without this you can't compile just this file on its own and you get errors highlighted in Visual Studio.  Not quite sure why it compiles as part of the full build!
