### PR TITLE
Fix #13213: Save as command deletes initial file

### LINKED ISSUE #13213: [MU4 Issue] Save As command deletes the initial score from disk
**To Reproduce**
1. Create score
2. Save it as '1'
3. Reopen 
4. Using **Save as**, re-save it as '1a' - **score '1' is deleted from disk and both scores are empty in Recent scores** 
 

https://user-images.githubusercontent.com/90187801/188708418-71fb4ff9-92a9-4960-928d-57c50e38c494.mp4

**Platform information**
Windows, Mac, Linux

### PR DESCRIPTION
**Pull request by HemantAntony**
Resolves: #13213

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

File: src/project/internal/notationproject.cpp [hunk 1]
```diff
@@ -593,9 +593,9 @@ mu::Ret NotationProject::makeCurrentFileAsBackup()
     }
 
     io::path_t backupFilePath = filePath + "~";
-    ret = fileSystem()->move(filePath, backupFilePath, true);
+    ret = fileSystem()->copy(filePath, backupFilePath, true);
     if (!ret) {
-        LOGE() << "failed to move from: " << filePath << ", to: " << backupFilePath;
+        LOGE() << "failed to copy: " << filePath << " to: " << backupFilePath;
         return ret;
```
Comment (wizofaus) [inline src/project/internal/notationproject.cpp:599]: while I agree this is better, are you sure it doesn't break regular save, which appears to try to move from "xxxx_saving" to "xxxx", which is likely to fail if xxxx stil exists?

Comment (HemantAntony) [reply src/project/internal/notationproject.cpp:599]: Oh I didn't think about that. Let me check

Comment (RomanPudashkin) [reply src/project/internal/notationproject.cpp:599]: >are you sure it doesn't break regular save, which appears to try to move from "xxxx_saving" to "xxxx", which is likely to fail if xxxx still exists?

It shouldn't because we call copy with replace = true. Anyway, I asked @DmitryArefiev  to check both Save and Save as

**Review by RomanPudashkin — APPROVED** [review]

File: src/project/internal/notationproject.cpp (hunk 1 above)
Comment (HemantAntony) [reply src/project/internal/notationproject.cpp:599]: When I checked it nothing broke. But I thought my solution might not be the correct fix :)

**Comment by DmitryArefiev** [comment]
Tested #13213 on Win10, Mac12, LinuxMint 20.2 - **FIXED**
