### PR TITLE
Fix #7819 - adjustment to previous page-clipping fix

### LINKED ISSUE #7819: [MU4 Issue] Instruments render outside the score if added a lot of instruments
**Describe the bug**
Instruments go outside the score if added a lot of instruments on the Score Wizard

**To Reproduce**
1. Start creating a new score
2. Add a lot of instruments (about 10-15)
3. Click Done and observe created score view.

**Expected behavior**
Instruments should not go outside the score if  a lot of instruments added to the Score Wizard

**Screenshots**
2021-03-30 01_56_30-Window

**Desktop (please complete the following information):**
Windows 10

**Additional context**

### PR DESCRIPTION
**Pull request by wizofaus**
Resolves: #7819 

Had previously fixed this but code had been moved around since and additional logic around when to apply clipping added by others.

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

File: src/engraving/rendering/dev/paint.cpp [hunk 1]
```diff
@@ -57,6 +57,7 @@ void Paint::paintScore(draw::Painter* painter, Score* score, const IScoreRendere
 
     // Setup Painter
     painter->setAntialiasing(true);
+    painter->setClipping(false);
```
Comment (cbjeukendrup) [inline src/engraving/rendering/dev/paint.cpp:60]: It looks like this change makes the condition `if (!painter->hasClipping()) {` in line +135 always true, which is remarkable. So we need to think carefully about that. It might undo the benefits of https://github.com/musescore/MuseScore/commit/f642ca7093333bf9a129fae393ce5c1ac311dc7b.

Comment (wizofaus) [reply src/engraving/rendering/dev/paint.cpp:60]: It won't be if the painter doesn't support clipping...
At the moment that condition is always *false*, so it never applies the correct clipping.

Comment (wizofaus) [reply src/engraving/rendering/dev/paint.cpp:60]: Actually it's worse than that, it appears this change has broken repainting while adding notes etc.  Looking into it.

Comment (wizofaus) [reply src/engraving/rendering/dev/paint.cpp]: Ok have re-done.  It seems to be working OK for the cases I can test now, and the logic is simpler (no ifs!).

**Review by cbjeukendrup — APPROVED** [review]

File: src/engraving/rendering/dev/paint.cpp [hunk 2]
```diff
@@ -129,21 +131,14 @@ void Paint::paintScore(draw::Painter* painter, Score* score, const IScoreRendere
             }
 
             // Draw page elements
-            bool disableClipping = false;
-
-            if (!painter->hasClipping()) {
-                painter->setClipping(true);
-                painter->setClipRect(pageRect);
```
Comment (RomanPudashkin) [inline src/engraving/rendering/dev/paint.cpp:136]: With this change, we can no longer specify a custom clipping area... I'm also wondering how it affects performance, since this code was added to reduce the CPU load during playback (only the playback cursor rect is redrawn)

File: src/engraving/rendering/dev/paint.cpp [hunk 3]
```diff
@@ -129,21 +131,14 @@ void Paint::paintScore(draw::Painter* painter, Score* score, const IScoreRendere
...
-                disableClipping = true;
```
Comment (RomanPudashkin) [inline src/engraving/rendering/dev/paint.cpp:137]: It's also causing this regression:

Screen Shot 2024-04-08 at 10 18 13

File: src/engraving/rendering/dev/paint.cpp (hunk 2 above)
Comment (cbjeukendrup) [reply src/engraving/rendering/dev/paint.cpp:136]: You can still specify a clip rect (namely via opt.frameRect) but with this change it will be intersected with the page rect, to avoid drawing outside page rect.

File: src/engraving/rendering/dev/paint.cpp (hunk 3 above)
Comment (cbjeukendrup) [reply src/engraving/rendering/dev/paint.cpp:137]: I think I've also seen that in master sometimes

**Comment by wizofaus** [comment]
I admit I didn't test during playback, can try, but I'm pretty sure the logical change is sound...

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

File: src/engraving/rendering/dev/paint.cpp (hunk 3 above)
Comment (wizofaus) [reply src/engraving/rendering/dev/paint.cpp:137]: How do you reproduce that?  I couldn't, using a build from my own branch.

Comment (wizofaus) [reply src/engraving/rendering/dev/paint.cpp:137]: Hmm ok I *can* reproduce it (it only seems to happen at particular zoom levels), but it *does* also happen using the version from master - just not quite as obviously, and only if you zoom in and out while playing back. Will investigate.

Comment (wizofaus) [reply src/engraving/rendering/dev/paint.cpp:137]: Wow, this has me totally baffled, nothing makes sense as to when and why this happens and what to do about it (for me most of the time zooming into 141% then starting playback is enough, but sometimes it doesn't happen at that level and you need to zoom in even further).  It's hard not to suspect there's a bug in Qt somewhere, but I agree it's definitely more likely to happen with the changes in this PR than on master, and I'd even accept it's likely to affect more users than the bug that it was trying to fix (seriously as that is).

Comment (wizofaus) [reply src/engraving/rendering/dev/paint.cpp:137]: Ok, found something that works, have a slightly better understanding now of why the existing clipping rectangle is getting set (though far from perfect), but it seems that the safest/most reliable/performant fix is to simply treat the case of the drawing rectangle extending below the page as a special case and in this case overriding the clipping rectangle with the page rectangle (intersecting was causing other issues).

File: src/engraving/rendering/dev/paint.cpp (hunk 2 above)
Comment (wizofaus) [reply src/engraving/rendering/dev/paint.cpp:137]: Reversed that change, couldn't get it to avoid that playback cursor repaint issue.

File: src/engraving/rendering/dev/paint.cpp [hunk 4]
```diff
@@ -122,6 +122,10 @@ void Paint::paintScore(Painter* painter, Score* score, const IScoreRenderer::Pai
                 painter->translate(-pageRect.topLeft());
             }
 
+            if (drawRect.bottom() > pageRect.bottom()) {
+                painter->setClipRect(pageRect);
```
Comment (wizofaus) [inline src/engraving/rendering/dev/paint.cpp:126]: Makes sense to treat this as a special case, as there's really the only one way elements can end up being drawn "off" the page, and in that case there's no point trying to maintain the QtQuick dirty rectangle optimisations (which are what control the existing clipping rect).

**Comment by wizofaus** [comment]
The vdiff failure here is real, it looks like anti-aliasing is not working properly. But the same is true for me when running a build from master! (actually I'd noticed that a bit recently, didn't think much of it)

File: src/engraving/rendering/dev/paint.cpp [hunk 5]
```diff
@@ -122,6 +122,11 @@ void Paint::paintScore(Painter* painter, Score* score, const IScoreRenderer::Pai
                 painter->translate(-pageRect.topLeft());
             }
 
+            if (painter->hasClipping() && drawRect.bottom() > pageRect.bottom()) {
```
Comment (cbjeukendrup) [inline src/engraving/rendering/dev/paint.cpp:125]: Actually, I think checking only the bottom is not really enough. Elements can fall off the page to the left or right side just as well as on the bottom side (for example, a too-long text element on the last measure of a system may extend beyond the right margin)

Comment (wizofaus) [reply src/engraving/rendering/dev/paint.cpp:125]: sure, I couldn't find a case of it, but happy to add those checks.

Comment (wizofaus) [reply src/engraving/rendering/dev/paint.cpp]: ok, now checks if the drawRect extends outside the pageRect on any side, and if so uses the *whole* page rectangle as the clip rectangle, which works as expected.  In principle it should be possible to do an intersection to work out the minimum clipping rectangle, but it seems to cause too much glitches around the edge.

**Comment by wizofaus** [comment]
Confirmed fix is still required & rebased.

**Comment by cbjeukendrup** [comment]
I think this looks good now, @RomanPudashkin any objections?

However I'm still slightly disappointed that the initial fix of intersecting the existing clip rect with the page rect [introduced a regression](https://github.com/musescore/MuseScore/pull/22135#discussion_r1555348204), because that was more elegant imo. 
I was wondering, would that regression be fixed by replacing https://github.com/musescore/MuseScore/blob/186c925cb4255e38b6f609868ad4049eff77c0c0/src/notation/view/abstractnotationpaintview.cpp#L1368-L1370 with 
```c++
    RectF dirtyRect1 = fromLogical(oldCursorRect).adjusted(-1, -1, 2, 2);
    RectF dirtyRect2 = fromLogical(newCursorRect).adjusted(-1, -1, 2, 2);
```
or perhaps 
```c++
    RectF dirtyRect1 = fromLogical(oldCursorRect).adjusted(-2, -2, 2, 2);
    RectF dirtyRect2 = fromLogical(newCursorRect).adjusted(-2, -2, 2, 2);
```
?

@RomanPudashkin which solution would you prefer, the current one or the original one?

**Comment by wizofaus** [comment]
As far as I can determine the original fix only didn't work reliably because of some bug in Qt, or something I couldn't figure out anyway. Artifacts still do appear from time to time even with the current master (but don't really cause a problem).
But it really is only to handle a situation that shouldn't really happen under normal circumstances - in fact arguably MuseScore should never try to place elements that don't fit on the page (hence if you have too many staves, it should force introduce a mid-system page-break, or force scale everything down to fit).

**Comment by RomanPudashkin** [comment]
@cbjeukendrup @wizofaus I've been playing with the playback cursor recently. My idea now is to draw it outside of the score view. Here's what it looks like: https://github.com/musescore/MuseScore/pull/24576/commits/af07099e87bb7ad31165d6af3be30b33ec33f8d0

This decently reduces CPU/GPU load during playback and we also don't have to increase the redraw area to fix this issue. Also, there will no longer be that problem when the playback cursor erases something during playback

**Comment by wizofaus** [comment]
> @cbjeukendrup @wizofaus I've been playing with the playback cursor recently. My idea now is to draw it outside of the score view. Here's what it looks like: [af07099](https://github.com/musescore/MuseScore/commit/af07099e87bb7ad31165d6af3be30b33ec33f8d0)
> 
> This decently reduces CPU/GPU load during playback and we also don't have to increase the redraw area to fix this issue. Also, there will no longer be that problem when the playback cursor erases something during playback

Is there a downside? (other than it using more QML, which I'm not really a fan of...)
Is it worth me taking this commit and combining with my original clipping fix in this PR?

**Comment by RomanPudashkin** [comment]
You don't have to do anything. Just wait until we merge my PR and rebase yours after that

**Comment by RomanPudashkin** [comment]
@wizofaus please rebase

File: src/engraving/rendering/score/paint.cpp [hunk 6]
```diff
@@ -122,6 +122,12 @@ void Paint::paintScore(Painter* painter, Score* score, const IScoreRenderer::Pai
                 painter->translate(-pageRect.topLeft());
             }
 
+            if (painter->hasClipping() && (drawRect.top() < pageRect.top() || drawRect.bottom() > pageRect.bottom()
```
Comment (RomanPudashkin) [inline src/engraving/rendering/score/paint.cpp:125]: Shouldn't it be drawRect.top() **>** pageRect.top() || drawRect.bottom() **<** pageRect.bottom()?

Comment (RomanPudashkin) [reply src/engraving/rendering/score/paint.cpp:125]: Or maybe we can even use something like drawRect.intersected(pageRect) here...

Comment (wizofaus) [reply src/engraving/rendering/score/paint.cpp:125]: If you merged that other change you mentioned to draw the cursor separately then yes, I'd like to try the intersect method again.  But no, this is otherwise correct - if the drawRect extends outside the pageRect, it uses the whole pageRect for clipping.

Comment (RomanPudashkin) [reply src/engraving/rendering/score/paint.cpp:125]: Yes, I merged it

Comment (wizofaus) [reply src/engraving/rendering/score/paint.cpp:125]: Something's changed since I last worked on this, I can't get the clipping rectangle to work properly at all now...happy to hand it over as I don't know how much time I'll have.  The problem definitely still exists at any rate.

Comment (wizofaus) [reply src/engraving/rendering/score/paint.cpp:125]: Actually...I did get it working...but the playback cursor still draws off the edge of the page area which looks a bit odd...

**Review by RomanPudashkin — APPROVED** [review]

**Comment by cbjeukendrup** [comment]
Suddenly I started doubting whether this is desirable. When things that fall off the page are not drawn, you won't ever notice that they are there:
- if an entire staff falls off the page, you can easily overlook that, and your full score won't have all instruments visible and the conductor will be confused
- if you have accidentally dragged an element off the page, and you can't see it anymore, you won't know that it is there. This means you're stuck with an obsolete element in your score; and more importantly, if that's an element that influences playback or something like that, you're going to have a hard time figuring out why playback is weird, because you have no way to see the element that's causing the weirdness.

Sorry for this very late realisation. But we'll need to give this some UX thought to this.

Of course, it is ugly, when stuff is drawn beyond the border of the page. But whenever that happens, it's a user error. If anything, we should try to prevent such user errors from happening; but we should not "mask" user errors, because that makes it impossible to correct them.

**Comment by MarcSabatella** [comment]
Definitely agreed - it's better to show the content off the page than not.  But better still to figure out something reasonable to do.  Merely scaling the page down to force it to fit isn't going to work well, because that will in turn impact how many measures fit on the page, which in turn may affect how much vertical space is required.  Maybe a warning could be added during corruption checks?

**Comment by wizofaus** [comment]
It's supposed to be WYSIWYG, i.e. representing what your output will look like when you print it out. 
I don't believe there's any other such application out there that doesn't crop/clip items that don't fit on the on-screen representation of the page.
And there may well be cases that's what the user wants, especially if it's just a design feature for a title page etc. Perhaps there's a case for having a mode where you can see items drawn off the edge of the page but what it does now by default very much looks like a bug - especially in the "publish" view.

**Comment by wizofaus** [comment]
BTW if you do manage to modify an element so it ends up drawn onto another page (e.g. I did by changing the horizontal justification), you can't interact with it at all or determine what it belongs to:

image

**Comment by wizofaus** [comment]
Though interestingly with the keyboard you can even enter notes in staves that are off the bottom of the page:

image

**Comment by wizofaus** [comment]
Perhaps we could leave items drawn off the page in "Floating" view only, whatever that is... (I've never quite understood).

**Comment by MarcSabatella** [comment]
I can’t think of any graphics editors I have ever used that *dont* still draw elements when moved off the page.  It’s actually a pretty crucial feature in that context.  Dragging things off the page is less of a thing in MuseSvore, but it still seems way more natural to still see it than not.  I’m more concerned with the case of a system extending past the bottom margin though, and making it as obvious as possible that this is what is happening.

**Comment by wizofaus** [comment]
Heh, I just tried using the "highlighter" Pen in MS Word Draw mode, and you do actually see it initially draw off the edge of the page boundaries, but then it cleans it up shortly after.  Seems to be a quirk of that tool as nothing else (WordArt etc.) ever draws off the edge of the page.  No other applications I tried (including Adobe Acrobat, etc.) allow drawing off the edge of a page at all, and elements that don't fit on the page are always clipped.  Which examples were you thinking of?

**Comment by wizofaus** [comment]
BTW the current behaviour (in MS 4.3) when entering a line of text that won't fit on the page isn't great, you end up not being able to see what you're typing:
image

**Comment by MarcSabatella** [comment]
Google Drawings, Inkscape, etc.  Drawing apps that allow you to place object on a canvas then move them.  It’s a common technique to move objects off the page temporarily while working as a form of temporary storage for elements you aren’t sure you will want to use, like in doing A/B comparisons of different designs.  Not that this relates directly to MuseScore, but the point is, it’s a very common pattern and the idea of having the off-canvas elements visible  is something that I’d think most users would be quite familiar with.  And as noted, it’s quite bad for elements you’ve moved off the page and potentially affecting layout and playback to be impossible to see and select.

**Comment by wizofaus** [comment]
Sure, I accept that there are some downsides to always clipping.  But at very least it should definitely do so in Publish mode, and really we need to think a bit more about how to ensure that objects drawn completely outside the page boundaries can still be interacted with (because they can't with the mouse in the current version).

**Comment by cbjeukendrup** [comment]
Clipping to page borders in Publish mode only seems a good compromise.
And yes, it is indeed problematic that items outside a page (or dragged to the wrong page, even) cannot be clicked. Probably not trivial to solve. But anyway, being able to see the element at least is still better than not being able to see it anymore at all.

**Comment by wizofaus** [comment]
That should be relatively easy to change, but it's worth asking then if it really resolves the bug as reported.

Is there any case for having systems split over multiple pages if required? (I have some study scores that do that, though they flip into landscape mode, and it's only ever across two "open" pages, never over a page turn).

**Comment by MarcSabatella** [comment]
Seems pretty clear the person reporting wouldn't be happy with any proposed rearranging of the pixels that end up on the outskirts of the page.  They presumably just want the music to actually fit on the page.  Which isn't a bad thing to want, but as noted, that a much harder problem.

Anyhow, I agree, not showing the off-page elements in publish mode seems like a no-brainer.  Potentially could also disappear if you turn off display of invisible elements, even though that of course isn't really right.

File: src/engraving/rendering/score/paint.cpp [hunk 7]
```diff
@@ -116,6 +116,14 @@ void Paint::paintScore(Painter* painter, Score* score, const IScoreRenderer::Pai
 
             painter->beginObject("page_" + std::to_string(pi));
 
+            if (opt.isPrinting && painter->hasClipping() && (drawRect.top() < pageAbsRect.top() || drawRect.bottom() > pageAbsRect.bottom()
+                                                             || drawRect.left() < pageAbsRect.left()
+                                                             || drawRect.right() > pageAbsRect.right())) {
```
Comment (cbjeukendrup) [inline src/engraving/rendering/score/paint.cpp:121]: Do we still need these `<` and `>` checks now that we're back at the `.intersected` solution?

Comment (wizofaus) [reply src/engraving/rendering/score/paint.cpp:121]: Technically no, but it's a minor optimisation that makes debugging and intent a bit clearer.

**Comment by zacjansheski** [comment]
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved

File: src/engraving/rendering/score/paint.cpp (hunk 7 above)
Comment (RomanPudashkin) [reply src/engraving/rendering/score/paint.cpp:121]: I don't think so... The intent is already pretty clear, and they do nothing for optimization. It would be better to get rid of these checks
