### PR TITLE
Hook height migration

### LINKED ISSUE #33348: Keyboard pedal hook issue
### Issue type

Engraving bug (incorrect score rendering)

### Description with steps to reproduce

1. Open the score 

[merry-go-round-of-life-howls-moving-castle-piano-tutorial (1).mscz.zip](https://github.com/user-attachments/files/27592805/merry-go-round-of-life-howls-moving-castle-piano-tutorial.1.mscz.zip)
2. Pay attention to measure 7 and 15. 
The issue reproduces in case of elements in parentheses (Ped.) which appears active element from the previous system.

### Supporting files, videos and screenshots

Image

### In which versions of MuseScore Studio is this issue present?

4.6, 4.7

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

macOS

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by miiizen**
Resolves: https://github.com/musescore/MuseScore/issues/33348
This PR migrates hook height signs (<4.6) on file read to avoid an additional score layout. 

It also fixes a bug in ornament cue note layout order covered up by this second layout.

### CODE REVIEW

File: src/engraving/rw/read410/tread.cpp [hunk 1]
```diff
@@ -4134,6 +4140,19 @@ void TRead::read(TextLineBase* b, XmlReader& e, ReadContext& ctx)
...
+            Spatium beginHookHeight = b->getProperty(Pid::BEGIN_HOOK_HEIGHT).value<Spatium>();
+            b->setProperty(Pid::BEGIN_HOOK_HEIGHT, -beginHookHeight);
+        }
+        if (!b->isStyled(Pid::END_HOOK_HEIGHT)) {
+            Spatium endHookHeight = b->getProperty(Pid::END_HOOK_HEIGHT).value<Spatium>();
+            b->setProperty(Pid::END_HOOK_HEIGHT, -endHookHeight);
+        }
+    }
+
+    compat::CompatUtils::resetHookHeightSign(b);
```
Comment (mike-spa) [inline src/engraving/rw/read410/tread.cpp:4144]: Seems like there's code before the function call that does the same thing as the function?

File: src/engraving/tests/compat114_data/hairpin-ref.mscx [hunk 2]
```diff
@@ -130,6 +130,8 @@
           <Spanner type="HairPin">
             <HairPin>
               <subtype>0</subtype>
+              <beginHookHeight>-1.9</beginHookHeight>
+              <endHookHeight>-1.9</endHookHeight>
```
Comment (mike-spa) [inline src/engraving/tests/compat114_data/hairpin-ref.mscx:134]: These tests changes look quite weird: why are we suddenly adding hookHeight tags to hairpins?

File: src/engraving/rw/read114/read114.cpp [hunk 3]
```diff
@@ -1174,6 +1174,7 @@ static void readVolta114(XmlReader& e, ReadContext& ctx, Volta* volta)
     }
     volta->setOffset(PointF());          // ignore offsets
     volta->setAutoplace(true);
+    CompatUtils::resetHookHeightSign(volta);
```
Comment (mike-spa) [inline src/engraving/rw/read114/read114.cpp:1177]: It makes me a bit uncomfortable to have to add this compat function to 20 different places across all the read module. Could we not move this to `EngravingCompat::doPreLayoutCompat`? It will perhaps slightly add to the reading time as we need to navigate and find these spanners, but it's well worth it IMO if it saves us from calling it so many times

**Review by mike-spa — COMMENTED** [review]
Would you mind moving the ornament cui note fix to a separate PR? I think the hook sign fix could potentially go in 4.7, but the cur note fix certainly not

File: src/engraving/rw/read114/read114.cpp (hunk 3 above)
Comment (miiizen) [reply src/engraving/rw/read114/read114.cpp:1177]: We could, but I'm keen to put as much compatibility code which doesn't require score context in the file reading code as possible. Otherwise we need to add the same compatibility fix for palette items in PaletteCompat, which is something we always forget to do and I'd prefer to avoid where possible. This was part of the motivation behind versioning the palette files.

I agree this is a bit messy though.

File: src/engraving/tests/compat114_data/hairpin-ref.mscx (hunk 2 above)
Comment (miiizen) [reply src/engraving/tests/compat114_data/hairpin-ref.mscx:134]: We've changed the hookHeight value by flipping it so it no longer matches the default. Hairpin's hook heights look like this by default pre 4.6
Screenshot 2026-03-05 at 10 45 40

File: src/engraving/rw/read114/read114.cpp (hunk 3 above)
Comment (mike-spa) [reply src/engraving/rw/read114/read114.cpp:1177]: Ah good point about the palettes, then yeah I think it's fine :+1:

**Comment by davidstephengrant** [comment]
Tested and approved on Ubuntu 24.04.4 LTS.

**Review by mike-spa — APPROVED** [review]
