### PR TITLE
Fix #10440: Re-add Remove measures to Context menu

### LINKED ISSUE #10440: Context menu no longer has 'Remove measures' option. We should re-add it with some UX cleanup.
**Describe the bug**
Removing measures is still quite hard in MS4. One method from MS3 was to right click on selected measures and opt to 'remove' them. This was always a little tough to find because there is another option called **'Delete'** which seems much more likely to fulfil that function.

I'm guessing someone assumed these two functions were duplicating functionality and removed one of them.

image

**Expected behavior**
We need to do two things:

1. We need to add a 'Delete measures' option (and still use the delete icon) - this should be tied to the existing shortcut: Ctrl (command) +backspace
2. Under that we put the existing 'Delete' feature but rename it to 'Clear measures' (and still use the delete symbol)

**Additional context**

### PR DESCRIPTION
**Pull request by duanjr**
Resolves: [#10440](https://github.com/musescore/MuseScore/issues/10440)

In order not to interfere with other menus，I only rewrite context menu when select measure(s).
I also add Icon to "time-delete", for it's only used here(except shortcut), I think it's ok to add that.

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

https://user-images.githubusercontent.com/71218187/153349899-d57d84c1-9a00-486c-8e81-2ccbe79d2f46.mp4

### CODE REVIEW

File: src/notation/view/notationcontextmenumodel.cpp [hunk 1]
```diff
@@ -80,7 +80,22 @@ MenuItemList NotationContextMenuModel::makeDefaultCopyPasteItems()
...
+        makeMenuItem("notation-cut"),
+        makeMenuItem("notation-copy"),
+        makeMenuItem("notation-paste"),
+        makeMenuItem("notation-swap"),
+    };
+
+    items << makeSeparator();
+
+    MenuItem* clearItem = makeMenuItem("notation-delete");
+    clearItem->setTitle("Clear measures");
```
Comment (RomanPudashkin) [inline src/notation/view/notationcontextmenumodel.cpp:93]: You missed translations here. Should be:

clearItem->setTitle(qtrc("notation", "Clear measures"))

The same for deleteItem

Comment (duanjr) [reply src/notation/view/notationcontextmenumodel.cpp]: Thanks for pointing it out. I already corrected it.

**Review by RomanPudashkin — APPROVED** [review]
