### PR TITLE
fixed #20034: Crash when navigate slur with Orca enabled on Linux

### LINKED ISSUE #20034: Crash when navigate slur with Orca enabled on Linux
### Issue type

Crash or freeze

### Steps to reproduce

1. Enable screen reader (Orca)
2. Create score with slur
3. Save and close
4. Reopen
5. Navigate slur with **Alt+right**

### MuseScore Version

4.2 master

### Regression

Yes, this used to work in **MuseScore 4.1.1**

### Operating system

LinuxUbuntu 22.04

**Doesn't occur** on Win/Mac

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Eism**
Resolves: #20034

Also see https://github.com/musescore/MuseScore/pull/19457#issuecomment-1820555056

### CODE REVIEW

File: src/engraving/dom/score.cpp [hunk 1]
```diff
@@ -160,7 +160,6 @@ Score::Score()
     m_style = DefaultStyle::defaultStyle();
 
     m_rootItem = new RootItem(this);
-    m_rootItem->setParent(this);
```
Comment (igorkorsukov) [inline src/engraving/dom/score.cpp:163]: Why should this be removed?

**Review by cbjeukendrup — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
Tested #20034 on Win10, Mac13.6, **LinuxMint 21** - **FIXED**
