### PR TITLE
Fix #20547: Staff creation when instrument is selected

### LINKED ISSUE #20547: Newly created stave in selected instrument is not selected automatically
### Issue type

UX/Interaction bug (incorrect behaviour)

### Bug description

When creating a new stave under an instrument, the stave is always created non-selected.
This happens whether the instrument itself is selected or not.

This allows a case where an instrument is selected, but one of its staves is not.
As far as I could see - this is the only way to get to that situation.

As a result - it is very confusing when hiding staves of that instrument.
Clicking the eye icon for the non-selected stave only hides that one.
But clicking the icon for other (selected) staves, hides the non-selected one as well.
This is because while the new stave is not selected, the instrument _is_, and hiding a selected stave hides _all_ selected staves (which is logical).
This caused me a great deal of confusion and made me write multiple bug reports (and then realize I didn't understand things correctly).

Since I could not find any other way to have a non-selected stave under a selected instrument, I think it's best if we change the new-stave behaviour to be automatically selected if the instrument it is created for is selected. 
Or, alternatively, remove all selection in this case.

### Steps to reproduce

1. Create new file
2. Go the the instruments pane
3. Select the current instrument
4. Open the drop-down, and add a new stave
5. Press the eye icon for the selected stave - and the non-selected stave gets hidden as well.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/1386239/de782a0b-e059-4e3e-a8e6-0772bcda5164

### MuseScore Version

4.2.0

### Regression

I don't know

### Operating system

Windows 11

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SalvadorCorreia**
Previously, when adding a new staff under a selected instrument, it was created as non-selected. This caused confusion, particularly when hiding staffs, as selected staffs affected the newly created one, but not vice versa. To resolve this issue, I have updated the behavior so that a newly created staff is automatically selected if the instrument it is created for is selected. This ensures consistency and clarity in managing staffs, addressing the confusion experienced by users.

Resolves: #20547

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

**Comment by cbjeukendrup** [comment]
Judging from `AbstractInstrumentsPanelTreeItem::setIsSelected`, we should perhaps go for a more general solution. What if you move this new code to `AbstractInstrumentsPanelTreeItem::appendChild` and `AbstractInstrumentsPanelTreeItem::insertChild`?

File: src/instrumentsscene/view/staffcontroltreeitem.cpp [hunk 1]
```diff
@@ -51,4 +51,7 @@ void StaffControlTreeItem::appendNewItem()
     staff->setDefaultClefType(part->instrument()->clefType(lastStaffIndex));
 
     masterNotation()->parts()->appendStaff(staff, m_partId);
+    if (this->parentItem()->isSelected()) {
```
Comment (cbjeukendrup) [inline src/instrumentsscene/view/staffcontroltreeitem.cpp:54]: For better readability, we prefer not unnecessarily using `this->`:
```suggestion
    if (parentItem()->isSelected()) {
```

**Comment by SalvadorCorreia** [comment]
I have currently followed @cbjeukendrup's instructions and believe to have made my solution more general.

**Review by cbjeukendrup — APPROVED** [review]

**Comment by zacjansheski** [comment]
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/20547 FIXED
