### PR TITLE
[MU4] fix #7819 - don't draw page elements outside page bounding box

### LINKED ISSUE #7819: [MU4 Issue] Instruments render outside the score if added a lot of instruments
**Describe the bug**
Instruments go outside the score if added a lot of instruments on the Score Wizard

**To Reproduce**
1. Start creating a new score
2. Add a lot of instruments (about 10-15)
3. Click Done and observe created score view.

**Expected behavior**
Instruments should not go outside the score if  a lot of instruments added to the Score Wizard

**Screenshots**
2021-03-30 01_56_30-Window

**Desktop (please complete the following information):**
Windows 10

**Additional context**

### PR DESCRIPTION
**Pull request by wizofaus**
Resolves: https://github.com/musescore/MuseScore/issues/7819

Ensures that score elements aren't drawn onto background (outside page bounding box)

- [ x ] I signed [CLA](https://musescore.org/en/cla)
- [ x ] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [ x ] I made sure the code compiles on my machine
- [ x ] I made sure there are no unnecessary changes in the code
- [ x ] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [ x ] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [ x ] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

File: src/notation/internal/notation.cpp [hunk 1]
```diff
@@ -326,11 +326,14 @@ void Notation::paintPages(draw::Painter* painter, const RectF& frameRect, const
...
         painter->translate(pagePosition);
         paintForeground(painter, page->bbox());
+        painter->qpainter()->setClipping(true);
+        painter->qpainter()->setClipRect(page->bbox().toQRect());
 
         QList<Element*> elements = page->items(frameRect.translated(-page->pos()));
         Ms::paintElements(*painter, elements);
 
         painter->translate(-pagePosition);
+        painter->qpainter()->setClipping(false);
```
Comment (wizofaus) [inline src/notation/internal/notation.cpp:336]: NB this is quite different to how it's done in MU3 (which draws the background last) but I would think is cleaner.

File: src/notation/internal/notation.cpp [hunk 2]
```diff
@@ -326,11 +326,14 @@ void Notation::paintPages(draw::Painter* painter, const RectF& frameRect, const
         PointF pagePosition(page->pos());
         painter->translate(pagePosition);
         paintForeground(painter, page->bbox());
+        painter->qpainter()->setClipping(true);
+        painter->qpainter()->setClipRect(page->bbox().toQRect());
```
Comment (igorkorsukov) [inline src/notation/internal/notation.cpp:330]: Я считаю, что лучше добавить эти методы в Painter и IPainterProvider.

Comment (igorkorsukov) [inline src/notation/internal/notation.cpp:330]: I believe, better to add these methods to Painter and IPainterProvider.

Comment (igorkorsukov) [reply src/notation/internal/notation.cpp:330]: `painter-> qpainter()` is temporary method for current compatible reason

File: src/notation/internal/notation.cpp (hunk 1 above)
Comment (igorkorsukov) [reply src/notation/internal/notation.cpp:336]: I believe, better to add these methods to Painter and IPainterProvider.

Comment (igorkorsukov) [reply src/notation/internal/notation.cpp:336]: painter-> qpainter() is temporary method for current compatible reason

**Review by igorkorsukov — APPROVED** [review]
