### PR TITLE
Don't unlink top frame when init parts

### LINKED ISSUE #27060: Crash after opening all parts, deleting top instrument, Undo all and opening all parts again
### Issue type

Crash or freeze

### Description with steps to reproduce

**CASE 1**

1. Open String Quartet template
2. Open all parts
3. Delete **Violin 1**
4. Undo all
5. Open all parts

https://github.com/user-attachments/assets/db8ca9e9-cbfe-4717-b28e-5dd9b039c805

**CASE 2**

1. Open Treble Clef template
2. Open all parts
3. Delete Piano
4. Undo all

https://github.com/user-attachments/assets/fd151a9c-0763-4a6e-a237-d8a826ac8310

### What is the latest version of MuseScore Studio where this issue is present?

4.5 RC

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

Windows 10
(also occurs on macOS)

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mike-spa**
Resolves: #27060

The crash happens because when undoing, the excerpt gets recreated, which calls this method `fillWithDefaultInfo`. 

I'm really not sure that I understand the purpose of this method, but it looks a bit strange cause it isn't actually filling the default information (as the name would suggest) but is just unlinking the top frame and its content. Indeed, when the excerpt gets recreated by undo, one can see by moving the Title text in the part that it isn't linked (it doesn't turn orange), which is undesirable.  

It seems that this additional unlinking is the cause of the crash, and I don't see an immediate reason why we _should_ unlink the top frame, so I've just tried removing the function and it seems to fix the crash. But @cbjeukendrup and @RomanPudashkin I think you should have a look at this too.

### CODE REVIEW

File: src/notation/internal/excerptnotation.cpp [hunk 1]
```diff
@@ -82,34 +78,6 @@ bool ExcerptNotation::isEmpty() const
     return m_excerpt->parts().empty();
 }
 
-void ExcerptNotation::fillWithDefaultInfo()
-{
-    TRACEFUNC;
-
-    IF_ASSERT_FAILED(m_excerpt || m_excerpt->excerptScore()) {
```
Comment (cbjeukendrup) [inline src/notation/internal/excerptnotation.cpp:89]: By the way, totally off-topic and irrelevant, but thanks to `clang-analyzer` I noticed that this assert contains a funny mistake, that isn't intuitively obviously because of the negation in `IF_ASSERT_FAILED`. Namely: what happens if `m_excerpt` is `false`?

**Review by cbjeukendrup — APPROVED** [review]
This removal makes sense to me. It looks like `ExcerptNotation::init` is not supposed to modify the `Score`. 

I don't really understand either why the text was being unlinked. The body of the method has evolved a lot; in its original form, it was introduced in https://github.com/musescore/MuseScore/pull/8887, where it also contained the unlink already. Perhaps that was necessary back then because otherwise there was no way at all to format full score and part scores differently? In that case it's not necessary anymore nowadays. 
Anyway, I see nothing against this change!

**Comment by RomanPudashkin** [comment]
This function originally did more things than just unlinking (see https://github.com/musescore/MuseScore/commit/fb2b4fd9fc273c0fa88992b93b7d7ac0066c55d3). Its implementation has been heavily changed over the years. The unlikning part was added because in MS3 you could edit the texts in the top frame in each excerpt score independently. But anyway, this looks good to me

**Review by RomanPudashkin — APPROVED** [review]
