### PR TITLE
fixed #12261: Play inputted chord

### LINKED ISSUE #12261: MIDI Keyboard: When inputting chords, some notes are not heard or not displayed
(Edited by Martin)
**To Reproduce**
See video below:
1. Plug in a MIDI Keyboard
2. When entering chords, some notes are not being picked up. Playback also often misses certain notes.

### PR DESCRIPTION
**Pull request by Eism**
Resolves: #12261

### CODE REVIEW

File: src/framework/midi/imidiinport.h [hunk 1]
```diff
@@ -22,6 +22,8 @@
 #ifndef MU_MIDI_IMIDIINPORT_H
 #define MU_MIDI_IMIDIINPORT_H
 
+#include <unordered_map>
```
Comment (vpereverzev) [inline src/framework/midi/imidiinport.h:25]: makes sense to replace with <vector>

**Review by vpereverzev — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
Tested #12261 on Win10, Mac12, LinuxMint 20.2 - **FIXED**
