### PR TITLE
Fix #14807: Hide Count-in option

### LINKED ISSUE #14807: [TASK] Since we are not implementing 'Count In' in MS4.0, we need to hide the UI for it
**Describe the bug**
This option needs to be hidden until we have the 'Count-in' feature re-implemented in 4.X

image

**Expected behavior**
Option is not visible

### PR DESCRIPTION
**Pull request by HemantAntony**
Resolves: #14807

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

File: src/playback/internal/playbackuiactions.cpp [hunk 1]
```diff
@@ -108,14 +108,14 @@ const UiActionList PlaybackUiActions::m_settingsActions = {
...
              ),
-    UiAction("countin",
-             mu::context::UiCtxAny,
-             mu::context::CTX_ANY,
-             TranslatableString("action", "Enable count-in when playing"),
-             TranslatableString("action", "Enable count-in when playing"),
-             IconCode::Code::COUNT_IN,
-             Checkable::Yes
-             ),
+//    UiAction("countin",                                      // See #14807
```
Comment (RomanPudashkin) [inline src/playback/internal/playbackuiactions.cpp:111]: You should keep only this change. All changes in other files should be excluded from this PR

**Comment by Tantacrul** [comment]
@RomanPudashkin - as long as you're happy, this one does what it says on the tin 😄 

image

@HemantAntony thanks so much!
