### PR TITLE
fixed #9966: Closing one of multiple projects leaves windows open

### LINKED ISSUE #9966: [MU4 Issue] Closing one of multiple projects leaves windows open (potential usability trap)
**Describe the bug**
Closing one of multiple open projects causes the score to close, but the project window remains open and the user is left seeing the workspace, wallpaper, and app icon in the system tray.

A potential issue with this is that the user could be forgiven for thinking their project is still open:
- They still see the MuseScore app icon in the system tray. Clicking on it brings forward an "empty" screen.
- They may attempt to quit MuseScore to solve this, inadvertently closing all other open projects.

Screenshot 2021-12-04 at 12 09 29 am

**Expected behavior**
My recommendation would be that, where more than one project is open, closing a project closes the entire window and removes the app icon from the system tray. Only where **only one** project is open should a close command keep the window open (so the user can open another score). 

This behaviour would be triggered by:

- File > Close
- Cmd/Ctrl+W
- Closing the window with the "X" icon in the title bar

**Desktop (please complete the following information):**

### PR DESCRIPTION
**Pull request by Eism**
A cyclic dependency has occurred
ActionController::quit re-calls the ProjectActionsController::closeOpenedProject method which has not yet completed

Resolves: #9966

### CODE REVIEW

File: src/multiinstances/internal/ipc/ipcsocket.cpp [hunk 1]
```diff
@@ -57,6 +57,10 @@ bool IpcSocket::connect(const QString& serverName)
             }
         });
 
+        QObject::connect(m_socket, &QLocalSocket::disconnected, [this]() {
+            m_disconnected.notify();
```
Comment (igorkorsukov) [inline src/multiinstances/internal/ipc/ipcsocket.cpp:61]: Maybe keep only this solution and remove with PeerClosedError ?

File: src/project/internal/projectactionscontroller.cpp [hunk 2]
```diff
@@ -359,7 +360,9 @@ bool ProjectActionsController::closeOpenedProject(bool quitApp)
         globalContext()->setCurrentProject(nullptr);
 
         if (quitApp) {
-            dispatcher()->dispatch("quit", actions::ActionData::make_arg1<bool>(false));
+            async::Async::call(this, [this](){
+                dispatcher()->dispatch("quit", actions::ActionData::make_arg1<bool>(false));
```
Comment (igorkorsukov) [inline src/project/internal/projectactionscontroller.cpp:364]: Maybe `async` needs to be added to the `quit` action handler? Or is the `async` needed only in this place? Then I think it's better to add a comment why

Comment (Eism) [reply src/project/internal/projectactionscontroller.cpp:364]: This is only needed here since we control the life cycle of the method(m_isProjectClosing) and cannot call such methods synchronously

File: src/multiinstances/internal/ipc/ipcsocket.cpp (hunk 1 above)
Comment (Eism) [reply src/multiinstances/internal/ipc/ipcsocket.cpp:54]: fixed

**Review by igorkorsukov — APPROVED** [review]

**Comment by DmitryArefiev** [comment]
Tested #9966 on Win10, Mac13 - **FIXED**
