### PR TITLE
Fix #8084: two checkmarks in Note Input menu in NoteInputBar

### LINKED ISSUE #8084: [MU4 Issue] Pencil icon dropdown has two ticks instead of one
**Describe the bug**
Pencil icon dropdown always has two ticks
In this dropdown only one item can have a tick

**To Reproduce**
1. Create a score
2. Click on 'Pencil' icon from the Note Input Bar and hold until dropdown appears
3. Click on any item from the dropdown
4.  Click on 'Pencil' icon from the Note Input Bar and hold until dropdown appears again
5. observe what item ticked

**Expected behavior**
In this dropdown only one item should have a tick

**Screenshots**
Double tick

**Desktop (please complete the following information):**
Windows 10

**Additional context**
In some cases dropdown items don’t aligned. Can't reproduce now

### PR DESCRIPTION
**Pull request by cbjeukendrup**
Resolves: #8084

This PR solves several issues with the Note Input menu. 

First, the order of the items was wrong, because the items were added by iterating over a QMap, which does not maintain the order (it sorts by key). Now, I changed this into a `std::vector<std::pair<...>>`, so we get the order we want.

Then, I fixed the checkmarks issue. I added a separate action for just toggling note input and setting the note input method to "Steptime (default)". This is also how it was in MuseScore 3.

However, in the original design, there is no checkmark at all; the selected method is just highlighted, so the checkmark is somewhat redundant. So I removed it in the third commit. Here's the two versions, so you can choose:
|With checkmark|Without checkmark|
|-|-|
|Schermafbeelding 2021-06-10 om 23 03 28|Schermafbeelding 2021-06-10 om 23 18 53|

### CODE REVIEW

File: src/notation/view/noteinputbarmodel.cpp [hunk 1]
```diff
@@ -834,18 +826,9 @@ std::vector<std::string> NoteInputBarModel::currentWorkspaceActions() const
     return toolbarData->actions;
 }
 
-void NoteInputBarModel::handleAction(const QString& action, int actionIndex)
+void NoteInputBarModel::handleAction(const QString& action)
 {
     ActionCode actionCode = codeFromQString(action);
-    if (isNoteInputModeAction(actionCode)) {
```
Comment (RomanPudashkin) [inline src/notation/view/noteinputbarmodel.cpp:840]: Thank you for this fix!

**Review by RomanPudashkin — APPROVED** [review]
