### PR TITLE
[MU4] fix #7644 - use last modified date for recent scores screen

### LINKED ISSUE #7644: [MU4 Issue] Wrong data of file created in MU4
**Describe the bug**
I created score yesterday (1 day ago)But in MU4 it said that score has been created 2 days ago

**To Reproduce**
1. Ceate a score and save it
2. The next day create a new score and save it
3. Look at the date of scores created on Home Tab

**Expected behavior**
Score`s date of creation should be displayed correctly

**Screenshots**

a6LNyWpIFTY
8u235mXZhM8

**Desktop (please complete the following information):**
Windows 10

**Additional context**
You may see on Windows folder screenshot that there are 2 scores created in different days ("1" and "file") but both of them have the same date in MU4 (2 days ago)

### PR DESCRIPTION
**Pull request by wizofaus**
Resolves: https://github.com/musescore/MuseScore/issues/7644

Recent scores screen was showing meta-data "creation" date/time which @Tantacrul agreed was unexpected and should be "last saved" date/time instead.

- [ x ] I signed [CLA](https://musescore.org/en/cla)
- [ x ] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [ x ] I made sure the code compiles on my machine
- [ x ] I made sure there are no unnecessary changes in the code
- [ x ] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [ x ] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [ x ] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

### CODE REVIEW

File: src/userscores/view/recentscoresmodel.cpp [hunk 1]
```diff
@@ -114,7 +115,8 @@ void RecentScoresModel::updateRecentScores(const MetaList& recentScoresList)
         obj[SCORE_TITLE_KEY] = !meta.title.isEmpty() ? meta.title : meta.fileName.toQString();
         obj[SCORE_PATH_KEY] = meta.filePath.toQString();
         obj[SCORE_THUMBNAIL_KEY] = meta.thumbnail;
-        obj[SCORE_TIME_SINCE_CREATION_KEY] = DataFormatter::formatTimeSinceCreation(meta.creationDate);
+        obj[SCORE_TIME_SINCE_CREATION_KEY] = DataFormatter::formatTimeSince(meta.creationDate);
```
Comment (wizofaus) [inline src/userscores/view/recentscoresmodel.cpp:118]: I left this in case it's decided it would be useful to have available (e.g. via a tooltip) in future.

**Comment by RomanPudashkin** [comment]
@vshalkevich please, check this

File: src/userscores/view/recentscoresmodel.cpp (hunk 1 above)
Comment (RomanPudashkin) [reply src/userscores/view/recentscoresmodel.cpp:118]: It is better to remove the unused field. We can easily add it later if we need it. But at the moment, we can slightly simplify this code

**Review by RomanPudashkin — APPROVED** [review]

File: src/userscores/view/recentscoresmodel.cpp (hunk 1 above)
Comment (wizofaus) [reply src/userscores/view/recentscoresmodel.cpp]: Done

**Comment by vshalkevich** [comment]
Works fine. Can be merged
