### PR TITLE
Fix #32538: Keep down spacer from forcing system to page bottom

### LINKED ISSUE #32538: Staff spacer down exceeding available page space is clipped visually but moves system to next page after reopening score
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

When a Staff spacer down is set to a size larger than the available vertical space remaining on a page, MuseScore appears to clip the spacer visually in the live layout. The systems remain on the same page and are compressed toward the top.
However, after saving the file and reopening it, the layout is recalculated and the last system moves to the next page.
This suggests that the live layout and the layout recalculated on file load treat oversized spacers differently.

**Steps to reproduce**
1. Create a score that fills most of a page with systems.
2. Add a Staff spacer down to the bottom staff of a system.
3. Increase the spacer size so that it exceeds the remaining vertical space on the page.
4. Observe that the spacer is clipped and the systems remain on the same page.
5. Save the score.
6. Close and reopen the file.

**Result**
After reopening the file, the last system moves to the next page.

**Expected result**
Either:
* the layout should update immediately and move the system to the next page, or
* the spacer should remain clipped after reopening.
The layout should be consistent between the live editor and the layout after reopening the score.

macOS Tahoe (26.0.1), Arch.: arm64, MuseScore Studio version (64-bit): 4.6.5-253511702, revision: github-musescore-musescore-653f38d

### Supporting files, videos and screenshots

Before save:
Image
After:

Image

Also see https://github.com/musescore/MuseScore/issues/32538#issuecomment-4032720156

### In which versions of MuseScore Studio is this issue present?

4.6.5-253511702

### Regression

I was unable to check

### Operating system

macOS

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by pedroataidefonseca**
Resolves: #32538 

This PR fixes a layout inconsistency where a large Staff spacer down could force a system to stretch to the page edge during live editing, but the layout would differ after reopening the score. The fix separates the semantics of down spacers:

Inter-system spacing: Down spacers continue to influence the minimum distance between systems (via SystemLayout::minDistance).

Page margins: Down spacers are excluded from page-end and footer margin calculations, which should only reflect the natural minBottom() of the system.

This prevents edge pinning artifacts while preserving the intended vertical spacing behavior of spacers.

Changes:

Added triggerLayout() override in Spacer to ensure relayout propagates correctly when spacers are edited.
Modified page-bottom margin calculations in PageLayout to use only natural system bottom, not spacer-inflated margins.

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [ ] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/muse_framework/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

File: src/engraving/dom/spacer.cpp [hunk 1]
```diff
@@ -161,6 +161,29 @@ PropertyValue Spacer::propertyDefault(Pid id) const
...
+    if (!s) {
+        return;
+    }
+
+    if (s->nstaves() == 0) {
+        EngravingItem::triggerLayout();
+        return;
+    }
+
+    s->setLayout(tick(), s->endTick(), 0, s->nstaves() - 1, this);
```
Comment (mike-spa) [inline src/engraving/dom/spacer.cpp]: This is a big no, it means that the entire score gets re-laid out and it could be very expensive and if the score is big. I don't think this is necessary

Comment (pedroataidefonseca) [reply src/engraving/dom/spacer.cpp]: I've pushed a new version that should correct that. I changed spacer relayout to be local instead of score-wide.

**Comment by Jojo-Schmitz** [comment]
Is this vtest failure intentional?
system-8-1 diff

**Comment by davidstephengrant** [comment]
@pedroataidefonseca Spacers on the last system of a page no longer have effect when vertical justification is disabled (which they should).

4.6.5:

[Screencast from 2026-03-20 14-24-16.webm](https://github.com/user-attachments/assets/ec7a3962-4b76-4b2c-8546-dbc3fd075098)


This PR:

[Screencast from 2026-03-20 14-21-59.webm](https://github.com/user-attachments/assets/c9aebee0-3eb6-4f59-96bf-f19dd7dc0ba3)

**Comment by davidstephengrant** [comment]
Also, system brackets can draw incorrectly when a system moves between pages. Forcing re-layout, reloading score, etc. causes this to draw correctly again.

See from approx. 00:12 here:

[Screencast from 2026-03-20 14-49-04.webm](https://github.com/user-attachments/assets/ca9c893f-210d-4ae7-97e3-5cabe4fdd9e5)

**Comment by pedroataidefonseca** [comment]
@davidstephengrant I pushed a version that addresses those errors and should fix them. Can you review?

**Comment by davidstephengrant** [comment]
@pedroataidefonseca Can you please rebase on master - this is currently crashing on launch.

**Comment by pedroataidefonseca** [comment]
@davidstephengrant I've rebased on master.

**Comment by davidstephengrant** [comment]
@pedroataidefonseca Can you please rebase once again? This is still crashing, but latest nightlies do appear to be OK.

**Comment by pedroataidefonseca** [comment]
@davidstephengrant I've rebased once again, can you check if everything is OK now?

**Comment by davidstephengrant** [comment]
Tested and approved on Ubuntu 24.04.4 LTS.
