### PR TITLE
Fix #22344: calculate divisions and duration using Fractions

### LINKED ISSUE #22344: XML export adds small amount of silence before left hand note when a septuplet is played in the right hand (Piano)
### Issue type

Import/export issue

### Bug description

When you export a septuplet in a piano piece, a small amount of silence is being added in the left hand.

Here is the example that is written in Musescore 4 (comes from Chopin's "Waltz in A Minor" with the septuplet being a written out trill):
image

When I then upload this into another notation software (Finale v27) you can see that there is a "dot" preceding the left hand:
image

If I then select that measure using the "Speedy Entry tool" and press "Escape" a modal shows up saying that too many notes are in the measure:
image

This is telling me that there seems to be a problem with the export.

### Steps to reproduce

Download Musescore 4 file that I used above
[Musescore 4.mscz.zip](https://github.com/musescore/MuseScore/files/14950829/Musescore.4.mscz.zip)

OR

1. Open Musescore 4
2. Choose "Piano" instrument
3. Enter a septuplet in the top stave
4. Now enter a quarter note in the left hand on beat 1 (note that the 7-tuplet will now simultaneously start with the lower staves quarter note)
5. Export XML

This should look something like this when done:
image

I also tried loading the exported Musescore 4 XML into Logic and you can see a slight gap there, too:
image

I then tried loading it into [Open Sheet Music Display](https://opensheetmusicdisplay.org/demos/public-typescript-demo/) to see what it looked like there, but it seemed to work?? 🤔

image

I then tried uploading it into Soundslice and their music editor showed a hidden element prior to the LH note:
image

My thoughts are that this might be a quantizing thing, at least for the import part into other software. Some software are taking the music very literally (maybe like a high PPQ) while others seem to be quantizing it to a lower more realistic value.

My question: if this is happening, is there any way to please "lock this in"?

Here are all of my test files used: [Archive.zip](https://github.com/musescore/MuseScore/files/14950960/Archive.zip)

Contents:
- Musescore 4 file with exported MusicXML and MIDI file
- Finale v27 file with exported MusicXML and MIDI file 

### Screenshots/Screen recordings

_No response_

### MuseScore Version

OS: macOS 14.4, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433

### Regression

I don't know

### Operating system

macOS Sonoma 14.4.1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lvinken**
Resolves: #22344

For historical reasons, the MusicXML exporter calculates the MusicXML divisions and duration values using ticks (the code predates the introduction of Fraction and was never updated). This works reasonably OK only for non-nested tuples up to quintuplets, but may introduce slight rounding errors.

Solution is to use Fractions in these calculations.

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [x] I created a unit test or vtest to verify the changes I made (if applicable)

### CODE REVIEW

File: src/importexport/musicxml/internal/musicxml/exportxml.cpp [hunk 1]
```diff
@@ -462,6 +462,42 @@ class ExportMusicXml
...
+    }
+    String res { f.toString() };
+    res += String(u" (%1)").arg(String::number(f.ticks()));
+    return res.toStdString();
+}
+
+#endif
+
+//---------------------------------------------------------
+//   fractionToStdString
```
Comment (rettinghaus) [inline src/importexport/musicxml/internal/musicxml/exportxml.cpp:483]:
```suggestion
//   durElemTicksToStdString
```

**Review by rettinghaus — CHANGES_REQUESTED** [review]
Looks cool, thanks! One small copy / paste error.

File: src/importexport/musicxml/internal/musicxml/exportxml.cpp (hunk 1 above)
Comment (lvinken) [reply src/importexport/musicxml/internal/musicxml/exportxml.cpp]: Thanks for catching this, done.

**Review by RomanPudashkin — APPROVED** [review]

**Comment by zacjansheski** [comment]
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/22344 FIXED

**Comment by Jojo-Schmitz** [comment]
Should this also make it into 4.3.2?

**Comment by RomanPudashkin** [comment]
> Should this also make it into 4.3.2?

no, it's not a regression (at least not a new one)
