### PR TITLE
Fix #28636: Slurs and grace notes surviving range deletes

### LINKED ISSUE #28636: Slur on grace note note deleted after select all + delete
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. Open a score
2. Press A, /, S to write a quarter note with a slurred grace note
3. Select all, delete, slur remains

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/aa5550b5-6aa9-4460-b59d-4d6297b068da

### What is the latest version of MuseScore Studio where this issue is present?

OS: macOS Sequoia (15.5), Arch.: arm64, MuseScore Studio version (64-bit): 4.6.0-251810327, revision: github-musescore-musescore-015978d

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

MacOS15

### Additional context

_No response_

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

### PR DESCRIPTION
**Pull request by mathesoncalum**
Resolves: #28636

This bug was introduced with 1792860002f73b8cfd1a4d7049b8fa2ef840a42e - feeding `Fraction::max` to `deleteOrShortenOutSpannersFromRange` resulted in some unexpected behaviour. I'm hoping we can go back to using `lastMeasure()->endTick()` without the need for separate "end tick" values for `deleteOrShortenOutSpannersFromRange` and for `deleteRangeAtTrack`. The unit tests seem fine with this, and I didn't notice anything strange during manual testing.

This PR also includes a new unit test for slurs and graces, and resolves some other related bugs (see video):
1. A spanner (e.g. slur) can never be selected if the grace note(s) it is attached to is de-selected
2. Grace notes survive range deletes despite being selected in the selection filter

https://github.com/user-attachments/assets/31432649-56f6-4a28-bb53-49c36a56d245

### CODE REVIEW

File: src/engraving/dom/edit.cpp [hunk 1]
```diff
@@ -3527,30 +3527,42 @@ void Score::deleteOrShortenOutSpannersFromRange(const Fraction& t1, const Fracti
...
-                if (moveStart) {
-                    Fraction tickDiff = t2 - spStartTick;
-                    sp->undoChangeProperty(Pid::SPANNER_TICK, t2);
-                    sp->undoChangeProperty(Pid::SPANNER_TICKS, sp->ticks() - tickDiff);
-                } else if (moveEnd) {
-                    Fraction tickDiff = spEndTick - t1;
-                    sp->undoChangeProperty(Pid::SPANNER_TICKS, sp->ticks() - tickDiff);
-                }
+        if (spStartTick >= t1 && spStartTick < t2
+            && spEndTick >= t1 && spEndTick <= t2) {
```
Comment (cbjeukendrup) [inline src/engraving/dom/edit.cpp]: Should it be like this?
```suggestion
        if (spStartTick >= t1 && spStartTick < t2
            && spEndTick > t1 && spEndTick <= t2) {
```

Comment (mathesoncalum) [reply src/engraving/dom/edit.cpp]: Updated. I will say there are a few quirky areas like this where we should try to reduce the duplication between the selection and deletion logic if we can. That's probably a task for another time, though.

**Review by cbjeukendrup — APPROVED** [review]

**Comment by zacjansheski** [comment]
Tested and approved. https://github.com/musescore/MuseScore/issues/28636 FIXED

Note: Slurs on grace notes are not picked up by range selection, same in nightly, regression of 4.5.2. I can open a separate issue if that is best.

https://github.com/user-attachments/assets/fbdca328-4a8b-43fe-b79f-14cccbf2fc45

**Comment by mathesoncalum** [comment]
Sorry for the delay @zacjansheski! I believe this is an edge case that only occurs when a grace note is slurred to its parent note at the very start of a selection range - it should be fixed now...

(@cbjeukendrup FYI)

**Review by cbjeukendrup — APPROVED** [review]

**Comment by zacjansheski** [comment]
Tested on MacOS 15, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/28636 FIXED
