### PR TITLE
Fix #17502: Exclude tab staves from clef change recalculation shenanigans

### LINKED ISSUE #17502: [MU4 Issue] Slured notes on the TAB staff are rendered wrong when slur goes over to next line
Screenshot 2023-05-08 at 20 51 59

compare tab notes with ties and with slurs:
[archive.zip](https://github.com/musescore/MuseScore/files/11423764/archive.zip)

Issue is also reproducible when inserting notes and slurs.

### PR DESCRIPTION
**Pull request by asattely**
Resolves: https://github.com/musescore/MuseScore/issues/17502

There is a fleet of methods to deal with recalculating the staff line based on clef, but none of them apply to tab staves.

### CODE REVIEW

File: src/engraving/libmscore/note.cpp [hunk 1]
```diff
@@ -2766,7 +2766,10 @@ void Note::updateRelLine(int relLine, bool undoable)
 
     const Staff* staff  = score()->staff(idx);
     const StaffType* st = staff->staffTypeForElement(this);
-
+    if (st->isTabStaff()) {
+        // tab staff is already correct, and the following relStep method doesn't apply whatsoever to tab staves
+        return;
+    }
```
Comment (Jojo-Schmitz) [inline src/engraving/libmscore/note.cpp:2772]: 3.x additionally has this it that place:
´``cpp
      if (chord()->staffMove()) {
            // check that destination staff makes sense (might have been deleted)
            int minStaff = part()->startTrack() / VOICES;
            int maxStaff = part()->endTrack() / VOICES;
            const Staff* stf = this->staff();
            if (idx < minStaff || idx >= maxStaff || st->group() != stf->staffTypeForElement(this)->group()) {
                  qDebug("staffMove out of scope %d + %d min %d max %d",
                     staffIdx(), chord()->staffMove(), minStaff, maxStaff);
                  chord()->undoChangeProperty(Pid::STAFF_MOVE, 0);
                  }
            }

```
Not needed on master?

**Review by mike-spa — APPROVED** [review]

**Review by abariska — APPROVED** [review]
