### PR TITLE
Fix #18451: export T hook

### LINKED ISSUE #18451: MusicXML exporting: the wrong line-end type is exported for brackets.
### Issue type

Other type of issue

### Bug description

Brackets with a line-end type of 'both' are not exported to MusicXML correctly. Instead the line-end type is exported as 'down':

```
<direction placement="below">
  <direction-type>
    <bracket type="stop" number="1" line-end="down" end-length="6"/>
  </direction-type>
</direction>
```

should be:

```
<direction placement="below">
  <direction-type>
    <bracket type="stop" number="1" line-end="both" end-length="6"/>
  </direction-type>
</direction>
```

### Steps to reproduce

1. Create a MuseScore project that has a bracket with a double line end. For example a let-ring or P.M. element
2. Export to MusicXML
3. Import the exported MusicXML file back in to MuseScore
4. Notice the line end for the bracket has changed

### Screenshots/Screen recordings

Before export:
Screenshot 2023-07-06 133249
After export:
Screenshot 2023-07-06 133224

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651553, revision: github-musescore-musescore-dbe7c6d

### Regression

I don't know

### Operating system

Windows 11

### Additional context

The MuseScore and MusicXML files:
[files.zip](https://github.com/musescore/MuseScore/files/11972151/files.zip)

### PR DESCRIPTION
**Pull request by rettinghaus**
Export T hook endings on dashed lines to MusicXML. 

Resolves #18451

### CODE REVIEW

File: src/importexport/musicxml/internal/musicxml/exportxml.cpp [hunk 1]
```diff
@@ -5124,13 +5124,19 @@ void ExportMusicXml::textLine(TextLineBase const* const tl, staff_idx_t staff, c
...
-            lineEnd = "down";
+            if (hookHeight < 0.0) {
+                lineEnd = "up";
+                hookHeight *= -1.0;
+            } else if (hookHeight > 0.0) {
+                lineEnd = "down";
+            } else {
+                lineEnd = "none";
+            }
+            rest += QString(" end-length=\"%1\"").arg(hookHeight * 10);
```
[the remark this answers is not in the document]
Comment (rettinghaus) [reply src/importexport/musicxml/internal/musicxml/exportxml.cpp:5138]: Actually the "none" case was handled above, and we missed to handle the start hook correctly.

[the remark this answers is not in the document]
Comment (rettinghaus) [reply src/importexport/musicxml/internal/musicxml/exportxml.cpp]: My changed implementation should be clearer and more universal.

File: src/importexport/musicxml/internal/musicxml/exportxml.cpp [hunk 2]
```diff
@@ -5123,14 +5122,21 @@ void ExportMusicXml::textLine(TextLineBase const* const tl, staff_idx_t staff, c
...
-            lineEnd = "up";
-            hookHeight *= -1.0;
-        } else {
-            lineEnd = "down";
-        }
-        rest += QString(" end-length=\"%1\"").arg(hookHeight * 10);
+    QString lineEnd;
+    switch (hookType) {
+    case HookType::HOOK_90T:
+        lineEnd = "both";
```
Comment (cbjeukendrup) [inline src/importexport/musicxml/internal/musicxml/exportxml.cpp:5128]: This looks much better, but now the `end-length` is not written anymore for T hook. Is that expected?

Comment (rettinghaus) [reply src/importexport/musicxml/internal/musicxml/exportxml.cpp:5128]: That was intentional. But I can add it if you'd prefer.

**Review by cbjeukendrup — APPROVED** [review]

**Review by oktophonie — APPROVED** [review]

File: src/importexport/musicxml/internal/musicxml/exportxml.cpp [hunk 3]
```diff
@@ -5123,14 +5122,22 @@ void ExportMusicXml::textLine(TextLineBase const* const tl, staff_idx_t staff, c
...
+        rest += QString(" end-length=\"%1\"").arg(fabsf(hookHeight * 20));
```
Comment (Jojo-Schmitz) [inline src/importexport/musicxml/internal/musicxml/exportxml.cpp:5129]: Why `fabsf()` for a `double` rather than `fabs()`

Comment (cbjeukendrup) [reply src/importexport/musicxml/internal/musicxml/exportxml.cpp:5129]: And why not even just `std::abs`?
@Jojo-Schmitz It would be great if you could add that to #19533

Comment (Jojo-Schmitz) [reply src/importexport/musicxml/internal/musicxml/exportxml.cpp:5129]: OK, will do

Comment (Jojo-Schmitz) [reply src/importexport/musicxml/internal/musicxml/exportxml.cpp:5129]: done
